### PR TITLE
Publish images per versions

### PR DESCRIPTION
**Pull request by oshercc**

### CODE REVIEW

**Review by ronniel1 — APPROVED** [review]
/lgtm
/approve

**Comment by YuviGold** [comment]
Should only allow `release-` prefix.
/hold

**Comment by oshercc** [comment]
@ronniel1 so what do you think about this? do we want it as is or only for release prefix?

**Comment by ronniel1** [comment]
I think we can add this like this.
Almost no one has permission to push to this repo directly

**Pull request merged**
