### PR TITLE
MGMT-8047: Approve the CSRs after the installation

### PR DESCRIPTION
**Pull request by ori-amizur**
# Assisted Pull Request

## Description

Day1 CSRs are approved by assisted controller.  Since the controller is
not aware of day2 workers, until now these CSRs needed to be approved
manually.
This modification, adds capability to assisted service, to approve these
CSRs.  In order for this to work, cluster kubeconfig has to be available in S3
(which is not always true for day2 hosts), and the cluster needs to be
available when using this kubeconfig.
There are two parts to this solution.
In host monitoring, each day2 host that is not in done stage, is checked against its corresponding node
(using kubeapi).  If the node is ready then the host is moved to done.
In case there is a problem acccessing the day1 cluster and the day2 host
is rebooting, it is moved to done (as it is today).  In this case it is
the user responsibility to approve the CSRs.
In cluster monitoring, if there is a day2 cluster with hosts that are
not in done stage yet, it tries to approve all the CSRs using kubeapi.
For the usage of these monitoring loops, a package with the needed
kubeapi operations was created.

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @tsorya 
/cc @filanov 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by filanov** [comment]
cc: @flaper87

**Comment by filanov** [comment]
cc: @romfreiman

**Comment by filanov** [comment]
cc: @avishayt

**Comment by filanov** [comment]
I'm not sure that our monitor should access the installed cluster with kubeconfig, what will happen if the cluster is using proxy?

**Comment by ori-amizur** [comment]
> 

How can we approve without it ?

**Comment by eranco74** [comment]
is checked against its corresponding node
(using kubeapi).??
From where? the assisted-service?
The assisted-service don't have access to the user cluster.

**Comment by ori-amizur** [comment]
> to the user cluster.

When using kubeapi, it accesses the user cluster.  Any difference ?

**Comment by filanov** [comment]
The difference is that it's part of a different product that assumes that it have connection to the spoke cluster, here we cannot know that.

**Comment by ori-amizur** [comment]
The question is, how can it be done otherwise ?

**Comment by eranco74** [comment]
This feature seems like something that should just work for ZTP (create a machine with the matching InterlnaIP and hostname).
For the cloud use case, it requires some component that runs on the installed cluster.

**Comment by filanov** [comment]
I agree the plan was for ZTP.
Here is how BMH controller take the client https://github.com/openshift/assisted-service/blob/ca9a803e06173cbfc6ec543ce31fa17a96ed35c0/internal/controller/controllers/bmh_agent_controller.go#L763

**Comment by ori-amizur** [comment]
> I agree the plan was for ZTP. Here is how BMH controller take the client
> 
> https://github.com/openshift/assisted-service/blob/ca9a803e06173cbfc6ec543ce31fa17a96ed35c0/internal/controller/controllers/bmh_agent_controller.go#L763

If the assisted succeeds to connect the spoke from this location, it will succeed in the other place.

**Comment by filanov** [comment]
But it will work only in disconnected environment, in the cloud we don't have access to the clusters.

**Comment by tsorya** [comment]
We can't push such code to SAAS solution, we shouldn't even try to connect to users cluster.

**Comment by tsorya** [comment]
please move it to controller and use it only in ztp flow

**Pull request closed without merging**
