### PR TITLE
NO-ISSUE update hive version to master

### PR DESCRIPTION
**Pull request by filanov**
Drop vip dhcp allocation support for kube-api
Fix tests and imports

### CODE REVIEW

**Comment by filanov** [comment]
subsystem passed 
```
Ran 2 of 140 Specs in 37.572 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 138 Skipped
```

**Comment by YuviGold** [comment]
/lgtm

In case you want someone else to look into it
/hold

**Comment by filanov** [comment]
@RazRegev does it affect E2E in some way?

**Comment by RazRegev** [comment]
> @RazRegev does it affect E2E in some way?

I don't see how this can effect the e2e test. 
Unless this new field is required, I don't see how this PR will effect the e2e

**Comment by filanov** [comment]
> Unless this new field is required, I don't see how this PR will effect the e2e

Need to set aipVIP and ingressVIP

**Pull request merged**
