### PR TITLE
MGMT-11509: Collect preprovisioningimages CR in operator gather job

### PR DESCRIPTION
**Pull request by eranco74**
- Should this PR be tested by the reviewer? no
- Is this PR relying on CI for an e2e test run? yes
- Should this PR be tested in a specific environment? operator job
- Any logs, screenshots, etc that can help with the review process? yes, look for the PPI CRs in the BMH folder under artifacts

-->

## List all the issues related to this PR
https://issues.redhat.com/browse/MGMT-11509

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @carbonin 
/cc @tsorya 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eranco74** [comment]
looks good
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/4266/pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-converged/1559070117554294784/artifacts/e2e-ai-operator-ztp-converged/assisted-baremetal-operator-gather/artifacts/baremetalhosts/ppi_ostest-extraworker-0.yaml

**Review by osherdp — APPROVED** [review]

**Pull request merged**
