### PR TITLE
NO-ISSUE: replace minio quay.io image repository

### PR DESCRIPTION
**Pull request by rccrdpccl**
Original image is now not possible to fetch without right permission:

```
$ podman pull quay.io/cloudservices/minio:latest
Trying to pull quay.io/cloudservices/minio:latest...
Error: initializing source docker://quay.io/cloudservices/minio:latest: reading manifest latest in quay.io/cloudservices/minio: unauthorized: access to the requested resource is not authorized
```

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
@rccrdpccl did you test this locally?

I'm hoping the images are compatible, but IIRC our CI tests don't use the deploy code from the PR so we'll have to be sure this works before merging even if the tests pass.

**Comment by rccrdpccl** [comment]
> I'm hoping the images are compatible, but IIRC our CI tests don't use the deploy code from the PR so we'll have to be sure this works before merging even if the tests pass.

Nice catch, I was hoping this will test it but you're right, I'll test it locally

**Comment by rccrdpccl** [comment]
Looks like tests run with the new image. Also, I've successfully tested subsystem locally

**Comment by rccrdpccl** [comment]
Looks like a flake with subsystem kubeapi

**Pull request merged**
