### PR TITLE
NO-ISSUE: add compression handler to http server

### PR DESCRIPTION
**Pull request by rccrdpccl**
This PR can potentially reduce 10x the size of the payload hence the speed of transfer.
It would impact the most biggest requests, but it will improve all requests to the API if performed with compression.

## List all the issues related to this PR

- [ ] New Feature 
- [X] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [X] Cloud
- [ ] Operator Managed Deployments
- [] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [] No tests needed

Deployed the image from the branch in integration, and tested requests against it.
It returned compressed payload reducing the transfer size by 10 times.

If we perform the same tests against the current integration, the response body is unchanged.

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rccrdpccl** [comment]
Already tested while draft: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/4419/pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted/1572207895452323840

**Comment by romfreiman** [comment]
Shouldn't it happen on the ingress level?

**Comment by rccrdpccl** [comment]
> Shouldn't it happen on the ingress level?

We have tried with production URL `https://api.openshift.com/api/assisted-install/` and it does not compress, so we deduced it's not done on any of the ingresses/gateways/loadbalancer levels.

We can look into possibilities for enabling at infra level though.

**Pull request merged**
