### PR TITLE
MGMT-5302 Removing deprecated /host_requirements endpoint and related model

### PR DESCRIPTION
**Pull request by jakub-dzon**
This PR removes `/host_requirements` endpoint and related model.

To be merged only after UI transitions completely from `/host_requirements` to `/clusters/{cluster_id}/preflight-requirements`.

### CODE REVIEW

**Comment by mareklibra** [comment]
This PR is blocked on https://github.com/openshift-assisted/assisted-ui-lib/pull/556 reaching OCM production.

**Review by YuviGold — APPROVED** [review]
I just love seeing code is being deleted
LGTM

**Review by flaper87 — APPROVED** [review]

**Pull request merged**
