### PR TITLE
MGMT-5396 Remove unneeded yaml - rebase leftovers

### PR DESCRIPTION
**Pull request by rollandf**
After rebasing on top of #1557 , the new CRD yaml was not removed.
Signed-off-by: Fred Rolland <frolland@redhat.com>

### CODE REVIEW

**Comment by rollandf** [comment]
@djzager PTAL

**Review by filanov — APPROVED** [review]

**Review by djzager — APPROVED** [review]
Not sure what was missing from #1709 but :man_shrugging: this looks good to me.

**Pull request merged**
