### PR TITLE
MGMT-12299: Changing the message user sees when the cluster doesn't contain the correct composition of control plane nodes and workers

### PR DESCRIPTION
**Pull request by danmanor**
Changing the message user sees when the cluster doesn't contain the correct composition of control plane nodes and workers

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — CHANGES_REQUESTED** [review]
should we also change those messages?
https://github.com/openshift/assisted-service/blob/9abcc9ab874f44b8ad69827704285cab3d269188/internal/operators/odf/validation_test.go#L171

**Comment by slaviered** [comment]
> should we also change those messages?
> 
> https://github.com/openshift/assisted-service/blob/9abcc9ab874f44b8ad69827704285cab3d269188/internal/operators/odf/validation_test.go#L171

Yes. This should be changed too along the line of the new wording scheme.

**Comment by danmanor** [comment]
@osherdp @slaviered addressed in https://github.com/openshift/assisted-service/pull/4546

**Comment by osherdp** [comment]
ztp is broken (regardless of your changes)

**Comment by osherdp** [comment]
/retest
trying to retest one more time

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/override ci/prow/edge-e2e-metal-assisted-cnv ci/prow/edge-e2e-metal-assisted-odf

**Comment by adriengentil** [comment]
/override ci/prow/edge-e2e-metal-assisted-cnv ci/prow/edge-e2e-metal-assisted-odf

**Comment by osherdp** [comment]
/override ci/prow/edge-e2e-metal-assisted-ocs ci/prow/edge-e2e-metal-assisted-cnv ci/prow/edge-e2e-metal-assisted-lvm ci/prow/edge-e2e-metal-assisted-odf

**Pull request merged**
