### PR TITLE
MGMT-19331: Add `secure_boot_state` to inventory

### PR DESCRIPTION
**Pull request by jhernand**
This patch adds a new `secure_boot_state` field to hosts inventory. This will be collected by the agent, and used to validate that secure boot is disabled when installing the _OpenShift AI_ operator with NVIDIA GPUs, as the NVIDIA driver requires that.

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-19331

- [X] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [X] Automation (CI, tools, etc)
- [X] Cloud
- [X] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [X] Title and description added to both, commit and PR.
- [X] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [X] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by jhernand** [comment]
/override e2e-agent-compact-ipv4 edge-e2e-ai-operator-disconnected-capi

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
