### PR TITLE
MGMT-15972: Remove Swagger definition for api_vip and ingress_vip

### PR DESCRIPTION
**Pull request by nmagnezi**
Additionaly, add a db migration to populate those VIPs in api_vips and ingress_vips arrays.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
/assign @filanov 

/hold
until we make sure UI does not get broken for this change.

**Review by filanov — APPROVED** [review]

**Comment by tsorya** [comment]
We allow breaking api?

**Comment by nmagnezi** [comment]
> We allow breaking api?

We have completed phase 3 as described in https://github.com/openshift/assisted-service/blob/master/docs/enhancements/dual-stack-vips.md#phase-3

now we remove those fields after the deprecation cycle has been completed.

**Pull request merged**
