### PR TITLE
MGMT-18155: handle state of day2 node in Done stage

### PR DESCRIPTION
**Pull request by danielerez**
When installing a day2 node, in some scenraios, the process can be stucked on 'installing-pending-user-action' state while the node is in Done stage.
E.g. after fixing an invalid certificate that failed verfication when trying to reach the using kubeconfig.

Thus, added 'InstallingPendingUserAction' as a SourceState for the relevant TransitionRule (which should move state to the final 'AddedToExistingCluster' DestinationState).

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
>/test all

@danielerez did you want to run more tests on this? I'm not sure this command did anything.

**Comment by danielerez** [comment]
> >/test all
> 
> 
> 
> @danielerez did you want to run more tests on this? I'm not sure this command did anything.

Seems all tests have already passed, so should be good enough:)

**Review by carbonin — APPROVED** [review]

**Comment by danielerez** [comment]
Rebased.
@carbonin Can you please `lgtm` again?

**Pull request merged**
