### PR TITLE
MGMT-7773: Bump OCP versions 4.8.9 -> 4.8.10

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @YuviGold
4.8 release notes: https://access.redhat.com/errata/RHBA-2021:3299

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by danielerez** [comment]
can be closed. 4.9 is also updated in: https://github.com/openshift/assisted-service/pull/2581

**Comment by gamli75** [comment]
can be closed. Updating 4.9 as well in: #2581

**Pull request closed without merging**
