### PR TITLE
MGMT-3130: Change unit tests to use httptest server instead of http server

### PR DESCRIPTION
**Pull request by filanov**
Change auth package tests to use httptest server
Change log package tests to use httptest server

### CODE REVIEW

**Review by slaviered — COMMENTED** [review]
what replaces the waitForServer() function ? since sometimes the server is not up yet when the calls starts?

**Comment by filanov** [comment]
> what replaces the waitForServer() function ? since sometimes the server is not up yet when the calls starts?

**Comment by filanov** [comment]
> what replaces the waitForServer() function ? since sometimes the server is not up yet when the calls starts?

If you take a look at the implementation there is a big difference between `ListenAndServe` and `NewService` the firs one doing much more logic before it actually starts the other one is started the goroutin only on Serve, so i don't think that it's needed in this case, and it will make the tests run faster, anyway if we will see that we still have races then we can always add this logic back.

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by filanov** [comment]
Just pushed the same code with a different hash, looks like it fixed prow.

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
