### PR TITLE
MGMT-7637: Bump OCP versions 4.8.4 -> 4.8.5, 4.7.23 -> 4.7.24

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.7 release notes: https://access.redhat.com/errata/RHBA-2021:3032
4.8 release notes: https://access.redhat.com/errata/RHSA-2021:3121

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
