### PR TITLE
MGMT-4492: Removing WITH_AMS_SUBSCRIPTIONS env variable.

### PR DESCRIPTION
**Pull request by ybettan**
# Assisted Pull Request

## Description

This variable was originally introduced in order to be able to easily
disable in on the transition period.

OCM integration should be enabled as long as we are running with any OCM
(AMS) instance, therefore, this configuration is redundant.

Signed-off-by: Yoni Bettan <ybettan@redhat.com>

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by gamli75** [comment]
@ybettan Do we have this parameter in test-infra? if the answer is yes - we need to remove it from there

**Comment by ybettan** [comment]
@gamli75 We do have it in test-infra as well:
```
$ git grep WITH_AMS_SUBSCRIPTION
README.md:| `WITH_AMS_SUBSCRIPTIONS`      | configure assisted-service to create AMS subscription for each registered cluster, default: false |
scripts/deploy_assisted_service.sh:export WITH_AMS_SUBSCRIPTIONS=${WITH_AMS_SUBSCRIPTIONS:-false}
skipper.env:WITH_AMS_SUBSCRIPTIONS
```

I will create a separate PR for it, anyway, this PR should be merged first (then test-infra and saas.yaml)

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
