### PR TITLE
[release-ocm-2.4] Bug 2072892: Backport `pin-latest.py` script

### PR DESCRIPTION
**Pull request by omertuc**
# Assisted Pull Request
## Description

When publishing the Infrastructure Operator bundle and catalog to quay
for the master branch, we scan the operator's manifests
(clusterserviceversion in particular) for the "latest" tag and pin it to
a particular image manifest digest. This is done using the pin-latest.py
script.

We would like to use the same script for doing similar pinning but for
our release branches.

This is needed because currently our
`periodic-ci-openshift-assisted-service-release-ocm-2.4-e2e-metal-assisted-kube-api-late-binding-single-node-periodic`
job is failing because it's using an outdated operator catalog image
that's no longer being published.

This script is needed for the new publishing process that we already
have in place for `release-ocm-2.5` and `master`.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @adriengentil

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by omertuc** [comment]
/override ci/prow/e2e-metal-assisted
/override ci/prow/e2e-metal-assisted-kube-api
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
/override ci/prow/e2e-metal-assisted-none
/override ci/prow/e2e-metal-assisted-operator-ztp
/override ci/prow/e2e-metal-assisted-operator-ztp-multinode-spoke
/override ci/prow/e2e-metal-assisted-static-ip
/override ci/prow/subsystem-aws
/override ci/prow/subsystem-kubeapi-aws

**Pull request merged**
