### PR TITLE
Bug 2030480: prevent installation BMH when rootDeviceHints is not eligible

### PR DESCRIPTION
**Pull request by erusso7**
This PR fixes [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=2030480). When installing the BMH, with the given `rootDeviceHints` config it was ignored if the device was not eligible. 

 Now, it will trigger an error and prevent the installation to continue

Providing an invalid device `/dev/unknown`, we got this log:
```
time="2022-04-01T10:01:52Z" level=error msg="failed to reconcile agent spec due to rootDeviceHints provided" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMACReconciler).reconcileAgentSpec" file="/go/src/github.com/openshift/origin/internal/controller/controllers/bmh_agent_controller.go:399" bare_metal_host=ostest-extraworker-0 bare_metal_host_namespace=bug-2030480 error="Provided hints are not eligible. &{/dev/unknown     0    <nil>}" go-id=615 request_id=0facdd20-f3aa-42ea-baf8-9692bb11e9ef
```

Providing a valid device `/dev/sda`, we got this log:
```
  {
    "cluster_id": "f9cefe22-4e3e-4bc8-82f6-1078caa3a2c4",
    "event_time": "2022-04-01T10:14:34.044Z",
    "host_id": "29d87175-3d65-4a8b-a8e3-eb1efd15fdc0",
    "infra_env_id": "42e2c764-2100-4a77-a7c2-fe39dd9f6b16",
    "message": "Host: extraworker-0, reached installation stage Writing image to disk: 100%",
    "name": "host_install_progress_updated",
    "severity": "info"
  },
```

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [X] [Bug fix](https://bugzilla.redhat.com/show_bug.cgi?id=2030480)
- [X] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @mkowalski 
/cc @bjacot 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by mkowalski** [comment]
/hold

After testing #3606 turns out that throwing `reconcileError{err}` in the BMAC leaves us with no user-visible error message, whereas finishing reconciliation successfully and passing an obviously invalid device to the Agent's spec causes Assisted Installer to fail the validation with an explicit message to the user.

**Comment by erusso7** [comment]
The other solution is already merged [#3606](https://github.com/openshift/assisted-service/pull/3606)

**Pull request closed without merging**
