### PR TITLE
MGMT-6765 document how to run ZTP workflow

### PR DESCRIPTION
**Pull request by osherdp**
Maybe have asked for us to have this.
It will explain step-by-step how to setup the environment and run the flow.
/cc @eranco74 @flaper87 @YuviGold @tsorya 
/hold

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm
:1st_place_medal:

**Comment by lranjbar** [comment]
/lgtm

I think it explains the process of running the ztp flow on dev-scripts well. 🎉

**Review by lranjbar — APPROVED** [review]

**Comment by osherdp** [comment]
/unhold
thanks @eranco74 and @lranjbar !

**Pull request merged**
