### PR TITLE
MGMT-4010, Bump OCP version from 4.6.12 to 4.6.999999999999 (auto created)

### PR DESCRIPTION
**Pull request by oshercc**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by oshercc** [comment]
test-infra test failed, HOLD label is set, see http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/4518/

**Comment by omertuc** [comment]
CI-test, please ignore

**Comment by oshercc** [comment]
Created a PR in app-interface GitLab https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/14799

**Pull request closed without merging**
