### PR TITLE
MGMT-4179: Move KubeAPI types to under the top-level directory

### PR DESCRIPTION
**Pull request by nmagnezi**
# Assisted Pull Request

## Description

This change migrates kubeAPI types to be a top-level directory.
Imports and docs were updated to match the new location.

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @filanov 
/cc @rollandf 
/cc @danielerez 
/cc @eliorerz 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [x] Are the title and description (in both PR and commit) meaningful and clear?
- [x] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — COMMENTED** [review]
I think that you need to change https://github.com/openshift/assisted-service/blob/master/PROJECT as well. 
I don't remember what does it do - @djzager ?

**Comment by nmagnezi** [comment]
> I think that you need to change https://github.com/openshift/assisted-service/blob/master/PROJECT as well.
> I don't remember what does it do - @djzager ?

@filanov Done.

**Comment by djzager** [comment]
> I think that you need to change https://github.com/openshift/assisted-service/blob/master/PROJECT as well.
> I don't remember what does it do - @djzager ?

My understanding is that it's needed for the `operator-sdk` commands that we use to generate manifests, bundles, etc.

**Review by djzager — APPROVED** [review]

**Pull request merged**
