### PR TITLE
MGMT-4079 CNV update

### PR DESCRIPTION
**Pull request by pkliczewski**
This PR updates OLM operator plugins development doc and adds cnv operator to monitored operators.

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
@gamli75, @machacekondra, @masayag, @jordigilh, @jakub-dzon please review

**Comment by jakub-dzon** [comment]
Looks good

**Pull request merged**
