### PR TITLE
Bug 1979906: Fix requeue logic inside mapInfraEnvToBMH

### PR DESCRIPTION
**Pull request by mkowalski**
This is a manual backport of #2173. We do not wait for the bot so that we can save some time and start CI run already in parallel as we wait for the master to merge.

/cc @flaper87 
/cc @rollandf 
/cc @akrzos

### CODE REVIEW

**Comment by mkowalski** [comment]
Tested with @flaper87 and @akrzos and 60 out of 60 nodes went to `provisioned`

```
[root@f16-h11-000-1029p ~]# oc get -A bmh
NAMESPACE               NAME                 STATE         CONSUMER                  ONLINE   ERROR
openshift-machine-api   openshift-master-0   unmanaged     bm-s4t98-master-0         true
openshift-machine-api   openshift-master-1   unmanaged     bm-s4t98-master-1         true
openshift-machine-api   openshift-master-2   unmanaged     bm-s4t98-master-2         true
openshift-machine-api   openshift-worker-0   unmanaged     bm-s4t98-worker-0-m55ng   true
openshift-machine-api   openshift-worker-1   unmanaged     bm-s4t98-worker-0-qphcx   true
sno00001                sno00001             provisioned                             true
sno00002                sno00002             provisioned                             true
[...]
sno00059                sno00059             provisioned                             true
sno00060                sno00060             provisioned                             true
```

**Review by flaper87 — APPROVED** [review]
:pizza:

**Pull request merged**
