### PR TITLE
MGMT-8447: Remove assisted-service-iso APIs and implementation

### PR DESCRIPTION
**Pull request by carbonin**
This was already set up to always return a 400 if the image service is
configured. Now that the image service is required this can just be
removed.

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-8447

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @nmagnezi 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [ ] ~~This change does not require a documentation update (docstring, `docs`, README, etc)~~ Updated
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
@nmagnezi @filanov I know we originally said we weren't going to edit the swagger or generated files on the first pass, but since this is an entirely separate API handler and it was already responding with 400 errors I figured it was easy enough to remove and probably wouldn't run into any conflicts.

**Review by filanov — APPROVED** [review]

**Comment by carbonin** [comment]
Do we need this test on this PR given that all the others passed? It's not marked as required.

I can override it if it doesn't pass this time ...

**Review by filanov — APPROVED** [review]

**Pull request merged**
