### PR TITLE
Add ppc64le & s390x RHCOS ISOs to configmap - rebase

### PR DESCRIPTION
**Pull request by jacobemery**
Rebase of previous [PR](https://github.com/openshift/assisted-service/pull/4333) that we stopped working on because CI/CD tests were failing on it. But in talking more we've realized this is ok and will need to make other changes in other Assisted Installer repos, and these changes don't break anything else.

Here's the [epic](https://issues.redhat.com/browse/MULTIARCH-2889) in the multi-arch Jira that this work is a part of, feel free to add labels that are relevant for the Assisted Installer team.

This PR adds ppc64le and s390x 4.11.9 RHCOS ISOs to match the recently added corresponding multi-arch release image for OCP, which includes these architectures.

@mkowalski had a [PR](https://github.com/openshift/assisted-service/commit/76c665404295aef6f822f49479f8ec9e58ce7fd2) merged that added a 4.11 multi-arch OCP image to the podman configmap. This multi-arch image included ppc64le and s390x, but these architectures were not added to the list of RHCOS ISOs. This PR adds them to the data/default_os_images.json file and the corresponding changes that were propagated via running 'make generate-configuration' in the project's root directory at the direction of @vrutkovs. 

Running the 'make generate-configuration' changed the config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml to add the s390x and ppc64le images, but it also made some less than desirable YAML reformatting changes. I reverted those as a part of this PR as well.

## List all the issues related to this PR
https://github.com/openshift/assisted-service/commit/76c665404295aef6f822f49479f8ec9e58ce7fd2
https://github.com/openshift/assisted-service/pull/4333

- [X] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [X] Title and description added to both, commit and PR. - Yes
- [X] Relevant issues have been associated (see [CONTRIBUTING] guide) - Yes
- [X] This change does not require a documentation update (docstring, `docs`, README, etc) - Not yet
- [X] Does this change include unit-tests (note that code changes require unit-tests) - No

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

This looks good, but will need to wait until the corresponding changes are made in the image service.
Right now attempting to deploy the image service with an s390x iso will crash it.

**Comment by mkowalski** [comment]
Is it going to "just work" with ppc64le? If yes, then my suggestion would be to have a separate PR for ppc64le that we can merge today, and one for s390x that will wait for the implementation in the Image Service.

From my experience holding a PR that modifies `default_*.json` is pointless as those require manual rebase once per week...

**Comment by carbonin** [comment]
>Is it going to "just work" with ppc64le?

I don't know. Either way I'd like to get one of those ISOs into the [image-service integration tests](https://github.com/openshift/assisted-image-service/blob/568b59ec570d2b2ed15f5070bb29697fc01c9525/integration_test/images_test.go#L32-L63) before merging something here that would cause the image service to fail on startup as that will fail every one of our e2e and subsystem CI jobs.

Actually do we run those on these PRs? I'd think it would fail here. Let's see.

/ok-to-test

**Comment by carbonin** [comment]
Yup, checks out:

```
waiting.exceptions.TimeoutExpired: Timeout of 1800 seconds expired waiting for assisted-image-service to be healthy
```

So we'll need the changes in the image service before we can merge this (at least in its current form).
Maybe just ppc64le would be able to get in?

**Comment by mkowalski** [comment]
> Maybe just ppc64le would be able to get in?

That was my suggestion. If we know s390x breaks image service, let’s not even consider it for now. If ppc64le has a chance to work (i.e. we don’t see a clear blocker), let’s feed only this arch into our CI and see how it behaves

**Comment by jacobemery** [comment]
@mkowalski @carbonin 

For ppc64le, we'd need to add another path to the list that the image service checks for the grub.cfg, and skip the tests related to isolinux.cfg.

For s390x, I think we should just skip minimal iso extraction for now, and we can add it back in if/when the CoreOS team enables it with `coreos-installer iso extract minimal-iso` command. And then we also need to skip the isolinux.cfg tests for s390x too. 

Here's a link [link](https://github.com/openshift/assisted-image-service/compare/main...jacobemery:assisted-image-service:main) to my working branch for the image-service where I have done the previous suggestions except for the ones regarding skipping isolinux.cfg tests because...

I need some help with that part. When I was testing previously in my now [stashed branch](https://github.com/openshift/assisted-image-service/compare/main...jacobemery:assisted-image-service:stash), I just nullified the isolinux.cfg tests, but that was just for testing, we can't just skip those. @carbonin suggested we split up the function in [pkg/isoeditor/rhcos.go](https://github.com/openshift/assisted-image-service/blob/main/pkg/isoeditor/rhcos.go), one for grub.cfg and one for isolinux.cfg and pass in arch so we can skip it based on whether we expect it for that arch (s390x and ppc64le both don't have isolinux.cfg files). Could I get some help on re-writing that?

**Comment by carbonin** [comment]
I'm going to pair with @jacobemery tomorrow on the image service changes. For now I think we should move this to wip/draft and just wait until we have those in.

Turns out ppc64le needs some of the same changes s390x needs so we'll handle them in one image service PR then come back to this.

**Comment by jacobemery** [comment]
> we'll handle them in one image service PR then come back to this.

@carbonin and I collaborated on and opened a [PR](https://github.com/openshift/assisted-image-service/pull/109) in the assisted-image-service.

**Comment by jacobemery** [comment]
> > we'll handle them in one image service PR then come back to this.

Our [PR](https://github.com/openshift/assisted-image-service/pull/109) in assisted-image-service merged. 

Could we re-test here?

**Comment by carbonin** [comment]
- The generated code one looks like a real failure. You'll need to regenerate again (or give me colab on your fork and let me do it if you don't want to set up the tooling).
- The unit tests are failing because one is referencing power and it was assuming it would fail, but the test is reading that defaults file so that will need to change in some way.
- The subsystem tests seem to not be using the most recent image service based on these logs:
```
{"file":"/go/src/github.com/openshift/origin/pkg/imagestore/imagestore.go:231","func":"github.com/openshift/assisted-image-service/pkg/imagestore.(*rhcosStore).Populate","level":"info","msg":"Creating minimal iso for 4.11-411.86.202210171842-0-s390x","time":"2022-12-22T16:09:56Z"}
{"error":"no grub.cfg found, possible paths are [EFI/redhat/grub.cfg EFI/fedora/grub.cfg]","file":"/go/src/github.com/openshift/origin/pkg/isoeditor/rhcos.go:52","func":"github.com/openshift/assisted-image-service/pkg/isoeditor.(*rhcosEditor).CreateMinimalISOTemplate","level":"warning","msg":"Failed to edit template configs","time":"2022-12-22T16:10:10Z"}
{"file":"/go/src/github.com/openshift/origin/main.go:74","func":"main.main.func1","level":"fatal","msg":"Failed to populate image store: failed to create minimal iso template for version map[cpu_architecture:s390x openshift_version:4.11 url:https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-s390x-live.s390x.iso version:411.86.202210171842-0]: no grub.cfg found, possible paths are [EFI/redhat/grub.cfg EFI/fedora/grub.cfg]\n","time":"2022-12-22T16:10:10Z"}
```

**Comment by jacobemery** [comment]
@carbonin ah right, I forgot about assisted-service using ppc64le as one of the non-supported archs during testing. I remember we caught this a while back too.

I'll add you as a collaborator to my fork.

**Comment by jacobemery** [comment]
Just pushed a few changes:
- [Synced](https://github.com/openshift/assisted-service/pull/4796/commits/757660599bdf1b8543ecdb7cd4e2ea89ba9653ad) my fork to pull in the most recent changes to the assisted-service.
- [Added](https://github.com/openshift/assisted-service/commit/6ed7ecd6acae4014241ed937921e4be531955e32) ppc64le and s390x to deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- [Nullified](https://github.com/openshift/assisted-service/commit/828b91acf46564abf346ce11bd223fff5fcf9df3) the now obsolete test against ppc64le in subsystem/kubeapi_test.go
- Ran 'make generate-configuration'" and [added](https://github.com/openshift/assisted-service/commit/0241c2e7fe2f26488a67259d6935149ec85d349e) resulting changes, including [reverting](https://github.com/openshift/assisted-service/commit/04d067a7e9cc074af460be1f93e047a3ef097f65) some unnecessary YAML reformatting that it did.

@carbonin I still need help with:
- internal/versions/versions_test.go it looks like it has changed some since we made changes [last time](https://github.com/openshift/assisted-service/commit/3e0f2c385c3259df0284c1851105930e06c77498). I can't seem to find the section on "release image without matching OS image" where we added chocobomb-fake-architecture. Nor the other changes we made to that file. You can find what we did previously in the linked commit from the previous PR.

**Comment by carbonin** [comment]
/unhold

This should be good to review now.

**Comment by romfreiman** [comment]
I assume this is the wrong pr to comment about, but do we have a feature flag for this logic? So we'll be able to expose it only to specific orgs from the SaaS? and in this way to provide users early access and test the functionality without us committing

**Comment by mkowalski** [comment]
> I assume this is the wrong pr to comment about, but do we have a feature flag for this logic? So we'll be able to expose it only to specific orgs from the SaaS? and in this way to provide users early access and test the functionality without us committing

You need multiarch release images to benefit from this feature anyway, so isn't it already covered? PowerPC ISO is useless without PowerPC release image and the latter is already filtered per org

**Comment by romfreiman** [comment]
im not sure it's about multi arch. I assume the default support goes with specific arch?

**Comment by jacobemery** [comment]
@mkowalski @romfreiman @carbonin Happy new year all! Thanks for the continued help on this. 

> do we have a feature flag for this logic?

We didn't add any feature flags yet, should we add it with this PR? Or can it be in a subsequent one.

> You need multi-arch release images to benefit from this feature anyway, so isn't it already covered?

Correct me if I'm wrong, but I thought the multi-arch release images have already been added.

**Comment by mkowalski** [comment]
> > You need multi-arch release images to benefit from this feature anyway, so isn't it already covered?
> 
> Correct me if I'm wrong, but I thought the multi-arch release images have already been added.

That's correct. I think what Rom is trying to say here is that he wants to have ability to set different support levels for different architectures even if they come from the same release payload.

I'm only guessing, but he wants to have a way of saying "4.12 on ARM via multi-arch payload is Tech Preview, but 4.12 on PowerPC using the same multi-arch payload is only Dev Preview"

**Comment by jacobemery** [comment]
> ability to set different support levels for different architectures even if they come from the same release payload

Ahh ok, thanks for the clarification @mkowalski, that would be good to have.

How can we go about doing that?

**Comment by carbonin** [comment]
> 4.12 on ARM via multi-arch payload is Tech Preview, but 4.12 on PowerPC using the same multi-arch payload is only Dev Preview

This is interesting .. it doesn't actually seem possible to do this through the UI even after merging this PR.

Currently the user just chooses the release by name then has a checkbox to say if they want arm or not (not being x86 then I suppose).

Does this concern still matter if it isn't possible to get the other architectures even after this change?

**Comment by jacobemery** [comment]
> it doesn't actually seem possible to do this through the UI even after merging this PR.
> 
> Currently the user just chooses the release by name then has a checkbox to say if they want arm or not (not being x86 then I suppose).

Right, UI changes are still needed before these architectures can be chosen, i.e. arm checkbox -> architecture dropdown.

> Does this concern still matter if it isn't possible to get the other architectures even after this change?

Good point, I'm not sure. What do you think @mkowalski and @romfreiman? Maybe it would be good to do in anticipation of the UI changes? Would this be a complex change in assisted-service?

**Comment by romfreiman** [comment]
@carbonin @jacobemery not sure I understand the question.

**Comment by carbonin** [comment]
Even after we merge this no one will be able to choose these new architectures through the UI.
Given this, do we need to block this for a feature flag?

**Comment by romfreiman** [comment]
Anyhow it goes to master and not to prod. So not sure we have to block it. But lets work on ff + ability to expose to specific orgs

**Comment by mkowalski** [comment]
> Currently the user just chooses the release by name then has a checkbox to say if they want arm or not (not being x86 then I suppose).

To state the obvious, but may be a good to remind ourselves what it does - the checkbox in the UI is responsible for setting the `architecture` field on the InfraEnv that is created. So not selecting it today will set `architecture: x86_64` and selecting will set `architecture: arm64`. This is not changing anytime soon as multi-arch infraenvs are not possible due to fact ISO cannot be multi-arch.

**Comment by carbonin** [comment]
Looks like there's another subsystem test that's assuming power os images don't exist.

Can you update this one @jacobemery https://github.com/openshift/assisted-service/blob/8b9913b2965a4eb5d829f0df56f9d0daa2786951/subsystem/cluster_v2_test.go#L477-L493 ?

**Comment by carbonin** [comment]
Opened https://issues.redhat.com/browse/MGMT-13190 to track the org-based exposure of these architectures.

**Comment by jacobemery** [comment]
> Looks like there's another subsystem test that's assuming power os images don't exist.
> 
> Can you update this one @jacobemery?

Done

**Comment by carbonin** [comment]
The subsystem test is now failing with something different :facepalm: 

```
[V2ClusterTests] multiarch
/assisted-service/subsystem/cluster_v2_test.go:369
  Fail to register infraenv with missing OS image [It]
  /assisted-service/subsystem/cluster_v2_test.go:477
  Expected
              
      <string>: The requested RHCOS version (4.11, arch: risc-v) does not have a matching OpenShift release image
  to contain substring
      <string>: No OS image for Openshift version 4.11.0-multi and architecture risc-v
```

Maybe it's best to just remove this test since it's now pretty much the same case as the one that follows it and I don't think we can make it different now that we don't have a mismatch between release and OS images (both support the same set of architectures).

**Comment by jacobemery** [comment]
> Maybe it's best to just remove this test

Done

**Review by carbonin — APPROVED** [review]

**Comment by jacobemery** [comment]
@danielerez @slaviered requesting your review for this PR. Could you take a look?

**Pull request merged**
