### PR TITLE
Bug 2073814: Assisted service POD is evicted when installing large multi-node cluster

### PR DESCRIPTION
**Pull request by ori-amizur**
- Filters are role , status
    - By default inventory and connectivity are not returned unless
      requested explicitly
    - Also add option in V2GetCluster api call to exclude the hosts from the
      result.

This is backport to 2.5

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @filanov 
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by filanov** [comment]
what is the original PR so i can compare?

**Comment by ori-amizur** [comment]
> what is the original PR so i can compare?

https://github.com/openshift/assisted-service/pull/3535

And

https://github.com/openshift/assisted-service/pull/3574

**Comment by filanov** [comment]
@ori-amizur please replace to BZ.

**Comment by filanov** [comment]
LGTM just need to replace with BZ

**Review by filanov — APPROVED** [review]

**Pull request merged**
