### PR TITLE
[release-ocm-2.5] MGMT-11412: fix flaky installation of golangci-lint

### PR DESCRIPTION
**Pull request by osherdp**
Basically a manual backport of https://github.com/openshift/assisted-service/pull/4077.

### CODE REVIEW

**Comment by eliorerz** [comment]
/retitle [release-ocm-2.5] MGMT-11412: fix flaky installation of golangci-lint

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by osherdp** [comment]
Requires https://github.com/openshift/release/pull/30948

**Pull request merged**
