### PR TITLE
MGMT-19190: Bump LSO version override to 4.18

### PR DESCRIPTION
**Pull request by danmanor**
Bump LSO version override to 4.18 to enable assisted operator deployment scripts for OCP 4.18

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eifrach** [comment]
verifed the package is found in 4.17
```bash
$ oc-mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.17 --package=local-storage-operator
NAME                    DISPLAY NAME  DEFAULT CHANNEL
local-storage-operator                stable

PACKAGE                 CHANNEL  HEAD
local-storage-operator  stable   local-storage-operator.v4.17.0-202410160306
```
missing in 4.18
```bash
$ oc-mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.18 --package=local-storage-operator
error: package "local-storage-operator" not found

```

/lgtm

**Review by adriengentil — APPROVED** [review]

**Comment by danmanor** [comment]
ZTP connected job succeeded but got timeout before it could finish, disconnected jobs are broken

**Comment by danmanor** [comment]
/override ci/prow/edge-e2e-ai-operator-disconnected-capi ci/prow/edge-e2e-ai-operator-ztp-disconnected ci/prow/edge-e2e-ai-operator-ztp

**Comment by danmanor** [comment]
FYI - @CrystalChun @carbonin

**Pull request merged**
