### PR TITLE
MGMT-7582: Fix hasMemoryForRole validation message

### PR DESCRIPTION
**Pull request by eliorerz**
Fix hasMemoryForRole validation message validating by UsableBytes but the message showing PhysicalBytes value

image

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @omertuc 
/cc @avishayt

### CODE REVIEW

**Comment by avishayt** [comment]
We should use physical - the correct fix is to change printHasMemoryForRole to use physical instead of usable

**Comment by eliorerz** [comment]
> We should use physical - the correct fix is to change printHasMemoryForRole to use physical instead of usable

It was changed few weeks ago https://github.com/openshift/assisted-service/pull/2115

**Comment by omertuc** [comment]
>Fix hasMemoryForRole validation message validating by UsableBytes but the message showing PhysicalBytes value

But the diff in this PR changed the message from usable to physical? It's the opposite of the PR description.

**Pull request merged**
