### PR TITLE
NO-ISSUE: Fixing metrics subsystem-test's spamming.

### PR DESCRIPTION
**Pull request by ybettan**
# Description

The test was using ginkgoWriter to print the metrics in case of failure
for debugging, but the issue was this buffer was filled multiple times
in each test, therefore, when printed, it duplicated the printed metrics
multiple times.

This fix is making sure the buffer gets written only once in each test.

Signed-off-by: Yoni Bettan <ybettan@redhat.com>

# What environments does this code impact?

- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

# How was this code tested?

Please, select one or more if needed:

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

It's recommended to take a few extra minutes to provide more information about
how this code was tested. Here are some questions that may be worth answering:

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run?
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

# Assignees

Please, add one or two reviewers that could help review this PR.

/assign @
/assign @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change includes unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ybettan** [comment]
/hold
Waiting to see the output of subsystem tests

**Comment by ybettan** [comment]
/unhold
Output seems OK:

4 tests failed:
```
$ cat subsystem.out | tail -n50
...
Summarizing 4 Failures:

[Fail] Metrics tests Host validation metrics [It] 'machine-cidr-defined' failed
/home/ybettan-linux/go/src/github.com/assisted-service/subsystem/metrics_test.go:166

[Fail] Metrics tests Host validation metrics [It] 'ntp-synced' failed
/home/ybettan-linux/go/src/github.com/assisted-service/subsystem/metrics_test.go:166

[Fail] Metrics tests Cluster validation metrics [It] 'all-hosts-are-ready-to-install' failed
/home/ybettan-linux/go/src/github.com/assisted-service/subsystem/metrics_test.go:166

[Fail] Metrics tests Cluster validation metrics [It] 'sufficient-masters-count' failed
/home/ybettan-linux/go/src/github.com/assisted-service/subsystem/metrics_test.go:166

Ran 181 of 182 Specs in 2053.916 seconds
FAIL! -- 177 Passed | 4 Failed | 0 Pending | 1 Skipped

$ cat subsystem.out | grep { | grep -v bucket | cut -d" " -f1 | sort | uniq -c | tail -n2 | head -n1
      4 service_assisted_installer_operation_duration_miliseconds_sum{operation="OCM-UpdateSubscriptionStatusActive"}
      (4 instances of a single metric record in the output)
```

0 tests failed:
```
```

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-operator-ztp
Unrelated error

**Pull request merged**
