### PR TITLE
OCPBUGSM-31903: Match 4.7 rootfs with iso version

### PR DESCRIPTION
**Pull request by carbonin**
# Assisted Pull Request

## Description

Commit ebe50b8caf2ef2fc8890b917339b1f74a2ed09f9 updated the rhcos image
url but didn't change the rootfs url to match. This is causing a hash
mismatch when a machine tries to download the rootfs causing the boot to
fail.

We have to update the template version here because the rootfs url is
baked into the minimal iso template.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1980753

## Failure Screenshot

image (4)

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

I deployed the assisted service in minikube, generated a 4.7 minimal iso and booted it to reproduce the issue.
To test the fix, I deleted the 4.7 minimal template and redeployed the service with the new value in `default_ocp_versions.json`.
A machine booted with an iso generated with the new deployment successfully pulled the rootfs and booted into the live iso.

## Assignees

/cc @danielerez 
/cc @oshercc 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
@oshercc is there some automation that needs updating to make sure this doesn't happen again or are you updating those versions manually?

**Comment by oshercc** [comment]
this is not changed as part of the automation updates and needs to be added some how, 

> @oshercc is there some automation that needs updating to make sure this doesn't happen again or are you updating those versions manually?

for some reason, this was not automatically updated as part of the automation, 
opened a task to fix: https://issues.redhat.com/browse/MGMT-7198

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
