### PR TITLE
NO-ISSUE: Fix hypershift destroy in CI test script

### PR DESCRIPTION
**Pull request by CrystalChun**
Missed modifying the hypershift destroy command
after changing the hypershift cli function to always run in the pod.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by paul-maidment** [comment]
For context, it might be good to have a link to your original PR here, it's harder to review this without context on how the hypershift command was changed

**Comment by CrystalChun** [comment]
> For context, it might be good to have a link to your original PR here, it's harder to review this without context on how the hypershift command was changed

Thanks for the feedback. I'll keep that in mind for next time.

> If this is the case then this PR looks good to me as you are simply correcting a place where you forgot to prefix a command with hypershift and all other commands in this file appear to follow this convention.

Yes, this is it.

> Why did you stop embedding hypershift into commands issued via hypershift_cli, I am making an assumption that this was to provide some degree of flexibility?

`hypershift_cli` previously had two paths:

1. disconnected which had a local `hypershift` binary downloaded and ran with that local binary 
2. connected which ran directly in the `hypershift` pod using the `hypershift` image

The connected way didn't require specifying the `hypershift` command as it targeted that command automatically when running the pod.

However, to also support disconnected running in the `hypershift` pod, the command to [update the CA trust before running `hypershift` is required](https://github.com/openshift/assisted-service/commit/b3b43c230adb091e06ad35fa4ff1b56913c6d293#diff-4b29d8945d215e31eee27b9391e2def7a525776ebfc850e827ffda4bac63fdccR172) and doing that required actually calling the `hypershift` command directly.

**Pull request merged**
