### PR TITLE
NO-ISSUE Increase timeout for assisted-service pod in operator deployment

### PR DESCRIPTION
**Pull request by lranjbar**
Not sure why I'm seeing this timeout now. Did something change with the assisted-service pod? @YuviGold @osherdp 

Timeouts here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17966/rehearse-17966-pull-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-bmh/1389357728454938624

### CODE REVIEW

**Comment by osherdp** [comment]
@lranjbar not a timeout. I think it's because of:
```storageclass.storage.k8s.io "assisted-service" not found```

And @YuviGold refactored related code yesterday, might be related to his changes

**Comment by lranjbar** [comment]
Resolved with https://github.com/openshift/release/pull/18285

**Pull request closed without merging**
