### PR TITLE
MGMT-6775 Bump OCP versions 4.7.11 -> 4.7.12, 4.8.0-fc.3 -> 4.8.0-fc.7

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.8 has no available release notes
4.7 release notes: https://access.redhat.com/errata/RHSA-2021:1561

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by romfreiman** [comment]
fc.5 is broken - sno will not work

**Comment by romfreiman** [comment]
Please update the commit message - it still says fc.5

**Comment by gamli75** [comment]
/retitle MGMT-6775, Bump OCP versions 4.7.11 -> 4.7.12, 4.8.0-fc.3 -> 4.8.0-fc.7

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
