### PR TITLE
MGMT-4543 Updating versions to latest releases (#1436)

### PR DESCRIPTION
**Pull request by gamli75**
Co-authored-by: osher cohen <oscohen@localhost.localdomain>

### CODE REVIEW

**Comment by YuviGold** [comment]
Notice that there is no e2e running for this change

**Comment by gamli75** [comment]
@YuviGold I know, I'm not worried about it because it was already merged to master and there is Jenkins job that runs subsystem tests after it will be merged http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/release_v1.0.18/

**Comment by YuviGold** [comment]
> @YuviGold I know, I'm not worried about it because it was already merged to master and there is Jenkins job that runs subsystem tests after it will be merged http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/release_v1.0.18/

Great. Just wanted to make sure. 
/unhold

**Pull request merged**
