### PR TITLE
NO-ISSUE Fixes in kubeAPI subsystem tests

### PR DESCRIPTION
**Pull request by rollandf**
- Increase timeout on some asserts
 - Wait for Installing instead of Preparing for Installation

### CODE REVIEW

**Comment by YuviGold** [comment]
Maybe it should use the `waitForClusterState` logic?
https://github.com/openshift/assisted-service/blob/ac59176add3f1a5f89fe47e1df021d9c9ab7589c/subsystem/cluster_test.go#L302-L327

**Review by filanov — APPROVED** [review]

**Comment by filanov** [comment]
@YuviGold for some states it make sense to wait for consistent state, in this case that we are waiting for installing it doesn't need to be consistent. 
for now the flow is to reconcile on the cluster resource every 10 seconds so the interval need to be really big, later we will change this logic to work with backend notification and then we can work with the model that you specified.

**Review by osherdp — APPROVED** [review]

**Comment by romfreiman** [comment]
/hold
To reduce spam

**Comment by carbonin** [comment]
/unhold

All tests are green. The spam should stop now.

**Comment by rollandf** [comment]
Thanks @carbonin !

**Pull request merged**
