### PR TITLE
MGMT-7817: Improvements for the operator upgrade CI job 

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
# Assisted Pull Request

## Description
Improvements for the operator upgrade CI job and related scripts. Below improvements are made:
- When  `ASSISTED_UPGRADE_OPERATOR` is `true` meaning we want to upgrade the operator then use `ASSISTED_DEPLOYMENT_METHOD` as `community-operators` in setup_assisted_operator.sh
- Use separate baremetal hosts to install SNO before and after the operator upgrade
- Better usage of env var related to operator upgrade

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by pawanpinjarkar** [comment]
/hold
May be not needed

**Review by flaper87 — APPROVED** [review]
:pizza:

**Pull request merged**
