### PR TITLE
MGMT-9272 Automatic agent classification labels

### PR DESCRIPTION
**Pull request by avishayt**
Resubmitting [this PR](https://github.com/openshift/assisted-service/pull/3516) which was [reverted](https://github.com/openshift/assisted-service/pull/3594) due to [this bug](https://issues.redhat.com/browse/MGMT-9840) which has now been fixed.

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/assign @filanov 
/assign @nmagnezi 
/assign @omertuc 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by omertuc** [comment]
Can you outline the differences from the previous PR, if any?

**Comment by avishayt** [comment]
> Can you outline the differences from the previous PR, if any?

No differences.  Rebased with no conflicts.

**Comment by omertuc** [comment]
Waiting for https://github.com/openshift/assisted-test-infra/pull/1633

**Pull request merged**
