### PR TITLE
MGMT-9023: Add hyperthreading feature usage

### PR DESCRIPTION
**Pull request by CrystalChun**
https://issues.redhat.com/browse/MGMT-9023
The hyperthreading feature usage will appear like
this:
````
  "Hyperthreading": {
    "data": {
      "hyperthreading_enabled": "all"
    },
    "id": "HYPERTHREADING",
    "name": "Hyperthreading"
  },
````

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

Test steps:
1. Deploy assisted-service with these changes and created a cluster
2. Get the cluster's feature usage to see the default setting was applied
    ````
    $ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} | jq -r '.feature_usage' | jq '.Hyperthreading'
      "Hyperthreading": {
        "data": {
          "enabled": "all"
        },
        "id": "HYPERTHREADING",
        "name": "Hyperthreading"
      }
    ````
3. Patch the cluster to not use hyperthreading
    ````
    $ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} -X PATCH -H "Content-Type: application/json" -d '{"hyperthreading":"none"}'
    ````
5. Get the cluster's feature usage to see the feature usage was removed
    ````
    $ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} | jq -r '.feature_usage' | jq '.Hyperthreading'
    null
    ````
7. Patch the cluster to only use hyperthreading on masters
    ````
    $ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} -X PATCH -H "Content-Type: application/json" -d '{"hyperthreading":"masters"}'
    ````
9. Get the cluster's feature usage to see the feature usage only set it to masters
    ````
    $ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} | jq -r '.feature_usage' | jq '.Hyperthreading'
      "Hyperthreading": {
        "data": {
          "enabled": "masters"
        },
        "id": "HYPERTHREADING",
        "name": "Hyperthreading"
      }
    ````

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests) - added subsystem test check

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

/cc @carbonin

### CODE REVIEW

**Comment by slaviered** [comment]
First,kudos on the detailed list of how to test this feature. I have a small comment: 
since the purpose of this field is to be ingested by a server that flushes it into elastic and since this piece of code flattens the data with no prefixing please name the field in a less generic way (like hyper_mode or something along this line). 

Also please notice that you need the extra data field only if you are planning to have a dashboard that analyzes the types of hyperthreading used. If it is not of interest to the managers/product owners you can omit it (but you can leave it too, as long it has a prefixed name it will not do much harm)

**Comment by CrystalChun** [comment]
> First,kudos on the detailed list of how to test this feature. I have a small comment:
since the purpose of this field is to be ingested by a server that flushes it into elastic and since this piece of code flattens the data with no prefixing please name the field in a less generic way (like hyper_mode or something along this line).

>Also please notice that you need the extra data field only if you are planning to have a dashboard that analyzes the types of hyperthreading used. If it is not of interest to the managers/product owners you can omit it (but you can leave it too, as long it has a prefixed name it will not do much harm)

````
  "Hyperthreading": {
    "data": {
      "hyperthreading_enabled": "all"
    },
    "id": "HYPERTHREADING",
    "name": "Hyperthreading"
  },
````

Thanks for reviewing @slaviered! Modified the data field to this, what do you think?

**Pull request merged**
