### PR TITLE
MGMT-7752: Bump OCP versions 4.8.5 -> 4.8.9, 4.7.24 -> 4.7.28

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @YuviGold
4.7 release notes: https://access.redhat.com/errata/RHSA-2021:3262
4.8 has no available release notes

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by YuviGold** [comment]
The disconnected job is broken until https://github.com/openshift/assisted-service/pull/2566 get merged
Please rerun to verify nothing gets broken
/hold
/lgtm

**Comment by romfreiman** [comment]
But it will never merged now... Will take another week :(

**Comment by YuviGold** [comment]
> But it will never merged now... Will take another week :(

We can merge it but we don't know if this bump could affect the disconnected job because it is broken ATM.
If you think it's not something that we should hold on to, then you can unhold and the PR would get merged.

**Comment by romfreiman** [comment]
if it's broken on 4.8.5 I dont think 4.8.9 will make it worse/better. So IMO we can merge.

**Pull request merged**
