### PR TITLE
Bug-2070838: Installation on baremetal SNO failed because 2 interfaces had overlapping subnets

### PR DESCRIPTION
**Pull request by ori-amizur**
When installing host with overlapping subnets, the installation may
fail.
Added validation that no host has addresses that belong to overlapping
networks.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @filanov 
/cc @avishayt 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ori-amizur** [comment]
> Overall, looks good. I think this validation should take into account the API (and Ingress) VIP. I don't think we care so much about overlapping networks, we care only if the user place a VIP on a network that the host have 2 interfaces on. Right?

Not sure about the VIPs.
The original problem happened on SNO - no VIPs

**Comment by tsorya** [comment]
It looks good but did we talk with ocp networking team? there should me requirement like this

**Pull request merged**
