### PR TITLE
MGMT-13447: Fix LVM subscription name is empty on SNO CNV

### PR DESCRIPTION
**Pull request by eliorerz**
Cherry-pick of https://github.com/openshift/assisted-service/pull/4930, https://github.com/openshift/assisted-service/pull/4963, https://github.com/openshift/assisted-service/pull/4959 and https://github.com/openshift/assisted-service/pull/4963

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

/cc @eliorerz

### CODE REVIEW

**Comment by eliorerz** [comment]
Also added https://github.com/openshift/assisted-service/pull/4959 and https://github.com/openshift/assisted-service/pull/4963

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
