### PR TITLE
MGMT-6532: Update Dockerfile.bundle for prow/ci-index

### PR DESCRIPTION
**Pull request by lranjbar**
Update the command prow/ci-index so that `IMAGES_BY_DIGEST=true`

### CODE REVIEW

**Comment by djzager** [comment]
And here I was trying to make the `Dockerfile.bundle` go away :sunglasses:

I'm not certain what we should do here. I was looking at the ci reference...specifically substitutions  (https://steps.ci.openshift.org/ci-operator-reference#line138) and it looks like we could simply specify the remainder of our images as [substitutions and prow ](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml#L43-L48) would take care of this for us. WDYT?

Let me know if I'm missing something.

**Comment by djzager** [comment]
> And here I was trying to make the `Dockerfile.bundle` go away

since I forgot to include it the first time around. Here is the PR I had submitted to openshift/release https://github.com/openshift/release/pull/18534

**Comment by lranjbar** [comment]
> And here I was trying to make the `Dockerfile.bundle` go away 
> 
> I'm not certain what we should do here. I was looking at the ci reference...specifically substitutions (https://steps.ci.openshift.org/ci-operator-reference#line138) and it looks like we could simply specify the remainder of our images as [substitutions and prow ](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml#L43-L48) would take care of this for us. WDYT?
> 
> Let me know if I'm missing something.

Ahhh... yeah I was testing this because I was confused with the error. I thought we would need the IMAGES_BY_DIGEST in prow. It looks like we wouldn't even need the `IMAGES_BY_DIGEST=true` in prow CI. Because it can substitute for us and it uses digest SHAs.

**Comment by osherdp** [comment]
@lranjbar where's the part it's doing ``MIROR_BY_DIGEST=true``?

**Comment by lranjbar** [comment]
@osherdp @YuviGold Closing and using https://github.com/openshift/release/pull/18534/files instead it will address this issue in prow CI

**Pull request closed without merging**
