### PR TITLE
MGMT-2624 removed proxy URL print when proxy URL is empty

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Review by avishayt — CHANGES_REQUESTED** [review]
Looks good, but please add a unit test where the proxy is not empty.

**Comment by omertuc** [comment]
> Looks good, but please add a unit test where the proxy is not empty.

Covered by https://github.com/openshift/assisted-service/blob/32d8818fcbab554964a4e14ab3b9867fc0d85e09/internal/bminventory/inventory_test.go#L158

Is that enough?

**Review by avishayt — APPROVED** [review]

**Pull request merged**
