### PR TITLE
[release-ocm-2.10] MGMT-18698: Use release image version as key instead of openshift version in unit-test

### PR DESCRIPTION
**Pull request by danmanor**
The current versions mechanism assumes on the fact that there are no two version which have the same `openshift_version` but different version. Therefore, we need to change one of the openshift versions to be x.y.z instead of x.y 

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danmanor** [comment]
/override ci/prow/e2e-ai-operator-ztp-sno-day2-workers ci/prow/e2e-ai-operator-ztp ci/prow/e2e-ai-operator-ztp-sno-day2-workers-late-binding

**Comment by danmanor** [comment]
/override ci/prow/e2e-ai-operator-ztp-sno-day2-workers ci/prow/e2e-ai-operator-ztp ci/prow/e2e-ai-operator-ztp-sno-day2-workers-late-binding

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
