### PR TITLE
MGMT-17773: Enforce go modules tidy

### PR DESCRIPTION
**Pull request by danmanor**
Currently, the assisted-service generated code test does not ensure that modules are tidy. This results in untidy builds which could potentially lead to build failures or redundant packages in builds. This PR enforces tidy all modules

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danmanor** [comment]
/override ci/prow/e2e-agent-compact-ipv4 ci/prow/edge-e2e-ai-operator-ztp ci/prow/edge-e2e-metal-assisted

**Comment by danmanor** [comment]
/override ci/prow/edge-subsystem-kubeapi-aws ci/prow/edge-subsystem-aws

**Comment by danmanor** [comment]
@adriengentil If we enforce it in the code itself, then no PR will be able to merge as it will not pass the generation test and the go code for building the images will be tidy and vendored across all images. your suggestion means we need to update it across all Dockerfiles instead of one place

**Comment by adriengentil** [comment]
I want to make sure that what we build is what we test. So if we perform tests/lint on code that when trough into go mod tidy, I think we should also make usre that we build also against the same code.

**Comment by danmanor** [comment]
lint should not test the code generation as well as we have a dedicated test for that. AFAIU the code used for lint/other tests will be the exact same code as would be in the builds, am I wrong ? @adriengentil

**Comment by adriengentil** [comment]
>lint should not test the code generation as well as we have a dedicated test for that. AFAIU the code used for lint/other tests will be the exact same code as would be in the builds, am I wrong ? @adriengentil 

To make a recap, this PR was created in the scope of dependabot builds failing because people push changes where `go mod tidy` was not run to them, right? So, we should have a presubmit check that verify that the go.mod is tidy. Does that makes sense?

Then, I agree that we should merge this PR to help developers to push the right changes then they upgrade go dependencies.

**Review by adriengentil — APPROVED** [review]

**Comment by danmanor** [comment]
/override ci/prow/e2e-agent-compact-ipv4 ci/prow/edge-e2e-ai-operator-ztp ci/prow/edge-e2e-metal-assisted ci/prow/edge-subsystem-kubeapi-aws ci/prow/edge-subsystem-aws

**Comment by danmanor** [comment]
/override ci/prow/e2e-agent-compact-ipv4 ci/prow/edge-e2e-ai-operator-ztp ci/prow/edge-e2e-metal-assisted ci/prow/edge-subsystem-kubeapi-aws ci/prow/edge-subsystem-aws

**Pull request merged**
