### PR TITLE
Bug 2035638: Stop BMH reconcile if InfraEnv label is missing

### PR DESCRIPTION
**Pull request by flaper87**
The reconcile loop was already stopping the BMH reconcile for CR's that
didn't have the infraenv label. However, this was happening after the
`inspect` label and cleaning were disabled, which caused BMAC to modify
BMH CR's that weren't part of the ZTP flow.

Move the infraenv check earlier in the `reconcileBMH` step so that BMAC
can stop the loop before doing changes to the CR.

Signed-off-by: Flavio Percoco <flavio@redhat.com>

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @mkowalski 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Comment by filanov** [comment]
@flaper87 this should be backported as well right?

**Comment by filanov** [comment]
/lgtm cancel
Can you please add tests covering it?

**Comment by filanov** [comment]
@flaper87 I see that two tests are failing in the subsystem, please take a look at them

**Comment by filanov** [comment]
@flaper87 retest will not help with the subsystem

**Comment by mkowalski** [comment]
ZTP failed for a reason of Metal3 repos renamed... It's already fixed up in dev-scripts

```
 +(utils.sh:270): sync_repo_and_patch(): git checkout master
error: pathspec 'master' did not match any file(s) known to git 
```

**Pull request merged**
