### PR TITLE
OCPRHV-637: Set 'replicas' to 0 in the machinset for the oVirt provider

### PR DESCRIPTION
**Pull request by mmartinv**
Set 'replicas' to 0 in the machinset instead of the install-config.yaml
This way we avoid the side effect of enabling the scheduling on masters
and MCO does not try to provision additional VMs at installation time.

This pull request depends on #3971 

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @eliorerz 
/cc @osherdp 
/cc @michaellevy101 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by romfreiman** [comment]
Does ovirt even work with ai?

**Comment by mmartinv** [comment]
> Does ovirt even work with ai?

Yes, it works pretty well actually

**Comment by osherdp** [comment]
> @mmartinv: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/edge-verify-generated-code	[7cbe7e6](https://github.com/openshift/assisted-service/commit/7cbe7e64d05a6c08e6bf1fe4cd316e3cbb81acc9)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/3972/pull-ci-openshift-assisted-service-master-edge-verify-generated-code/1541382992985853952)	true	`/test edge-verify-generated-code`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=assisted-service&pr=3972). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:mmartinv).

please do ``skipper make generate`` to fix that ^

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Pull request merged**
