### PR TITLE
NO-ISSUE: Allow use of 'envtest'

### PR DESCRIPTION
**Pull request by jhernand**
This patch prepares the project so that tests will be able to use the 'envtest' package.

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-19120

- [ ] New Feature 
- [X] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [X] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [X] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [X] Title and description added to both, commit and PR.
- [X] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [X] This change does not require a documentation update (docstring, `docs`, README, etc)
- [X] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by paul-maidment** [comment]
I'm cool with this being a 'NO-ISSUE' but would love more context on what you have planned. 

Looks like integration tests, somewhere between unit and subsystem?

**Comment by jhernand** [comment]
@paul-maidment I need/want this for the tests that I am adding in #7090. I'd call those are unit tests, in the same sense that tests that use a database are unit tests, only that here the underlying infrastructure is a Kubernetes API server instead of a database. But I am fine if we want to call them "integration" or anything else.

**Comment by rccrdpccl** [comment]
/lgtm

great addition :heart:

**Pull request merged**
