### PR TITLE
MGMT-13292: Add the installed version on the monitored operator response

### PR DESCRIPTION
**Pull request by eliorerz**
Add version to `monitored-operator` struct so we will be able to know which version was installed.

e.g.

```json
[
    {
        "cluster_id": "2e2c9b79-8029-4759-8054-ccaa96a360e2",
        "name": "console",
        "operator_type": "builtin",
        "status": "available",
        "status_info": "All is well",
        "status_updated_at": "2023-02-13T13:59:36.649Z",
        "timeout_seconds": 3600,
        "version": "4.12.3"
    },
    {
        "cluster_id": "2e2c9b79-8029-4759-8054-ccaa96a360e2",
        "name": "lvm",
        "namespace": "openshift-storage",
        "operator_type": "olm",
        "status": "available",
        "status_info": "install strategy completed with no errors",
        "status_updated_at": "2023-02-13T14:02:40.004Z",
        "subscription_name": "lvms-operator",
        "timeout_seconds": 1800,
        "version": "4.12.0"
    }
]
```

## List all the issues related to this PR

- [ ] Enhancement

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

### CODE REVIEW

**Comment by tsorya** [comment]
If we have subsystem for this logic lets update it if not lgtm

**Comment by eliorerz** [comment]
> If we have subsystem for this logic lets update it if not lgtm

Updated the subsystem test to validate operator version after set

**Pull request merged**
