### PR TITLE
MGMT-2043 - Implement GET /clusters/{cluster_id}/install-config

### PR DESCRIPTION
**Pull request by carbonin**
This API will return the fully rendered InstallConfig yaml which
will be used with `openshift-install`. This takes into account
both the default config we use as well as any customizations the
user has made to the cluster or the overrides.

### CODE REVIEW

**Comment by eranco74** [comment]
Who is this API for?

**Comment by eranco74** [comment]
What will be the result of calling this APi before the user Sets nodes roles, sets the machineNetwork,  VIPs, etc...?

**Comment by carbonin** [comment]
Just creating a cluster then immediately querying this endpoint gives you this yaml:

```yaml
apiVersion: v1
baseDomain: ""
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: ""
  serviceNetwork:
  - 172.30.0.0/16
metadata:
  name: cluster-9e61fcfe-6a5b-46a5-bfbf-051a97cced89
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 0
platform:
  baremetal:
    provisioningNetworkInterface: ens4
    apiVIP: ""
    ingressVIP: ""
    dnsVIP: ""
    hosts: []
fips: false
pullSecret: ""
sshKey: ""
```

**Comment by carbonin** [comment]
@eranco74 can you re-review? I had to rebase.

**Review by eranco74 — COMMENTED** [review]
/approve

**Pull request merged**
