### PR TITLE
MGMT-4921 Rename InstallEnv --> InfraEnv

### PR DESCRIPTION
**Pull request by nmagnezi**
As the assisted-service KubeAPI approaches a point in which it starts to integrate with other projects, we make final changes to the API naming.

This started with https://github.com/openshift/assisted-service/pull/1363 to rename group and version.

This PR renames InstallEnv to InfraEnv.
Rename will include both CRD and its matching controller.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@nmagnezi Nice find + replace PR :) I have a question about how we we maintain api since you changes breaks it. Do we have any policy to maintain older version `v1alpha1` for some time or is it OK to drop it?

**Comment by nmagnezi** [comment]
> @nmagnezi Nice find + replace PR :) I have a question about how we we maintain api since you changes breaks it. Do we have any policy to maintain older version `v1alpha1` for some time or is it OK to drop it?

Glad you liked it :-)
We're still under heavy development and no officially supporting this API. For that reason, https://github.com/openshift/assisted-service/pull/1363 was done as an in-place change (rather than adding a version).

`v1beta1` will be the first API version that other products will use to integrate with assisted-service, so I assume we'll need to keep it around and have some deprecation cycle when we move forward from that.

**Review by flaper87 — CHANGES_REQUESTED** [review]
Could you use `git mv` for the `installenv_controller.go` rename. From the commit it looks like you just renamed the file. I'd like to properly preserve the history of this file

**Comment by flaper87** [comment]
One more comment, could you expand both, the commit and the PR, messages? Renames are important, and we should make sure the motivations are kept in the git history. Here are some guidelines from the K8S community repo:

https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines

**Comment by nmagnezi** [comment]
> Could you use `git mv` for the `installenv_controller.go` rename. From the commit it looks like you just renamed the file. I'd like to properly preserve the history of this file

@flaper87, I have attempted this with no success.
Regardless of this specific PR, I notice that when I `git mv <file>`, it loses the history.
It does, however, preserve the `git blame` per-line output (the same happens for this PR).

According to [this StackOverflow thread](https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history ), it is expected.

Please let me know if I missed anything.

**Comment by flaper87** [comment]
> > Could you use `git mv` for the `installenv_controller.go` rename. From the commit it looks like you just renamed the file. I'd like to properly preserve the history of this file
> 
> @flaper87, I have attempted this with no success.
> Regardless of this specific PR, I notice that when I `git mv <file>`, it loses the history.
> It does, however, preserve the `git blame` per-line output (the same happens for this PR).
> 
> According to [this StackOverflow thread](https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history), it is expected.
> 
> Please let me know if I missed anything.

Everything seems to have worked as expected. What happened in the previous version of this PR is that the `installenv` file appeared as *removed* and a new `infraenv` file had been *added*. That would have made you the author and sole owner of that file. 

With the `git mv` steps, the file was *renamed* in the git history. If you run `git log` in that file in this PR, it won't show you much unless you pass `--follow` to `git log` so that it follows the history from before the rename. Does this make sense?

Here's a screenshot of what Github shows right now, which is desired in this case:

DeepinScreenshot_select-area_20210413090342

Thanks for preserving the git history, future devs will thank you for this :smiley:

**Review by flaper87 — COMMENTED** [review]
/test e2e-metal-assisted-kube-api
/lgtm

**Comment by nmagnezi** [comment]
> /test e2e-metal-assisted-kube-api
> /lgtm

`e2e-metal-assisted-kube-api` will fail for now, but it is okay.
Once this PR gets merged I'll run those tests from https://github.com/openshift/assisted-test-infra/pull/702
CC: @osherdp

**Review by djzager — APPROVED** [review]

**Comment by nmagnezi** [comment]
> @nmagnezi: PR needs rebase.

Rebased

**Review by flaper87 — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
Doesn't seem to pass anytime soon

**Pull request merged**
