### PR TITLE
MGMT-17849: escape '%' in agent.service proxy urls

### PR DESCRIPTION
**Pull request by AlonaKaplan**
The proxy url format is `http://<user>:<password>@<ipaddr>:<port>`
The user and password may contain url escaped characters (starting with '%').
    
systemd rejects unknown '%' specifiers on unit configuration [1].
Therefore, agent.service proxy urls should escape '%' -> '%%' to avoid being rejected.
    
`Environment=HTTP_PROXY=http://usr%40name:passwd%5D@10.10.1.1:3128`
    
should become
    
`Environment=HTTP_PROXY=http://usr%%40name:passwd%%5D@10.10.1.1:3128`

The PR also includes a small refactoring moving all the similar tests that are testing the proxy data in the ignition
file to a DescribeTable.
    
[1] https://github.com/systemd/systemd/blob/a1b2c92d8290c76a29ccd0887a92ac064e1bb5a1/NEWS#L10

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

The change was tested with unit tests only.

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ori-amizur** [comment]
Seems OK.  It should be tested end-to-end to verify that it works properly.

**Comment by AlonaKaplan** [comment]
[Rebase](https://github.com/openshift/assisted-service/compare/d943fa10e45e7bb12c7b82544c2760c0e2053bf9..6ea44b9f9fb157d70838397df606fc5f08015f7e)

**Pull request merged**
