### PR TITLE
Raz/mgmt 1659 cluster/host canceled status

### PR DESCRIPTION
**Pull request by RazRegev**
On cancel installation, instead of setting the cluster status
to 'error', it will be set to a new status 'canceled' (when we
monitor the service it would be helpful to know if
installations were failed or cancelled without having to check
statusInfo).

### CODE REVIEW

**Comment by RazRegev** [comment]
/hold
until ui will support this new status

**Review by YuviGold — APPROVED** [review]
LGTM

**Review by jtomasek — CHANGES_REQUESTED** [review]
Hosts in 'cancelled' state don't have `progress.current_stage` property set. Cancelled state should behave the same as Error state and keep the last installation stage so the UI can calculate and show the installation progress percentage when the user cancelled the installation.

**Review by jtomasek — APPROVED** [review]

**Review by YuviGold — APPROVED** [review]

**Review by avishayt — APPROVED** [review]
Looks great, and thanks for updating the state machine diagrams!

**Comment by RazRegev** [comment]
look like the checks are stuck. 
closing this PR and reopening.

**Pull request closed without merging**
