### PR TITLE
MGMT-6653, Bump OCP versions 4.7 and 4.8

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.7  release notes: https://access.redhat.com/errata/RHSA-2021:1550
4.8  has no available release notes

### CODE REVIEW

**Comment by oshercc** [comment]
Created a PR in app-interface GitLab https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/19850

**Comment by oshercc** [comment]
Running all tests

**Comment by oshercc** [comment]
@djzager Can you please take a look, not sure why this wasn't updated
{noformat}[2021-05-26T10:28:45.667Z] diff --git a/deploy/olm-catalog/manifests/****-service-operator.clusterserviceversion.yaml b/deploy/olm-catalog/manifests/****-service-operator.clusterserviceversion.yaml{noformat}

**Review by djzager — APPROVED** [review]

**Comment by gamli75** [comment]
/hold
we don't want to update fc.5 - it will break our SNO installation and we reverted it

**Review by gamli75 — APPROVED** [review]

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
