### PR TITLE
MGMT-13431: ODF storage class not recognizing all available disks in the cluster

### PR DESCRIPTION
**Pull request by danmanor**
This bug was discovered in assisted-service with `OpenShift` version 4.12. It relates to a specific situation where the service generates a `StorageCluster` manifest containing an incorrect number of `ODF` disks. This issue seems to arise when the service uses the default value of `o.config.ODFDisksAvailable` in the manifest, as there exists a scenario where this attribute is not properly set with the appropriate count due to the involvement of a separate instance of the service.
As a solution, I added an additional count prior to manifest generation. This ensures an accurate count of disks, regardless of whether it is performed by a single instance or multiple instances of the service.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eliorerz** [comment]
Rebase you RP

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/retitle MGMT-13431: ODF storage class not recognizing all available disks in the cluster

**Pull request merged**
