### PR TITLE
MGMT-15525: Use go 1.18 when setting up environment

### PR DESCRIPTION
**Pull request by carbonin**
Without this this command was failing with the following output:

```
[2023-08-09 17:01:25] + /tmp/golang_installer
[2023-08-09 17:01:25] Welcome to the Go installer!
[2023-08-09 17:01:26] Downloading Go version go1.21.0
[2023-08-09 17:01:26] time 2023-08-04T20:14:06Z to /root/.go
[2023-08-09 17:01:26] This may take a bit of time...
[2023-08-09 17:01:26] Downloading Go from 400 Bad Request failed with HTTP status %!s(MISSING)
```

Also correct a minor typo in a function name.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
Disconnected job passed :man_shrugging: removing WIP

**Review by gamli75 — APPROVED** [review]

**Review by filanov — APPROVED** [review]

**Comment by carbonin** [comment]
/override e2e-agent-compact-ipv4

known dev-scripts issue

**Comment by adriengentil** [comment]
/cherry-pick release-ocm-2.8

Failing in the same way in all other branches:
https://search.ci.openshift.org/?search=Downloading+Go+from+400+Bad+Request+failed+with+HTTP+status&maxAge=168h&context=1&type=build-log&name=.*assisted.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Pull request merged**
