### PR TITLE
MGMT-4585: Enable flexible scaling for OCS

### PR DESCRIPTION
**Pull request by rewantsoni**
Signed-of-by: Rewant Soni <resoni@redhat.com>

# Description

The OCS Operator v 4.7 introduces the flexible scaling feature which greatly simplifies the OSD placement. Updating the StorageCluster CR to enable this feature, add flexibleScaling in the CR, change the count value to the number of disks, and replica to 1. This PR also removes the condition in which the number of disks is a multiple of 3, form clusterValidation. 

# What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

# How was this code tested?

Please, select one or more if needed:

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

It's recommended to take a few extra minutes to provide more information about
how this code was tested. Here are some questions that may be worth answering:

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run?
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

# Assignees

Please, add one or two reviewers that could help review this PR.

/assign @priyanka19-98 
/assign @nbalacha 
/assign @gobindadas

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by nbalacha — APPROVED** [review]

**Comment by rewantsoni** [comment]
@nbalacha can you approve the PR again, I had to change a test because of #1999

**Review by nbalacha — APPROVED** [review]
/lgtm

**Comment by gamli75** [comment]
@rewantsoni I think that this change requires also a change in the e2e test, right?
@lalon4 FYI

**Comment by rewantsoni** [comment]
> @rewantsoni I think that this change requires also a change in the e2e test, right?
> @lalon4 FYI

Yes, I have made the changes in the CI tests and opened a MR for that

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
