### PR TITLE
MULTIARCH-4515: Bump version dependency.

### PR DESCRIPTION
**Pull request by AmadeusPodvratnik**
Bump version for [MULTIARCH-4515: Add support for ins-file as boot artefact.](https://github.com/openshift/assisted-image-service/commit/d3f8a0398019e0858bf78319156249218912ce09)

go get github.com/openshift/assisted-image-service@d3f8a0398019e0858bf78319156249218912ce09
go  mod tidy
go mod vendor

## List all the issues related to this PR

- [] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by AmadeusPodvratnik** [comment]
@omertuc I see some test failures ... just checking if this is related to gomega ...

**Comment by omertuc** [comment]
The issues are due to the image-service repo having go 1.21 while the assisted-service repo has go 1.20

**Comment by rccrdpccl** [comment]
@carbonin we will need to change golang version is CI as well ([this](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml#L65) and more)

Btw good point, I think we need to get some other changes in.

@AmadeusPodvratnik can you please change Golang version in `ci-images/`?

**Comment by gamli75** [comment]
@eifrach please review

**Comment by gamli75** [comment]
> cc @adriengentil @rccrdpccl @gamli75 do we require anything outside of this for a golang version bump?

let's change the go version in the DS images as well 
https://gitlab.cee.redhat.com/rh-ecosystem-edge/assisted-installer/assisted-installer-projects/-/blob/rhai-1.0-rhel-8/distgit/containers/assisted-service/Dockerfile.in?ref_type=heads

@eifrach has a task to do it in all our repositories - I asked him to review it as well.

**Comment by AmadeusPodvratnik** [comment]
@rccrdpccl I just updated the golang to 1.21 for root docker files and the ci-images.

**Comment by eifrach** [comment]
@AmadeusPodvratnik can you rebase it with the master?

there are a few changes witht the linter / unit-test that may be missing here

**Comment by rccrdpccl** [comment]
@AmadeusPodvratnik can we close this?

**Comment by AmadeusPodvratnik** [comment]
Bump is not necessary ...

**Pull request closed without merging**
