### PR TITLE
Bug 2049874: Proxy support in ACI

### PR DESCRIPTION
**Pull request by eliorerz**
Backport of https://github.com/openshift/assisted-service/pull/3215

```
apiVersion: v1
baseDomain: redhat.com
proxy:
  httpProxy: http://[1001:db9::1]:3129
  httpsProxy: http://[1001:db9::1]:3129
  noProxy: 2002:db8::/53,2003:db8::/112,1001:db9::/120,.test-infra-cluster-0a79ed3b.redhat.com,.test-infra-cluster-0a79ed3b.redhat.com,2002:db8::/53,2003:db8::/112,1001:db9::/120
networking:
...
```

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [x] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @osherdp 
/cc @tsorya 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eliorerz** [comment]
`test-infra` release-ocm-2.4 branch is still partially broken, overriding e2e tests:

/override ci/prow/e2e-metal-assisted
/override ci/prow/e2e-metal-assisted-kube-api
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
/override ci/prow/e2e-metal-assisted-none
/override ci/prow/e2e-metal-assisted-static-ip

**Review by nmagnezi — COMMENTED** [review]
LGTM.
Please keep the conflicted files list in the commit message for future manual backports. It makes it easier for reviewers to pay close attention to how conflicts were resolved.
it looks like this:

```
conflicts:
    path/to/file.go
    path/to/another/file.go
```

Can this be merged, or are we waiting for additional confirmation?

**Review by osherdp — APPROVED** [review]

**Pull request merged**
