### PR TITLE
MGMT-3508 Adjust Grafana dashboards to filter data by openshift version

### PR DESCRIPTION
**Pull request by oshercc**
update general & weekly overview to have the options to be filtered by oc versuion 
dev dashbards:

### CODE REVIEW

**Review by nmagnezi — COMMENTED** [review]
**Weekly overview -** the filter was not applied to:
1. Clusters With Hosts
2. Clusters Generated ISO (Unique by ClusterId)
3. Clusters Started Install (Unique by ClusterId)

**Weekly overview -** the filter was not applied to:
1. Installations results
2. Average Hosts Per Cluster
3. Cluster Count by emailDomain

General comments:
1. (Nit) The filter name is `ocp_version`, why not OpenShift Version same as the label?
2. I think it would be better if we have a dropdown box with version options (e.g. 4.6, 4.7), as opposed to a free text. @ErezAlster what do you think?

**Comment by oshercc** [comment]
> **Weekly overview -** the filter was not applied to:
> 
> 1. Clusters With Hosts
> 2. Clusters Generated ISO (Unique by ClusterId)
> 3. Clusters Started Install (Unique by ClusterId)
> 
> **Weekly overview -** the filter was not applied to:
> 
> 1. Installations results
> 2. Average Hosts Per Cluster
> 3. Cluster Count by emailDomain
> 
> General comments:
> 
> 1. (Nit) The filter name is `ocp_version`, why not OpenShift Version same as the label?
> 2. I think it would be better if we have a dropdown box with version options (e.g. 4.6, 4.7), as opposed to a free text. @ErezAlster what do you think?

If we use a dropdown we will need to update the dashboard every micro version, not sure this is something we want to do.

**Comment by nmagnezi** [comment]
> > **Weekly overview -** the filter was not applied to:
> > 
> > 1. Clusters With Hosts
> > 2. Clusters Generated ISO (Unique by ClusterId)
> > 3. Clusters Started Install (Unique by ClusterId)
> > 
> > **Weekly overview -** the filter was not applied to:
> > 
> > 1. Installations results
> > 2. Average Hosts Per Cluster
> > 3. Cluster Count by emailDomain
> > 
> > General comments:
> > 
> > 1. (Nit) The filter name is `ocp_version`, why not OpenShift Version same as the label?
> > 2. I think it would be better if we have a dropdown box with version options (e.g. 4.6, 4.7), as opposed to a free text. @ErezAlster what do you think?
> 
> If we use a dropdown we will need to update the dashboard every micro version, not sure this is something we want to do.

The data only includes major+minor (not micro).
In Prometheus --> `sum by (openshiftVersion)(service_assisted_installer_cluster_creations)` currently results `{openshiftVersion="4.6"}`

**Comment by oshercc** [comment]
> > > **Weekly overview -** the filter was not applied to:
> > > 
> > > 1. Clusters With Hosts
> > > 2. Clusters Generated ISO (Unique by ClusterId)
> > > 3. Clusters Started Install (Unique by ClusterId)
> > > 
> > > **Weekly overview -** the filter was not applied to:
> > > 
> > > 1. Installations results
> > > 2. Average Hosts Per Cluster
> > > 3. Cluster Count by emailDomain
> > > 
> > > General comments:
> > > 
> > > 1. (Nit) The filter name is `ocp_version`, why not OpenShift Version same as the label?
> > > 2. I think it would be better if we have a dropdown box with version options (e.g. 4.6, 4.7), as opposed to a free text. @ErezAlster what do you think?
> > 
> > 
> > If we use a dropdown we will need to update the dashboard every micro version, not sure this is something we want to do.
> 
> The data only includes major+minor (not micro).
> In Prometheus --> `sum by (openshiftVersion)(service_assisted_installer_cluster_creations)` currently results `{openshiftVersion="4.6"}`

ok, so for every minor
still needs to be updated, isn't adding the text filter make more sense?

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Pull request merged**
