### PR TITLE
NO-ISSUE: downgrade 4.7 version to test auto bump new mechanism

### PR DESCRIPTION
**Pull request by osherdp**
# Assisted Pull Request

## Description

We now try to implement the same automatic-bump of default OCP versions that we have on Jenkins, to prow.
Because there are no available new versions now, I figured out it's a good idea to try out the mechanism in a full wet-mode way. Downgrading OCP 4.7 in upstream tests shouldn't have any major effect.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @eliorerz 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-day2
/override ci/prow/e2e-metal-assisted-ipv4v6
/override ci/prow/e2e-metal-assisted-ipv6
/override ci/prow/e2e-metal-assisted-multi-version
/override ci/prow/e2e-metal-assisted-networking
/override ci/prow/e2e-metal-assisted-olm
/override ci/prow/e2e-metal-assisted-operator-disconnected
/override ci/prow/e2e-metal-assisted-single-node
way too many non-relevant jobs

**Pull request merged**
