### PR TITLE
Bug 2077162: Can not provision SNOs in a disconnected environment

### PR DESCRIPTION
**Pull request by eranco74**
Recent updates to the oc client used by the assisted-service seems to break ICSP in disconnected environment.
This PR revert these changes:
1. Revert "NO-ISSUE: Add a retry when fetching oc with curl (#3687)"
This reverts commit 0da8d3899d8e421a424a78816bbcc75b22683384.

2. Revert "[MGMT-5442](https://issues.redhat.com//browse/MGMT-5442): assisted-service should use official oc client (#3657)"
This reverts commit cdbb65b98076673d156f5a5b787bad9378528531.

3. Revert "Bug 2069976: Error with oc-mirror using an old outdated unsupported oc client in AI (#3598)"
This reverts commit 53616082111984bbb43f4c848f7ce11c915f579f.

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run? Yes
- Should this PR be tested in a specific environment? Disconnected env
- Any logs, screenshots, etc that can help with the review process? 
Running:
./oc adm -v=5 release extract --command=openshift-install --to=./ --insecure=false <mirrored release image> --registry-config=/tmp/registry.json 2>&1 >/dev/null | grep "Will extract"
and checking where it's extracting from (should be from an image in the mirror registry and not quay.io...)

-->

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Comment by eranco74** [comment]
No need to cherry-pick the revert because the cherry-pick never merged into release-ocm-2.5
https://github.com/openshift/assisted-service/pull/3634

**Pull request merged**
