### PR TITLE
MGMT-3908 Port mapSecretToCluster to clusterDeployment controller

### PR DESCRIPTION
**Pull request by nmagnezi**
One change here is that in hive clusterDeployment Spec, PullSecretRef
is a LocalObjectReference, meaning it has no Namespace attribute.

Therefore, under the assumption that a k8s secret and clusterDeployment
reside on the same namespace, I remove that from the if statement.

### CODE REVIEW

**Comment by nmagnezi** [comment]
/hold
testing

**Review by nmagnezi — COMMENTED** [review]
/test images

**Review by nmagnezi — COMMENTED** [review]
/unhold
/assign @filanov 
/assign @RazRegev

**Review by nmagnezi — COMMENTED** [review]
# Tested With

```yaml
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: mycluster
  namespace: assisted-installer
spec:
  baseDomain: hive.example.com
  clusterName: mycluster
  installStrategy:
    agent:
      networking:
        clusterNetwork:
          - cidr: 10.128.0.0/14
            hostPrefix: 23
        ServiceNetwork:
          - 172.30.0.0/16
      provisionRequirements:
        controlPlaneAgents: 3
        agentSelector:
          matchLabels:
            bla: aaa
  platform:
    #agentBareMetal:
    # apiVIP: 1.2.3.8
    #apiVIPDNSName: ""
    # ingressVIP: 1.2.3.9
     vipDHCPAllocation: true
  provisioning:
    imageSetRef:
      name: openshift-v4.7.0
    installConfigSecretRef:
      name: mycluster-install-config
    sshPrivateKeySecretRef:
      name: mycluster-ssh-key
  pullSecretRef:
    name: pull-secret
```

* I added a debug print in[ this if statement](https://github.com/openshift/assisted-service/pull/1019/files#diff-40883156aab921707c5a73dfa3b451bbd3accb4c0636d715d0a7768db8904b57R494), to detect the pull secret update events:
```golang
r.Log.Info("DEBUGGING: mapSecretToClusterDeployment match!")
```

# Result

* once I updated the pullsecret I got:

```golang
time="2021-02-03T15:37:25Z" level=info msg="DEBUGGING: mapSecretToClusterDeployment match!" func="github.com/openshift/assisted-service/internal/controller/controllers.(*ClusterDeploymentsReconciler).SetupWithManager.func1" file="/go/src/github.com/openshift/origin/internal/controller/controllers/clusterdeployments_controller.go:499"
time="2021-02-03T15:37:25Z" level=info msg="DEBUGGING: mapSecretToClusterDeployment match!" func="github.com/openshift/assisted-service/internal/controller/controllers.(*ClusterDeploymentsReconciler).SetupWithManager.func1" file="/go/src/github.com/openshift/origin/internal/controller/controllers/clusterdeployments_controller.go:499"
```

`kubectl -n assisted-installer describe clusterdeployments.hive.openshift.io mycluster`
```yaml
Name:         mycluster
Namespace:    assisted-installer
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"hive.openshift.io/v1","kind":"ClusterDeployment","metadata":{"annotations":{},"name":"mycluster","namespace":"assisted-inst...
API Version:  hive.openshift.io/v1
Kind:         ClusterDeployment
Metadata:
  Creation Timestamp:  2021-02-03T15:29:31Z
  Generation:          1
  Managed Fields:
    API Version:  hive.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:baseDomain:
        f:clusterName:
        f:installStrategy:
          .:
          f:agent:
            .:
            f:networking:
              .:
              f:ServiceNetwork:
              f:clusterNetwork:
            f:provisionRequirements:
              .:
              f:agentSelector:
                .:
                f:matchLabels:
                  .:
                  f:bla:
              f:controlPlaneAgents:
        f:platform:
          .:
          f:vipDHCPAllocation:
        f:provisioning:
          .:
          f:imageSetRef:
            .:
            f:name:
          f:installConfigSecretRef:
            .:
            f:name:
          f:sshPrivateKeySecretRef:
            .:
            f:name:
        f:pullSecretRef:
          .:
          f:name:
    Manager:         kubectl
    Operation:       Update
    Time:            2021-02-03T15:29:31Z
  Resource Version:  312487
  UID:               6721deea-f8f7-4810-b48f-9419c1e6f63f
Spec:
  Base Domain:   hive.example.com
  Cluster Name:  mycluster
  Install Strategy:
    Agent:
      Networking:
        Service Network:
          172.30.0.0/16
        Cluster Network:
          Cidr:         10.128.0.0/14
          Host Prefix:  23
      Provision Requirements:
        Agent Selector:
          Match Labels:
            Bla:               aaa
        Control Plane Agents:  3
  Platform:
    Vip DHCP Allocation:  true
  Provisioning:
    Image Set Ref:
      Name:  openshift-v4.7.0
    Install Config Secret Ref:
      Name:  mycluster-install-config
    Ssh Private Key Secret Ref:
      Name:  mycluster-ssh-key
  Pull Secret Ref:
    Name:  pull-secret
Events:    <none>
```

**Review by filanov — APPROVED** [review]

**Pull request merged**
