### PR TITLE
[WIP] MGMT-8987: Allow for one worker to be added when masters are schedulable

### PR DESCRIPTION
**Pull request by mkowalski**
This commit changes the validation of cluster agents in order to allow
installation of a cluster with 3 masters and 1 worker node in case when
schedulable masters are enabled.

This architecture has been reviewed and is used by workflows like ZTP
and factory pipelines.

Co-authored-by: Flavio Percoco <flavio@redhat.com>
Closes: [MGMT-8987](https://issues.redhat.com/browse/MGMT-8987)

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @flaper87 
/cc @mresvanis 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by mkowalski** [comment]
/retitle [WIP] MGMT-8987: Allow for one worker to be added when masters are schedulable
/hold Needs unit tests

**Comment by romfreiman** [comment]
Did we talk to qe about it?

**Comment by romfreiman** [comment]
/hold
We should sync with qe and ui on such change. I assume it's gonna break many tests for them

**Pull request closed without merging**
