### PR TITLE
MGMT-9094: Wrong default timestamp for install_started_at and install…

### PR DESCRIPTION
**Pull request by tsorya**
[MGMT-9094](https://issues.redhat.com/browse/MGMT-9094): Wrong default timestamp for install_started_at and install_completed_at

Removing defaults from swagger

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Comment by osherdp** [comment]
@tsorya UI works well with this change? Or does it also need to be changed

**Comment by jkilzi** [comment]
> @tsorya UI works well with this change? Or does it also need to be changed

@osherdp it will break the UI... we changed the default to be the one that starts with 2000 in [v2.0.10](https://github.com/openshift-assisted/assisted-ui-lib/pull/1092)

**Comment by jkilzi** [comment]
@osherdp If you merge this one, I'll release ASAP a new version of the UI that adapts to this change.
cc @lalon4

**Comment by osherdp** [comment]
> @osherdp If you merge this one, I'll release ASAP a new version of the UI that adapts to this change. cc @lalon4

yes, I think it will be a good idea
Although I think it also means we'll backport it to API v2.1 otherwise we'll need to drag compatibility issue for too much time

**Pull request merged**
