### PR TITLE
NO-ISSUE: Graduate hive CRDs to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by jordigilh**
# Assisted Pull Request

## Description

Kubernetes 1.22 [no longer supports](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122) CRDS with version `apiextensions.k8s.io/v1beta1`. This [impacts](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1196/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api/1455153244295663616/build-log.txt) using minikube version v.1.22.0 and above when creating a cluster with the `assisted-test-infra`.

```
RuntimeError: command=kubectl --namespace assisted-installer apply -f /home/assisted/assisted-service/hack/crds//hive.openshift.io_clusterdeployments.yaml exited with an error=error: unable to recognize "/home/assisted/assisted-service/hack/crds//hive.openshift.io_clusterdeployments.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1" code=1
```

The new manifests contain the latest values of the [hive.openshift.io_clusterdeployments.yaml](https://github.com/openshift/hive/blob/2bbebf5983eecf3e539241cecd2c46a1681b472e/config/crds/hive.openshift.io_clusterdeployments.yaml) and [hive.openshift.io_clusterimagesets.yaml](https://github.com/openshift/hive/blob/2bbebf5983eecf3e539241cecd2c46a1681b472e/config/crds/hive.openshift.io_clusterimagesets.yaml) as defined in the hive project.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @osherdp 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by jordigilh** [comment]
@osherdp can you take a look at this PR. According to the kubernetes documentation, the api version `apiextensions.k8s.io/vbeta1` for the CRDs is no loner supported in v1.22. I've taken the latest version of the manifests from the hive project and copied them over here.

**Comment by osherdp** [comment]
/cc @nmagnezi @rollandf 
I guess this should only affect our tests, right?
On any other place it will be the customer responsibility matching k8s hub version and hive version to be compatible

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
To save resources

**Comment by rollandf** [comment]
> /cc @nmagnezi @rollandf I guess this should only affect our tests, right? On any other place it will be the customer responsibility matching k8s hub version and hive version to be compatible

I agree. Let see if CI pass

**Comment by osherdp** [comment]
@jordigilh you'll need to change the commit message to the structure of ``NO-ISSUE: <message>``, seems like this is failing ``continuous-integration/jenkins/pr-merge`` job

**Review by nmagnezi — CHANGES_REQUESTED** [review]
Please update the documentation to match this change.
for instance, examples we have under `docs/hive-integration/crds`

**Comment by rollandf** [comment]
> Please update the documentation to match this change. for instance, examples we have under `docs/hive-integration/crds`

I don't think any update is needed. This PR update the definition of the CRD itself, but not changing any fields.

**Comment by jordigilh** [comment]
> > Please update the documentation to match this change. for instance, examples we have under `docs/hive-integration/crds`
> 
> I don't think any update is needed. This PR update the definition of the CRD itself, but not changing any fields.

I did not change any fields, or at least not intentionally. All I did was to copy over the latest manifests, I can see that the schema has changed in its structure, but I am unsure if that will cause any impact to the CRs, if any. I guess as mentioned here, this will be detected in the tests.
Should this change in the CRDs be highlighted in the next release?

**Comment by jordigilh** [comment]
Tests are green. Any further comments to this PR?

**Pull request merged**
