### PR TITLE
MGMT-7879: Bump OCP versions release 4.8.10 -> 4.8.12, release 4.7.28 -> 4.7.31, release 4.9.0-rc.0 -> 4.9.0-rc.4, rhcos 4.9.0-rc.0 -> 4.9.0-rc.4

### PR DESCRIPTION
**Pull request by oshercc**
@osherdp @gamli75 @YuviGold
4.9 has no available release notes
4.8 release notes: https://access.redhat.com/errata/RHBA-2021:3511
4.7 release notes: https://access.redhat.com/errata/RHBA-2021:3510

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by osherdp** [comment]
@gamli75 shouldn't we skip 4.7 as well?

**Comment by osherdp** [comment]
ipv6 and disconnected jobs seem to always fail in the last couple of weeks
also, they are not connected to the cloud environment

**Comment by osherdp** [comment]
/unhold
(networking job is also pending a fix)

**Comment by osherdp** [comment]
Too much git conflict
I think I'll let the job create a new PR

**Pull request closed without merging**
