### PR TITLE
MGMT-4153, Bump OCP version from 4.6.16 to 4.6.17 (auto created)

### PR DESCRIPTION
**Pull request by oshercc**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by oshercc** [comment]
test-infra test passed, HOLD label removed, see http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/4729/

**Comment by omertuc** [comment]
/hold
GitLab PR was *not* created due to a script error

**Pull request closed without merging**
