### PR TITLE
[release-ocm-2.8] MGMT-15034: MGMT-15047: use installer to deploy on external platform

### PR DESCRIPTION
**Pull request by adriengentil**
OCI implementation in 2.8 is outdated, this PR back-ports https://github.com/openshift/assisted-service/pull/5312 and https://github.com/openshift/assisted-service/pull/5381

### CODE REVIEW

**Comment by adriengentil** [comment]
/override ci/prow/e2e-agent-compact-ipv4 ci/prow/edge-assisted-operator-catalog-publish-verify ci/prow/edge-ci-index ci/prow/edge-e2e-ai-operator-ztp ci/prow/edge-e2e-ai-operator-ztp-3masters ci/prow/edge-e2e-ai-operator-ztp-capi ci/prow/edge-e2e-ai-operator-ztp-disconnected ci/prow/edge-e2e-ai-operator-ztp-hypershift-zero-nodes ci/prow/edge-e2e-metal-assisted ci/prow/edge-e2e-nutanix-assisted ci/prow/edge-e2e-oci-assisted ci/prow/edge-e2e-vsphere-assisted ci/prow/edge-images ci/prow/edge-lint ci/prow/edge-subsystem-aws ci/prow/edge-subsystem-kubeapi-aws ci/prow/edge-unit-test ci/prow/edge-verify-generated-code

overriding all edge jobs as I opened this pr against master by mistake

**Review by gamli75 — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Comment by gamli75** [comment]
/override ci/prow/e2e-agent-compact-ipv4 ci/prow/edge-assisted-operator-catalog-publish-verify ci/prow/edge-ci-index ci/prow/edge-e2e-ai-operator-ztp ci/prow/edge-e2e-ai-operator-ztp-3masters ci/prow/edge-e2e-ai-operator-ztp-capi ci/prow/edge-e2e-ai-operator-ztp-disconnected ci/prow/edge-e2e-ai-operator-ztp-hypershift-zero-nodes ci/prow/edge-e2e-metal-assisted ci/prow/edge-e2e-nutanix-assisted ci/prow/edge-e2e-oci-assisted ci/prow/edge-e2e-vsphere-assisted ci/prow/edge-images ci/prow/edge-lint ci/prow/edge-subsystem-aws ci/prow/edge-subsystem-kubeapi-aws ci/prow/edge-unit-test ci/prow/edge-verify-generated-code

**Pull request merged**
