### PR TITLE
MGMT-12975: Update 4.12 release image to use GA version

### PR DESCRIPTION
**Pull request by eliorerz**
Upgrade 4.12 images to use the globally available ones

/cc @osherdp @gamli75

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by eliorerz** [comment]
Day2 jobs are broken, overriding:
 
/override ci/prow/edge-e2e-metal-assisted-day2 
/override ci/prow/edge-e2e-metal-assisted-day2-single-node

**Pull request merged**
