### PR TITLE
MGMT-7564: cluster credentials only for cluster owner

### PR DESCRIPTION
**Pull request by sagidayan**
# Assisted Pull Request

## Description
Cluster credentials should be accessible only for cluster owner.

Updated swagger security for endpoint /v1/clusters/{cluster_id}/credentials

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @avishayt 
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Review by avishayt — APPROVED** [review]

**Comment by carbonin** [comment]
Reopening to try to kick app-sre test check.

**Comment by carbonin** [comment]
This had previously passed all these pending tests and was stuck on the `ci.ext.devshift.net PR build` check.
Given that this is blocking QE's nightly tests I'm going to merge this one manually.

**Pull request merged**
