### PR TITLE
NO-ISSUE Add the local auth secret to the operator bundle

### PR DESCRIPTION
**Pull request by carbonin**
Missed these changes in https://github.com/openshift/assisted-service/pull/1397

@rwsu @djzager Anything else I missed? :worried:

### CODE REVIEW

**Review by flaper87 — APPROVED** [review]
/approve

will let @rwsu pull the trigger

**Comment by carbonin** [comment]
@flaper87 The github approve puts both `lgtm` and `approve` ... just a heads up

**Review by rwsu — APPROVED** [review]
/lgtm

**Pull request merged**
