### PR TITLE
NO-ISSUE Create grafana-dashboard-assisted-service-staging.configmap.…

### PR DESCRIPTION
**Pull request by gamli75**
…yaml

### CODE REVIEW

**Comment by gamli75** [comment]
cc: @nmagnezi

**Review by nmagnezi — COMMENTED** [review]
@yobshans all of our existing dashboards have datasource dropdown that allows users to change the datasource on the fly.
By that, we can use the same dashboards both for stage and prod.
Can you please add such a dropdown to yours? it is currently hardcoded to stage.

I've added the relevant code

https://github.com/openshift/assisted-service/blob/6adf01fe23a84523562ea813470f3aecb5438f53/dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml#L9181-L9201

**Comment by yobshans** [comment]
@nmagnezi Yes, I know. Actually I need only Staging because I won't run performance on Production. 
But if you feel it will be better can you please update with your approach. 
Thank you

**Review by nmagnezi — COMMENTED** [review]
@yobshans 
I imported your dashboard. Few things:
1. Please reach out to APP-SRE. I don't see any metrics in stage currently. Makes it not possible to really review.
2. You have a lot of leftovers from the playground. The `Building blocks` and some more empty rows. Please remove those.

Please ping me when it is ready for another look.

**Comment by yobshans** [comment]
@nmagnezi Thank you for your review. Unfortunately I do not have permission to edit this file. Can you please fix found issues.

**Comment by yobshans** [comment]
@gamli75 HI, I need your help to progress with dashboard enabling. Thank you.

**Comment by nmagnezi** [comment]
> @nmagnezi Thank you for your review. Unfortunately I do not have permission to edit this file. Can you please fix found issues.

@yobshans I have worked out something that will solve this. find it here: https://coreos.slack.com/archives/C016EF00KS5/p1614610334116400

**Comment by yobshans** [comment]
@nmagnezi the working dashboard 
http://f13-h26-b04-5039ms.rdu2.scalelab.redhat.com:3000/d/assisted-service-staging/staging-env-assisted-service-dashboard?orgId=1
No need Production since I use namespace="assisted-installer-stage" which is existed only on Staging env

**Comment by gamli75** [comment]
closed, new PR will be provided by @nmagnezi

**Pull request closed without merging**
