### PR TITLE
MGMT-15771: Allow to keep vSphere with UMN installation

### PR DESCRIPTION
**Pull request by eliorerz**
Change UMN and CMN feature support features to ignore `cluster.user_managed_networking` as a preparation for removing `user_managed_networking`

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

/cc @eliorerz

### CODE REVIEW

**Comment by avishayt** [comment]
As we previously discussed, I recommend adding a new platform for vsphere-umn to make it explicit for the user.

**Comment by eliorerz** [comment]
> As we previously discussed, I recommend adding a new platform for vsphere-umn to make it explicit for the user.

@avishayt We eventually decided against implementing it by adding an `assisted` unique platform. 
Personally, I believe we shouldn't add a "new platform type" to `assisted` just to mark enabled UMN for vSphere. In the future, this approach might result in duplicated platforms for each platform supporting both CMN and UMN. If clarity for the user is the goal, we can either make the cluster UMN property read-only or integrate it into the platform structure, similar to how we marked external platforms.

**Comment by avishayt** [comment]
> > As we previously discussed, I recommend adding a new platform for vsphere-umn to make it explicit for the user.
> 
> @avishayt We eventually decided against implementing it by adding an `assisted` unique platform. Personally, I believe we shouldn't add a "new platform type" to `assisted` just to mark enabled UMN for vSphere. In the future, this approach might result in duplicated platforms for each platform supporting both CMN and UMN. If clarity for the user is the goal, we can either make the cluster UMN property read-only or integrate it into the platform structure, similar to how we marked external platforms.

So how does a user say that they want vsphere UMN vs CMN?

**Comment by eliorerz** [comment]
> > > As we previously discussed, I recommend adding a new platform for vsphere-umn to make it explicit for the user.
> > 
> > 
> > @avishayt We eventually decided against implementing it by adding an `assisted` unique platform. Personally, I believe we shouldn't add a "new platform type" to `assisted` just to mark enabled UMN for vSphere. In the future, this approach might result in duplicated platforms for each platform supporting both CMN and UMN. If clarity for the user is the goal, we can either make the cluster UMN property read-only or integrate it into the platform structure, similar to how we marked external platforms.
> 
> So how does a user say that they want vsphere UMN vs CMN?

Set or unset the VIPs

**Pull request closed without merging**
