### PR TITLE
MGMT-15699: Service changes for avoiding MCO reboot

### PR DESCRIPTION
**Pull request by ori-amizur**
Send the feature flag through the install command to indicate if the skip mco reboot feature is enabled.
The relevant logic is logic is done by the assisted installer.

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
/uncc
as I have less input about it

**Comment by filanov** [comment]
/hold 
until 2.9 will be in feature freeze (7.9)

**Comment by carbonin** [comment]
>In order to avoid MCO reboot the release image and the pull secret are needed by assisted installer. Therefore, they were added to the install command.
In addition feature flag was added. If this flag is set, the pull secret is sent in the install command.
Only if the pull secret is ent, the MCO reboot will be avoided.

I only see the feature flag being sent here. Is there more work to be done on the service side or is the pull secret stuff a detail on the installer side (i.e. the installer sets the pull secret somewhere when this flag is set)?

Also can you link to the installer PR when it is up?

**Comment by ori-amizur** [comment]
> I only see the feature flag being sent here. Is there more work to be done on the service side?
No.  AFAIK this is the only work needed on the service side.

**Review by filanov — COMMENTED** [review]
Please add a tests that validate the argument that you pass

**Review by filanov — APPROVED** [review]

**Pull request merged**
