### PR TITLE
MGMT-12678: Deprecate API and Ingress VIP (Singular)

### PR DESCRIPTION
**Pull request by nmagnezi**
Those will be replaced by plural API and Ingress VIPs

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Comment by filanov** [comment]
/override ci/prow/edge-e2e-ai-operator-ztp-hypershift-zero-nodes

**Comment by avishayt** [comment]
/hold
When we deprecated the v1 APIs we set "deprecated: true".  Is there a reason not to do that here?

**Comment by filanov** [comment]
> /hold When we deprecated the v1 APIs we set "deprecated: true". Is there a reason not to do that here?

as far as i remember deprecate works only on an api level and not on an attribute level, but i'm not 100% sure.

**Comment by nmagnezi** [comment]
> /hold When we deprecated the v1 APIs we set "deprecated: true". Is there a reason not to do that here?

@avishayt 
Based on [swagger docs](https://swagger.io/docs/specification/2-0/paths-and-operations/), the `deprecated: true` is something you can add to an API endpoint, not to an attribute.

**Comment by avishayt** [comment]
That's right.
/unhold

**Pull request merged**
