### PR TITLE
MGMT-7804: Create healthchecks for monitoring routines

### PR DESCRIPTION
**Pull request by eranco74**
# Assisted Pull Request

## Description
The assisted-installer cluster-monitor seems to hang for hours from time to time, whenever it hangs clusters dont' get updated by the monitor.
This cause few issues, that lead to installation failures (mainly we've seen clusters stuck in timeout while preparing for installaiton until they timeout).

Adding last run timestamp to each thread object that will run monitor.
Updated liveness probe to watch the last run timestamp with 5 minutes timeout
Adding logs around cluster monitor in order to see what takes so long.

- Should this PR be tested by the reviewer? No
- Is this PR relying on CI for an e2e test run? For regression
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

This PR was tested using this [branch](https://github.com/eranco74/assisted-service/tree/malformed_monitor) in subsystem with a malformed monitor (that sleeps) 
The liveness prob failed and the pod got restarted.
-->

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @filanov 
/cc @tsorya 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
Hotfix PR: https://github.com/openshift/assisted-service/pull/2619

**Comment by filanov** [comment]
Lets make sure we have some test to validate that logic.

**Review by filanov — CHANGES_REQUESTED** [review]
Please add tests

**Comment by osherdp** [comment]
/hold
(test writing will get finished in another commit)

**Comment by eranco74** [comment]
Replaced by https://github.com/openshift/assisted-service/pull/2647

**Pull request closed without merging**
