### PR TITLE
MGMT-7163: Bump OCP versions 4.8.0-rc.2 -> 4.8.0-rc.3

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.8 has no available release notes

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/test e2e-metal-assisted-kube-api
(internal server error from quay.io. Maybe we should consider mirroring image on prow)

**Pull request merged**
