### PR TITLE
MGMT-11949: MGMT-12278: Update libksba and libxml2

### PR DESCRIPTION
**Pull request by eliorerz**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

/cc @gamli75 @osherdp

### CODE REVIEW

**Comment by gamli75** [comment]
@eliorerz do we need to do this also in the DS docker file?
https://gitlab.cee.redhat.com/rh-ecosystem-edge/assisted-installer/assisted-installer-projects/-/blob/rhai-1.0-rhel-8/distgit/containers/assisted-service/Dockerfile.in

**Comment by eliorerz** [comment]
> do we need to do this also in the DS docker file?

The fix is included in `ubi8-minimal:8.7-923`  (rhacm-2.4-rhel-8) but not in `ubi8-minimal:8.6-902.1661794353` (rhacm-2.3-rhel-8)

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Pull request merged**
