### PR TITLE
MGMT-13058: validating platform type for SNO

### PR DESCRIPTION
**Pull request by slaviered**
Manual Chery-pick [MGMT-12422](https://issues.redhat.com//browse/MGMT-12422): 
1. Fix bm platform update failure when cluster platform different from bm/none (#4564) 
2. Add support in None Platform
3. Adjusting tests to fit the new logic based on the test state in master

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by slaviered** [comment]
Regression tests by QA verified that:
1. SNO + platformType: BareMetal is not allowed due to usermanagedNetworking=true vaidation so over all this flow was fixed
2. Combination of Multi-node with platformType: VSphere, None and BareMetal are working correctly
3. VSphere works with both userManagedNetworking true and false as expected
4. None to platformType is now supported

vsphere validation and SNO was introduced by a separate PR vsphere validation was introduced in this https://github.com/openshift/assisted-service/commit/3877164b2edcc315720ea49cc29d27e2964a4658 and will be ported in a separate PR and backlog.

**Review by filanov — APPROVED** [review]

**Pull request merged**
