### PR TITLE
MGMT-8207: Worker logs does not collected while cluster in status error

### PR DESCRIPTION
**Pull request by tsorya**
[MGMT-8207](https://issues.redhat.com/browse/MGMT-8207): Worker logs does not collected while cluster in status error
We tried to mount not existing file on all nodes though it should exist
only in bootstrap

# Assisted Pull Request

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @osherdp 
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by filanov** [comment]
testing retitle
/retitle MGMT-8207: Worker logs are not collected while cluster in status error

**Comment by filanov** [comment]
/retitle Bug 2023646: Worker logs are not collected while cluster in status error

**Comment by osherdp** [comment]
how much struggle

**Pull request merged**
