### PR TITLE
MGMT-3797, Bump OCP version from 4.6.8 to 4.6.12 (auto created)

### PR DESCRIPTION
**Pull request by ronniel1**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by ronniel1** [comment]
test-infra test passed, HOLD label removed, see http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/4120/

**Comment by YuviGold** [comment]
Like https://github.com/openshift/assisted-service/pull/966. It didn't run `make update-ocp-version`
/hold

**Comment by oshercc** [comment]
this PR can be deleted

**Comment by YuviGold** [comment]
> this PR can be deleted

I think that the last PR was closed and the automatic job created a new one.

**Comment by YuviGold** [comment]
Closing since https://github.com/openshift/assisted-service/pull/976 is opened.

**Pull request closed without merging**
