### PR TITLE
MGMT-10866: Update assisted container to CentOS 9

### PR DESCRIPTION
**Pull request by nmagnezi**
A fix for https://github.com/nmstate/nmstate/issues/1914 (needed for MGMT-8568)
got pushed to a CentOS 9 RPM, which also brings a more recent version of nmstate.

This is a good incentive to move to CentOS 9 stream - so we can get
the nmstate-devel C libs that include the generate config command.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/unhold
Test is now skipped

**Comment by nmagnezi** [comment]
/hold
will take a closer look at that failed kubeAPI test.

**Comment by nmagnezi** [comment]
I have found the root cause for why `deploy clusterDeployment and infraEnv and with an invalid NMState config YAML
` subsystem test fails with CentOS 9 stream:

The test, as implied by the name, is checking for a negative case where the NMState config is not valid.

**config used in testfile**
```yaml
foo: bar
```

**The response we get with nmstate 1.3.1, the version found in CentOS 8 stream**
```sh
$ nmstatectl gc testfile
--- {}
```


**The response we get with nmstate 1.3.1, the version found in CentOS 9 stream**
```sh
$ nmstatectl gc testfile
---
NetworkManager: []
```
It seems like nmstate changed their response.
When I look at the existing code, this condition should be adapted to the new nmstate response:
https://github.com/openshift/assisted-service/blob/a6d0cfb4625b407740369aa0a87297a90ddd641a/pkg/staticnetworkconfig/generator.go#L140-L142

I'll open a Jira ticket to keep track of this.

**Review by osherdp — APPROVED** [review]

**Comment by nmagnezi** [comment]
Keeping the `hold` label so we can get https://github.com/openshift/assisted-service/pull/4156 merged first. It will fix subsystem for nmstate version coming with CentOS9 stream

**Review by osherdp — APPROVED** [review]

**Pull request merged**
