### PR TITLE
OCPBUGSM-31691: Add Machine net CIDR to ACI status

### PR DESCRIPTION
**Pull request by nmagnezi**
# Assisted Pull Request

## Description

Add Machine net CIDR to ACI status.

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @filanov 
/cc @rollandf 
/cc @danielerez 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [x] Are the title and description (in both PR and commit) meaningful and clear?
- [x] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
Created resources from the examples under [docs/hive-integration/crds](https://github.com/openshift/assisted-service/tree/master/docs/hive-integration/crds)
`machineNetworkCidr`is now listed (and filled).


```yaml
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions.hive.openshift.io/v1beta1","kind":"AgentClusterInstall","metadata":{"annotations":{},"name":"test-agent-cluster-install","namespace":"spoke-cluster"},"spec":{"clusterDeploymentRef":{"name":"single-node"},"imageSetRef":{"name":"openshift-v4.8.0"},"networking":{"clusterNetwork":[{"cidr":"10.128.0.0/14","hostPrefix":23}],"machineNetwork":[{"cidr":"192.168.126.0/24"}],"serviceNetwork":["172.30.0.0/16"]},"provisionRequirements":{"controlPlaneAgents":1}}}
  creationTimestamp: "2021-07-06T15:03:28Z"
  finalizers:
  - agentclusterinstall.agent-install.openshift.io/ai-deprovision
  generation: 1
  name: test-agent-cluster-install
  namespace: spoke-cluster
  ownerReferences:
  - apiVersion: hive.openshift.io/v1
    kind: ClusterDeployment
    name: single-node
    uid: df9369e4-2e1f-4602-a9d6-0f5a8d42b8e6
  resourceVersion: "4582698"
  uid: be282165-7d62-401d-af0e-70a5c6fdb80a
spec:
  clusterDeploymentRef:
    name: single-node
  imageSetRef:
    name: openshift-v4.8.0
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    machineNetwork:
    - cidr: 192.168.126.0/24
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 1
status:
  conditions:
  - lastProbeTime: "2021-07-06T15:04:43Z"
    lastTransitionTime: "2021-07-06T15:04:43Z"
    message: SyncOK
    reason: SyncOK
    status: "True"
    type: SpecSynced
  - lastProbeTime: "2021-07-06T15:04:43Z"
    lastTransitionTime: "2021-07-06T15:04:43Z"
    message: 'The cluster''s validations are failing: Single-node clusters must have
      a single master node and no workers.'
    reason: ValidationsFailing
    status: "False"
    type: Validated
  - lastProbeTime: "2021-07-06T15:04:43Z"
    lastTransitionTime: "2021-07-06T15:04:43Z"
    message: The cluster is not ready to begin the installation
    reason: ClusterNotReady
    status: "False"
    type: RequirementsMet
  - lastProbeTime: "2021-07-06T15:04:43Z"
    lastTransitionTime: "2021-07-06T15:04:43Z"
    message: The installation has not yet started
    reason: InstallationNotStarted
    status: "False"
    type: Completed
  - lastProbeTime: "2021-07-06T15:04:43Z"
    lastTransitionTime: "2021-07-06T15:04:43Z"
    message: The installation has not failed
    reason: InstallationNotFailed
    status: "False"
    type: Failed
  - lastProbeTime: "2021-07-06T15:04:43Z"
    lastTransitionTime: "2021-07-06T15:04:43Z"
    message: The installation is waiting to start or in progress
    reason: InstallationNotStopped
    status: "False"
    type: Stopped
  connectivityMajorityGroups: '{}'
  debugInfo:
    eventsURL: http://10.104.201.173:8090/api/assisted-install/v1/clusters/8cdb56ab-d93f-452e-a45c-ed4b97ef4adf/events?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiOGNkYjU2YWItZDkzZi00NTJlLWE0NWMtZWQ0Yjk3ZWY0YWRmIn0.5aVmgjMhAHMevtxnVCutSOWDniq6Js_dEXhQysVNiThgXOIFKrWr3FnmB-ajKjTpiNq2HLXrSJnFZdv1GOQSaw
    logsURL: http://10.104.201.173:8090/api/assisted-install/v1/clusters/8cdb56ab-d93f-452e-a45c-ed4b97ef4adf/logs?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiOGNkYjU2YWItZDkzZi00NTJlLWE0NWMtZWQ0Yjk3ZWY0YWRmIn0.ZQRxW1umq8T8QtvJbAeAO5TPozmLIiilHaShm2kbie1Hkr6QgmcYM9ICsRyDWnSrCNPhyqS195l0nYgpbNAutg
    state: insufficient
    stateInfo: Cluster is not ready for install
  machineNetworkCidr: 192.168.126.0/24
```

**Comment by filanov** [comment]
/hold 
@avishayt in the spec we have it as an array, but we support only one entry.
How should we show it in the status?

**Comment by avishayt** [comment]
> /hold
> @avishayt in the spec we have it as an array, but we support only one entry.
> How should we show it in the status?

Do you remember why it's an array?  And isn't it calculated from the VIPs?

**Comment by filanov** [comment]
> > /hold
> > @avishayt in the spec we have it as an array, but we support only one entry.
> > How should we show it in the status?
> 
> Do you remember why it's an array? And isn't it calculated from the VIPs?

I see that in the install config it's an array https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-configuration-parameters-network_installing-bare-metal-network-customizations
Maybe we should keep it an array so we will not need to break the API later.

**Comment by avishayt** [comment]
> Maybe we should keep it an array so we will not need to break the API later.

Yes agree.  Looks like we already made that decision in the Spec, let's stick with it.

**Comment by nmagnezi** [comment]
/unhold

Ready for review again.
`status.machineNetwork` is now an array.

```yaml
apiVersion: v1
items:
- apiVersion: extensions.hive.openshift.io/v1beta1
  kind: AgentClusterInstall
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions.hive.openshift.io/v1beta1","kind":"AgentClusterInstall","metadata":{"annotations":{},"name":"test-agent-cluster-install","namespace":"spoke-cluster"},"spec":{"clusterDeploymentRef":{"name":"single-node"},"imageSetRef":{"name":"openshift-v4.8.0"},"networking":{"clusterNetwork":[{"cidr":"10.128.0.0/14","hostPrefix":23}],"machineNetwork":[{"cidr":"192.168.126.0/24"}],"serviceNetwork":["172.30.0.0/16"]},"provisionRequirements":{"controlPlaneAgents":1}}}
    creationTimestamp: "2021-07-08T12:18:01Z"
    finalizers:
    - agentclusterinstall.agent-install.openshift.io/ai-deprovision
    generation: 1
    name: test-agent-cluster-install
    namespace: spoke-cluster
    ownerReferences:
    - apiVersion: hive.openshift.io/v1
      kind: ClusterDeployment
      name: single-node
      uid: f7dccb07-8676-4724-92d5-e105ebdde9f5
    resourceVersion: "4940121"
    uid: 39bbae20-1fd6-4b95-8dd8-672a1bb53a07
  spec:
    clusterDeploymentRef:
      name: single-node
    imageSetRef:
      name: openshift-v4.8.0
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 192.168.126.0/24
      serviceNetwork:
      - 172.30.0.0/16
    provisionRequirements:
      controlPlaneAgents: 1
  status:
    conditions:
    - lastProbeTime: "2021-07-08T12:18:01Z"
      lastTransitionTime: "2021-07-08T12:18:01Z"
      message: SyncOK
      reason: SyncOK
      status: "True"
      type: SpecSynced
    - lastProbeTime: "2021-07-08T12:18:01Z"
      lastTransitionTime: "2021-07-08T12:18:01Z"
      message: The cluster is not ready to begin the installation
      reason: ClusterNotReady
      status: "False"
      type: RequirementsMet
    - lastProbeTime: "2021-07-08T12:18:06Z"
      lastTransitionTime: "2021-07-08T12:18:06Z"
      message: 'The cluster''s validations are failing: Single-node clusters must
        have a single master node and no workers.'
      reason: ValidationsFailing
      status: "False"
      type: Validated
    - lastProbeTime: "2021-07-08T12:18:01Z"
      lastTransitionTime: "2021-07-08T12:18:01Z"
      message: The installation has not yet started
      reason: InstallationNotStarted
      status: "False"
      type: Completed
    - lastProbeTime: "2021-07-08T12:18:01Z"
      lastTransitionTime: "2021-07-08T12:18:01Z"
      message: The installation has not failed
      reason: InstallationNotFailed
      status: "False"
      type: Failed
    - lastProbeTime: "2021-07-08T12:18:01Z"
      lastTransitionTime: "2021-07-08T12:18:01Z"
      message: The installation is waiting to start or in progress
      reason: InstallationNotStopped
      status: "False"
      type: Stopped
    connectivityMajorityGroups: '{}'
    debugInfo:
      eventsURL: http://10.106.114.133:8090/api/assisted-install/v1/clusters/a7174048-986c-43bf-907d-253cf95bf0d9/events?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiYTcxNzQwNDgtOTg2Yy00M2JmLTkwN2QtMjUzY2Y5NWJmMGQ5In0.q0CxGs20fRjyjlwXh7QuGwsej4UuylPggwxbhtXhCf-YJyfyU-Zzg1NCO9SkOE_mfXxipwD1Q6D5r6imDZyj2w
      logsURL: http://10.106.114.133:8090/api/assisted-install/v1/clusters/a7174048-986c-43bf-907d-253cf95bf0d9/logs?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiYTcxNzQwNDgtOTg2Yy00M2JmLTkwN2QtMjUzY2Y5NWJmMGQ5In0.k79kYmXtzdHzLGgQON2rcfVUsRC7YXBA5tfkakXaWRblWTWvUsB0ELt1lZ2HdyoQ2a7spaUPljNo_0pCnHbgwA
      state: insufficient
      stateInfo: Cluster is not ready for install
    machineNetwork:
    - cidr: 192.168.126.0/24
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by nmagnezi** [comment]
/hold
need to regenerate.

**Comment by filanov** [comment]
LGTM, @avishayt @mhrivnak can you please take a look as well?

**Review by filanov — APPROVED** [review]

**Pull request merged**
