### PR TITLE
[cloud_hotfix_releases] MGMT-12528 - Disable network scanning for very large IPv4 subnets

### PR DESCRIPTION
**Pull request by adriengentil**
cherry-pick of https://github.com/openshift/assisted-service/pull/4601

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
/override ci/prow/subsystem-aws
https://github.com/openshift/assisted-service/pull/4578#issuecomment-1305615771

**Comment by adriengentil** [comment]
I think the `ci/prow/edge-*` jobs were triggered because I choose master as base brnach by mistake when opening the PR

**Comment by adriengentil** [comment]
/override ci/prow/e2e-metal-assisted-networking ci/prow/edge-e2e-metal-assisted ci/prow/edge-e2e-ai-operator-ztp

**Pull request merged**
