### PR TITLE
MGMT-15732: Fix unbound variable

### PR DESCRIPTION
**Pull request by CrystalChun**
https://issues.redhat.com/browse/MGMT-15732
Variable didn't have a default value, causing
tests to exit prematurely due to the potential
of this being unset.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

/cc @filanov

### CODE REVIEW

**Comment by CrystalChun** [comment]
The hypershift and capi jobs are failing because of the API upgrades (see https://github.com/openshift/cluster-api-provider-agent/pull/82#issuecomment-1719259602)

Note another WIP [PR](https://github.com/openshift/cluster-api-provider-agent/pull/85) is opened to address this

**Comment by danielerez** [comment]
Looks good. You can ignore the failing 'zero-nodes' test, it's failing for a few weeks. We can just disable it for now.

**Pull request merged**
