### PR TITLE
Moving conversion helpers to separate package

### PR DESCRIPTION
**Pull request by jakub-dzon**
This PR moves existing size conversion functions to a separate package to avoid cyclic imports in other changes.

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Comment by YuviGold** [comment]
Shouldn't it move under `pkg`? @filanov

**Comment by jakub-dzon** [comment]
> Shouldn't it move under `pkg`? @filanov

> Shouldn't it move under `pkg`? @filanov

Done.

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
