### PR TITLE
Use official swagger codegen docker image for client generation

### PR DESCRIPTION
**Pull request by carbonin**
This image has the fix to make things work with python 3.7
additionally the previous image was archived and unmaintained.

Fixes https://github.com/filanov/bm-inventory/issues/522

Moved from https://github.com/filanov/bm-inventory/pull/524

### CODE REVIEW

**Comment by tsorya** [comment]
if it passes test-infra looks good for me

**Comment by carbonin** [comment]
> if it passes test-infra looks good for me

Is this part of the CI suite or something we need to look at separately?

**Comment by carbonin** [comment]
This is also required for the kind of key handling I'm doing in https://github.com/openshift/assisted-test-infra/pull/71

**Comment by rollandf** [comment]
LGTM :+1:

**Comment by nmagnezi** [comment]
LGTM 👍

**Pull request merged**
