### PR TITLE
Bug 2065649: Fix image tags in operator's CSV

### PR DESCRIPTION
**Pull request by mkowalski**
This PR fixes image references for the release branch so that they
correctly point to `:ocm-2.5` instead of `:latest`.

Closes-bug: #2065649

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @omertuc 
/cc @javipolo 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by omertuc** [comment]
You're trying to merge into the wrong branch
/hold

**Comment by mkowalski** [comment]
/retest

`/bin/sh: docker: command not found` a flake?

**Comment by mkowalski** [comment]
/retest

`/bin/sh: docker: command not found` a flake?

**Comment by mkowalski** [comment]
/retest-required

Infra/OS issues

**Comment by mkowalski** [comment]
/retest-required

🙀

**Comment by gamli75** [comment]
@mkowalski @omertuc Does this PR mean that we will need to do the same after every new OCM release? 
@filanov @romfreiman FYI

**Comment by omertuc** [comment]
> @mkowalski @omertuc Does this PR mean that we will need to do the same after every new OCM release? @filanov @romfreiman FYI

Yes

**Comment by mkowalski** [comment]
Yes, we have been doing it in the past and, unless there is something fundamental we are not aware of, we will need to keep doing it

**Pull request merged**
