### PR TITLE
MGMT-7142: Bump OCP versions 4.7.16 -> 4.7.18, 4.8.0-rc.1 -> 4.8.0-rc.2

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.7 release notes: https://access.redhat.com/errata/RHBA-2021:2502
4.8 has no available release notes

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by YuviGold** [comment]
single-node job passed installation but failed due to a known issue failing to resolve DNS in our infra.
/override ci/prow/e2e-metal-assisted-single-node

**Pull request merged**
