### PR TITLE
MGMT-7774: convert V1 APIs to V2 APIs

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
The following APIs are being converted:
1) cluster reset
    POST /v1/clusters/{cluster_id}/actions/reset --> POST /v2/clusters/{cluster_id}/actions/reset

2) get cluster preflight requirments
    GET /v1/clusters/{cluster_id}/preflight-requirements --> GET /v2/clusters/{cluster_id}/preflight-requirements

3) upload ingress certificate
     POST /v1/clusters/{cluster_id}/uploads/ingress-cert --> POST /v2/clusters/{cluster_id}/uploads/ingress-cert

4) complete installation
     POST /v1/clusters/{cluster_id}/actions/complete_installation --> POST /v2/clusters/{cluster_id}/actions/complete_installation

5) report cluster logs progress
    PUT /v1/clusters/{cluster_id}/logs_progress --> PUT /v2/clusters/{cluster_id}/logs-progress

# Assisted Pull Request

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by avishayt** [comment]
In the commit message you have "/v2/clusters/{cluster_id}/actions/complete_installation", but it should be "complete-installation" (with a hyphen instead of underscore).  It's correct in the swagger.

**Comment by yevgeny-shnaidman** [comment]
> In the commit message you have "/v2/clusters/{cluster_id}/actions/complete_installation", but it should be "complete-installation" (with a hyphen instead of underscore). It's correct in the swagger.

fixed

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Pull request merged**
