### PR TITLE
Revert "MGMT-6576 - Bump 4.8 OCP to fc.5"

### PR DESCRIPTION
**Pull request by osherdp**
Reverts openshift/assisted-service#1791
Seems like SNO doesn't work on this version because of a bug in recent monitoring operator.

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Comment by omertuc** [comment]
Any logs/link for "SNO doesn't work"?

**Comment by romfreiman** [comment]
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#periodic-ci-openshift-release-master-nightly-4.8-e2e-metal-single-node-live-iso

**Comment by filanov** [comment]
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api

**Comment by osherdp** [comment]
/override ci/prow/assisted-operator-install-aws ci/prow/e2e-metal-assisted ci/prow/e2e-metal-assisted-operator-ztp ci/prow/subsystem-aws ci/prow/subsystem-kubeapi-aws ci/prow/system-test

**Pull request merged**
