### PR TITLE
MGMT-11386: approve day2 CSRs for an agent without BMH

### PR DESCRIPTION
**Pull request by danielerez**
In day2 flow, when reconciling an agent the CSRs should be manually approved if not done by the cluster-machine-approver. As the automatic approval is done only when a BMH exists for an agent (and non-UMN), we should try to approve agents without associated BMHs.

Hence, approving CSRs for rebooting hosts when:
* Agent belongs to a none platform cluster
* No BMH exists for agent

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danielerez** [comment]
> The condition should be "if is none" **or** "if no BMH exist"
> 
> A none-platform ZTP (BMH-based) installation also needs our help in approving CSRs

Sure, changed.

**Review by ori-amizur — APPROVED** [review]

**Pull request merged**
