### PR TITLE
MGMT-9532: Don't set openshift version in upgrade files

### PR DESCRIPTION
**Pull request by carbonin**
These versions will always be set dynamically based on the value of
ASSISTED_UPGRADE_OPERATOR in the common.sh script. There's no reason for
us to maintain defaults here.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

:man_shrugging: I don't really know how to test this, but it's been broken for quite a while.
Hoping to get this in and see if the rehearse tests pass on https://github.com/openshift/release/pull/27293

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @osherdp 
/cc @eliorerz 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by osherdp** [comment]
As for the testing method, I'd recommend getting changes in ``release`` repo first and then testing the changes in assisted-service. Otherwise it takes a lot of time getting things merged in assisted-service

For that to be possible, we should have a ``e2e-metal-assisted-operator-ztp-periodic-upgrade`` presubmit job, which I'm not sure why it's not existing

Other option: temporarily clone your branch in the ``release`` PR, right before this line: https://github.com/openshift/release/blob/72259045c7cbeaad1c64f31eb923552789c5b74e/ci-operator/step-registry/assisted/baremetal/operator/setup/assisted-baremetal-operator-setup-commands.sh#L13

/lgtm
/hold
(just to wait for the testing results)

**Comment by carbonin** [comment]
/unhold

Going to just remove the hold from this one because this shouldn't affect anything other than the test that's already failing and it's quite a bit of work to get my branch running in the release rehearse jobs.

**Pull request merged**
