### PR TITLE
assisted-service-operator: bundle versions

### PR DESCRIPTION
**Pull request by djzager**
# Description

Moving the in-source version to `v99.0.0-unreleased` should guarantee us
a few things:
1. We don't need to keep creating PRs to bump the version, although we
   may want to add released versions to the `spec.skips` section of the
   clusterserviceversion.
2. It will be easy for us to identify in development/testing when an
   operator is created/installed from source versus community-operators
   (or even ACM mechanisms).

Additionally, with the creation of the `ocm-2.3` branch, we should no
longer be targetting the `ocm-2.3` channel with the operator being built
from master.

# What environments does this code impact?

- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

# How was this code tested?

Please, select one or more if needed:

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [x] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

It's recommended to take a few extra minutes to provide more information about
how this code was tested. Here are some questions that may be worth answering:

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run?
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

# Assignees

/assign @celebdor 
/assign @lranjbar 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change includes unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by mkowalski** [comment]
I have built the operator bundle directly from this PR. It gave me the following result

```
# operator-sdk run bundle \
>   --namespace assisted-installer-pr1902-1 \
>   quay.io/mkowalski/assisted-service-operator-bundle:pr1902-1
INFO[0006] Successfully created registry pod: quay-io-mkowalski-assisted-service-operator-bundle-pr1902-1
INFO[0006] Created CatalogSource: assisted-service-operator-catalog
INFO[0006] OperatorGroup "operator-sdk-og" created
INFO[0006] Created Subscription: assisted-service-operator-v99-0-0-unreleased-sub
INFO[0033] Approved InstallPlan install-clt84 for the Subscription: assisted-service-operator-v99-0-0-unreleased-sub 
INFO[0033] Waiting for ClusterServiceVersion "assisted-installer-pr1902-1/assisted-service-operator.v99.0.0-unreleased" to reach 'Succeeded' phase 
INFO[0033]   Waiting for ClusterServiceVersion "assisted-installer-pr1902-1/assisted-service-operator.v99.0.0-unreleased" to appear 
INFO[0046]   Found ClusterServiceVersion "assisted-installer-pr1902-1/assisted-service-operator.v99.0.0-unreleased" phase: Pending 
INFO[0049]   Found ClusterServiceVersion "assisted-installer-pr1902-1/assisted-service-operator.v99.0.0-unreleased" phase: InstallReady 
INFO[0052]   Found ClusterServiceVersion "assisted-installer-pr1902-1/assisted-service-operator.v99.0.0-unreleased" phase: Installing
[...]
```

Looks very nice, so now I clearly see if I'm rolling on my own version or the official one 👍🏻

**Comment by mkowalski** [comment]
/approve cancel
/lgtm

(sorry for the noise, checking what this bot is doing 😅 )

**Comment by djzager** [comment]
Hopefully a rebase will be the kick needed to get `pr-merge` to run.

**Pull request merged**
