### PR TITLE
MGMT-2732 Run assisted-service disconnected with mirror registry

### PR DESCRIPTION
**Pull request by sacharya**

### CODE REVIEW

**Review by djzager — APPROVED** [review]
/lgtm

**Comment by romfreiman** [comment]
Why isn't it part of test-infra?

**Comment by sacharya** [comment]
@romfreiman I think David is working on enabling disconnected in test-infra and CI. https://issues.redhat.com/browse/MGMT-2953
But I think there is still value in making the registry configurable here.

**Comment by djzager** [comment]
> @romfreiman I think David is working on enabling disconnected in test-infra and CI. https://issues.redhat.com/browse/MGMT-2953
> But I think there is still value in making the registry configurable here.

I suspect I could easily be missing something so please correct me if I'm wrong. But I don't see anything that, for MGMT-2953, would require changes to test-infra. My original thought was that I could simply work through automating the disconnected process and add it to the Jenkinsfile like the [current on-prem](https://github.com/openshift/assisted-service/blob/master/Jenkinsfile#L53-L59).

**Pull request closed without merging**
