### PR TITLE
NO-ISSUE Revert PR#1285 adding operator-bundle to build-all and publish

### PR DESCRIPTION
**Pull request by rwsu**
The publish step is failing with

"quay.io: unauthorized: access to the requested resource is not authorized"

### CODE REVIEW

**Comment by rwsu** [comment]
/hold 

looks like the builds are ok now after creating the missing repository in quay.io

**Review by flaper87 — COMMENTED** [review]
Any idea why the push is not authorized? As in, how can we get access for this push (assuming this is what we want)?

/lgtm

**Comment by rwsu** [comment]
We needed to create the repository first in order for the push to work. @ronniel1 has helped set that up. Several builds have passed with publish success. Closing this PR.

**Comment by YuviGold** [comment]
Not sure how it passed before. But the `operator-sdk` isn't installed correctly on our Jenkins slaves and error is passed silently.
```bash
[root@522d3f6cc375 origin]# operator-sdk --help
/usr/local/bin/operator-sdk: line 1: Not: command not found
[root@faa1b82ea24b origin]# cat operator-sdk_linux_amd64 
Not Found
```
From a glance, it looks like amd64 asset isn't being released for operator-sdk.
Moreover, I thing we shouldn't use "latest" version since it might get broken.

**Pull request merged**
