### PR TITLE
MGMT-8098: Bump OCP versions release 4.7.34 -> 4.7.36, release 4.8.15 -> 4.8.17, release 4.9.0 -> 4.9.4

### PR DESCRIPTION
**Pull request by osherdp**
4.9 release notes: https://access.redhat.com/errata/RHBA-2021:3935
4.7 release notes: https://access.redhat.com/errata/RHBA-2021:3931
4.8 release notes: https://access.redhat.com/errata/RHBA-2021:3927

/cc @romfreiman @celebdor @gamli75
/test all
/hold

### CODE REVIEW

**Comment by osherdp** [comment]
OVNKubernetes seems to always fail

**Comment by osherdp** [comment]
@danielerez when you got time to have a look
why does it use 4.8.15 instead of 4.8.17 on the ``e2e-metal-assisted-networking`` job?
I'm looking here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2843/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-networking/1455107177248198656/artifacts/e2e-metal-assisted-networking/baremetalds-assisted-gather/artifacts/2000-01-01_00:00:00_189cd9d3-7fc3-4a41-b5e6-8c1164f242a0/metadata.json

**Comment by danielerez** [comment]
> 4.8.15

Shouldn't it be handled by this PR? This PR updates to 4.8.17, and other jobs also still use 4.8.15:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2843/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-olm/1454916998570971136/artifacts/e2e-metal-assisted-olm/baremetalds-assisted-gather/artifacts/2021-10-31_21:32:50_1021f401-fe0b-4298-bc42-7f1e809750ad/metadata.json

**Comment by osherdp** [comment]
> > 4.8.15
> 
> Shouldn't it be handled by this PR? This PR updates to 4.8.17, and other jobs also still use 4.8.15: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2843/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-olm/1454916998570971136/artifacts/e2e-metal-assisted-olm/baremetalds-assisted-gather/artifacts/2021-10-31_21:32:50_1021f401-fe0b-4298-bc42-7f1e809750ad/metadata.json

yeah that's what troubling me. where does it take this version from?

**Comment by danielerez** [comment]
> > > 4.8.15
> > 
> > 
> > Shouldn't it be handled by this PR? This PR updates to 4.8.17, and other jobs also still use 4.8.15: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2843/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-olm/1454916998570971136/artifacts/e2e-metal-assisted-olm/baremetalds-assisted-gather/artifacts/2021-10-31_21:32:50_1021f401-fe0b-4298-bc42-7f1e809750ad/metadata.json
> 
> yeah that's what troubling me. where does it take this version from?

Yeah seems 4.8.17 is available only in fast channel, so we get it from there:
https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.8&arch=amd64

**Review by mkowalski — APPROVED** [review]
🥐

**Review by filanov — APPROVED** [review]

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-multi-version
(unstable job)

**Pull request merged**
