### PR TITLE
MGMT-10973 - kube-api imported clusters should be considered imported

### PR DESCRIPTION
**Pull request by omertuc**
As part of 564650feca372064314282d98d6fd9c6ee69bd2c we pretended
imported kube-api clusters are not imported, which is wrong, just
to disable DNS validations because those validations were causing
issues in the CAPI CI and we had to merge the PR quickly because
it was needed for a SaaS release.

This commit reverts that hack. We expect the capi CI to fail, but
at-least now we can fix it without hurrying to get it merged for
a release.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @eranco74

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by omertuc** [comment]
@eranco74 results available [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/4155/pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-capi/1549311055857979392)

**Comment by omertuc** [comment]
Let's wait a while after the https://github.com/openshift/assisted-test-infra/pull/1765 merge and then retest

**Comment by eranco74** [comment]
Please rebase it on top of master once https://github.com/openshift/assisted-service/pull/4171 merge
and let's make sure edge-e2e-metal-assisted-capi pass

**Comment by omertuc** [comment]
It should've already passed following https://github.com/openshift/assisted-test-infra/pull/1765

**Comment by eranco74** [comment]
> It should've already passed following [openshift/assisted-test-infra#1765](https://github.com/openshift/assisted-test-infra/pull/1765)

Note that the test only configures the api and api-int DNS records (and doesn't configure *.apps...) and that's why the agent validations fails:
```
{ID:api-domain-name-resolved-correctly Status:success Message:Domain name resolution for the api.test-infra-cluster-ca80f8cf.redhat.com domain was successful or not required} {ID:api-int-domain-name-resolved-correctly Status:success Message:Domain name resolution for the api-int.test-infra-cluster-ca80f8cf.redhat.com domain was successful or not required} {ID:apps-domain-name-resolved-correctly Status:failure Message:Couldn't resolve domain name *.apps.test-infra-cluster-ca80f8cf.redhat.com on the host. To continue installation, create the necessary DNS entries to resolve this domain name to your cluster's application ingress IP address}
```

**Comment by eranco74** [comment]
> It should've already passed following [openshift/assisted-test-infra#1765](https://github.com/openshift/assisted-test-infra/pull/1765)

The test will pass since the DNS validation should get skipped following this https://github.com/openshift/assisted-test-infra/pull/1765 as it did [here](https://github.com/openshift/assisted-service/pull/4174)
I guess you just need to rebase this PR (though I think we can just merge it).

**Pull request merged**
