### PR TITLE
NO-ISSUE Don't recreate the s3 client for local ignition generator

### PR DESCRIPTION
**Pull request by carbonin**
I'm also not sure how this worked previously. It looks like the s3 client used when uploading the generated files would have had a separate data directory form the one we then would have used to download the files.

It feels like it's either broken now, or this will break something, but I'm also not sure how to test this.
@djzager @mhrivnak can you help out here (or suggest someone who might be able to)?

### CODE REVIEW

**Comment by mhrivnak** [comment]
@sacharya you probably have a better memory than I do about how the local FS client works. I recall that the client's working directory within each local job was scoped to each cluster's own directory for a reason, but I don't recall what that was.

**Comment by sacharya** [comment]
@carbonin If you upload the files to workDir, you will likely break the Download operation. clusterId/files format was to mimic the directory structure used by s3 as local filesystem is implementing the same interface.

**Comment by carbonin** [comment]
Actually, looking at this again ... The only place the local job implementation would even use that passed in s3 client is for [fetching any user-provided manifests](https://github.com/openshift/assisted-service/blob/d5a4c9feb1b5ddd86c1cb29f97e91f628a28938e/internal/ignition/ignition.go#L274) as it never calls `UploadToS3`.

The generator is passed the working directory based on the job's working directory which is already scoped to the cluster [here](https://github.com/openshift/assisted-service/blob/d5a4c9feb1b5ddd86c1cb29f97e91f628a28938e/pkg/job/local_job.go#L36). This means that we never actually have to use the s3client for uploading because the [default for the s3client data directory](https://github.com/openshift/assisted-service/blob/d5a4c9feb1b5ddd86c1cb29f97e91f628a28938e/cmd/main.go#L268) is the same as the [job config](https://github.com/openshift/assisted-service/blob/d5a4c9feb1b5ddd86c1cb29f97e91f628a28938e/pkg/job/job.go#L49).

Actually, this makes me feel like there are several bugs we have yet to discover with on-prem:
1. User-provided manifests may not be applied
    - If this is a bug it will be fixed by this PR
2. Changing the WORK_DIR environment variable would make us unable to download the host ignition files
    - For this one, we can probably explicitly set the s3 clients working directory to the job working directory with a comment

@sacharya what do you think?

**Comment by sacharya** [comment]
You are right. The install-config files get generated in the clusterId directory and there is no need to call UploadToS3.

I'd just test the download workflow to make sure it's not broken. That piece of code has changed quite a bit. Otherwise, it looks good.

**Comment by carbonin** [comment]
/hold

With this change I'm getting an error related to chrony manifests. Looking into it now.
```
INFO[0158]/go/src/github.com/openshift/origin/internal/oc/release.go:151 github.com/openshift/assisted-service/internal/oc.(*release).extractFromRelease() extracting openshift-baremetal-install binary to /data/installercache/quay.io/openshift-release-dev/ocp-release:4.6.12-x86_64  go-id=483 pkg=local-job-wrapper request_id=36fb58d8-fefb-46ac-a13d-b539861b5981
INFO[0163]/go/src/github.com/openshift/origin/internal/ignition/ignition.go:288 github.com/openshift/assisted-service/internal/ignition.(*installerGenerator).Generate() Adding manifest /4fe3a9a1-86ab-4e29-bff0-74fd2c955728/manifests/openshift/masters-chrony-configuration.yaml to working dir for cluster 4fe3a9a1-86ab-4e29-bff0-74fd2c955728  go-id=483 pkg=local-job-wrapper request_id=36fb58d8-fefb-46ac-a13d-b539861b5981
ERRO[0163]/go/src/github.com/openshift/origin/internal/ignition/ignition.go:293 github.com/openshift/assisted-service/internal/ignition.(*installerGenerator).Generate() Failed to download manifest /4fe3a9a1-86ab-4e29-bff0-74fd2c955728/manifests/openshift/masters-chrony-configuration.yaml to working dir for cluster 4fe3a9a1-86ab-4e29-bff0-74fd2c955728  error="open /data/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/manifests/openshift/masters-chrony-configuration.yaml: no such file or directory" go-id=483 pkg=local-job-wrapper request_id=36fb58d8-fefb-46ac-a13d-b539861b5981
ERRO[0163]/go/src/github.com/openshift/origin/internal/bminventory/inventory.go:1529 github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).generateClusterInstallConfig() failed generating kubeconfig files for cluster 4fe3a9a1-86ab-4e29-bff0-74fd2c955728  error="open /data/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/manifests/openshift/masters-chrony-configuration.yaml: no such file or directory" go-id=483 pkg=Inventory request_id=36fb58d8-fefb-46ac-a13d-b539861b5981
WARN[0163]/go/src/github.com/openshift/origin/internal/bminventory/inventory.go:1323 github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).InstallClusterInternal.func3.1() Cluster installation initialization failed    cluster_id=4fe3a9a1-86ab-4e29-bff0-74fd2c955728 error="failed generating kubeconfig files for cluster 4fe3a9a1-86ab-4e29-bff0-74fd2c955728: open /data/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/manifests/openshift/masters-chrony-configuration.yaml: no such file or directory" go-id=21 pkg=Inventory request_id=36fb58d8-fefb-46ac-a13d-b539861b5981
INFO[0163]/go/src/github.com/openshift/origin/internal/cluster/common.go:63 github.com/openshift/assisted-service/internal/cluster.updateClusterStatus() cluster 4fe3a9a1-86ab-4e29-bff0-74fd2c955728 has been updated with the following updates [status error status_info failed generating kubeconfig files for cluster 4fe3a9a1-86ab-4e29-bff0-74fd2c955728: open /data/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/4fe3a9a1-86ab-4e29-bff0-74fd2c955728/manifests/openshift/masters-chrony-configuration.yaml: no such file or directory status_updated_at 2021-02-04T13:30:56.959Z install_completed_at 2021-02-04T13:30:56.959Z]  go-id=483 pkg=cluster-state request_id=36fb58d8-fefb-46ac-a13d-b539861b5981
```

**Comment by carbonin** [comment]
I think there's a bug in the filesystem s3 client.
It's adding a leading slash when returning object names from [ListObjectsByPrefix](https://github.com/openshift/assisted-service/blob/27fab2c5e6364ffe84173d533164b83fdb67fac4/pkg/s3wrapper/filesystem.go#L298) but in other places we [assert that there is no leading slash](https://github.com/openshift/assisted-service/blob/27fab2c5e6364ffe84173d533164b83fdb67fac4/internal/cluster/cluster_test.go#L2015). Additionally the [comment in ignition.go](https://github.com/openshift/assisted-service/blob/27fab2c5e6364ffe84173d533164b83fdb67fac4/internal/ignition/ignition.go#L1056-L1057) seems to indicate that it doesn't expect a slash (and the code breaks if a slash is present as we can see).

@mhrivnak @rwsu do you remember if adding that leading slash was particularly important in https://github.com/openshift/assisted-service/pull/337 ?

**Comment by carbonin** [comment]
/unhold

This ended up being a bit bigger than I intended, but I think it's worthwhile and fixes a few bugs.

**Review by djzager — APPROVED** [review]
Looks good to me. Ping @sacharya for a second set of :eyes: and a `lgtm`.

**Comment by carbonin** [comment]
/hold

Forgot to fix the work dir config issue. Testing that now

**Pull request merged**
