### PR TITLE
OCPBUGS-15346,OCPBUGS-13611: update gin version

### PR DESCRIPTION
**Pull request by suybhat**
Update github.com/gin-gonic/gin  package version to v1.9.1 for usage in indirect dependancies using replace.
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rccrdpccl** [comment]
/hold

Latest go-http-metrics (used by assisted-image-service, which is the dependency that requires gin) is `v0.11.0`. If we 
update to latest it should also update gin dependency.

@paul-maidment WDYT about updating that instead? IIUC it shouldn't have any breaking change

**Comment by paul-maidment** [comment]
@rccrdpccl I think that assisted-service is already running the right version of gin, so I am confused?

`paulmaidment@fedora ~/projects/workspaces/1/assisted-service (master)$ go mod graph | grep gin-gonic
github.com/slok/go-http-metrics@v0.11.0 github.com/gin-gonic/gin@v1.9.1`

**Comment by rccrdpccl** [comment]
@suybhat how did we get alerted of this vulnerability? Is the current image being flagged by some scan? As @paul-maidment  commented it looks like we already running the replaced version

**Comment by bfournie** [comment]
The issue was with `release-4.14` so we should just target that branch

In `release-4.14`
```
$ go mod graph | grep "gin-gonic/gin"
github.com/slok/go-http-metrics@v0.10.0 github.com/gin-gonic/gin@v1.7.4
github.com/slok/go-http-metrics@v0.9.0 github.com/gin-gonic/gin@v1.6.3
```

**Comment by rccrdpccl** [comment]
Thanks @bfournie - sure, let's merge this in release-4.14. I'll close this PR

**Pull request closed without merging**
