### PR TITLE
AGENT-215: Set release mirror for agent-based-installer

### PR DESCRIPTION
**Pull request by bfournie**
For the agent-based-installer the release mirror needs to be set when configured in the agent. Use the assisted-service environment variable to accomplish this.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by bfournie** [comment]
> I'm not sure what this `releaseMirror` param is doing. (seems obsolete) Seems that it's never passed to the `getReleaseVersionAndCpuArch` function. From looking at the code it seems that you can just use `releaseImage` with the argument you want to pass as `releaseMirror` and get the same behavior.

So the releaseMirror is passed from getReleaseVersionAndCpuArch() to releaseHandler.GetOpenshiftVersion() and there is a slight difference in behavior - https://github.com/openshift/assisted-service/blob/master/internal/oc/release.go#L118. The last parameter to getImageFromRelease() "insecure" is always true in this case. So just setting releaseImage to releaseMirror won't give the same behavior.

**Comment by eranco74** [comment]
> > I'm not sure what this `releaseMirror` param is doing. (seems obsolete) Seems that it's never passed to the `getReleaseVersionAndCpuArch` function. From looking at the code it seems that you can just use `releaseImage` with the argument you want to pass as `releaseMirror` and get the same behavior.
> 
> So the releaseMirror is passed from getReleaseVersionAndCpuArch() to releaseHandler.GetOpenshiftVersion() and there is a slight difference in behavior - https://github.com/openshift/assisted-service/blob/master/internal/oc/release.go#L118. The last parameter to getImageFromRelease() "insecure" is always true in this case. So just setting releaseImage to releaseMirror won't give the same behavior.

You are right,
Since your code is going to be the only place that uses the releaseMirror option, consider changing GetOpenshiftVersion signature to get `insecure bool`  instead of `releaseMirror string`.
e.g.
`func (r *release) GetOpenshiftVersion(log logrus.FieldLogger, releaseImage string, insecure bool, pullSecret string) (string, error)`
It should simplify the code, and actually represent what it's actually mean.

**Pull request merged**
