### PR TITLE
MGMT-3877, Bump OCP version from 4.6.12 to 4.6.15 (auto created)

### PR DESCRIPTION
**Pull request by ronniel1**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by YuviGold** [comment]
@oshercc  Should close the previous PR or update it https://github.com/openshift/assisted-service/pull/995

**Comment by ronniel1** [comment]
test-infra test passed, HOLD label removed, see http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/4321/

**Comment by oshercc** [comment]
@gamli75 can you please ask Ronni to close this PR and delete the branch?

**Comment by gamli75** [comment]
not relevant anymore

**Pull request closed without merging**
