### PR TITLE
NO-ISSUE: grammar fix in log messages

### PR DESCRIPTION
**Pull request by mhrivnak**

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Review by avishayt — APPROVED** [review]

**Comment by eranco74** [comment]
@YuviGold  seems that /retest doesn't trigger a new build of this PR (last build was 9 days ago...)
http://10.46.10.2:8080/blue/organizations/jenkins/assisted-service/activity?branch=PR-418

**Comment by YuviGold** [comment]
> @YuviGold seems that /retest doesn't trigger a new build of this PR (last build was 9 days ago...)
> http://10.46.10.2:8080/blue/organizations/jenkins/assisted-service/activity?branch=PR-418

@eranco74 
`openshift-bot` comments `/retest` if it senses a failure but only the `openshift-ci-robot` know how to interpret this command. Jenkins doesn't have this feature.

**Pull request merged**
