### PR TITLE
OCPBUGSM-1936338 Fixed the total disks to be used while generating OCS manifests.

### PR DESCRIPTION
**Pull request by priyanka19-98**
Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Review by nbalacha — CHANGES_REQUESTED** [review]
While this will work, a better approach would be to remove the duplication of the config in both ocsOperator and OcsValidator. Can the ocsOperator implement the OCSValidator interface as well?

**Comment by priyanka19-98** [comment]
> While this will work, a better approach would be to remove the duplication of the config in both ocsOperator and OcsValidator. Can the ocsOperator implement the OCSValidator interface as well?

Could you please elaborate more on the same.

**Comment by nbalacha** [comment]
> > While this will work, a better approach would be to remove the duplication of the config in both ocsOperator and OcsValidator. Can the ocsOperator implement the OCSValidator interface as well?
> 
> Could you please elaborate more on the same.

There is a config element in the ocsOperator struct as well as the ocsValidator struct. Do we need 2 copies of the same?
Instead we could just have the ocsOperator implement the validation interface as well instead of having a validator struct.

**Comment by nbalacha** [comment]
> > > While this will work, a better approach would be to remove the duplication of the config in both ocsOperator and OcsValidator. Can the ocsOperator implement the OCSValidator interface as well?
> > 
> > 
> > Could you please elaborate more on the same.
> 
> There is a config element in the ocsOperator struct as well as the ocsValidator struct. Do we need 2 copies of the same?
> Instead we could just have the ocsOperator implement the validation interface as well instead of having a validator struct.

I am going to approve this PR but I think we should work with a single config going forward.

**Comment by priyanka19-98** [comment]
> > > > While this will work, a better approach would be to remove the duplication of the config in both ocsOperator and OcsValidator. Can the ocsOperator implement the OCSValidator interface as well?
> > > 
> > > 
> > > Could you please elaborate more on the same.
> > 
> > 
> > There is a config element in the ocsOperator struct as well as the ocsValidator struct. Do we need 2 copies of the same?
> > Instead we could just have the ocsOperator implement the validation interface as well instead of having a validator struct.
> 
> I am going to approve this PR but I think we should work with a single config going forward.

yes, that would require some refactoring work.

**Pull request merged**
