### PR TITLE
MGMT-10569: Remove cluster ignition_config_overrides column

### PR DESCRIPTION
**Pull request by carbonin**
Remove the ignition_config_overrides column from the database and remove the corresponding attribute from the model.

Automigrate doesn't remove columns so we need to do this manually
It's required to `Exec` here because the gormigrate `DropColumn` function requires that the model contain the field being dropped, but that is also being removed with this change. Additionally it doesn't support the `IF EXISTS` portion so it would require more logic to handle this migration correctly.

The migration that populates an infraEnv for each cluster is also removed as a part of this change.
It should not be needed in any environment at this point and keeping it would mean trying to maintain this migration without using the cluster model and that's not worth the effort when this is never expected to be needed again.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

1. Deployed latest `master` branch locally to minikube.
2. Built this branch and deployed the resulting image.
3. Verified that the column was correctly removed.

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @avishayt 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by avishayt** [comment]
Looks good, thanks!  Please fix lint.

**Comment by carbonin** [comment]
CAPI job is failing everywhere it seems.

**Comment by carbonin** [comment]
/unhold

Nevermind, didn't realize it wasn't a required test.

**Pull request merged**
