### PR TITLE
MGMT-13454: Group Host and boot logs to a single tarball

### PR DESCRIPTION
**Pull request by nmagnezi**
## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
cluster logs example from `ci/prow/edge-e2e-metal-assisted` artifacts: [cluster_1dc45877-8624-47ea-a102-a8dd2a31e0d8_logs.tar](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/4975/pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted/1625025868462034944/artifacts/e2e-metal-assisted/assisted-common-gather/artifacts/2023-02-13_07-34-33_1dc45877-8624-47ea-a102-a8dd2a31e0d8/cluster_1dc45877-8624-47ea-a102-a8dd2a31e0d8_logs.tar)

**Comment by omertuc** [comment]
The extensions for each individual host tar inside that tar is `.tar.gz` but in reality they're all uncompressed `.tar` archives

**Comment by nmagnezi** [comment]
> The extensions for each individual host tar inside that tar is `.tar.gz` but in reality they're all uncompressed `.tar` archives

Fixed.

**Comment by eranco74** [comment]
Is there a pending PR to fix the signatures in [assisted-installer-deployment](https://github.com/openshift-assisted/assisted-installer-deployment/blob/master/tools/add_triage_signature.py)?

**Comment by nmagnezi** [comment]
> Is there a pending PR to fix the signatures in [assisted-installer-deployment](https://github.com/openshift-assisted/assisted-installer-deployment/blob/master/tools/add_triage_signature.py)?

@eranco74 yes: https://github.com/openshift-assisted/assisted-installer-deployment/pull/349

**Comment by slaviered** [comment]
@nmagnezi So now logs_info also report on the boot logs? that will insure that the user will get a notice if he want to reset the installation where not all logs are packaged yet

**Pull request merged**
