### PR TITLE
Wrap JWKS and OCM URLs with quotation marks in configMap

### PR DESCRIPTION
**Pull request by nmagnezi**
This handles yaml parsing issues in Python reflected in CI

### CODE REVIEW

**Comment by nmagnezi** [comment]
cc: @oshercc - please test this before you merge

**Comment by nmagnezi** [comment]
@oshercc 
I have deployed with this change and the configMap with the result is [here](https://gist.github.com/nmagnezi/3cce00e7281778783238f1b82df43081#file-assisted-service-config-yaml-L13), not that in [line 23](https://gist.github.com/nmagnezi/3cce00e7281778783238f1b82df43081#file-assisted-service-config-yaml-L23) it does wrap the URL with quotation marks (snipped) --> `"JWKS_URL":"https://api.openshift.com/.well-known/jwks.json"`

please do validate that this resolves the parsing issue you encountered.

**Comment by nmagnezi** [comment]
> @oshercc
> I have deployed with this change and the configMap with the result is [here](https://gist.github.com/nmagnezi/3cce00e7281778783238f1b82df43081#file-assisted-service-config-yaml-L13), not that in [line 23](https://gist.github.com/nmagnezi/3cce00e7281778783238f1b82df43081#file-assisted-service-config-yaml-L23) it does wrap the URL with quotation marks (snipped) --> `"JWKS_URL":"https://api.openshift.com/.well-known/jwks.json"`
> 
> please do validate that this resolves the parsing issue you encountered.

also when tested locally: `SUCCESS! -- 49 Passed | 0 Failed | 0 Pending | 0 Skipped`

**Comment by oshercc** [comment]
@nmagnezi it a good fix, but didn't fix the specific case I talked about.
Thanks!

**Pull request merged**
