### PR TITLE
NO-ISSUE add swagger changes validation to the build

### PR DESCRIPTION
**Pull request by osherdp**
/hold

### CODE REVIEW

**Comment by YuviGold** [comment]
@osherdp Can you add it under `ci-lint` Makefile target? So we don't have to create another Jenkins stage.

**Comment by YuviGold** [comment]
@osherdp WDYT? IMO that's still relevant.

**Comment by osherdp** [comment]
I guess that the functionality is still very valuable
But I don't like it on the ``Makefile``. It depends on ``git diff``, so that if you'll fix it but don't commit it the check fails...

**Comment by YuviGold** [comment]
> I guess that the functionality is still very valuable
> But I don't like it on the `Makefile`. It depends on `git diff`, so that if you'll fix it but don't commit it the check fails...

I don't understand the difference.
I just mentioned instead of having a new dedicated step, you should use the `Init` step that calls a Makefile target `ci-lint` and upgrade its validations.
It would still have the same functionality for generating the swagger content and failing in case of a git diff.

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
