### PR TITLE
NO-ISSUE: Removed obsolete installation-timeout from the install command

### PR DESCRIPTION
**Pull request by eranco74**
# Assisted Pull Request

## Description
 Cleanup old obsolete code
 This parameter isn't used and will not be supported once https://github.com/openshift/assisted-installer/pull/341 merges

- Should this PR be tested by the reviewer? no
- Is this PR relying on CI for an e2e test run? For regression
- Should this PR be tested in a specific environment? no
- Any logs, screenshots, etc that can help with the review process? no

-->

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @YuviGold 
/cc @tsorya 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eranco74** [comment]
@YuviGold any idea what's wrong with prow/subsystem-* ?
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2355/pull-ci-openshift-assisted-service-master-subsystem-aws/1424727462067048448

**Review by YuviGold — APPROVED** [review]

**Comment by eranco74** [comment]
One of the hosts took longer to complete the installation
```
INFO     root:utils.py:192 Asked hosts to be in one of the statuses from ['installed'] and currently hosts statuses are [(1, '821c8ccf-6690-4742-aca1-3ee0267ae8e3', 'test-infra-cluster-a7501342-master-1', 'master', 'installed', 'Done'), (2, 'f97edfe2-ce0e-4b1c-843e-66e4dbe6ac3f', 'test-infra-cluster-a7501342-worker-0', 'worker', 'installing-in-progress', 'Joined'), (3, 'cbf50618-5317-4ee6-924c-bfcdeb92551b', 'test-infra-cluster-a7501342-worker-1', 'worker', 'installed', 'Done'), (4, 'e9ba43b2-00a0-4f17-9724-6bd31bcd4a62', 'test-infra-cluster-a7501342-master-2', 'master', 'installed', 'Done'), (5, 'a070af73-201b-407f-af22-06710a797817', 'test-infra-cluster-a7501342-master-0', 'master', 'installed', 'Done')]

``` 
doesn't seem related to the change in the PR
/retest

**Pull request merged**
