### PR TITLE
AGENT-205: Fix OCP image build

### PR DESCRIPTION
**Pull request by vfreex**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
I think usage of [quay.io/ocpmetal/oc-image:bug-1823143-multi-arch-ai-bug-2069976](http://quay.io/ocpmetal/oc-image:bug-1823143-multi-arch-ai-bug-2069976)  should be preserved, as the changes didn't get into oc 4.11
/hold
(just until we figure out the status of this patch, everything else looks good :) )

**Review by eranco74 — COMMENTED** [review]
/hold
We need the custom oc for supporting installation with mirror registry

**Comment by lranjbar** [comment]
/approve

Please note that this change is only to `Dockerfile.assisted-service.ocp` which is the assisted-service image landing in the OCP payload. From what I understand the Openshift policy is: "All the images in the OCP payload have to use the other official images in the OCP payload." We will have to get this fix in the official `oc` image in the OCP payload to support disconnected environments.

In the meantime, we need to have this image built by ART so that we can start testing the OCP payload official image for assisted-service properly. I will let others from the Openshift Agent Team weigh in on this but while this is unfortunate that this bug is still not fixed... this is likely the path forward for us.

@vfreex Thank you for opening this PR for us. 😃 

Agent team: @dhellmann @zaneb @rwsu @pawanpinjarkar @andfasano @bfournie @celebdor

**Comment by zaneb** [comment]
If this just prevents us from doing disconnected installs then I think it is the right way to move forward for now. We may have to re-evaluate if the bug doesn't get a timely fix, but anything is better than nothing.
If the way that assisted-service interacts with the CLI does not work with the standard binary (e.g. passes a command-line argument that will be rejected?) then we might need to find another approach even in the short term. That's not going to involve using a base image from quay though, so I think we should go ahead with this change in either case.

/hold cancel

**Comment by lranjbar** [comment]
JIRA issue tracker: AGENT-205

**Pull request merged**
