### PR TITLE
NO-ISSUE: add warning and info panel to log dashboard

### PR DESCRIPTION
**Pull request by rccrdpccl**
Adding additional panels to quickly glance over different loglevels.

image

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 
- [x] Monitoring
## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by vrutkovs** [comment]
Looks good, but is "Tail" and "Info" useful? I'd expect us to be interested in Error/Warning only, the rest needs context and thus, Explore view would be more fitting?

**Comment by rccrdpccl** [comment]
> Looks good, but is "Tail" and "Info" useful? I'd expect us to be interested in Error/Warning only, the rest needs context and thus, Explore view would be more fitting?

You're right, I agree for Info logs. With tail I find it useful to know that the application is actually responding in some cases, wouldn't you agree?
All panels are limited to 300 records

**Comment by vrutkovs** [comment]
Ah, yeah, that might be useful. Lets drop Info then

**Comment by rccrdpccl** [comment]
@vrutkovs dropped info panel

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
