### PR TITLE
NO-ISSUE: Tidy golang dependencies before vendoring in base image

### PR DESCRIPTION
**Pull request by danmanor**
Tidy is required before vendoring - this is failing dependabot PRs

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by adriengentil** [comment]
If we merge something that is not tidy, what will happen if a developer opens a PR? Will some jobs fail? Will the linter fail?

**Comment by danmanor** [comment]
@adriengentil Fair point, I am not sure. dependabot is actually tiding the files, but still we get an error during Dockerfile.base building in its jobs. I think we should enforce tiding as part of the generation test

**Comment by adriengentil** [comment]
We need to make sure before merging this PR.

**Comment by danmanor** [comment]
@adriengentil agreed - https://github.com/openshift/assisted-service/pull/6600

**Comment by danmanor** [comment]
@adriengentil @eifrach  We should be good to merge this now as well

**Pull request merged**
