### PR TITLE
Update swagger-codgen-cli to its latest version

### PR DESCRIPTION
**Pull request by eliorerz**
- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @YuviGold 
/cc @osherdp

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
wait, this is image from docker hub?
because it's a problem rate-limiter wise

**Comment by eliorerz** [comment]
> wait, this is image from docker hub?
> because it's a problem rate-limiter wise

So we have to tag and to upload it to `quay.io`?

**Comment by osherdp** [comment]
@eliorerz yes it's preferred 
let's see who has permissions to that organization and can mirror this version

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/retitle Update swagger-codgen-cli to its latest version

**Pull request merged**
