### PR TITLE
MGMT-7468: Bump OCP versions 4.7.21 -> 4.7.22, 4.8.2 -> 4.8.3

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.8 release notes: https://access.redhat.com/errata/RHBA-2021:2896
4.7 release notes: https://access.redhat.com/errata/RHBA-2021:2903

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Review by carbonin — APPROVED** [review]

**Pull request merged**
