### PR TITLE
Bug 2089195: [release-ocm-2.5] Expose ipxe boot artifacts via HTTP

### PR DESCRIPTION
**Pull request by vrutkovs**
Cherry-pick of https://github.com/openshift/assisted-service/pull/3705 on ACM 2.5 branch.
TODO:
* [x] Update go.mod once https://github.com/openshift/assisted-image-service/pull/77 merges

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

until 2.5.0 is tagged and frozen - or until a dedicated .1 branch is created

**Review by filanov — APPROVED** [review]

**Pull request merged**
