### PR TITLE
Bug 1969315: Don't queue BMH reconcile if the InfraEnv URL hasn't changed

### PR DESCRIPTION
**Pull request by flaper87**
# Description

* Bug 1969304: Don't queue BMH reconcile if the InfraEnv URL hasn't changed

The reconcileBMH function already verifies whether the InfraEnv URL has changed or not. The InfraEnv watcher doesn't, tho.

This commit checks whether the BMH should be reconciled based on the InfraEnv info, before queuing the request. The check is
now used by both, the watcher and the reconcileBMH function

Signed-off-by: Flavio Percoco <flavio@redhat.com>

* Bug 1969304: Apply suggestions from code review

Co-authored-by: David Zager <dzager@redhat.com>

* Bug 1969304: Resolve merge conflict issue

Signed-off-by: Flavio Percoco <flavio@redhat.com>

Co-authored-by: Flavio Percoco <flavio@redhat.com>
Co-authored-by: David Zager <dzager@redhat.com>
(cherry picked from commit d35ba1c854f4c4d43655ae2d3ee7778629501b08)

Conflicts:
       internal/controller/controllers/bmh_agent_controller.go

# What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

# How was this code tested?

Please, select one or more if needed:

- [x] Subsystem (unit-tests)
- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

It's recommended to take a few extra minutes to provide more information about
how this code was tested. Here are some questions that may be worth answering:

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run?
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

# Assignees

Please, add one or two reviewers that could help review this PR.

/assign @mkowalski 
/assign @djzager 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by djzager — APPROVED** [review]
Change looks good. Will need to wait until https://bugzilla.redhat.com/show_bug.cgi?id=1969304 is verified before it can be merged.

**Review by nmagnezi — CHANGES_REQUESTED** [review]
looks okay overall, but this should have some unit-tests included.

**Comment by flaper87** [comment]
> looks okay overall, but this should have some unit-tests included.

This is covered by the existing unit-tests, fwiw. We could add some more that are specific to the function, I guess.

**Comment by flaper87** [comment]
This PR (mistakenly) included code that belonged to https://github.com/openshift/assisted-service/pull/1960

It basically included 2 backports in 1. This was my mistake when doing the manual backports to solve a merge conflict. Better care must be taken when doing manual backports and during the backport reviews. We must always reference and compare the parent PR with the backport

**Pull request merged**
