### PR TITLE
NO-ISSUE: testing go1.20 in all packages

### PR DESCRIPTION
**Pull request by eifrach**
- This change is for testing change to go1.20  

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eifrach** [comment]
hey @carbonin, I appricate you're input here.

This will solve some of our depndenices issues and also fix this [PR](https://github.com/openshift/assisted-service/commit/7ebd8dc0ed82e847d12d42cf131128dce96ec48e)  you created 

thanks in advance

**Comment by carbonin** [comment]
As far as I can tell the only user of this is https://github.com/openshift/assisted-service/blob/315899d8f379c6899f53ffd1c67b340870d32480/hack/setup_env.sh#L102-L104.

I think it would be worth investigating if we need that `hive_from_upstream` function.
Then if the last caller of `golang` is removed then definitely get rid of it.

**Comment by carbonin** [comment]
Picking this back to 2.9 to see if it addresses https://issues.redhat.com/browse/MGMT-19476

**Pull request merged**
