### PR TITLE
MGMT-4297 Nuke Image and Cluster CRDs and Controllers

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
/hold
until https://github.com/openshift/assisted-service/pull/1029 get merged

**Comment by nmagnezi** [comment]
/unhold
**Tested locally**

`skipper make test FOCUS="kube-api" ENABLE_KUBE_API=true`

**Result**
```golang
------------------------------
[kube-api]cluster installation
  deploy clusterDeployment with agents and wait for ready
  /home/nmagnezi/go/src/github.com/assisted-service/subsystem/kubeapi_test.go:213

• [SLOW TEST:16.445 seconds]
[kube-api]cluster installation
/home/nmagnezi/go/src/github.com/assisted-service/subsystem/kubeapi_test.go:199
  deploy clusterDeployment with agents and wait for ready
  /home/nmagnezi/go/src/github.com/assisted-service/subsystem/kubeapi_test.go:213
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 140 Specs in 16.477 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 139 Skipped
--- PASS: TestSubsystem (16.50s)
PASS
ok  	github.com/openshift/assisted-service/subsystem	17.691s
```

**Review by filanov — APPROVED** [review]

**Comment by osherdp** [comment]
it's so much better than those dad jokes:
/joke

**Pull request merged**
