### PR TITLE
NO-JIRA adding docker.io to build image. Fixes usage on hosts were do…

### PR DESCRIPTION
**Pull request by tsorya**
…cker.io is not added to podman config

### CODE REVIEW

**Comment by YuviGold** [comment]
Let's use `quay.io`

**Comment by tsorya** [comment]
@YuviGold there is no such image in quay.io

**Comment by mhrivnak** [comment]
The upstream origin image to use would be `registry.svc.ci.openshift.org/origin/builder:golang-1.14`
@tsorya @YuviGold

**Comment by YuviGold** [comment]
Not relevant anymore. We moved to quay.io images on https://github.com/openshift/assisted-service/pull/795
/close

**Pull request closed without merging**
