### PR TITLE
NO-ISSUE: added arm64 images for ocp 4.10

### PR DESCRIPTION
**Pull request by danielerez**
Added 4.10 arm64 images to default_os_images and default_release_images.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @osherdp 
/cc @gamli75 

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — APPROVED** [review]
Let's hope PV size is enough for it in integration
If not, we can always remove 4.9 ARM image (or increase the size)

**Comment by romfreiman** [comment]
Lets remove 4.9. Why do we need it?

@osherdp @gamli75 why are we running 4.6 job here?

**Comment by gamli75** [comment]
> Lets remove 4.9. Why do we need it?
> 
> @osherdp @gamli75 why are we running 4.6 job here?

@romfreiman we have task & open PR for it, see: https://issues.redhat.com/browse/MGMT-9743

**Comment by osherdp** [comment]
Shouldn't bother us anymore (when updating ``data/`` dir): openshift/release/pull/27322

**Comment by osherdp** [comment]
/hold
seems like ``verify-generated-code`` fails consistently 
(and it might be a good idea to remove 4.9 ARM image on the way)

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/override ci/prow/e2e-ai-operator-ztp-ipv4v6-3masters-ocp-49
/override ci/prow/e2e-ai-operator-ztp-ipv4v6-sno-ocp-49
(currently broken)
/unhold
(anything else looks okay)

**Comment by danielerez** [comment]
> New changes are detected. LGTM label has been removed.

rebased

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
subsystem job fails consistently, and the tests failing symptom only appears for this PR
@danielerez can you take a look?

**Comment by danielerez** [comment]
> Details

updated tests, let's see now

**Review by osherdp — APPROVED** [review]

**Comment by danielerez** [comment]
/hold
pending https://github.com/openshift/assisted-service/pull/3594

**Pull request merged**
