### PR TITLE
OCPBUGSM-35242: Set x86_64 as the default architecture for OsImages and ReleaseImages

### PR DESCRIPTION
**Pull request by flaper87**
# Assisted Pull Request

## Description

This commit aligns the definition of OsImages and ReleaseImages to what was discussed in the enhancement
proposal[0]. The default architecture should be x86_64.

[0] https://github.com/openshift/assisted-service/blob/34c986435c1e85776b2bcb0544eab2e6e77a2c2b/docs/enhancements/arm64-cpu-architecture.md\#cluster-creation-and-iso-generation

Signed-off-by: Flavio Percoco <flavio@redhat.com>

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @carbonin 
/cc @djzager 
/cc @danielerez 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danielerez** [comment]
Is there any behavioural effect in this change? I.e. afaik, setting default in swagger doesn't force the API to use it, so it's only relevant if storing in DB. Anyway, it's a good change even if just for making the API clearer :)

**Comment by flaper87** [comment]
> Is there any behavioural effect in this change? I.e. afaik, setting default in swagger doesn't force the API to use it, so it's only relevant if storing in DB. 

I think this is exactly what we want. The problem we noticed is that when `cpu_architecture` is missing from the `OsImages` env var in an operator workflow, the value is set to an empty string, which results in the image generation failing.

> Anyway, it's a good change even if just for making the API clearer :)

**Review by carbonin — APPROVED** [review]

**Comment by carbonin** [comment]
/override ci/prow/e2e-metal-assisted-networking
/override ci/prow/e2e-metal-assisted-operator-ztp-dualstack
/override ci/prow/e2e-metal-assisted-operator-ztp-dualstack-multinode-spoke

These are all known failures that we're working on and are not related to this PR

**Pull request merged**
