### PR TITLE
MGMT-3618 Add progress info to event

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by rollandf** [comment]
@gamli75

**Comment by rollandf** [comment]
```
1/13/2021, 5:11:38 PM | Update  cluster installation progress: Cluster version is available: false ,  message: Unable to apply 4.6.8: the cluster operator authentication is  degraded
1/13/2021, 5:10:38 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 98% complete
1/13/2021, 5:09:38 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 98% complete
1/13/2021, 5:08:38 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 10% complete
1/13/2021, 5:07:39 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 97% complete
```

**Comment by gamli75** [comment]
> ```
> 1/13/2021, 5:11:38 PM | Update  cluster installation progress: Cluster version is available: false ,  message: Unable to apply 4.6.8: the cluster operator authentication is  degraded
> 1/13/2021, 5:10:38 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 98% complete
> 1/13/2021, 5:09:38 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 98% complete
> 1/13/2021, 5:08:38 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 10% complete
> 1/13/2021, 5:07:39 PM | Update cluster installation progress: Cluster version is available: false , message: Working towards 4.6.8: 97% complete
> ```

@rollandf there is something strange with the percentages: 97 -> 10 -> 98

**Comment by rollandf** [comment]
I am only adding the message... this is what is reported by controller

**Review by avishayt — APPROVED** [review]

**Pull request merged**
