### PR TITLE
NO-ISSUE: Deprecating /v1/clusters/{cluster_id}/host-requirements API.

### PR DESCRIPTION
**Pull request by ybettan**
# Assisted Pull Request

UI don't use that API anymore and uses
/v1/clusters/{cluster_id}/preflight-requirements instead.

In addition we have only 2 hits on that API in prod so users doesn't
seems to use it either.

Signed-off-by: Yoni Bettan <ybettan@redhat.com>

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ybettan** [comment]
/hold
Waiting for @avishayt 's approval, as it is in the [v2 API doc](https://docs.google.com/spreadsheets/d/1GRs2eJSM8Fy7zGO80cNKyJxQByOicNnJP42R2FfEfZ4/edit#gid=1989175040) for some reason.

FYI @gamli75

**Review by avishayt — APPROVED** [review]

**Pull request merged**
