### PR TITLE
[release-ocm-2.12] MGMT-19158: Always try to cache the ClusterImageSet

### PR DESCRIPTION
**Pull request by CrystalChun**
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/6962

---

Previously, the ClusterImageSet defined by a ClusterDeployment was only cached if the cluster was being created. This is problematic in the long run if assisted is restarted and the cluster is not recreated. Errors "getting the release image" will occur due to this.

To prevent this, we'll now always try to cache the ClusterImageSet defined for a cluster even if it's already installed. This also allows us to ensure that the image the user specified in the ClusterImageSet as the release image to be installed.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by paul-maidment** [comment]
/lgtm
Looks like a backport of an already merged PR

**Pull request merged**
