### PR TITLE
MGMT-2458 fix subsystem test install_cluster install command failed

### PR DESCRIPTION
**Pull request by gamli75**

### CODE REVIEW

**Comment by carbonin** [comment]
How/why does this fix the test? I don't really understand why this is a problem. Did we add some kind of retry logic for the old error code?

**Comment by gamli75** [comment]
not fixed the issue

**Comment by gamli75** [comment]
@carbonin I closed this PR since it didn't fix the issue - I think it's something that related to the monitor but not sure. Sara is investigating this issue.

**Comment by carbonin** [comment]
Yeah, no problem. I didn't realize it was just a test.

**Pull request closed without merging**
