### PR TITLE
MGMT-18505: Fix installation from a 4.17 hub with converged flow

### PR DESCRIPTION
**Pull request by carbonin**
This allows ironic inspector URL to be missing in ICC config secret.

In 4.17 this is expected to be missing as the inspector service as been
removed.

If this URL is provided the agent will attempt to contact the inspector
service when it shouldn't causing the install to fail.

In earlier versions the secret will not be present so the controller
will continue to provide the inspector service URL as before.

## List all the issues related to this PR

Resolves https://issues.redhat.com/browse/MGMT-18505

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

Deployed a 4.17 hub cluster and installed a 4.17 SNO from assisted installed on it with this branch image.

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
Looks like this update is going to require us to bump go to 1.22...

```
[1/2] STEP 6/9: RUN cd cmd && CGO_ENABLED=1 GOFLAGS="" GO111MODULE=on go build -o /build/assisted-service
go: github.com/openshift/image-customization-controller in ../vendor/modules.txt requires go >= 1.22 (running go 1.21.11; GOTOOLCHAIN=local)
```

@adriengentil do you know if we have any immediate plans to do this? That would also effectively rule out a backport though ...

**Comment by gamli75** [comment]
please retitle and add MGMT-18505

**Comment by adriengentil** [comment]
> @adriengentil do you know if we have any immediate plans to do this? That would also effectively rule out a backport though ...

not that I'm aware of but @danmanor is currently working at updating the build images, so it may be the opportunity to update go version as well: https://github.com/openshift/assisted-service/pull/6637/files

**Comment by adriengentil** [comment]
Hum, what fails is the build of https://github.com/openshift/assisted-service/blob/master/Dockerfile.assisted-service.ocp#L2C1-L2C88

**Comment by gamli75** [comment]
> Looks like this update is going to require us to bump go to 1.22...
> 
> ```
> [1/2] STEP 6/9: RUN cd cmd && CGO_ENABLED=1 GOFLAGS="" GO111MODULE=on go build -o /build/assisted-service
> go: github.com/openshift/image-customization-controller in ../vendor/modules.txt requires go >= 1.22 (running go 1.21.11; GOTOOLCHAIN=local)
> ```
> 
> @adriengentil do you know if we have any immediate plans to do this? That would also effectively rule out a backport though ...

Yes, there is a task to do it https://issues.redhat.com/browse/MGMT-18384 @eifrach

**Comment by eifrach** [comment]
> Looks like this update is going to require us to bump go to 1.22...

The task was to update to 1.21, do we want to switch to 1.22? I assume if we do the assisted service we will also update all other related services

**Comment by carbonin** [comment]
Sorry for the confusion and how long it took me to update this, but I'm hoping the 4.16 branch will work. It also has the fix we need.

**Review by adriengentil — APPROVED** [review]

**Comment by carbonin** [comment]
We need to backport this so I'll create a custom backport PR that includes this as well as [the original change](https://github.com/openshift/assisted-service/pull/6533)

**Pull request merged**
