### PR TITLE
[release-ocm-2.11] NO-ISSUE: Change debug Dockerfile so it will not require prior actions

### PR DESCRIPTION
**Pull request by danmanor**
cherry-pick of https://github.com/openshift/assisted-service/pull/6674

### CODE REVIEW

**Comment by danmanor** [comment]
/override e2e-ai-operator-ztp ci/prow/e2e-ai-operator-ztp-sno-day2-workers ci/prow/e2e-ai-operator-ztp-sno-day2-workers-late-binding ci/prow/subsystem-aws ci/prow/subsystem-kubeapi-aws

**Comment by danmanor** [comment]
/override e2e-ai-operator-ztp ci/prow/e2e-ai-operator-ztp-sno-day2-workers ci/prow/e2e-ai-operator-ztp-sno-day2-workers-late-binding ci/prow/subsystem-aws ci/prow/subsystem-kubeapi-aws

**Comment by danmanor** [comment]
/override ci/prow/e2e-ai-operator-ztp ci/prow/e2e-ai-operator-ztp-sno-day2-workers ci/prow/e2e-ai-operator-ztp-sno-day2-workers-late-binding ci/prow/subsystem-aws ci/prow/subsystem-kubeapi-aws

**Comment by danmanor** [comment]
/override ci/prow/e2e-ai-operator-ztp ci/prow/e2e-ai-operator-ztp-sno-day2-workers ci/prow/e2e-ai-operator-ztp-sno-day2-workers-late-binding ci/prow/subsystem-aws ci/prow/subsystem-kubeapi-aws

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
