### PR TITLE
MGMT-9934: Use compatible iPXE script format

### PR DESCRIPTION
**Pull request by CrystalChun**
[MGMT-9934](https://issues.redhat.com/browse/MGMT-9934)
The iPXE script initially used did not have a compatible
syntax for different iPXE versions.

This PR modifies the syntax of the iPXE script so that it
is compatible with different iPXE versions.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [x] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment: deployed hosts using [iPXE flow](https://github.com/openshift/assisted-test-infra/pull/1578) and saw they booted and installed fine using the new script
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @filanov 
/cc @javipolo 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — COMMENTED** [review]
How was it tested?
Lets backport?

**Comment by CrystalChun** [comment]
@filanov 

> How was it tested?


Used assisted-test-infra environment: deployed hosts using [iPXE boot flow](https://github.com/openshift/assisted-test-infra/pull/1578) and saw they booted and installed fine using the new script

**Comment by filanov** [comment]
Need a BZ

**Comment by CrystalChun** [comment]
/retitle Bug 2074638: Use compatible iPXE script format

**Pull request merged**
