### PR TITLE
NO-ISSUE Create grafana-dashboard-assisted-service-staging.configmap.yaml"

### PR DESCRIPTION
**Pull request by yobshans**
Create Assisted Service Staging resource monitoring dashboard

### CODE REVIEW

**Comment by yobshans** [comment]
@nmagnezi

**Review by gamli75 — APPROVED** [review]

**Comment by yobshans** [comment]
/retitle NO-ISSUE Create grafana-dashboard-assisted-service-staging.configmap.yaml

**Comment by gamli75** [comment]
/retitle NO-ISSUE Create grafana-dashboard-assisted-service-staging.configmap.yaml"

**Review by nmagnezi — COMMENTED** [review]
@yobshans is this dashboard currently applies somewhere? maybe a test Grafana.

I know it has been approved, but I'd still like to review it.

**Comment by yobshans** [comment]
@nmagnezi Hey, it is the same what was deleted except removed uid: playground and added path to Assisted Installer.
No deployed in any place. Probably you can try in playground to import it

**Comment by gamli75** [comment]
replaced with https://github.com/openshift/assisted-service/pull/1159

**Comment by nmagnezi** [comment]
@yobshans APP-SRE Grafana playground does not allow JSON imports.
I'll figure out a different solution. Will review it tomorrow.

**Comment by yobshans** [comment]
@nmagnezi Please, review new one MR https://github.com/openshift/assisted-service/pull/1159
Thanks

**Pull request closed without merging**
