### PR TITLE
MGMT-1743 - use smee to proxy requests to run the jenkins job

### PR DESCRIPTION
**Pull request by carbonin**
The smee client will handle routing to the correct path for us,
we just need to post to the url endpoint which is configured in a
secret in the openshift cluster.

cc @YuviGold

### CODE REVIEW

**Review by apahim — APPROVED** [review]
LGTM, thank you!

**Comment by carbonin** [comment]
@YuviGold can you post here when you have the smee client running on jenkins?
/hold

**Comment by YuviGold** [comment]
> @YuviGold can you post here when you have the smee client running on jenkins?
> /hold
Added the client as a systemd service :) 
/unhold

**Pull request merged**
