### PR TITLE
NO-ISSUE: Add openshift-edge-bot as an OWNER

### PR DESCRIPTION
**Pull request by danmanor**
Add openshift-edge-bot as an OWNER in order to run konflux pipelines on its PRs

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danmanor** [comment]
/cherry-pick release-ocm-2.10 release-ocm-2.9 release-ocm-2.8 release-ocm-2.7

**Review by adriengentil — APPROVED** [review]

**Comment by adriengentil** [comment]
@pastequo Do you know if it's the only way to allow our bot user to run konflux pipelines? There not such thing like trusted apps like we have in [Prow](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/assisted-service/_pluginconfig.yaml#L20)?

**Comment by danmanor** [comment]
I spoke with @pastequo and he mentioned it runs only if:
* openshift-edge-bot is part of the owners
*A repo owner adds /ok-to-test label
Is that correct ?

**Comment by adriengentil** [comment]
If we can have a global setting, we could avoid updating all the branches

**Comment by adriengentil** [comment]
Another solution is to add a rule in https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/assisted-service/_prowconfig.yaml#L31 to add `/ok-to-test` when PR author is `openshift-edge-bot`.
https://docs.prow.k8s.io/docs/components/core/tide/config/#queries

**Comment by pastequo** [comment]
I'm not aware of a global setting, but theorically we can configure konflux to use the default branch pipeline. Maybe in this  case it would use the OWNER file of the default branch. To confirm

**Comment by danmanor** [comment]
I don't see harm in merging this as it is for now

**Comment by rccrdpccl** [comment]
> Add openshift-edge-bot as an OWNER in order to run konflux pipelines on its PRs

Hasn't this pipeline just executed without either of them?

**Comment by danmanor** [comment]
@rccrdpccl  I opened the PR and I am in the OWNERS list

**Comment by adriengentil** [comment]
Another idea, since the bot is trusted by Prow, we should be able to add the label on the PR from the OCP bump job itself.

**Comment by danmanor** [comment]
@adriengentil That is a good idea, I am closing this PR

**Pull request merged**
