### PR TITLE
MGMT-5847 Move InstallConfig annotation to AgentClusterInstall CRD

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by rollandf** [comment]
/hold
on top of #1614

**Comment by rollandf** [comment]
This PR is just moving the annotation to the new CRD.

The HyperThreading as not yet been implemented, and I agree with your concerns.
This should be raised when the design starts.
Related JIRA tickets: https://issues.redhat.com/browse/MGMT-6022 https://issues.redhat.com/browse/MGMT-4868


> Overall looks good.
> Seems that agentClusterInstall have some fields that might conflict with this annotation (specifically the example in the tests and the docs)
> [openshift/hive@48b7c09](https://github.com/openshift/hive/commit/48b7c09dc9033d3037a1017f658f4d28fdc6de3e)
> 
> What should the user use?
> What is the desired behavior in case of conflict?

**Comment by filanov** [comment]
> This PR is just moving the annotation to the new CRD.
> 
> The HyperThreading is not yet implemented, and I agree with your concerns.
> This should be raised when the design starts.
> Related JIRA tickets: https://issues.redhat.com/browse/MGMT-6022 https://issues.redhat.com/browse/MGMT-4868
> 
> > Overall looks good.
> > Seems that agentClusterInstall have some fields that might conflict with this annotation (specifically the example in the tests and the docs)
> > [openshift/hive@48b7c09](https://github.com/openshift/hive/commit/48b7c09dc9033d3037a1017f658f4d28fdc6de3e)
> > What should the user use?
> > What is the desired behavior in case of conflict?

It's a good question, conflicts will result in infinite loops. 
Maybe at this point, we should document a different example just not to confuse the users 
@mhrivnak @avishayt how do you think we should address such conflicts?

**Comment by filanov** [comment]
May we start with a sync error if a specific configuration is applied with annotations.

**Comment by rollandf** [comment]
> May we start with a sync error if a specific configuration is applied with annotations.

In any case, this PR is just moving to the new CRD.
I would not add more logic in this one, but handle it when working on the HyperThreading task

**Review by filanov — APPROVED** [review]

**Comment by rollandf** [comment]
Rebasing

**Review by filanov — APPROVED** [review]

**Pull request merged**
