### PR TITLE
Mgmt 1680 Add agent version header for agent API calls

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
cc: @avishayt

**Comment by gamli75** [comment]
Not sure we need to add it to all APIs - maybe just to APIs that the agent calls in the service, such as getNextSteps & postStepReply - @avishayt what do you think?

**Comment by nmagnezi** [comment]
> Not sure we need to add it to all APIs - maybe just to APIs that the agent calls in the service, such as getNextSteps & postStepReply - @avishayt what do you think?

@avishayt ping

**Comment by avishayt** [comment]
> Not sure we need to add it to all APIs - maybe just to APIs that the agent calls in the service, such as getNextSteps & postStepReply - @avishayt what do you think?

I think it's fine the way it is.  I guess what you mean is that some of these are called by assisted-controller and not agent?  In the worst case the header won't be used.  I think it makes sense to add it wherever we have agentAuth to make it easier to manage.

**Comment by nmagnezi** [comment]
tested with https://github.com/openshift/assisted-installer-agent/pull/17 ; ran test-infra with `make run_full_flow_with_install`

label added: `discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10"`

```
[root@dell-r730-025 ~]# curl `minikube ip`:31099/metrics | grep -i assisted_installer_host_installation_phase_seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  135k    0  135k    0     0  18.9M      0 --:--:-- --:--:-- --:# HELP service_assisted_installer_host_installation_phase_seconds Histogram/sum/count of time for each phase, by phase, final install result, and OCP version
--:-# TYPE service_assisted_installer_host_installation_phase_seconds histogram
- 16.5Mservice_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.005"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.01"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.025"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.05"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.1"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.25"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="0.5"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="1"} 0
100  18service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="2.5"} 0
0k    0service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="5"} 0
  180k service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="10"} 0
   0   service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="20"} 0
  0  22service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="30"} 0
.0M      service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="40"} 0
0 --:--service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="50"} 0
:-- --:service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="60"} 0
--:-- --service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="90"} 0
:--:--service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="120"} 0
 22.0M
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="150"} 0
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="180"} 1
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="210"} 1
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="240"} 1
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="270"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="300"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="360"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="420"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="480"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="540"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="600"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="900"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="1200"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="1500"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="1800"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="2100"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="2400"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="2700"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="3000"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="3300"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="3600"} 3
service_assisted_installer_host_installation_phase_seconds_bucket{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done",le="+Inf"} 3
service_assisted_installer_host_installation_phase_seconds_sum{discoveryAgentVersion="quay.io/nmagnezi/assisted-installer-agent:agent_ver10",openshiftVersion="4.5",phase="Configuring",result="Done"} 636.305323069
```

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
