### PR TITLE
Adding post deploy Job to trigger external CI

### PR DESCRIPTION
**Pull request by apahim**
Depends on the app-interface counterpart:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8907

### CODE REVIEW

**Comment by apahim** [comment]
@carbonin

**Comment by romfreiman** [comment]
@YuviGold

**Comment by YuviGold** [comment]
Can you explain where and it used and how?

**Comment by apahim** [comment]
Here's the Jira ticket: https://issues.redhat.com/browse/APPSRE-2377
On your team, you're tracking the work here: https://issues.redhat.com/browse/MGMT-1743
This Job will be created after every deployment. That trigger is configured here:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8919/diffs

**Comment by romfreiman** [comment]
@YuviGold @gamli75 @carbonin can you sync on this one?

**Comment by YuviGold** [comment]
> @YuviGold @gamli75 @carbonin can you sync on this one?

Not yet.
/hold

**Pull request merged**
