### PR TITLE
MGMT-5402, Bump OCP versions

### PR DESCRIPTION
**Pull request by oshercc**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by oshercc** [comment]
Created a PR in app-interface GitLab https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/18631

**Comment by oshercc** [comment]
Currently no test platform is available, un-holding

**Comment by gamli75** [comment]
@oshercc please close this PR

**Comment by gamli75** [comment]
No need to update 4.6 - I closed this PR

**Pull request closed without merging**
