### PR TITLE
MGMT-1970 Set DHCP vip allocation mode as true by default

### PR DESCRIPTION
**Pull request by ori-amizur**
/cc @ronniel1 
/cc @YuviGold

### CODE REVIEW

**Comment by filanov** [comment]
@ori-amizur How does it marked in the UI?

**Comment by ori-amizur** [comment]
> @ori-amizur How does it marked in the UI?

@filanov  The default is not marked in the UI.  The UI is aware only to the current vip-dhcp-allocation flag status.  It is part of the cluster record.

**Comment by filanov** [comment]
> > @ori-amizur How does it marked in the UI?
> 
> @filanov The default is not marked in the UI. The UI is aware only to the current vip-dhcp-allocation flag status. It is part of the cluster record.

OK as long as we don't get into a strange UX issue i'm ok with that.

**Review by filanov — APPROVED** [review]

**Pull request merged**
