### PR TITLE
MGMT-6584 Add host progress stages while waiting for control plane

### PR DESCRIPTION
**Pull request by eranco74**
Added:
 - HostStageWaitingForBootkube
 - HostStageWaitingForController

Removed:
 - HostStageStartWaitingForControlPlane - obsolete

### CODE REVIEW

**Comment by romfreiman** [comment]
Does it affect UI? Tests?

**Comment by eranco74** [comment]
> Does it affect UI? Tests?

This change doesn't affect anything.
Once the assisted-installer will start using the new stages we might need to update the 2e2 test.
About the UI, I don't think there should be any changes.

**Pull request merged**
