### PR TITLE
MGMT-7231: Deploy ODF operator

### PR DESCRIPTION
**Pull request by rewantsoni**
Signed-off-by: Rewant Soni <resoni@redhat.com>

# Assisted Pull Request
Add changes related to the ODF operator.

## Description
We are partially removing OCS, the installer and service will still handle OCS to maintain compatibility with OCP4.8. In further patches, OCS will be completely removed from the service.

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @pkliczewski 
/cc @avishayt 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

### CODE REVIEW

**Comment by pkliczewski** [comment]
@filanov who can help with review?

**Comment by avishayt** [comment]
Is this basically just a copy-paste of OCS?

**Comment by rewantsoni** [comment]
> Is this basically just a copy-paste of OCS?

Yes, it is

**Comment by avishayt** [comment]
> > Is this basically just a copy-paste of OCS?
> 
> Yes, it is

If OCS will stick around, then it would be better to create a thin plugin for ODF that just calls OCS methods.  If you are willing to drop support for OCS in the near future, then this is fine.  Maintaining two copies of the same code is not a good idea.

**Comment by rewantsoni** [comment]
> If OCS will stick around, then it would be better to create a thin plugin for ODF that just calls OCS methods. If you are willing to drop support for OCS in the near future, then this is fine. Maintaining two copies of the same code is not a good idea.

I agree, OCS will stop supporting after OCP 4.8 is removed from Assisted-installer. Till when are we supporting OCP 4.8?

**Comment by avishayt** [comment]
> > If OCS will stick around, then it would be better to create a thin plugin for ODF that just calls OCS methods. If you are willing to drop support for OCS in the near future, then this is fine. Maintaining two copies of the same code is not a good idea.
> 
> I agree, OCS will stop supporting after OCP 4.8 is removed from Assisted-installer. Till when are we supporting OCP 4.8?

4.8 has full support until January 18, 2022 and maintenance support until January 27, 2023.

**Comment by pkliczewski** [comment]
@rewantsoni please share as much code as you can between ocs and odf operators

**Comment by rewantsoni** [comment]
> @rewantsoni please share as much code as you can between ocs and odf operators

@pkliczewski @avishayt If we reuse the code, when we remove ocs, we would have to make a lot of changes again, and there will be problems with messages with resuing the code. As OCP4.8 is supported till Jan18, OCS will be there till Jan18, will remove OCS from AI code after 18th Jan. So, I think we can keep the code separate for OCS and ODF. 

/cc @gobindadas

**Comment by filanov** [comment]
> @filanov who can help with review?

@yevgeny-shnaidman and @ori-amizur please help with the review.

**Comment by gobindadas** [comment]
I think instead of adding code for ODF in existing pkg, it better to keep seperate. Other wise lot of code refactor required in future while removing OCS once it's deprecated/not supported.

**Comment by pkliczewski** [comment]
> I think instead of adding code for ODF in existing pkg, it better to keep seperate. Other wise lot of code refactor required in future while removing OCS once it's deprecated/not supported.

As this change is time sensitive and we will remove OCS soon. I think it makes sense to have 2 separate operators. @avishayt what do you think?

**Comment by flaper87** [comment]
@rewantsoni could you elaborate, in the description, on why we are adding ODF. IT may be confusing to some folks to see OCS and ODF. 

P.S: I will assign you to the ticket since you opened the PR :)

**Comment by pkliczewski** [comment]
@rewantsoni please check why `ci/prow/e2e-metal-assisted-olm` failed. This job is testing changes you made here.

**Comment by rewantsoni** [comment]
> @rewantsoni please check why `ci/prow/e2e-metal-assisted-olm` failed. This job is testing changes you made here.

Sure, checking

**Comment by pkliczewski** [comment]
Please add description. Are you sure the UI, subsystem and integration tests would work with removing OCS from the service? I thought we wanted to remove it gradually.

**Comment by rewantsoni** [comment]
> Please add description. Are you sure the UI, subsystem and integration tests would work with removing OCS from the service? I thought we wanted to remove it gradually.

Yes, I ran manual tests and it works with UI, the tests pass on the subsystem. The installer and service still handle OCS and replace it with ODF, we will remove it completely when we don't need 4.8 is Saas day1 operation.

**Comment by pkliczewski** [comment]
/hold
This PR depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/1040 without it the UI is broken

**Comment by rewantsoni** [comment]
Depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/1040

**Comment by osherdp** [comment]
/retest
known failure. should be fixed by now

**Comment by osherdp** [comment]
@rewantsoni @pkliczewski @lalon4 
we did not intentionally prepared to have ocs-odf in release 2.1.0
are we okay to include that as well @lalon4 ?

**Comment by lalon4** [comment]
We wont be able to test ODF for 2.1.0 (its next week). I would suggest to merge ODF changes after taking master (in a day?), then we can test it against Integration for a while, align automation, and than take it to stage. We than have enough time for the next release a week after

**Review by avishayt — APPROVED** [review]

**Comment by osherdp** [comment]
Unit tests are failing, and it seems relevant to OLM changes

**Comment by osherdp** [comment]
Also ``e2e-metal-assisted-olm-suite`` fails specifically for ODF installation (LSO and CNV are passing) so I think it requires some digging around

**Comment by osherdp** [comment]
@rewantsoni let me know if you need some help figuring out those failures

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-operator-ztp
seems to have passed for a previous commit, so we can make that exception this time

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-cnv 
/override ci/prow/e2e-metal-assisted-ocs
previous united job has passed already

**Pull request merged**
