### PR TITLE
MGMT-6497 Extend swagger to store route information in inventory

### PR DESCRIPTION
**Pull request by jordigilh**
Extends the inventory information to store the default route information from the host.
This additional structure follows the code in Kuberentes to [validate](https://github.com/kubernetes/kubernetes/blob/7ccd90e7d7c6d727a7497c901c45776592ec5e45/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go#L133-L137) the default routing information. 

This information will be used for a new host validation that will check if a given host has at least a default route.

### CODE REVIEW

**Comment by jordigilh** [comment]
@ori-amizur can you take a look at this PR? It's about adding a new schema into the inventory to capture the route information. The information captured is more than we need right now (we just need to know if there are default routes defined at this point), but it might come handy if we want to do some cross validation to match nodes that share a network configuration for instance.
Let me know if you think it's overkill.

**Review by avishayt — APPROVED** [review]

**Pull request merged**
