### PR TITLE
OCPBUGSM-27640: localjob when storage=filesystem

### PR DESCRIPTION
**Pull request by djzager**
This makes it so the type of job we use for iso generation is determined
based on the filesystem instead of the deploy target. This should fix
issues where when the `k8` deployment is specified with the `filesystem`
storage option, ISOs are created and immediately deleted.

### CODE REVIEW

**Comment by djzager** [comment]
Looking at the failures it looks like there are adjustments that need to be made to assisted-test-infra

**Comment by tsorya** [comment]
@djzager i think that you need changes inside service and not test-infra
First of all you need to add STORAGE default to s3 cause you will break cloud deployments.
Then you will need to update tools/deploy_assisted_installer_configmap.py to allow you to change STORAGE value.

From this point you will need to update Makefile to support STORAGE param and add option to customize storage parameter that you path to deployment script.

I think that if "filesystem" was set you should remove scality deployment cause there is no reason have it in this case.

You should go through subsystem tests logic and make sure we deploy it right in case ENABLE_KUBE_API was set. 
As i understand by default if ENABLE_KUBE_API was set we should use STORAGE="filesystem" , so will be nice that service Makefile will support it and support override option too.

**Comment by tsorya** [comment]
I think that the only change you need inside test-infra is adding STORAGE to skipper.env that will allow to change default STORAGE in case if ENABLE_KUBE_API was set

**Comment by lranjbar** [comment]
So currently this STORAGE variable is the only remaining thing using the TARGET=ocp last I checked. It also gives you a nice search for where changes need to be.

This part of the deploy script should be changed to use STORAGE:
https://github.com/openshift/assisted-service/blob/master/tools/deploy_assisted_installer.py#L63-L70

This also shows the other variables that need to be set when STORAGE=filesystem

**Pull request merged**
