### PR TITLE
NO-ISSUE: Fix typo in the documentation

### PR DESCRIPTION
**Pull request by flaper87**
jira: NO_ISSUE
Signed-off-by: Flavio Percoco <flaper87@gmail.com>

### CODE REVIEW

**Comment by osherdp** [comment]
/approve
@flaper87 do you want to add yourself in the OWNERS file?

**Comment by osherdp** [comment]
master is broken, so it will take some time to fix it

**Comment by rollandf** [comment]
The commit message should start with NO-ISSUE

**Pull request merged**
