### PR TITLE
NO-ISSUE: remove openshift_versions support

### PR DESCRIPTION
**Pull request by danielerez**
# Assisted Pull Request

## Description

Removed backwards compatibility of OPENSHIFT_VERSIONS env var support.
OS_IMAGES and RELEASE_IMAGES env var should be now exclusively used.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @filanov 
/cc @avishayt 
/cc @osherdp 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danielerez** [comment]
@avishayt this PR completely removes support for OPENSHIFT_VERSIONS env var. Do you think we should wait with this for now to keep backwards compatibility, or is it fine to move forward with this?

**Comment by avishayt** [comment]
> @avishayt this PR completely removes support for OPENSHIFT_VERSIONS env var. Do you think we should wait with this for now to keep backwards compatibility, or is it fine to move forward with this?

Who will it break?

**Comment by danielerez** [comment]
> > @avishayt this PR completely removes support for OPENSHIFT_VERSIONS env var. Do you think we should wait with this for now to keep backwards compatibility, or is it fine to move forward with this?
> 
> Who will it break?

It might affect on-prem users who update the service and still use only the old var, although the new vars are specified in onprem-environment file: https://github.com/openshift/assisted-service/blob/56130849043f9e3218669133236ab457ac40c525/onprem-environment#L13-L14

**Comment by osherdp** [comment]
> > > @avishayt this PR completely removes support for OPENSHIFT_VERSIONS env var. Do you think we should wait with this for now to keep backwards compatibility, or is it fine to move forward with this?
> > 
> > 
> > Who will it break?
> 
> It might affect on-prem users who update the service and still use only the old var, although the new vars are specified in onprem-environment file:
> 
> https://github.com/openshift/assisted-service/blob/56130849043f9e3218669133236ab457ac40c525/onprem-environment#L13-L14

this file is for the old on-prem environment that used podman? or rather for the operator?

**Comment by danielerez** [comment]
> > > > @avishayt this PR completely removes support for OPENSHIFT_VERSIONS env var. Do you think we should wait with this for now to keep backwards compatibility, or is it fine to move forward with this?
> > > 
> > > 
> > > Who will it break?
> > 
> > 
> > It might affect on-prem users who update the service and still use only the old var, although the new vars are specified in onprem-environment file:
> > https://github.com/openshift/assisted-service/blob/56130849043f9e3218669133236ab457ac40c525/onprem-environment#L13-L14
> 
> this file is for the old on-prem environment that used podman? or rather for the operator?

Only for the old one iinm.

**Comment by osherdp** [comment]
Now we need to remove ``OPENSHIFT_VERSION`` parameter from the template, no?
Except from that, I don't mind that we'll push it for the next version

**Comment by danielerez** [comment]
> Now we need to remove `OPENSHIFT_VERSION` parameter from the template, no? Except from that, I don't mind that we'll push it for the next version

Right, rebased and removed from template. Should be ok to move forward with this.
/unhold

**Review by osherdp — APPROVED** [review]

**Pull request merged**
