### PR TITLE
NO-ISSUE: remove butane usage

### PR DESCRIPTION
**Pull request by osherdp**
Backport of both https://github.com/openshift/assisted-service/pull/4040 and https://github.com/openshift/assisted-service/pull/3555.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @filanov 
/cc @omertuc 

## Checklistmaybe need to rebase because of other changes?

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
validating that it fixes verify-generated-code

**Comment by omertuc** [comment]
Duplicate of https://github.com/openshift/assisted-service/pull/4088 ?

**Comment by osherdp** [comment]
> Kinda duplicate of #4088 ?

no need to pin if there's actually no need :smile:

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
