### PR TITLE
MGMT-10535: Set inventory+labels after inventory reported

### PR DESCRIPTION
**Pull request by avishayt**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — COMMENTED** [review]
Can you please add a comment and explain why was that an issue?

**Comment by avishayt** [comment]
For most of the time the agent controller existed, the inventory in the CR was populated and the labels were applied only after the agent sent the inventory.  This meant that whoever was looking at the CR Status and labels was seeing accurate information.  This behavior was recently changed (commit 565a13bcd1ca10c7d66f2e305f9810be67e77345) , so the inventory and labels referred to defaults and would later be updated once the agent sent the inventory.  However, this meant that we are showing misleading information.  This commit brings back the old behavior.

**Pull request merged**
