### PR TITLE
MGMT-15715: Allow handling multi-document YAML custom manifests

### PR DESCRIPTION
**Pull request by adriengentil**
Multi document yamls are not supported during installation.

This change looks into the custom manifests files uploaded by the user,
and splits multi document yaml files into several ones.

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Review by paul-maidment — APPROVED** [review]

**Comment by adriengentil** [comment]
/hold
will update  https://github.com/openshift/assisted-service/blob/master/docs/user-guide/install-customization.md

**Comment by adriengentil** [comment]
@avishayt I added few words in the the doc

**Review by avishayt — APPROVED** [review]

**Review by gamli75 — APPROVED** [review]

**Comment by adriengentil** [comment]
/test edge-verify-generated-code
CI flake

**Pull request merged**
