### PR TITLE
MGMT-13947: Revert assisted boot reporter service

### PR DESCRIPTION
**Pull request by nmagnezi**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
/override ci/prow/edge-e2e-ai-operator-ztp ci/prow/e2e-agent-compact

cutting jobs that shouldn't be relevant here

**Comment by nmagnezi** [comment]
uploading logs locally now returns:
`{"code":606,"message":"logs_type in query should be one of [host controller]"}`

**Comment by nmagnezi** [comment]
looks like the `ci/prow/e2e-agent-compact` job is broken

**Comment by nmagnezi** [comment]
we should override it, based on https://redhat-internal.slack.com/archives/C02SPBZ4GPR/p1678892139170969

**Pull request merged**
