### PR TITLE
MGMT-8716: uses Pod definition with podman

### PR DESCRIPTION
**Pull request by mhrivnak**
The Pod definition and ConfigMap definition can be retrieved by
themselves and used to run assisted-service locally without needing to
clone the repository or use developer tools like `make`. It also
presents a more familiar definition for the Pod than the several lines
of shell script it replaces.

Per the related issue [MGMT-8715](https://issues.redhat.com/browse/MGMT-8715) it is no longer required to mount in
the nginx.conf file to the UI container, so it is removed by this PR.

# Assisted Pull Request

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 
- [x] Refactor

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

I ran the service using podman and installed a cluster.

## Assignees

/cc @
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rollandf** [comment]
`generate.sh` is trying to update `onprem-environment`:

https://github.com/openshift/assisted-service/blob/master/hack/generate.sh#L100-L103

**Comment by osherdp** [comment]
ahh, I see you didn't mean to start review process right away
sorry about that @mhrivnak

**Comment by mhrivnak** [comment]
> `generate.sh` is trying to update `onprem-environment`:
> 
> https://github.com/openshift/assisted-service/blob/master/hack/generate.sh#L100-L103

Can you help me understand how/when that gets run by a user? I did not encounter that flow as part of any podman-based documentation or process.

**Comment by mhrivnak** [comment]
> > `generate.sh` is trying to update `onprem-environment`:
> > https://github.com/openshift/assisted-service/blob/master/hack/generate.sh#L100-L103
> 
> Can you help me understand how/when that gets run by a user? I did not encounter that flow as part of any podman-based documentation or process.

Ah, is this release tooling that keeps the openshift release data current in all the places?

**Comment by flaper87** [comment]
Leaving the generate part out, this looks good to me! Exciting to see our story here improve

**Comment by rollandf** [comment]
@osherdp
Is the generate.sh part here https://github.com/openshift/assisted-service/blob/master/hack/generate.sh#L100-L103 needed ?

**Comment by osherdp** [comment]
> @osherdp Is the generate.sh part here https://github.com/openshift/assisted-service/blob/master/hack/generate.sh#L100-L103 needed ?

As long as we have a way to use same versions from default_release_versions.json, then no

**Comment by osherdp** [comment]
btw @mhrivnak, make sure to trigger the relevant job that tests podman installation with each commit you're adding. For example:
/test e2e-metal-assisted-onprem

**Comment by mhrivnak** [comment]
It looks like test-infra makes a bunch of assumptions about the deployment method with podman, so it will need updating also.

How do you want to handle that? Is it possible for me to make a PR to assisted-test-infra, and have that PR and this PR test with each other? I'm guessing that's too much to ask.

@flaper87 @osherdp @rollandf

**Comment by mhrivnak** [comment]
I made a PR to test-infra fixing the way it deploys with podman. But there's still the question of how to test that PR and this PR together?

https://github.com/openshift/assisted-test-infra/pull/1373

**Comment by flaper87** [comment]
> It looks like test-infra makes a bunch of assumptions about the deployment method with podman, so it will need updating also.
> 
> How do you want to handle that? Is it possible for me to make a PR to assisted-test-infra, and have that PR and this PR test with each other? I'm guessing that's too much to ask.
> 
> @flaper87 @osherdp @rollandf

I'm afraid this is not possible. 

I thought we could create a symlink of the `configmap yaml` as the `onprem-environment` file but after looking at the test-infra PR, I don't think that will be possible. 

If we want to do the switch with the minimum breakage possible, we would have to add 2 targets, keep the existing one now, merge the PR, migrate test-infra, then remove the deprecated one. For this specific case, I would probably just sync the work and get them both in. Hopefully, we will contain the breakage enough.

**Comment by osherdp** [comment]
@mhrivnak we can contain the temporal breakage I think. We mostly have the job running nightly, less as a required presubmit job
just pick a time you're comfortable with merging the two PRs and testing the change after they both in, allowing some time for reverts if we'll need to

**Comment by mhrivnak** [comment]
Ok then, they should both be ready. I'll be standing by on Monday to fix anything that breaks after they merge.

**Comment by osherdp** [comment]
@mhrivnak sounds great
please ping me on slack when you wake up :)

**Pull request merged**
