### PR TITLE
MGMT-12915: Day 2 workers cannot resolve api-int.* when attempting to pull ignition

### PR DESCRIPTION
**Pull request by eranco74**
Revert "bm_inventory: use HTTPS if possible for day2 workers (#4150)"

This reverts commit 6ecf7f1869f33d307c2ac424e671bd8b5356fc44.

The original PR move the day-2 worker to using "https" instead of "http" for fetching the worker ignition but in fact it's also moving it to use the domain rather than the API VIP, which doesn't work when the user didn't initially configure DNS on the day-1 cluster.

- Should this PR be tested by the reviewer?
- Is this PR relying on CI for an e2e test run?
- Should this PR be tested in a specific environment?
- Any logs, screenshots, etc that can help with the review process?

-->

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eranco74** [comment]
/hold
Currently, this isn't an issue, we might figure out a workaround without having to revert it.

**Comment by eranco74** [comment]
infra issue

/test edge-e2e-ai-operator-ztp-capi

**Comment by eranco74** [comment]
Still infra issue

/test edge-e2e-ai-operator-ztp-capi

**Comment by vrutkovs** [comment]
https://github.com/openshift/assisted-service/pull/4911 is stuck on failing tests, so lets do a full revert until its fixed

/hold cancel

**Comment by eranco74** [comment]
Had to rebase again...

**Comment by eranco74** [comment]
/override ci/prow/edge-e2e-ai-operator-ztp 
LSO issue is blocking this PR for 2 days now, meanwhile, capi jobs are broken.
overriding the test

**Pull request merged**
