### PR TITLE
NO-ISSUE: Return bytes from `executeTemplate` template function

### PR DESCRIPTION
**Pull request by jhernand**
Currently the `executeTemplate` template function returns a string,
therefore assuming the result is text. This could make it difficult to
generate binary files. To make that more feasible this patch changes it
so that it returns an array of bytes. The conversion to UTF-8 encoded
strings will be performed by a new `toString` function.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [] No tests needed

Tested manually in the development environment.

## Assignees

/cc @
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by omertuc** [comment]
Thank you!

/lgtm

/hold wait for https://github.com/openshift/assisted-service/pull/4052 ?

**Comment by jhernand** [comment]
@omertuc I think this is ready for a final review and merge. Please take a look. There are no changes since your last review, just rebased.

**Pull request merged**
