### PR TITLE
Making app-sre-jenkins job fail if the scripts fails.

### PR DESCRIPTION
**Pull request by ybettan**
Before the fix the scripts `pr_check.sh` and `build_deploy.sh` will fail
only if the last command of each one of them fails, after the fix
each failure in the scripts will make it exit with error code
immediately.

Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
@ybettan I think there was some mistake assigning this to me, instead of @mavazque.

**Comment by ybettan** [comment]
Hi @matejvasek, it was an error indeed, I have updated the message but apparently you still got the notification.
Sorry for that.

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Review by filanov — APPROVED** [review]

**Pull request merged**
