### PR TITLE
MGMT-12956: Add feature IDs for ppc64le and s390x

### PR DESCRIPTION
**Pull request by jacobemery**
Add Feature IDs and feature support levels for ppc64le and s390x architectures, as well as the results from running `skipper make generate`.

Story: [MGMT-12956](https://issues.redhat.com/browse/MGMT-12956)
Epic: [MULTIARCH-2889](https://issues.redhat.com/browse/MULTIARCH-2889)

Thanks @eliorerz for the help!

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested) 
Ran `skipper make generate` and it returned:
`All validation tests have completed successfully`
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc) Will be completed before release
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by jacobemery** [comment]
cc/ @eliorerz

**Review by eliorerz — CHANGES_REQUESTED** [review]

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
