### PR TITLE
BUG 1969933: Improve image_status_updated event message

### PR DESCRIPTION
**Pull request by nmagnezi**
The image_status_updated event message will now:
1. Use float numbers up to two decimal places.
2. Display image size in Megabytes instead of bytes.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @empovit
/cc @filanov 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
How it looks currently: [events.html](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/3278/pull-ci-openshift-assisted-service-master-e2e-metal-assisted/1488939251646074880/artifacts/e2e-metal-assisted/baremetalds-assisted-gather/artifacts/2022-02-02_19:06:49_adc2cdfd-ed9e-440b-ab3e-5e70874114dc/events.html)

Example:
`Host test-infra-cluster-c0319338-master-1: New image status registry.build03.ci.openshift.org/ci-op-bv5bqdnr/pipeline@sha256:5cc682f7114864e94022c7d29a4e4319436c769bd790362f9ea289f2ec6f09ce. result: success. time: 10.86 seconds; size: 474.64 Megabytes; download rate: 45.83 MBps`

**Review by filanov — APPROVED** [review]

**Pull request merged**
