### PR TITLE
NO-ISSUE: In 4.12 use 4.11 LSO and legacy security context

### PR DESCRIPTION
**Pull request by mkowalski**
Cherry-picks: #4476
Cherry-picks: #4478

/cc @vrutkovs

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by mkowalski** [comment]
/test unit-test

Race condition in unit test? LOL

**Comment by mkowalski** [comment]
/retest-required

This is a failure of dev-scripts to spawn Hub using 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest

```
level=debug msg=Using Install Config loaded from state file
level=info msg=Waiting up to 1h0m0s (until 11:17AM) for the cluster at https://api.ostest.test.metalkube.org:6443 to initialize...
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 502 of 804 done (62% complete)
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 757 of 804 done (94% complete)
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 763 of 804 done (94% complete)
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 768 of 804 done (95% complete)
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 768 of 804 done (95% complete)
level=debug msg=Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, console, ingress, monitoring, openshift-samples
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 780 of 804 done (97% complete)
level=debug msg=Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, console, ingress, monitoring
level=debug msg=Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, console, monitoring
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 797 of 804 done (99% complete)
level=debug msg=Still waiting for the cluster to initialize: Some cluster operators are still updating: authentication, monitoring
level=debug msg=Still waiting for the cluster to initialize: Working towards 4.11.0-0.ci.test-2022-10-13-091254-ci-op-c1kpy0j8-latest: 802 of 804 done (99% complete)
level=debug msg=Still waiting for the cluster to initialize: Cluster operator monitoring is not available
level=info msg=Cluster operator baremetal Disabled is False with : 
level=info msg=Cluster operator cloud-controller-manager TrustedCABundleControllerControllerAvailable is True with AsExpected: Trusted CA Bundle Controller works as expected
level=info msg=Cluster operator cloud-controller-manager TrustedCABundleControllerControllerDegraded is False with AsExpected: Trusted CA Bundle Controller works as expected
level=info msg=Cluster operator cloud-controller-manager CloudConfigControllerAvailable is True with AsExpected: Cloud Config Controller works as expected
level=info msg=Cluster operator cloud-controller-manager CloudConfigControllerDegraded is False with AsExpected: Cloud Config Controller works as expected
level=info msg=Cluster operator etcd RecentBackup is Unknown with ControllerStarted: The etcd backup controller is starting, and will decide if recent backups are available or if a backup is required
level=error msg=Cluster operator ingress Degraded is True with IngressDegraded: The "default" ingress controller reports Degraded=True: DegradedConditions: One or more other status conditions indicate a degraded state: PodsScheduled=False (PodsNotScheduled: Some pods are not scheduled: Pod "router-default-57798789f-wpqvm" cannot be scheduled: 0/4 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 3 node(s) didn't match Pod's node affinity/selector, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/4 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 3 Preemption is not helpful for scheduling. Make sure you have sufficient worker nodes.)
level=info msg=Cluster operator insights SCAAvailable is False with Forbidden: Failed to pull SCA certs from https://api.openshift.com/api/accounts_mgmt/v1/certificates: OCM API https://api.openshift.com/api/accounts_mgmt/v1/certificates returned HTTP 403: {"code":"ACCT-MGMT-11","href":"/api/accounts_mgmt/v1/errors/11","id":"11","kind":"Error","operation_id":"fd755122-8f80-42dc-bd45-3c1bbd9a4e2f","reason":"Account with ID 2DUeKzzTD9ngfsQ6YgkzdJn1jA4 denied access to perform create on Certificate with HTTP call POST /api/accounts_mgmt/v1/certificates"}
level=info msg=Cluster operator insights ClusterTransferAvailable is False with NoClusterTransfer: no available cluster transfer
level=info msg=Cluster operator insights Disabled is False with AsExpected: 
level=error msg=Cluster operator kube-controller-manager Degraded is True with GarbageCollector_Error: GarbageCollectorDegraded: error fetching rules: Get "https://thanos-querier.openshift-monitoring.svc:9091/api/v1/rules": dial tcp: lookup thanos-querier.openshift-monitoring.svc on 172.30.0.10:53: read tcp 10.129.0.17:43082->172.30.0.10:53: i/o timeout
level=info msg=Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack.
level=error msg=Cluster operator monitoring Degraded is True with UpdatingPrometheusOperatorFailed: Failed to rollout the stack. Error: updating prometheus operator: reconciling Prometheus Operator Admission Webhook Deployment failed: updating Deployment object failed: waiting for DeploymentRollout of openshift-monitoring/prometheus-operator-admission-webhook: got 1 unavailable replicas
level=info msg=Cluster operator monitoring Available is False with UpdatingPrometheusOperatorFailed: Rollout of the monitoring stack failed and is degraded. Please investigate the degraded status error.
level=info msg=Cluster operator network ManagementStateDegraded is False with : 
level=error msg=Cluster initialization failed because one or more operators are not functioning properly.
level=error msg=The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
level=error msg=https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
level=error msg=The 'wait-for install-complete' subcommand can then be used to continue the installation
level=error msg=failed to initialize the cluster: Cluster operator monitoring is not available
+(utils.sh:1): create_cluster(): auth_template_and_removetmp
+(utils.sh:664): auth_template_and_removetmp(): echo 6
+(utils.sh:665): auth_template_and_removetmp(): generate_auth_template
+(utils.sh:297): generate_auth_template(): set +x
PING 192.168.111.25 (192.168.111.25) 56(84) bytes of data.
64 bytes from 192.168.111.25: icmp_seq=1 ttl=64 time=0.144 ms

--- 192.168.111.25 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.144/0.144/0.144/0.000 ms
Warning: Permanently added '192.168.111.25' (ECDSA) to the list of known hosts.
cat: /opt/metal3/auth/clouds.yaml: No such file or directory
+(utils.sh:666): auth_template_and_removetmp(): removetmp
+(utils.sh:660): removetmp(): '[' -n '' ']'
+(utils.sh:660): removetmp(): true
make: *** [Makefile:48: ocp_run] Error 6
Fetching kubeconfig, other credentials...
Adding proxy-url in kubeconfig
dev-scripts setup completed, fetching logs
tar: Removing leading `/' from member names
Removing REDACTED info from log...
```

**Comment by vrutkovs** [comment]
Needs a valid bug to merge

**Pull request merged**
