### PR TITLE
AGENT-723: Use json.Marshal to correctly process vSphere credentials

### PR DESCRIPTION
**Pull request by rwsu**
The vSphere vcenter Username field tag is named "user", but because the yaml.Marshal function is used, it fails to interpret the "user" field tag defined in json and marshals the Username field out as "username". The install-config.yaml is written out with Username as "username", but it should be "user". Consequently when the install-config is fed back to openshift-install to generate the ignition files, this error occur:
    
"error running openshift-install create manifests, stdout: level=warning msg=failed to parse first occurrence of unknown field: failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"username\"\nlevel=info msg=Attempting to unmarshal while ignoring unknown keys because strict unmarshaling failed\nlevel=error msg=failed to fetch Master Machines: failed to load asset \"Install Config\": failed to create install config: invalid \"install-config.yaml\" file: [platform.vsphere.vcenters.username: Required value: must specify the username, ..."

To fix this issue yaml.Marshal is replaced with json.Marshal.

Depends on: https://github.com/openshift/assisted-service/pull/5585

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [] None
- [x] Agent-based installation

## How was this code tested?

- [x] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rwsu** [comment]
edge-e2e-vsphere-assisted failed with 

> [1;33m2023-10-31 21:38:43,611  python_terraform WARNING    - 140389278377792 - error: b'\nError: error 503 Service Unavailable\n\n  with vsphere_file.ISO_UPLOAD[0],\n  on main.tf line 72, in resource "vsphere_file" "ISO_UPLOAD":\n  72: resource "vsphere_file" "ISO_UPLOAD" {\n\n' 	(/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/python_terraform/__init__.py:306)[0m

Looks like infrastructure issue. Retrying the test.
/test edge-e2e-vsphere-assisted

**Review by adriengentil — APPROVED** [review]
/hold 
we need to wait for https://github.com/openshift/assisted-service/pull/5585, right?

**Comment by rwsu** [comment]
I've closed PR#5585 since this PR contains its contents. Let's review the combination of both here to make it more simple.
/unhold

**Comment by zaneb** [comment]
Note that it is possible to still do YAML marshalling with the json field tags - the trick is to use the [`sigs.k8s.io/yaml` library](https://pkg.go.dev/sigs.k8s.io/yaml#section-readme) (which uses JSON marshalling under the hood) in place of `gopkg.in/yaml.v2`. So it may be possible to make this change smaller by switching the libraries. (Struct tags still need to be changed from `yaml` to `json` though.)

**Pull request merged**
