### PR TITLE
AGENT-205: Use of internal package fails OCP build

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
The OCP build [ART-4060](https://issues.redhat.com/browse/ART-4060) fails due to the use of an internal package.

Ref: 
brew task https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45260777 
https://download.eng.bos.redhat.com/brewroot/work/tasks/777/45260777/x86_64.log

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by pawanpinjarkar** [comment]
While this PR tries to fix the ART build issue, I am trying to see if there are any other alternatives.

**Comment by osherdp** [comment]
Seems like it's not needed, #3839 sets ``WORK_DIR`` instead (and apart from the patched oc thing seems legit)

**Comment by lranjbar** [comment]
@pawanpinjarkar Take a look at #3839 from ART when you are able to. 😃 I think this is the route we will have to take for now.

**Comment by pawanpinjarkar** [comment]
Thanks for looking into this problem while I was sick. The PR was not meant to be merged when created.

**Pull request closed without merging**
