### PR TITLE
OCPBUGSM-17571 Block creating a cluster without a pull secret

### PR DESCRIPTION
**Pull request by tsorya**

### CODE REVIEW

**Comment by gamli75** [comment]
@avishayt we don't need the pull secret validation after this task, can we remove it?
@tsorya see IsPullSecretSet in cluster/validator_id.go

**Comment by tsorya** [comment]
@gamli75 we can do it in another ticket

**Comment by avishayt** [comment]
@gamli75 You're right, good observation.  I think we can do it in another task though, the validation will just never fail, right?

**Comment by gamli75** [comment]
@avishayt it will never fail since we check that it's not empty in creating & updating cluster.
@tsorya can you please open a new ticket for removing the pull secret validation.

**Pull request merged**
