### PR TITLE
Bump OCP versions release 4.7.36 -> 4.7.37, release 4.8.19 -> 4.8.20, release 4.9.6 -> 4.9.7

### PR DESCRIPTION
**Pull request by osherdp**
4.9 release notes: https://access.redhat.com/errata/RHBA-2021:4579
4.7 release notes: https://access.redhat.com/errata/RHBA-2021:4572
4.8 release notes: https://access.redhat.com/errata/RHBA-2021:4574

/cc @romfreiman @celebdor @gamli75
/hold

### CODE REVIEW

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-operator-disconnected
(broken test)

**Pull request merged**
