### PR TITLE
MGMT-6457 Remove boot files download and upload

### PR DESCRIPTION
**Pull request by carbonin**
This PR removes the API to download boot files and the code for extracting and uploading them to storage when the service starts.

The last (and only) user of the boot-files API was the minimal ISO which was changed to use a URL configured in `OPENSHIFT_VERSIONS` in https://github.com/openshift/assisted-service/pull/1697

### CODE REVIEW

**Comment by carbonin** [comment]
Leaving this as WIP until I finish manual testing.

**Review by avishayt — APPROVED** [review]

**Review by avishayt — APPROVED** [review]

**Pull request merged**
