### PR TITLE
Bug 2069976: Error with oc-mirror using an old outdated unsupported oc client in AI

### PR DESCRIPTION
**Pull request by eranco74**
Updated the oc-image to an updated version of oc that support the new oc mirror behavior

## List all the issues related to this PR
https://bugzilla.redhat.com/show_bug.cgi?id=2069976
https://bugzilla.redhat.com/show_bug.cgi?id=1823143

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD  :disappointed: 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
Describe in the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2069976)
- [ ] No tests needed

## Assignees

/cc @tsorya 
/cc @romfreiman 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eranco74** [comment]
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 5m0s grace period","severity":"error","time":"2022-03-31T09:36:57Z"}

/test e2e-metal-assisted-operator-disconnected

**Review by filanov — APPROVED** [review]

**Review by flaper87 — APPROVED** [review]

**Pull request merged**
