### PR TITLE
MGMT-18105: Update registry.svc.ci.openshift.org to registry.ci.openshift.org (bugzilla #6552)

### PR DESCRIPTION
**Pull request by ArthurVardevanyan**
Issue: https://github.com/openshift/assisted-service/issues/6552

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [X] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [X] Automation (CI, tools, etc)
- [X] Cloud
- [X] Operator Managed Deployments
- [] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [X] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [] No tests needed

## Checklist

- [X] Title and description added to both, commit and PR.
- [X] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [X] This change does not require a documentation update (docstring, `docs`, README, etc)
- [X] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rccrdpccl** [comment]
/retitle NO-ISSUE: (bugzilla #6552) Update registry.svc.ci.openshift.org to registry.ci.openshift.org

**Comment by rccrdpccl** [comment]
/lgtm
/approve

Thanks for your contribution @ArthurVardevanyan 

@gamli75 I think this should be backported to all branches, would you agree?

**Comment by gamli75** [comment]
> Member

There is an open epic to change this repository https://issues.redhat.com/browse/MGMT-18105 
@danmanor

**Comment by rccrdpccl** [comment]
/retitle MGMT-18105: Update registry.svc.ci.openshift.org to registry.ci.openshift.org (bugzilla #6552)

**Comment by danmanor** [comment]
@gamli75 Yes, we need to add `quay-proxy.ci.openshift.org` to the list as well

**Pull request merged**
