### PR TITLE
Add SERVICE_REPLICAS_COUNT to skipper.yaml

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by YuviGold** [comment]
Shouldn't it be `REPLACES_COUNT` ?

**Comment by rollandf** [comment]
> Shouldn't it be `REPLACES_COUNT` ?

From Makefile: https://github.com/openshift/assisted-service/blob/master/Makefile#L37

```
# We decided to have an option to change replicas count only while running in minikube
# That line is checking if we run on minikube
# check if SERVICE_REPLICAS_COUNT was set and if yes change default value to required one
REPLICAS_COUNT = $(shell if ! [ "${TARGET}" = "minikube" ];then echo 3; else echo $(or ${SERVICE_REPLICAS_COUNT},3);fi)
```

**Comment by YuviGold** [comment]
> > Shouldn't it be `REPLACES_COUNT` ?
> 
> From Makefile: https://github.com/openshift/assisted-service/blob/master/Makefile#L37
> 
> ```
> # We decided to have an option to change replicas count only while running in minikube
> # That line is checking if we run on minikube
> # check if SERVICE_REPLICAS_COUNT was set and if yes change default value to required one
> REPLICAS_COUNT = $(shell if ! [ "${TARGET}" = "minikube" ];then echo 3; else echo $(or ${SERVICE_REPLICAS_COUNT},3);fi)
> ```

I think that line should be updated as well.
Was there a meaning for two different environment variables? @tsorya

**Comment by rollandf** [comment]
> > > Shouldn't it be `REPLACES_COUNT` ?
> > 
> > 
> > From Makefile: https://github.com/openshift/assisted-service/blob/master/Makefile#L37
> > ```
> > # We decided to have an option to change replicas count only while running in minikube
> > # That line is checking if we run on minikube
> > # check if SERVICE_REPLICAS_COUNT was set and if yes change default value to required one
> > REPLICAS_COUNT = $(shell if ! [ "${TARGET}" = "minikube" ];then echo 3; else echo $(or ${SERVICE_REPLICAS_COUNT},3);fi)
> > ```
> 
> I think that line should be updated as well.
> Was there a meaning for two different environment variables? @tsorya

REPLICAS_COUNT is changed only on minikube:
`REPLICAS_COUNT = $(shell if ! [ "${TARGET}" = "minikube" ];then echo 3; else echo $(or ${SERVICE_REPLICAS_COUNT},3);fi)`

**Review by YuviGold — APPROVED** [review]
LGTM

**Pull request merged**
