### PR TITLE
Bug 1996531: Reduce singleNodeRebootTimeout from 120 minutes to 80 minutes

### PR DESCRIPTION
**Pull request by eranco74**
# Assisted Pull Request

## Description

Updated the timeout
Added UT for SNO and multi node cluster
Update the wording and added the installation disk to the status info (MGMT-7641)

- Should this PR be tested by the reviewer? no
- Is this PR relying on CI for an e2e test run? yes for regression
- Should this PR be tested in a specific environment? no
- Any logs, screenshots, etc that can help with the review process? no

-->

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @tsorya 
/cc @lalon4 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Review by filanov — CHANGES_REQUESTED** [review]
Can you please add a test?

**Comment by eranco74** [comment]
> Can you please add a test?

I'll add a test for the SNO case

**Comment by eranco74** [comment]
```
waiting.exceptions.TimeoutExpired: Timeout of 1800 seconds expired waiting for assisted-service to be healthy
```
/retest

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
