### PR TITLE
MGMT-16164: Install 4.14 redhat-operators catalog for LSO

### PR DESCRIPTION
**Pull request by danmanor**
This change just bumps our hack of using 4.14 catalog for `LSO` installation to `OCP` grater than `4.14`.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]

**Comment by adriengentil** [comment]
> please run cnv test to verify that it's working
cnv/odf still run on 4.13, I have a task to update them once they are released tomorrow: https://issues.redhat.com/browse/MGMT-16056

**Comment by danmanor** [comment]
> cnv/odf still run on 4.13
Where do you see that ? @adriengentil

**Pull request merged**
