### PR TITLE
Bug 2131023: Allow arm64 sno installation

### PR DESCRIPTION
**Pull request by tsorya**
Currently we can't install sno cluster as ai is searching for x86 image as it thinks that sno is baremetal platform. In master it was fixed by setting platform to None for SNO but this fix is too big and all we need is not to allow overriding image for sno installation.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by romfreiman** [comment]
@mkowalski

**Comment by mkowalski** [comment]
Let me understand the logic for this change...

Currently for non-x86 for platform Baremetal we are extracting `openshift-baremetal-installer` from the x86 release payload. This is desired behaviour as non-x86 release payload does *not* contain the binary that we can use in Hub.

What this change is trying to say is
* if architecture is non-x86
* and if platform is Baremetal
* and if cluster is SNO
then *do not* override `installerReleaseImageOverride` variable.

So for ARM SNO our installer release image will be ARM image. Which part of the code ensures that later in the process we are using `openshift-install` binary and not `openshift-baremetal-install`? Because the cluster's platform is Baremetal, I would expect that the latter is used and stuff fails.

Please correct me which part of the above reasoning is wrong (and even better, embed somewhere in the comment so that people in the future don't repeat my wrong reasoning)

**Comment by mkowalski** [comment]
> ## How was this code tested?
> 
>     * [ ]  assisted-test-infra environment
> 
>     * [ ]  dev-scripts environment
> 
>     * [ ]  Reviewer's test appreciated
> 
>     * [ ]  Waiting for CI to do a full test run
> 
>     * [ ]  Manual (Elaborate on how it was tested)
> 
>     * [x]  No tests needed

No please no, at least write that you tested it manually or something

**Comment by tsorya** [comment]
it was tested already https://coreos.slack.com/archives/C01LZ5SBLLQ/p1664495619235259?thread_ts=1664382800.392479&cid=C01LZ5SBLLQ

**Comment by tsorya** [comment]
You can see here https://github.com/openshift/assisted-service/blob/release-ocm-2.6/pkg/generator/generator.go#L103 and here https://github.com/openshift/assisted-service/blob/release-ocm-2.6/pkg/generator/generator.go#L124 that in SNO case we will provide None platform to extract function.
This fix is only for ocm 2.6 in master it was already fixed by settin none platform for SNO

**Comment by mkowalski** [comment]
So based on https://github.com/openshift/assisted-service/blob/release-ocm-2.6/pkg/generator/generator.go#L124 for SNO we have UserManagedNetworking=True and Platform=Baremetal and for this reason the extract function gets the proper binary, is that correct? If so, that change here is good to go. It’s quite a spaghetti but I guess that’s the price for having the whole concept of UserManagedNetworking

**Comment by tsorya** [comment]
Yep.

**Comment by filanov** [comment]
/override ci/prow/e2e-ai-operator-ztp-disconnected 
job is broken

**Pull request merged**
