### PR TITLE
MGMT-14810: Remove API and Ingress VIP

### PR DESCRIPTION
**Pull request by nmagnezi**
## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Comment by nmagnezi** [comment]
/hold
fixing CI issues

**Comment by bfournie** [comment]
Note that the e2e-agent-compact-ipv4  will fail with
`level=debug msg=Host master-2: updated status from discovering to pending-for-input (Waiting for user input: Host couldn't synchronize with any NTP server ; Machine Network CIDR is undefined; the Machine Network CIDR can be defined by setting either the API or Ingress virtual IPs)`
This is because the agent installer passes in the singular APIVIP/IngressVIP in CreateClusterParams and uses install-config overrides when more than one VIP is defined.

Once this fix merges then the agent installer change https://github.com/openshift/installer/pull/7574 that uses APIVIPs/IngressVIPs can merge.

**Comment by bfournie** [comment]
I tested this PR along with the agent installer PR https://github.com/openshift/installer/pull/7574 to use APIVIPs/IngressVIPs (instead of singular VIP) and hit this issue:
```
Oct 12 17:29:07 master-0 service[2724]: time="2023-10-12T17:29:07Z" level=error msg="Error registering cluster ostest" func="github.com/openshift/assisted-service/internal/cluster.(*registrar).registerCluster" file="/src/internal/cluster/registrar.go:70" pkg=cluster-state
Oct 12 17:29:07 master-0 service[2724]: time="2023-10-12T17:29:07Z" level=error msg="update cluster failed" func="github.com/openshift/assisted-service/internal/cluster.(*registrar).registerCluster.func1" file="/src/internal/cluster/registrar.go:44" pkg=cluster-state
Oct 12 17:29:07 master-0 service[2724]: time="2023-10-12T17:29:07Z" level=error msg="Failed to registered cluster ostest with id be1fd3cd-be8c-4749-b95a-10621fd622f0" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).RegisterClusterInternal.func1" file="/src/internal/bminventory/inventory.go:521" cluster_id=be1fd3cd-be8c-4749-b95a-10621fd622f0 error="ERROR: column \"api_vip\" of relation \"clusters\" does not exist (SQLSTATE 42703)" go-id=98 pkg=Inventory request_id=582992a6-c40a-480f-9ea8-b8baca701be1
```
Let me know if more info is needed.

**Comment by nmagnezi** [comment]
@bfournie Thanks!
Replied here: https://github.com/openshift/installer/pull/7574#issuecomment-1763108816

**Comment by bfournie** [comment]
> @bfournie Thanks! Replied here: [openshift/installer#7574 (comment)](https://github.com/openshift/installer/pull/7574#issuecomment-1763108816)

Thanks. I tested your latest update along with https://github.com/openshift/installer/pull/7574 and it works well

**Comment by avishayt** [comment]
@nmagnezi Ready to go?

**Comment by nmagnezi** [comment]
> @nmagnezi Ready to go?

@avishayt as soon as I fix the broken jobs

**Comment by andfasano** [comment]
It could be useful also to test agent-sno job, as it uses directly ZTP manifests as input configuration (while the other agent jobs are based on the install-config.yaml)

/test e2e-agent-sno-ipv6

**Review by avishayt — APPROVED** [review]

**Pull request merged**
