### PR TITLE
MGMT-6670: Revert all the dual-stack work

### PR DESCRIPTION
**Pull request by mkowalski**
This code is an attempt to revert the following commits

```
d271e2bd - Mateusz Kowalski, 12 hours ago : Bug 1999297: Trigger VIP reallocation only when the primary machine CIDR changes (#2527)
7e1b1109 - Mateusz Kowalski, 26 hours ago : MGMT-6670: Fix handling of empty network in various network params (#2512)
f9bab512 - Mateusz Kowalski, 2 days ago : MGMT-6670: Fix BelongsToMachineCidr validator message (#2511)
51ee4ce4 - Mateusz Kowalski, 2 days ago : MGMT-6898: Fix MachineNetworks validation for multi-network setup (#2507)
9d64b25d - Mateusz Kowalski, 6 days ago : MGMT-6670: Extend validator for L2 majority groups (#2414)
56247fd7 - Yuval Goldberg, 8 days ago : MGMT-4321: Bugfix flaky auto assign machine cidr deadlock
3ca606e5 - Yuval Goldberg, 9 days ago : MGMT-4321: Bugfix flaky auto assign DHCP machine cidr (#2468)
7dd390d9 - Yuval Goldberg, 9 days ago : MGMT-7498: Migrate multiple networks (#2445)
ed043991 - Mateusz Kowalski, 9 days ago : MGMT-7498: Add backwards compatibility for network configuration (#2455)
a40e053c - Mateusz Kowalski, 10 days ago : MGMT-7464: Pass multiple machine networks to install-config.yaml (#2432)
261a4bfd - Mateusz Kowalski, 13 days ago : MGMT-6670: Create a getter for Machine Network CIDR (#2416)
344d88cb - Yuval Goldberg, 13 days ago : MGMT 4321: delete networks records on deletion (#2423)
a2ab6438 - Mateusz Kowalski, 2 weeks ago : MGMT-6670: Extend validator for host in machineNetwork (#2403)
2918f97e - Yuval Goldberg, 2 weeks ago : MGMT-4321: Service support multiple networks (#2340)
196700b7 - Yuval Goldberg, 3 weeks ago : MGMT-6897: Swagger support multiple networks (#2339)
f2010a32 - Yuval Goldberg, 4 weeks ago : Organize update network params (#2307)
f96503bc - Yuval Goldberg, 5 weeks ago : MGMT-6897: Add network_config field to cluster (#2281)
```

This code reverts the following commits with the respective states

```
d271e2bd - ok, clean
7e1b1109 - ok, clean
f9bab512 - ok, clean
51ee4ce4 - ok, clean
9d64b25d - DIRTY, done
56247fd7 - ok, clean
3ca606e5 - ok, clean
7dd390d9 - DIRTY, done
ed043991 - ok, clean
a40e053c - ok, clean
261a4bfd - DIRTY, done
344d88cb - DIRTY, done
a2ab6438 - ok, clean
2918f97e - DIRTY, done
196700b7 - not reverted
f2010a32 - not reverted
f96503bc - not reverted
```

------------------

This code compiles.

------------------

This code fails the following unit-tests

```
• Failure [0.092 seconds]
Permanently delete clusters
/home/kmateusz/git/github.com/assisted-service/internal/cluster/cluster_test.go:2519
  permanently delete clusters success [It]
  /home/kmateusz/git/github.com/assisted-service/internal/cluster/cluster_test.go:2559

  Expected
      <int>: 0
  not to equal
      <int>: 0

  /home/kmateusz/git/github.com/assisted-service/internal/cluster/cluster_test.go:2586
```
```
• Failure [0.092 seconds]
Permanently delete clusters
/home/kmateusz/git/github.com/assisted-service/internal/cluster/cluster_test.go:2519
  permanently delete clusters success [It]
  /home/kmateusz/git/github.com/assisted-service/internal/cluster/cluster_test.go:2559

  Expected
      <int>: 0
  not to equal
      <int>: 0

  /home/kmateusz/git/github.com/assisted-service/internal/cluster/cluster_test.go:2586
```

------------------

This code is available as the following container image

`quay.io/mkowalski/assisted-service:this-branch-is-a-revert-of-all-the-work-done-in-order-to-support-dual-stack-1`

------------------

This code has not been manually tested.

### CODE REVIEW

**Comment by mkowalski** [comment]
/test e2e-metal-assisted

```
 INFO[2021-09-02T09:42:50Z] ************ baremetalds assisted setup command ************
Could not create directory '/.ssh'.
Warning: Permanently added '147.75.94.239' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
ssh: connect to host 147.75.94.239 port 22: Connection timed out
```

**Comment by flaper87** [comment]
/hold 

We are not going down this path. Instead, backwards compatibility is being added to `v1` as part of https://github.com/openshift/assisted-service/pull/2485

**Pull request closed without merging**
