### PR TITLE
MGMT-13008: ignition size validation on register infraenv

### PR DESCRIPTION
**Pull request by danielerez**
As a follow-up to https://github.com/openshift/assisted-service/pull/4894, added the ignition size validation also to RegisterInfraEnv and UpdateInfraEnv APIs.
These APIs were missed in the aforementioned PR. Also, removed the validation in v2UpdateHostIgnition API which is redundant as we don't embed the host ignition in the ISO.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
>which handled only the v2UpdateHostIgnition API

Sorry I must have missed this. This API is the only one that _doesn't_ need this validation as the host ignition isn't being embedded into the ISO. You can remove the validation from the host ignition APIs.

**Comment by danielerez** [comment]
> > which handled only the v2UpdateHostIgnition API
> 
> Sorry I must have missed this. This API is the only one that _doesn't_ need this validation as the host ignition isn't being embedded into the ISO. You can remove the validation from the host ignition APIs.

Hmm, but won't it be confusing if we don't have it also in v2UpdateHostIgnition any way? Not sure we want to have such inconsistency, unless we can maybe treat it as a workaround(?):/

**Comment by carbonin** [comment]
Why would we limit it for no reason? One needs to fit into a fixed size spot in the ISO, the other doesn't.
They have nothing to do with each other and won't likely have the same kind of content.

**Comment by danielerez** [comment]
> Why would we limit it for no reason? One needs to fit into a fixed size spot in the ISO, the other doesn't. They have nothing to do with each other and won't likely have the same kind of content.

ok, removed.

**Review by carbonin — APPROVED** [review]

**Pull request merged**
