### PR TITLE
Mgmt 13607:  Get CAPI image from the release

### PR DESCRIPTION
**Pull request by eranco74**
When creating hosted cluster using hypershift from 4.11 release the hostedcontrolplane fail to start the cluster-api pod because it is using hardcoded registry.ci.openshift.org/hypershift/cluster-api:v1.0.0 image that no longer exists (since Jan 25) 

This PR update the test setup to get the CAPI image from the release

- Should this PR be tested by the reviewer? no
- Is this PR relying on CI for an e2e test run? no
- Should this PR be tested in a specific environment? hypershift + capi
- Any logs, screenshots, etc that can help with the review process? no

-->

## List all the issues related to this PR
https://issues.redhat.com/browse/MGMT-13607

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eranco74** [comment]
/retest e2e-ai-operator-ztp-capi 
devscripts-setup failied

**Review by avishayt — APPROVED** [review]

**Comment by eranco74** [comment]
Something went wrong:
```
    state:
      waiting:
        message: |
          container create failed: time="2023-02-09T13:21:24Z" level=error msg="runc create failed: unable to start container process: exec: \"/manager\": stat /manager: no such file or directory"
        reason: CreateContainerError
```

**Comment by eranco74** [comment]
```
docker inspect $CLUSTER_API_IMAGE | jq ".[0].Config.Entrypoint"
[
  "/bin/cluster-api-controller-manager"
]
```
:thinking:

**Comment by eranco74** [comment]
Hmm
https://github.com/openshift/hypershift/pull/1826/files#diff-b5cde720842b19b53da3f454d827e27327c4559b2e4849906dac728586f51eb3R2523
Unsure how this is supposed to work.

**Comment by eranco74** [comment]
retry with the image used [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.11-periodics-4.11-aws-conformance/1621571516711833600/artifacts/aws-conformance/dump/artifacts/namespaces/clusters-40073c3813170a857ef3/core/pods/cluster-api-7cd89b449-j4tmm.yaml)

/test e2e-ai-operator-ztp-capi

**Pull request closed without merging**
