### PR TITLE
MGMT-8415: Remove the infra-env image download endpoint

### PR DESCRIPTION
**Pull request by carbonin**
# Assisted Pull Request

## Description

This endpoint assumed we were uploading the image to s3 and that won't
be the case in most situations. Even before the move to the image
service the download url in the infra-env should always be correct so
users should always just use that.

https://issues.redhat.com/browse/MGMT-8415

Marking as WIP because this is built on https://github.com/openshift/assisted-service/pull/2884 to avoid conflict in subsystem tests.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 
- [x] Tech Debt

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @avishayt 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by avishayt — COMMENTED** [review]
Would like another set of eyes on the image service deployment

**Comment by carbonin** [comment]
@avishayt the image service deployment is being added in https://github.com/openshift/assisted-service/pull/2884.
I have the commits here as well to avoid a conflict.

Eventually the only commit in this PR will be the last one.

**Comment by carbonin** [comment]
@avishayt this one is ready to go if you could take another look

**Review by avishayt — APPROVED** [review]

**Pull request merged**
