### PR TITLE
MGMT-8893: set arm64 support as dev-preview

### PR DESCRIPTION
**Pull request by danielerez**
# Assisted Pull Request

## Description

Added 4.10 to SupportLevelsList and set arm64 feature as dev-preview.

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @filanov 
/cc @avishayt
/cc @romfreiman 
/cc @sagidayan  

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danielerez** [comment]
/unhold
Set arm as dev-preview in 4.10

**Comment by romfreiman** [comment]
This does not mean that we expose it right away, right?

**Comment by danielerez** [comment]
> This does not mean that we expose it right away, right?

What do you mean by exposed? It's mainly needed for the UI - to enable arm on 4.10. Should we wait with this change until UI is implemented?

**Comment by romfreiman** [comment]
We're not pushing the UI yet, so I assume it's fine. Also, we dont expose 4.10 AFAIK....

**Pull request merged**
