### PR TITLE
NO-ISSUE: Remove host ID from upload logs log

### PR DESCRIPTION
**Pull request by oshercc**
# Assisted Pull Request

## Description
 log line is relevant to all the logs and not only for host, so in case of controller logs we will get null

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @tsorya 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by nmagnezi — COMMENTED** [review]
Can you please explain why?

**Comment by oshercc** [comment]
the cluster id is irrelevant here so for now the log line looks like:
`Uploading logs from host <nil> in cluster d808b208-f532-4f17-ad1c-4d9b6924e443`

**Comment by oshercc** [comment]
> Can you please explain why?

the cluster id is irrelevant here so for now the log line looks like:
Uploading logs from host <nil> in cluster d808b208-f532-4f17-ad1c-4d9b6924e443

**Comment by tsorya** [comment]
@nmagnezi cause this log line is relevant to all the logs and not only for host, so in case of controller logs we will get null

**Review by nmagnezi — COMMENTED** [review]
so perhaps log the host when:
`if params.LogsType == string(models.LogsTypeHost)`
as in line 4582 so we won't lose that info?

**Comment by oshercc** [comment]
> so perhaps log the host when:
> `if params.LogsType == string(models.LogsTypeHost)`
> as in line 4582 so we won't lose that info?

I do not think there will ever be any host info for us to lose

**Pull request merged**
