### PR TITLE
[BZ1872302] Exposing grafana and prometheus as NodePort instead of clusterIP on Minikube

### PR DESCRIPTION
**Pull request by jparrill**
- Fixing [BZ1872302](https://bugzilla.redhat.com/show_bug.cgi?id=1872302)

### CODE REVIEW

**Comment by jparrill** [comment]
Could you please guys merge this one? 

/cc @romfreiman @ronniel1

**Comment by ronniel1** [comment]
@jparrill is this relevant for our upcoming release on cloud?

**Comment by jparrill** [comment]
> @jparrill is this relevant for our upcoming release on cloud?

Nope, just for minikube

**Review by filanov — APPROVED** [review]

**Pull request merged**
