### PR TITLE
MGMT-18059: Mark OCI as supported integration

### PR DESCRIPTION
**Pull request by adriengentil**
Remove OCI from technology preview as it is now a supported integration.

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by adriengentil** [comment]
/override ci/prow/e2e-metal-assisted-day2 ci/prow/e2e-metal-assisted-ipv4v6 ci/prow/e2e-metal-assisted-lvm ci/prow/e2e-metal-assisted-odf ci/prow/e2e-metal-assisted-onprem ci/prow/e2e-metal-assisted-single-node ci/prow/e2e-metal-assisted-static-ip-suite ci/prow/lint ci/prow/subsystem-aws ci/prow/unit-test ci/prow/verify-generated-code

these jobs were  triggered because I messed up with https://github.com/openshift/assisted-service/pull/6405

**Pull request merged**
