### PR TITLE
OCPBUGS-34181: Don't use the statically linked installer if FIPS is enabled

### PR DESCRIPTION
**Pull request by carbonin**
Adds a check for the FIPS status of the current system and blocks use of the statically linked installer binary if FIPS is enabled.

## List all the issues related to this PR

Resolves https://issues.redhat.com//browse/OCPBUGS-34181

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

Mostly operator and ABI since FIPS will never be active in the Cloud.

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
This is an alternative approach to https://github.com/openshift/assisted-service/pull/6353 that will hopefully fix both https://issues.redhat.com//browse/OCPBUGS-34181 and https://issues.redhat.com//browse/OCPBUGS-33227

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Pull request merged**
