### PR TITLE
[ocm-2.3] Bug 1968452: Clarify "Mirror Registry Configuration" doc

### PR DESCRIPTION
**Pull request by rwsu**
Documentation now states how configuring the mirror registry
affects the discovery image's ignition config and the
install-config.yaml file used to install a cluster.

The limitation where the registries.conf mirroring must be repo
scope and not registry scope is explained.

cherry-pick of #2021

Signed-off-by: Richard Su <rwsu@redhat.com>

### CODE REVIEW

**Review by djzager — APPROVED** [review]

**Comment by rollandf** [comment]
@flaper87 please approve

**Pull request merged**
