### PR TITLE
MGMT-8058: Update Operator CSV for OCM 2.4

### PR DESCRIPTION
**Pull request by lranjbar**
# Assisted Pull Request

## Description

Updating the operator cluster service version to the ocm-2.4 images on the ocm-2.4 release branch.

[MGMT-8058](https://issues.redhat.com/browse/MGMT-8058)

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @celebdor 
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by flaper87 — APPROVED** [review]
lgtm

**Comment by lranjbar** [comment]
Repurposing this PR it was discovered that the replacements weren't working right.

/assign @djzager

**Review by djzager — CHANGES_REQUESTED** [review]
Please also update https://github.com/openshift/assisted-service/blob/8183d673054b6cf188c906aca1301aca028e2e2c/Makefile#L83 to only use `ocm-2.4` channel

**Comment by lranjbar** [comment]
Originally was only updating the operator CSV however the assisted-image-service was in CrashLoopBackOff due to trying to pull missing OS images.

Error from assisted-image-service log:
```
{"file":"/go/src/github.com/openshift/origin/main.go:40","func":"main.main","level":"fatal","msg":"Failed to populate image store: failed to download https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.9.0-rc.0/rhcos-4.9.0-rc.0-x86_64-live.x86_64.iso: Request to https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.9.0-rc.0/rhcos-4.9.0-rc.0-x86_64-live.x86_64.iso returned error code 404\n","time":"2021-10-21T20:44:16Z"}
```

**Comment by lranjbar** [comment]
I have rolled the change discussed in https://github.com/openshift/release/pull/23142 into this PR. (Moving the postgres image to the new org)

At this point the quick fixes don't seem to be working on the `assisted-test-infra` jobs. I'm not sure if there will be a quick fix other than merging this PR to fix those.

**Comment by osherdp** [comment]
/retest
maybe after https://github.com/openshift/release/pull/23208 we have a better chance to have the changes in place

**Comment by osherdp** [comment]
/test e2e-metal-assisted-ipv6
```
RuntimeError: command=kubectl --namespace assisted-installer get service assisted-service | grep assisted-service exited with an error=Error from server: etcdserver: request timed out code=1
```
(known failure, which we still don't know how to handle properly)

**Comment by lranjbar** [comment]
Single node error is same as well

```
RuntimeError: command=kubectl --namespace assisted-installer get service assisted-service | grep assisted-service exited with an error=Error from server: etcdserver: request timed out code=1
```

**Comment by lranjbar** [comment]
The job of late-binding-single-node has an extremely high failure rate and the error is the same as master.

See:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-kube-api-late-binding-single-node-periodic

**Comment by lranjbar** [comment]
Same with the disconnected job it also does not work on master:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-disconnected-periodic

**Comment by lranjbar** [comment]
The errors related to no pulling in the os_images properly seem to be resolved which is the main reason for this PR.

Should be good to go.

**Review by osherdp — APPROVED** [review]

**Comment by celebdor** [comment]
This PR fixes OperatorHub's 2.4 channel to use the right RHCOS and container images. Let's take it in.

**Pull request merged**
