### PR TITLE
MGMT-8380: Stop setting custom manifest feature flag for OLM operators

### PR DESCRIPTION
**Pull request by CrystalChun**
[MGMT-8380](https://issues.redhat.com/browse/MGMT-8380): 

**Problem**:
There are two scenarios when manifests need to be created:
1. When an OLM operator is enabled for a Cluster
2. When a user requests to create custom manifests for a Cluster

Both the scenarios above called the same create manifest function,
which sets a feature flag called "Custom Manifests" to true. This
is incorrect behavior for the first scenario since an OLM operator's
manifests are not custom manifests and should not enable this feature
flag.

**Solution**: Use the create manifest internal function instead when
creating manifests for OLM operators. The internal function evades
setting the custom manifest feature flag.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

1. Used the assisted-test-infra environment to deploy nodes
2. List the cluster to see if the custom manifests flag was enabled
    ````bash
    curl $SERVICE_URL/api/assisted-install/v2/clusters | jq -r '.[].feature_usage' | jq
    ````
3. Manually called the create custom manifests API
    ````bash
    curl \
        --header "Content-Type: application/json" \
        --header "Authorization: Bearer $TOKEN" \
        --request POST \
        --data "{\"file_name\":\"$file\", \"folder\":\"$folder\", \"content\":\"$content\"}" \
    "$SERVICE_URL/api/assisted-install/v2/clusters/$CLUSTER_ID/manifests"
    ````
3. List the cluster again to see if the custom manifests flag was enabled

## Assignees

/cc @carbonin 
/cc @sagidayan 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
Code changes look good, but I think you have the PR description backwards.

You say:
>This PR removes the enabling of the flag when the custom manifests API is hit

But this is the case when we still want the flag. This PR ensures we don't set the flag when a user selects an additional operator to install and doesn't use the custom manifests API directly, right?

Also, the commit message could be better. Please take a look at https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines for some info about writing good commit messages.

Specifically in this case the first line of your commit is too long and the details from the PR description (when corrected) should be present in the commit body.

**Comment by CrystalChun** [comment]
@carbonin Thanks for the link to the guidelines and for the guidance! How does the commit message and PR message look now?

**Comment by carbonin** [comment]
Looks great!

**Review by carbonin — APPROVED** [review]

**Comment by osherdp** [comment]
/override ci.ext.devshift.net PR build
already passed, and it seems like the github context just hasn't been updated

**Pull request merged**
