### PR TITLE
MGMT-7282: Use community operators to install AI operator for ocm-2.3

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
# Assisted Pull Request

## Description
Use community operators to install AI operator for ocm-2.3. Use the existing catalog_source_name everywhere but override and set  `CATALOG_SOURCE_NAME` to  `community-operators` in case of operator upgrade scenario. Also, set the channel to `ocm-2.3` when creating the subscription from `community-operators`  before the operator upgrade. To upgrade, set the channel to `alpha`.

`CATALOG_SOURCE_NAME` , `CHANNEL_INSTALL_OVERRIDE`and  `CHANNEL_UPGRADE_OVERRIDE` will be set in the job config for the operator upgrade test in openshift/release.

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [] No tests needed

## Assignees

/cc @lranjbar 
/cc @djzager 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by lranjbar** [comment]
Seems to have broken the default run in the base ztp job:

```
 - lastTransitionTime: "2021-09-21T23:46:31Z"
    message: targeted catalogsource openshift-marketplace/catalog_source_name missing
    reason: UnhealthyCatalogSourceFound
    status: "True"
    type: CatalogSourcesUnhealthy
```

**Comment by pawanpinjarkar** [comment]
> Seems to have broken the default run in the base ztp job:
> 
> ```
>  - lastTransitionTime: "2021-09-21T23:46:31Z"
>     message: targeted catalogsource openshift-marketplace/catalog_source_name missing
>     reason: UnhealthyCatalogSourceFound
>     status: "True"
>     type: CatalogSourcesUnhealthy
> ```

it's because of the typo. Now fixed and set to  $catalog_source_name

**Review by flaper87 — APPROVED** [review]
:pizza:

**Pull request merged**
