### PR TITLE
MGMT-4942 Download rootfs from mirror.openshift.com

### PR DESCRIPTION
**Pull request by carbonin**
Currently, to support a minimal iso, our service also hosts the rootfs over the API.
Serving that rootfs to many hosts booting the minimal iso simultaneously may cause a load on the service that is unacceptable for resource or performance reasons.

The rootfs is also available as a release artifact on mirror.openshift.com so use that by default.

For a disconnected environment, this will mean that the rootfs will need to be hosted somewhere the hosts can access it and `OPENSHIFT_VERSIONS` should be configured with the new download path. (Same requirement as the base iso)

cc @jparrill

### CODE REVIEW

**Comment by carbonin** [comment]
@djzager this will mean a change to https://github.com/openshift/assisted-service/pull/1592 to add the rootfs

**Comment by carbonin** [comment]
@avishayt as a followup I would like to stop extracting the rootfs and remove the `boot-files` api endpoint, but I'm not sure if we still have a use-case for that or if anyone is currently using the endpoint in the cloud. I asked about metrics for endpoint usage in the cloud but it looks like we may not have them.

**Comment by avishayt** [comment]
@carbonin This is a tradeoff that we should consider carefully.  The upsides to this approach are as you stated.  The downsides are (1) the service is no longer self-contained, although an operator deployment could use a local mirror, and (2) more importantly, we won't have any indication if we're failing at this point.  For example, today if there's some issue downloading the rootfs we (should) have an event.  We (could) also have an event when it's downloaded successfully to better monitor the boot progress.

A compromise might be to use the existing redirect logic in that API.  So our endpoint would be called and we could emit a debug event, then return 307 to redirect to the mirror.  We still won't be aware of any errors though.

Another alternative would be to stream from the mirror each time.

I think this warrants some further discussion - I will add it to today's arch meeting agenda.

**Comment by carbonin** [comment]
@avishayt did today's talk resolve these concerns?

> (1) the service is no longer self-contained, although an operator deployment could use a local mirror

I think in the case of the cloud the mirror should be at least as reliable as our service, and as you said we're already not self-contained for disconnected cases.

> today if there's some issue downloading the rootfs we (should) have an event

We don't. Currently the rootfs url is not cluster-specific and there's no (reasonable) way of adding that information to the request. A generic event say "someone failed to download a rootfs" isn't particularly useful.

> A compromise might be to use the existing redirect logic in that API. So our endpoint would be called and we could emit a debug event, then return 307 to redirect to the mirror. We still won't be aware of any errors though.
> Another alternative would be to stream from the mirror each time.

All that said, we could still definitely do either of these. What do you think?

**Comment by avishayt** [comment]
Let's proceed with this PR

**Review by djzager — APPROVED** [review]
/lgtm

**Pull request merged**
