### PR TITLE
MGMT-1929 - Add required fields to install config

### PR DESCRIPTION
**Pull request by carbonin**
This adds the missing fields to the install config struct.
They will later be made customizable.

### CODE REVIEW

**Comment by avishayt** [comment]
So far so good

**Comment by romfreiman** [comment]
how do u know that those are all the feilds?

**Comment by carbonin** [comment]
@romfreiman These are based on the example config in https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-bare-metal-config-yaml_installing-restricted-networks-bare-metal and the epic description.

**Comment by romfreiman** [comment]
np. not sure whether u're familiar, but there is an explain command in the openshift-installer binary - u can execute and got more documentation (if u're interested :) )

**Comment by carbonin** [comment]
Good to know @romfreiman. Taking a look at that repo, is there are reason we reinvented their [`InstallConfig` type](https://github.com/openshift/installer/blob/master/pkg/types/installconfig.go#L61)? Should we be using that rather than our own representation which is bound to be out of date. Maybe something to do with supporting multiple openshift versions?

**Comment by romfreiman** [comment]
> Good to know @romfreiman. Taking a look at that repo, is there are reason we reinvented their [`InstallConfig` type](https://github.com/openshift/installer/blob/master/pkg/types/installconfig.go#L61)? Should we be using that rather than our own representation which is bound to be out of date? Maybe something to do with supporting multiple openshift versions?

I have no idea. I would rather stick to the original one (installer one). @avishayt @filanov @ronniel1 ?

**Comment by filanov** [comment]
Can you please run test-infra to make sure that it works?

**Comment by carbonin** [comment]
> Can you please run test-infra to make sure that it works?
@filanov Just finished a successful run. :+1:

**Comment by carbonin** [comment]
Closing this as it's included in https://github.com/openshift/assisted-service/pull/230

**Pull request closed without merging**
