### PR TITLE
Bug 2006549: Pass CA certificate to the UploadLogsCmd

### PR DESCRIPTION
**Pull request by mkowalski**
# Assisted Pull Request

## Description

This commit fixes a bug causing UploadLogsCmd not pass CA certificate in
case when assisted service runs in the HTTPS mode. This causes any
attempt to upload logs from the agent to the service to fail with the
error

```
x509: certificate signed by unknown authority
```

Closes: [OCPBUGSM-35383](https://issues.redhat.com/browse/OCPBUGSM-35383)

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @carbonin 
/cc @flaper87 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by mkowalski** [comment]
/override ci/prow/e2e-metal-assisted-networking

It fails everywhere.

**Review by flaper87 — APPROVED** [review]
:pizza:

**Pull request merged**
