### PR TITLE
Bug 2081266: Upon modifyin DNS entry in DHCP server - SNO OCP platform does not update resolv.conf

### PR DESCRIPTION
**Pull request by tsorya**
Bug 2068301: Upon modifyin DNS entry in DHCP server - SNO OCP platfor…m does not update resolv.conf

Changing force dns script for sno , now it will recreate resolv.conf
every network manager restart

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [] None

## How was this code tested?

- [] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [] No tests needed

## Assignees

/cc @ori-amizur 
/cc @eranco74 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by tsorya** [comment]
/retitle Bug 2068301: Upon modifyin DNS entry in DHCP server - SNO OCP platform does not update resolv.conf

**Comment by tsorya** [comment]
/retitle Bug 2081266: Upon modifyin DNS entry in DHCP server - SNO OCP platform does not update resolv.conf

**Pull request merged**
