### PR TITLE
CORS-2750: Move to rhel9, decouple from cli image

### PR DESCRIPTION
**Pull request by joepvd**
## List all the issues related to this PR
Move the image to rhel9. To do so, the openshift-clients rpm is installed rather than the oc binary plucked from the cli image. 

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by joepvd** [comment]
/hold
brew is not ready yet to build on rhel9

**Comment by ashwindasr** [comment]
Green build: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2856721

**Comment by zaneb** [comment]
For the e2e-agent-compact-ipv4 build (which has FIPS enabled) to pass, we need the [assisted-service container](https://github.com/openshift/assisted-service/blob/master/Dockerfile.assisted-service.ocp#L18) to also be RHEL9-based.
Of course changing that one first will also fail. Since we can't make the change atomic we'll have to have both PRs ready to go, override the tests, and merge both as close together as possible.

**Comment by joepvd** [comment]
Successful test build with this PR and https://github.com/openshift/assisted-installer/pull/760 and https://github.com/openshift-eng/ocp-build-data/pull/4659:
- [ose-agent-installer-api-server-container-v4.16.0-202404150400.p0.g4f6d88c.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3003105)
- [ose-agent-installer-csr-approver-container-v4.16.0-202404150400.p0.gd8dd7cb.assembly.test.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3003104)

**Comment by zaneb** [comment]
/retitle CORS-2750: Move to rhel9, decouple from cli image

**Comment by joepvd** [comment]
/hold
Needs to go together with https://github.com/openshift/installer/pull/8196

**Comment by zaneb** [comment]
edge-e2e-metal-assisted tests are failing with:

```
[2024-04-30 22:16:51] openshift-tests: /lib64/libc.so.6: version `GLIBC_2.34'\'' not found (required by openshift-tests)
[2024-04-30 22:16:51] openshift-tests: /lib64/libc.so.6: version `GLIBC_2.32'\'' not found (required by openshift-tests)'
```

but it is _not_ due to this PR (other PRs have the same error). Presumably it is caused by https://github.com/openshift/origin/pull/28733

**Comment by zaneb** [comment]
I don't think I can override, but I'll give it a go because this is blocking https://github.com/openshift-eng/ocp-build-data/pull/4659 which is blocking the agent release informing job.
/override ci/prow/edge-e2e-metal-assisted

**Pull request merged**
