### PR TITLE
MGMT-7643: support pre-releases in update_versions

### PR DESCRIPTION
**Pull request by danielerez**
# Assisted Pull Request

## Description

Pre-release OCP 4.9 has been recently added to default_ocp_versions.json.
As the pre-release rhcos images are now available only in a dedicated folder[1],
added support to include pre-releases if no stable yet.

[1] https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

Tested script manually in jenkins job.

## Assignees

/cc @oshercc 
/cc @gamli75 
/cc @YuviGold 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by YuviGold** [comment]
I don't understand. We still would like to update pre-release versions

**Comment by danielerez** [comment]
> I don't understand. We still would like to update pre-release versions

This PR is just for fixing the current logic of skipping pre-release versions.
So are we sure we want to update pre-release versions? that wasn't the behaviour so far for 4.8...

**Comment by gamli75** [comment]
> > I don't understand. We still would like to update pre-release versions
> 
> This PR is just for fixing the current logic of skipping pre-release versions.
> So are we sure we want to update pre-release versions? that wasn't the behaviour so far for 4.8...
> WDYT @gamli75 @oshercc

Yes, we want to update pre-release as well. @YuviGold  Does the API support pre-release versions?

**Comment by YuviGold** [comment]
> > > I don't understand. We still would like to update pre-release versions
> > 
> > 
> > This PR is just for fixing the current logic of skipping pre-release versions.
> > So are we sure we want to update pre-release versions? that wasn't the behaviour so far for 4.8...
> > WDYT @gamli75 @oshercc
> 
> Yes, we want to update pre-release as well. @YuviGold Does the API support pre-release versions?

yes. It's the candidate channel. We can see that fc-1 is already available
```bash
➜  ~ curl https://api.openshift.com/api/upgrades_info/v1/graph\?channel\=candidate-4.9\&arch\=amd64 | jq '[.nodes[]] | max_by(.version)'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2158  100  2158    0     0   3902      0 --:--:-- --:--:-- --:--:--  3902
{
  "version": "4.9.0-fc.1",
  "payload": "quay.io/openshift-release-dev/ocp-release@sha256:e91b987df153df116fd8754c5ae8ba83b8c6769d676f5b01f4028bd4528ab38a",
  "metadata": {
    "io.openshift.upgrades.graph.release.channels": "candidate-4.9",
    "io.openshift.upgrades.graph.release.manifestref": "sha256:e91b987df153df116fd8754c5ae8ba83b8c6769d676f5b01f4028bd4528ab38a"
  }
}
```

**Comment by danielerez** [comment]
Added support for updating pre-releases (e.g. https://github.com/openshift/assisted-service/pull/2581)

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
