### PR TITLE
OCPBUGS-13250: Fix disk name in generated HardwareDetails

### PR DESCRIPTION
**Pull request by zaneb**
Use a disk 'name' that matches the format returned by ironic inspection in Metal³ when setting the HardwareDetails for a BareMetalHost CR generated by the assisted.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by oourfali** [comment]
@zaneb thanks for the fix!
@filanov can you please review?

**Review by avishayt — APPROVED** [review]

**Comment by filanov** [comment]
it's a shame that there are not tests
/cherry-pick release-ocm-2.8

**Comment by filanov** [comment]
it's a shame that there are not tests
/cherry-pick release-ocm-2.8

**Pull request merged**
