### PR TITLE
NO-ISSUE: Pin gocov version

### PR DESCRIPTION
**Pull request by danielerez**
As done in https://github.com/openshift/assisted-service/pull/6900, pinning `github.com/axw/gocov` version to v1.1.0 (thanks @CrystalChun!).
Also, pinning `github.com/AlekSi/gocov-xml` version to v1.1.0 (which was missing from the original PR).
This should resolve the following error:
```
+ go install github.com/AlekSi/gocov-xml@v0.0.0-20190121064608-3a14fb1c4737
go: downloading github.com/AlekSi/gocov-xml v0.0.0-20190121064608-3a14fb1c4737
go: finding module for package github.com/axw/gocov
go: downloading github.com/axw/gocov v1.2.1
go: toolchain upgrade needed to resolve github.com/axw/gocov
go: github.com/axw/gocov@v1.2.1 requires go >= 1.22.0 (running go 1.21.13; GOTOOLCHAIN=local)
```

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by eifrach** [comment]
lgtm, let's also added it to ignored packages so it won't get updated 

```yaml
# .github/dependabot.yml
    groups:
      go-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
      go-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "github.com/axw/gocov/gocov*"
      - dependency-name: "github.com/AlekSi/gocov-xml*"
```

**Comment by gamli75** [comment]
please close https://github.com/openshift/assisted-service/pull/6900 after your fix

**Pull request merged**
