### PR TITLE
NO-ISSUE: rename docker image for postgres 12 as latest tag disappeared

### PR DESCRIPTION
**Pull request by rccrdpccl**
```$ podman pull quay.io/centos7/postgresql-12-centos7:latest
Trying to pull quay.io/centos7/postgresql-12-centos7:latest...
WARN[0001] Failed, retrying in 1s ... (1/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
WARN[0003] Failed, retrying in 1s ... (2/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
WARN[0006] Failed, retrying in 1s ... (3/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
```
```$ podman pull quay.io/sclorg/postgresql-12-c8s:latest
Trying to pull quay.io/sclorg/postgresql-12-c8s:latest...
Getting image source signatures
Copying blob 0c2ad7c16e40 done   |
Copying blob 9516588f908c skipped: already exists
Copying blob e9d33304e2e9 done   |
Copying config 1dc9bf4b68 done   |
Writing manifest to image destination
1dc9bf4b68aee4972b5f39a7f2f3797dfd1a895c1a7c1b50c65d7e095aa6bd4b
```
https://quay.io/repository/centos7/postgresql-12-centos7?tab=tags&tag=latest

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rccrdpccl** [comment]
it looks like the latest tag disappeared

**Review by danmanor — APPROVED** [review]

**Comment by eifrach** [comment]
maybe we should use centos8 which still has builds
`quay.io/sclorg/postgresql-12-c8s:latest`

**Comment by rccrdpccl** [comment]
ztp job won't work until we merge https://github.com/openshift/release/pull/50301

**Comment by rccrdpccl** [comment]
/override edge-e2e-ai-operator-ztp edge-e2e-ai-operator-ztp-capi edge-e2e-ai-operator-disconnected-capi

**Comment by rccrdpccl** [comment]
/override ci/prow/edge-e2e-ai-operator-ztp ci/prow/edge-e2e-ai-operator-ztp-capi ci/prow/edge-e2e-ai-operator-disconnected-capi

**Pull request merged**
