### PR TITLE
MGMT-10780: Explicitly pass OCP version to Hypershift

### PR DESCRIPTION
**Pull request by mkowalski**
In order to control the version of the hosted cluster from the Prow job
definition, we are explicitly passing the `--release-image` to the
`hypershift create` command. This is leveraging the current design that
uses `ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE` to decide what is the
OCP version used in the spoke cluster in the ZTP flow.

Contributes-to: [MGMT-10780](https://issues.redhat.com//browse/MGMT-10780)

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @eranco74 
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by mkowalski** [comment]
Supersedes #3937

**Comment by mkowalski** [comment]
Something in the workload cluster namespace still fails

```
    "name": "kube-apiserver",
    "ready": false,
    "restartCount": 19,
    "started": false,
    "state": {
      "waiting": {
        "message": "back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-6bf8cb59d4-9z58k_assisted-spoke-cluster-assisted-test-cluster(c6a6a965-30d9-4f6f-b82e-2e4f6d4e782b)",
        "reason": "CrashLoopBackOff"
      }
    }

[...]

  {
    "image": "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:759c96686af12dbc2a00d53945e19c3029be08be6922380cc9277321e4ad4160",
    "imageID": "",
    "lastState": {},
    "name": "machine-approver-controller",
    "ready": false,
    "restartCount": 0,
    "started": false,
    "state": {
      "waiting": {
        "reason": "PodInitializing"
      }
    }
  }
```

I do see however that the command includes a correct reference to the release image

```
+ hypershift create cluster agent --name assisted-test-cluster --base-domain redhat.example --pull-secret /root/pull-secret.json --ssh-key /root/.ssh/id_rsa.pub --agent-namespace assisted-spoke-cluster --namespace assisted-spoke-cluster --control-plane-operator-image quay.io/hypershift/hypershift-operator:latest --release-image registry.build02.ci.openshift.org/ci-op-d1jvzzi8/release@sha256:ec92f6a13199a3039e75fea9426267cdf67901292d597ee2c5836850042d2064
```

**Review by javipolo — APPROVED** [review]

**Pull request merged**
