### PR TITLE
Bug 2131017: Fix MinSizeGigabytes root device hint

### PR DESCRIPTION
**Pull request by zaneb**
We should reject disks that are *smaller* than the minimum size.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by CrystalChun** [comment]
Good catch! Highly recommend to add unit tests 👍

**Comment by avishayt** [comment]
Wow nice catch.  It's worrisome that you fixed this without updating any unit tests... Do you mind adding?

**Comment by filanov** [comment]
Please add a test to make sure that it will not happen again?

**Comment by zaneb** [comment]
@CrystalChun @avishayt @filanov Now with unit test.

**Comment by filanov** [comment]
Can you please add a negative test as well?

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Pull request merged**
