### PR TITLE
NO-ISSUE: Fix OKD podman deploy

### PR DESCRIPTION
**Pull request by mlorenzofr**
This PR fixes the deploy of OKD using podman. More info in the issue #6562 

# List all the issues related to this PR
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug fix
- [ ] Tests
- [x] Documentation
- [x] CI/CD

# What environments does this code impact?
- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

# How was this code tested?
- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

# Checklist
- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see CONTRIBUTING guide)
- [ ] This change does not require a documentation update (docstring, docs, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

# Reviewers Checklist
* Are the title and description (in both PR and commit) meaningful and clear?
* Is there a bug required (and linked) for this change?
* Should this PR be backported?

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]
/retitle NO-ISSUE: Fix OKD podman deploy

**Comment by bekiroz** [comment]
I have installed okd version but copy password not working 
image
i tested with firefox and google chrome. 
i tested openshift version then copy password works.

**Pull request merged**
