### PR TITLE
MGMT-8844: Assisted-installer update SNO minimum RAM requirement to 16GB

### PR DESCRIPTION
**Pull request by paul-maidment**
[MGMT-8844](https://issues.redhat.com/browse/MGMT-8844): Assisted-installer update SNO minimum RAM requirement to 16GB

The purpose of this change is to reduce the required amount of memory that we validate for SNO nodes. 
Presently, we expect the node to have 32GB of RAM. The requirement is that we reduce this validation to check that we have a minimum of 16GB RAM.

Summary of change:
The main change was to the file `data/default_hw_requirements.json` changing "sno"."ram_mib" to 16384 MB from 32768MB. Then executing `skipper make generate-config` to generate some of the config automatically.
A search of the code tree highlighted some other ares in which values still needed to be changed. These have been applied in this pull request.

* The `onprem-environment` environment file contains the configuration for Podman deployment.
* `internal/controller/controllers/agentserviceconfig_controller.go` contains the configuration for ZTP (Zero touch provisioning.)
* `config/onprem-iso-fcc.yaml`
* `config/onprem-iso-config.ign`

Various tests have been updated to contain the correct SNO ram_mib value moving forward...
* internal/hardware/validator_test.go
* internal/host/transition_test.go

Documentation and search indexes have been updated as appropriate also
* docs/dev/hardware-requirements.md
* site/dev/hardware-requirements/index.html
* site/search/search_index.json
* deploy/operator/README.md

This pull request will require a test plan before we can move it forward fully.

Passing unit and subsystem tests would be a prerequisite. So this PR has been marked in a "Draft" status to allow those tests to execute.
This change will require us to adjust the CI configuration. A task has been created for this here

https://issues.redhat.com/browse/MGMT-8960

The goal is to update SaaS, podman, ZTP, CI and to cover any QE concerns with an appropriate test plan. It is assumed that this will need to be tested in all of these environments when ready.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [x] Tests
- [x] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [X] assisted-test-infra environment
- [X] dev-scripts environment
- [ ] Reviewer's test appreciated
- [X] Waiting for CI to do a full test run
- [X] Manual (Elaborate on how it was tested)
- [ ] No tests needed

* Ran full unit tests against the code changes in this PR - All passed.
* Ran a full set of subsystem tests against the code changes in this PR
	- Garbage collector test appears to fail intermittently, though this also happens on master.
	
* Need to run a manual check on the preflight requirements in the testing environment. This can be done in the local (minikube based) test environment.

	By performing the following procedure first on upstream master and then on our branch, we can see that the changes are being used to determine preflight-requirements as we expect they should be.

	```
	export SNOClusterID=`curl -X POST \
	-H "Content-Type: application/json" \
	-d '{"name":"testcluster","high_availability_mode":"None","openshift_version":"4.8","pull_secret":"{\"auths\":{\"cloud.openshift.com\":{\"auth\":\"dXNlcjpwYXNzd29yZAo=\",\"email\":\"r@r.com\"}}}","base_dns_domain":"redhat.com"}' \
	http://$INSTALLER_HOST:$SERVICE_PORT/api/assisted-install/v2/clusters |  jq --raw-output '.["id"]'`
	
	curl -s -X GET -H "Content-Type: application/json" http://$INSTALLER_HOST:$SERVICE_PORT/api/assisted-install/v1/clusters/${SNOClusterID}/preflight-requirements | jq '.["ocp"]["master"]["quantitative"]["ram_mib"]'
	
	```
	
	On upstream master, the result of the above will be 32768 whereas the result on our PR will be 16384. This indicates the change was applied sucessfuly, with the output JSON looking similar to below.

	# Observe that the JSON response contains the correct limits.

	```"ocp": {
	    "master": {
	      "qualitative": null,
	      "quantitative": {
		"cpu_cores": 8,
		"disk_size_gb": 120,
		"installation_disk_speed_threshold_ms": 10,
		"ram_mib": 16384
	      }
	    }```

## Assignees

<!--
Please, add one or two reviewers that could help review this PR. Use `/assign` if you want to assign
this PR directly to someone.
-->

## Checklist

- [X] Title and description added to both, commit and PR.
- [X] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [X] Reviewers have been listed
- [X] This change does not require a documentation update (docstring, `docs`, README, etc)
	The upstream documentation in the project has been updated as part of this change.
- [ ] Does this change include unit-tests (note that code changes require unit-tests)
	This is a configuration change and does not have a corresponding unit test.

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-operator-disconnected
(broken)

**Review by osherdp — APPROVED** [review]

**Review by filanov — APPROVED** [review]

**Comment by omertuc** [comment]
/hold Please include the PR description in the commit message
Also please specify the reason for lowering the requirement

**Comment by filanov** [comment]
> /hold Please include the PR description in the commit message Also please specify the reason for lowering the requirement

good catch

**Comment by omertuc** [comment]
Feel free to unhold when you want the PR to merge

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
CI broken. Until resolution I'm holding so we can save resources
check ci channel on slack for when resolution comes

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-operator-disconnected
(broken)

/override ci/prow/e2e-metal-assisted-multi-version
(extremely flaky)

**Pull request merged**
