### PR TITLE
Make get_image_without_tag work when registry has a port

### PR DESCRIPTION
**Pull request by carbonin**
Another try to get the disconnected stuff to work. I promise I'll look more closely at the test results this time :sweat_smile: 

Previously `get_image_without_tag` would return just the registry hostname for an image with a port:

```
$ get_image_without_tag_old 'virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:latest'
virthost.ostest.test.metalkube.org
```

This change makes the function work for all cases:

```
$ get_image_without_tag 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:51ad3c2b7792f2a0c551282b6c0650d8eb80c5cfd5fc912a6b7e79e088ad67e0'
quay.io/openshift-release-dev/ocp-v4.0-art-dev
$ get_image_without_tag 'virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:latest'
virthost.ostest.test.metalkube.org:5000/localimages/local-release-image
$ get_image_without_tag 'quay.io/edge-infrastructure/assisted-service:latest'
quay.io/edge-infrastructure/assisted-service
```

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-11998

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

See examples in description

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
Hopefully this will get the disconnected job in https://github.com/openshift/release/pull/36093 to pass :pray:

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
Even with the mentioned tests being done, let's hold the PR to make sure disconnected job (or maybe other jobs that are optional) passes before merging 
/hold

**Comment by carbonin** [comment]
It will pass either way, I just need to see the registry conf getting created correctly

**Comment by carbonin** [comment]
Oh, but yeah, since this is touching how the other registries get created too we'll definitely need to see it pass.

**Comment by carbonin** [comment]
This looks better to me:

```
[2023-02-27 16:56:54]     [[registry]]
[2023-02-27 16:56:54]       location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
[2023-02-27 16:56:54]       insecure = false
[2023-02-27 16:56:54]       mirror-by-digest-only = true
[2023-02-27 16:56:54] 
[2023-02-27 16:56:54]       [[registry.mirror]]
[2023-02-27 16:56:54]         location = "virthost.ostest.test.metalkube.org:5000/localimages/local-release-image"
```

**Comment by carbonin** [comment]
Disconnected succeeded and the registries.conf looked like I wanted it to.

/unhold

**Pull request merged**
