### PR TITLE
MGMT-12368: Verify that Kernel Arguments API does not change in the future

### PR DESCRIPTION
**Pull request by ori-amizur**
Since Coreos Installer supports [append, replace, delete] operations on kernel arguments,  this API is modified accordingly.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

/cc @carbonin 
/cc @avishayt

### CODE REVIEW

**Comment by carbonin** [comment]
Should we have an explicit reset operation? It's hard to understand that passing an empty list of args is the intended way to do that.

**Comment by ori-amizur** [comment]
> Should we have an explicit reset operation? It's hard to understand that passing an empty list of args is the intended way to do that.

I think reset is meaningless since we are not editing and saving ISO.  The ISO is always in its default state.  We are modifying and streaming it without saving.

**Comment by carbonin** [comment]
> I think reset is meaningless since we are not editing and saving ISO. The ISO is always in its default state. We are modifying and streaming it without saving.

I'm aware of this, but we do need a way for users to clear the value from the DB. I'm wondering if an update with an empty list is enough or if we should consider something more explicit? I'm just trying to ensure we get this right this time and don't have to change the API again.

Curious what @avishayt thinks.

**Comment by avishayt** [comment]
Thanks for this PR.  Let's think about usability.  A few questions since I don't have time right now to try it out:
1. Do we know what the default kernel arguments are at this point, or is that knowledge only in the image service?
2. Why does the "replace" action exist as opposed to using "delete" and "append"?
3. To confirm my understanding - "delete" would be used only for removing a default kernel arg, "replace" would be used for changing the value of default kernel arg, and "append" would be for adding new args.  Correct?

**Comment by ori-amizur** [comment]
> Do we know what the default kernel arguments are at this point, or is that knowledge only in the image service?

Even the image service is not aware of the kernel arguments, although it is possible to query them.  In addition, these arguments may vary between different ISO files.

> Why does the "replace" action exist as opposed to using "delete" and "append"?

That's Coreos Installer terminology

> To confirm my understanding - "delete" would be used only for removing a default kernel arg, "replace" would be used for changing the value of default kernel arg, and "append" would be for adding new args. Correct?

Yes

**Review by avishayt — APPROVED** [review]
I'm OK with this API, thanks for the change

**Pull request merged**
