### PR TITLE
MGMT-18130: Allow infra-operator to start in non OCP kubernetes clusters

### PR DESCRIPTION
**Pull request by carbonin**
Only watch the OCP-specific kinds from our operator when it is running in an OpenShift cluster.

This doesn't address the rest of the runtime issues, but allows the operator to start in non-OCP kubernetes clusters.

## List all the issues related to this PR

Resolves https://issues.redhat.com/browse/MGMT-18130

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

Deployed the operator manually to a kind cluster without error.

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by CrystalChun** [comment]
Looks good! Looks like a `make lint` and ignore error needs to be added based on the lint CI job

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Comment by carbonin** [comment]
/hold

Going to switch the CRD detection to use the same method we use for BMH: https://github.com/openshift/assisted-service/blob/e19be01334a7662ab99b153874d3ff0867e14192/cmd/main.go#L904-L913

**Comment by carbonin** [comment]
>Going to switch the CRD detection to use the same method we use for BMH:

After some thought, I think I'm going to leave it the way it is.
1. It's easier to test this way with a simple fake client
2. The difference between when there was an error detecting if the CRD is present and when it is not present is more clear with this method

**Pull request merged**
