### PR TITLE
MGMT-17826: Terminate reconcile early if ManagedCluster CRD not present 

### PR DESCRIPTION
**Pull request by paul-maidment**
When the ManagedCluster CRD is not present during installation of the infrastructure operator, a failure is encountered

```
"failed to get API group resources: unable to retrieve the complete list of server APIs: cluster.open-cluster-management.io/v1: the server could not find the requested resource"
```

This results in a non functional operator.

This PR aims to address that by ensuring that we do not complete the reconcile loop (and therefore perfom the check for the presence of a ManagedCluster CR) if the CRD is not present.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by carbonin — COMMENTED** [review]
Does this work? I'd expect this to fail when we set up our watches as well.

**Comment by paul-maidment** [comment]
As per our discussion and some further testing.
It's more beneficial to us to leave things the way they are.
I'm going to close this PR as per that discussion.

**Comment by paul-maidment** [comment]
Re-opening as I have discovered that the infrastructure operator will not function correctly unless we handle this issue.

**Comment by carbonin** [comment]
>as I have discovered that the infrastructure operator will not function correctly unless we handle this issue

Can you elaborate a bit more? Ideally we'd have the failing behavior explained in the bug and also here in more detail.

**Comment by carbonin** [comment]
While I think we should consider this, I'm still split.

All customers would install the operator through MCE and thus would definitely have ManagedCluster, but we also publish our operator in the community operators catalog to install standalone. This change would break that workflow.

That said, we do the same thing for BMH and treating the two resources the same would make sense. But on the other hand booting using a BMH is a much more common use case than managing the local cluster with assisted.

@avishayt what do you think?

**Comment by paul-maidment** [comment]
> > as I have discovered that the infrastructure operator will not function correctly unless we handle this issue
> 
> Can you elaborate a bit more? Ideally we'd have the failing behavior explained in the bug and also here in more detail.

It is effectively a crash as soon as a watch is attempted on Managed cluster.

So in a way it is very similar to the behaviour I have placed in this PR, with the exception that the code in this PR makes it very clear why the error occurs.

**Comment by paul-maidment** [comment]
> While I think we should consider this, I'm still split.
> 
> All customers would install the operator through MCE and thus would definitely have ManagedCluster, but we also publish our operator in the community operators catalog to install standalone. This change would break that workflow.
> 
> That said, we do the same thing for BMH and treating the two resources the same would make sense. But on the other hand booting using a BMH is a much more common use case than managing the local cluster with assisted.
> 
> @avishayt what do you think?

I think my original proposal to terminate the LocalClusterImportController reconcile loop early in the case of Managed cluster CRD not present is reasonable.

It prevents a hard crash while allowing the rest of the operator to be functional.

After creation of the Managed cluster CRD. The operator is able to start (though the user will need to force a reconcile)

**Pull request closed without merging**
