### PR TITLE
MGMT-12024: Revert "Use NMState GenerateConfiguration Go binding (#3870)"

### PR DESCRIPTION
**Pull request by nmagnezi**
This reverts commit 151f68b08d2f0e9111bc5115ba88482e675997a0.
```
Conflicts:
	Dockerfile.assisted-service
	Dockerfile.assisted-service-build
	Dockerfile.assisted-service.ocp
	go.mod
	go.sum
	vendor/modules.txt
```

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
/hold
testing in CI

**Comment by carbonin** [comment]
Why are we reverting this?

While I think I know some of the story, it's important to add the reasoning to the commit and PR.

**Comment by vrutkovs** [comment]
Its in the linked ticket - it breaks ART build, we'd need to revert until they fix it

**Pull request merged**
