### PR TITLE
Remove redundant files for bumping OCP versions

### PR DESCRIPTION
**Pull request by osherdp**
# Assisted Pull Request

## Description

Now that we have the ocp-bumping mechanism implemented in [prow](https://prow.ci.openshift.org/?job=*bump-ocp*) (and in [assisted-installer-deployment](https://github.com/openshift-assisted/assisted-installer-deployment/blob/master/tools/bump_ocp_releases.py) repo), we can remove the old code and configuration.

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @eliorerz 
/cc @danielerez 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
/test e2e-metal-assisted-kube-api
Seems like infra problem

**Comment by danielerez** [comment]
nice!
@osherdp so what would be the process for testing new code in the bump tool?
I.e. could we temporarily modify the prow job to check new behaviour?

**Comment by osherdp** [comment]
> nice!
> @osherdp so what would be the process for testing new code in the bump tool?
> I.e. could we temporarily modify the prow job to check new behaviour?

Every time you change the script, if should run it in dry-run mode so that you can inspect the output (and more specifically the git diff)

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by danielerez** [comment]
> > nice!
> > @osherdp so what would be the process for testing new code in the bump tool?
> > I.e. could we temporarily modify the prow job to check new behaviour?
> 
> Every time you change the script, if should run it in dry-run mode so that you can inspect the output (and more specifically the git diff)

ok, so we should probably just need to  ensure that dry run is no longer limited in behaviour (besides actually sending a PR).
then maybe we can have another flag here to avoid the long process of rhcos download: https://github.com/openshift-assisted/assisted-installer-deployment/blob/c23e1da77fecb55883ef80652674d2f47366749b/tools/bump_ocp_releases.py#L312
can be handled later on though.
/lgtm

**Comment by osherdp** [comment]
> > > nice!
> > > @osherdp so what would be the process for testing new code in the bump tool?
> > > I.e. could we temporarily modify the prow job to check new behaviour?
> > 
> > 
> > Every time you change the script, if should run it in dry-run mode so that you can inspect the output (and more specifically the git diff)
> 
> ok, so we should probably just need to ensure that dry run is no longer limited in behaviour (besides actually sending a PR). then maybe we can have another flag here to avoid the long process of rhcos download: https://github.com/openshift-assisted/assisted-installer-deployment/blob/c23e1da77fecb55883ef80652674d2f47366749b/tools/bump_ocp_releases.py#L312 can be handled later on though. /lgtm

Sounds like a great plan 👍

**Pull request merged**
