### PR TITLE
MGMT-3740, Bump OCP version from 4.6.8 to 4.6.12 (auto created)

### PR DESCRIPTION
**Pull request by ronniel1**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by YuviGold** [comment]
```
time="2021-01-24T01:43:48Z" level=fatal msg="Failed to extract and upload file initrd.img from ISO" func=github.com/openshift/assisted-service/pkg/s3wrapper.ExtractBootFilesFromISOAndUpload file="/go/src/github.com/openshift/origin/pkg/s3wrapper/util.go:55" error="Failed to read file /images/pxeboot/initrd.img from ISO: Unknown filesystem on partition 0" go-id=332 request_id=
```
Could this file be missing? @avishayt

**Comment by romfreiman** [comment]
@danielerez

**Comment by YuviGold** [comment]
@oshercc  RHCOS image is incorrect. There is no
`https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.12/rhcos-4.6.12-x86_64-live.x86_64.iso` image.

**Comment by romfreiman** [comment]
of course not. How did we come to such conclusion?

**Comment by oshercc** [comment]
im checking

**Pull request closed without merging**
