### PR TITLE
MGMT-2989 increase timeout of writing to disk from 10 minutes to 30 m…

### PR DESCRIPTION
**Pull request by ronniel1**
…inutes

### CODE REVIEW

**Comment by avishayt** [comment]
/hold

We reset the timeout every time we have a progress update since MGMT-2270 - it should be 10 minutes for every 5%.  Why are we failing here?

**Comment by ronniel1** [comment]
> /hold
> 
> We reset the timeout every time we have a progress update since [MGMT-2270](https://issues.redhat.com/browse/MGMT-2270) - it should be 10 minutes for every 5%. Why are we failing here?

@avishayt see my reply in the ticket

**Review by eranco74 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
