### PR TITLE
NO-ISSUE: corrects image reference in pod definition

### PR DESCRIPTION
**Pull request by mhrivnak**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Review by filanov — APPROVED** [review]

**Comment by osherdp** [comment]
> /test e2e-metal-assisted-onprem

/hold
(otherwise, PR merging will not wait for job completion)

**Review by flaper87 — APPROVED** [review]

**Comment by mhrivnak** [comment]
This download from github timed out in the test setup. :thinking: `curl -L --retry 5 https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.3.0/kustomize_v4.3.0_linux_amd64.tar.gz`

**Comment by osherdp** [comment]
/hold
``e2e-metal-assisted`` job seems broken. investigating

**Comment by osherdp** [comment]
for more info: https://coreos.slack.com/archives/C014N2VLTQE/p1643182963205200

**Pull request merged**
