### PR TITLE
Revert "MGMT-2765 Run a subet of subsystem tests for onprem in Jenkin…

### PR DESCRIPTION
**Pull request by oshercc**
This reverts commit df6fc7a9e07366aec892579bf807a9c5d2bc762e.

this commit causes the CI to be flaky. reverting for now until stabilizes 
FYI @rwsu @YuviGold @ronniel1

### CODE REVIEW

**Comment by rwsu** [comment]
Stability has improved after adding retries with this PR: https://github.com/openshift/assisted-service/pull/742

I think this can be closed unless you think revert still needed.

**Comment by YuviGold** [comment]
Not relevant anymore.
/close

**Pull request closed without merging**
