### PR TITLE
MGMT-7356: Bump OCP versions 4.8.0-rc.3 -> 4.8.2

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.8 release notes: https://access.redhat.com/errata/RHSA-2021:2438

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by YuviGold** [comment]
/lgtm

Till all tests pass
/hold

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
