### PR TITLE
MGMT-2254 Migrate Grafana dashboards to assisted-service codebase

### PR DESCRIPTION
**Pull request by nmagnezi**
Starting with assisted-installer-vendor-phases

### CODE REVIEW

**Comment by oshercc** [comment]
LGTM

**Comment by filanov** [comment]
Where is it used?

**Comment by nmagnezi** [comment]
> Where is it used?

In APP-SRE Grafana.
They ask all application to host their own dashboard code, and add references in their code base (GitHub URL + git sha)

**Review by filanov — APPROVED** [review]

**Comment by oshercc** [comment]
@filanov this is pulled to the sre Grafana dashboard, until now the dashboard configuration is saved on the app-sre git-lab 
we think the correct location to save it is here. 
if you want to see how the dashboard looks like it is available [here](http://f13-h26-b04-5039ms.rdu2.scalelab.redhat.com:3000/d/iRPhv9KMz/vendor-average-phases-duration?orgId=1)

**Pull request merged**
