### PR TITLE
MGMT-4144 FIO visualize to resource dashboard

### PR DESCRIPTION
**Pull request by oshercc**
adding a histegram visualize for FIO from service_assisted_installer_cluster_host_disk_sync_duration_ms 

query:
```sum(service_assisted_installer_cluster_host_disk_sync_duration_ms_bucket) by (le)```
fio

### CODE REVIEW

**Comment by oshercc** [comment]
@nmagnezi @derez

**Comment by oshercc** [comment]
@ronniel1

**Comment by ronniel1** [comment]
I think we need to get these metrics related to installation success/failures.
We need this to understand what is the threshold we should use in order to fail FIO validations

**Comment by oshercc** [comment]
> I think we need to get these metrics related to installation success/failures.
> We need this to understand what is the threshold we should use in order to fail FIO validations

I am not sure we can correlate by the information given by this metric if the FIO & the fail reason.

**Review by nmagnezi — COMMENTED** [review]
did you validate those numbers against the result with using histogram_quantile?

https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile

**Review by nmagnezi — COMMENTED** [review]
> I think we need to get these metrics related to installation success/failures.
> We need this to understand what is the threshold we should use in order to fail FIO validations

@ronniel1, even if we'll make a query that correlates between FIO and clusters with install result = error, we'll have no metric or label that directly specifies the reason for failure.

**Comment by flaper87** [comment]
/close

Closing for inactivity. Reopen when ready to update/merge

**Pull request closed without merging**
