### PR TITLE
Wording fixes and tweaks

### PR DESCRIPTION
**Pull request by andybraren**
A variety of spelling, capitalization, and grammatical fixes and tweaks for `swagger.yaml` and `validator.go`, some of which appear in the Assisted Installer GUI. Related to [PD-578](https://issues.redhat.com/browse/PD-578). FYI @jtomasek @mareklibra @nirfarkas.

I haven't done many API reviews before, so comments/corrections welcome!

Most common changes:
- Adding periods to the end of `description` and `summary` definitions
- Capitalizing proper nouns, which is what we do in the GUI (aligned with [PatternFly](https://www.patternfly.org/v4/design-guidelines/content/capitalization))
- Expanding some acronyms like VIP to Virtual IP, which might be a little more familiar

I also wonder if we should hide the Machine Network CIDR validation in the GUI since we don't expose it there and we already have validations for the API & Ingress VIPs. WDYT @jtomasek?

Here's where those validations appear (not including this PR's updated wording):

image

### CODE REVIEW

**Comment by YuviGold** [comment]
@andybraren The Jenkins job failed.
You need to fix the testing as well, there are places where we check for the exact events strings.

/cc @avishayt have a look

BTW, Can the error window be structured as a bulleted list instead of a textbox?

**Comment by avishayt** [comment]
Looks great, thanks Andy!  Please let me know if you need help getting the tests to pass.

**Comment by andybraren** [comment]
I think I fixed the validators, but I'm not sure what to do to make Jenkins happy with me @avishayt. 🙂

And good idea @YuviGold, a bulleted list would make the inline alert easier to read. WDYT @mareklibra?

**Comment by mareklibra** [comment]
Recent state:


With bullets:


@andybraren Bullets are easier to read. I am not sure about spacing on the left side, should the bullets be aligned with the word "Cluster" above?

**Comment by YuviGold** [comment]
@andybraren You just need to fix the expected strings of these two tests because they verify the returned events strings :)
```bash
[2020-09-17T09:15:38.109Z] • Failure [0.230 seconds]
[2020-09-17T09:15:38.109Z] Refresh Cluster - With DHCP
[2020-09-17T09:15:38.109Z] /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:997
[2020-09-17T09:15:38.109Z]   All transitions
[2020-09-17T09:15:38.109Z]   /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:1029
[2020-09-17T09:15:38.109Z]     ready to dhcp timeout - api vip not defined [It]
[2020-09-17T09:15:38.109Z]     /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:1383
[2020-09-17T09:15:38.109Z] 
[2020-09-17T09:15:38.109Z]     Expected
[2020-09-17T09:15:38.109Z]         <string>: API Virtual IP is undefined; IP allocation from the DHCP server timed out
[2020-09-17T09:15:38.109Z]     to match regular expression
[2020-09-17T09:15:38.109Z]         <string>: API VIP IP allocation from DHCP server has been timed out
[2020-09-17T09:15:38.109Z] 
[2020-09-17T09:15:38.109Z]     /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:319
[2020-09-17T09:15:38.109Z] ------------------------------
[2020-09-17T09:15:38.109Z] • Failure [0.233 seconds]
[2020-09-17T09:15:38.109Z] Refresh Cluster - With DHCP
[2020-09-17T09:15:38.109Z] /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:997
[2020-09-17T09:15:38.109Z]   All transitions
[2020-09-17T09:15:38.109Z]   /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:1029
[2020-09-17T09:15:38.109Z]     ready to insufficient - api vip not defined [It]
[2020-09-17T09:15:38.109Z]     /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:1383
[2020-09-17T09:15:38.109Z] 
[2020-09-17T09:15:38.109Z]     Expected
[2020-09-17T09:15:38.109Z]         <string>: API Virtual IP is undefined; after the Machine Network CIDR has been defined, the API Virtual IP is received from a DHCP lease allocation task which may take up to 2 minutes
[2020-09-17T09:15:38.109Z]     to match regular expression
[2020-09-17T09:15:38.109Z]         <string>: after the machine network CIDR has been defined, the API VIP is received from DHCP lease allocation task which may take up to 2 minutes
[2020-09-17T09:15:38.109Z] 
[2020-09-17T09:15:38.109Z]     /home/workspace/assisted-service_PR-351/internal/cluster/transition_test.go:319
```

@mareklibra  The bulleted list looks much better!

**Comment by andybraren** [comment]
@YuviGold Thank you, it looks like Prow is passing now!

@mareklibra I think they should be aligned with "Cluster," but that's something I'd expect the PatternFly component/s to support natively without any custom CSS. Placing a [Text](https://www.patternfly.org/v4/components/text/react) component within an alert seems to add too much padding though (seen below). Am I doing it wrong? 🙂

If not, maybe we should ask about it in the [PatternFly Slack](https://patternfly.slack.com/) or [file an issue](https://github.com/patternfly/patternfly) next week.

image

**Review by YuviGold — APPROVED** [review]

**Comment by andybraren** [comment]
@YuviGold I've rebased this and I think the build bots are mostly happy. 🙂 Let me know if there's anything more I need to do on my end.

**Comment by YuviGold** [comment]
> @YuviGold I've rebased this and I think the build bots are mostly happy.  Let me know if there's anything more I need to do on my end.

@andybraren Unfortunately the messages need to be changed under a new test case `NTP refresh cluster` :(
http://assisted-jenkins.lab.eng.tlv2.redhat.com/blue/organizations/jenkins/assisted-service/detail/PR-351/27/pipeline/

**Comment by andybraren** [comment]
@YuviGold Fixed, how about now? 🤞

**Pull request merged**
