### PR TITLE
NO-ISSUE: Generate /models/vendor directory correctly

### PR DESCRIPTION
**Pull request by carbonin**
These should have been updated previously, but were missed it seems.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @danielerez 
/cc @nmagnezi 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Comment by nmagnezi** [comment]
> /lgtm

@carbonin I approved it. But please open a Jira ticket for CI to catch such issues in the future.
CC: @osherdp , @filanov

**Comment by carbonin** [comment]
Looking into it a bit more deeply (I just wanted to get these out of my local branch diff).

It seems like I get these files when I do `skipper make generate-vendor` but not when I use `skipper make generate`.
Trying to figure out why/how now.

**Comment by carbonin** [comment]
So it turns out our "fix" for generating swagger to remove all the `Dot` or `Dash` instances in `/models` is also editing all the files in the vendor directory. Some dependency was legitimately using `Dot` and `Dash` in their constants and we were editing their source.

In this PR I'm going to limit the depth of the find, but I'm also going to open a JIRA to remove the hack for editing the generated models. Ideally we should make the generate work correctly in some way.

cc @ori-amizur looks like this was originally added in ca65aa3a0e71526bc94731de6a26e79c694a725b

**Review by osherdp — APPROVED** [review]

**Comment by carbonin** [comment]
Opened https://issues.redhat.com/browse/MGMT-10839 to handle removing the need for the `--remove-dots-and-dashes` target.

**Pull request merged**
