### PR TITLE
NO-ISSUE: Move 4.8 support_level from beta to production

### PR DESCRIPTION
**Pull request by oshercc**
@romfreiman @gamli75

### CODE REVIEW

**Comment by gamli75** [comment]
@oshercc please move the default:true from 4.7 to 4.8 - see https://github.com/openshift/assisted-service/blob/master/data/default_ocp_versions.json#L19

**Comment by gamli75** [comment]
/hold

hold until we will change the default flag as well

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
