### PR TITLE
MGMT-5999 Add a flag to enable day2 in kubeapi

### PR DESCRIPTION
**Pull request by rollandf**
Add a flag to disable by default the automatic creation of Day2 cluster in KubeApi.

Signed-off-by: Fred Rolland <frolland@redhat.com>

### CODE REVIEW

**Comment by rollandf** [comment]
/hold
Need support day2 in subsystem

**Review by nmagnezi — COMMENTED** [review]
Maybe add an info log saying that day2 is switched on  / off when assisted-service starts (if kubeAPI is enabled)?

**Comment by rollandf** [comment]
> Maybe add an info log saying that day2 is switched on / off when assisted-service starts (if kubeAPI is enabled)?

We usually don't print the options in the log.

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Pull request merged**
