### PR TITLE
MGMT-7777: Bump OCP versions rchos 4.9.0-fc.0 -> 4.9.0-rc.0, 4.8.9 -> 4.8.10, 4.9.0-fc.0 -> 4.9.0-rc.0

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @YuviGold
4.8 release notes: https://access.redhat.com/errata/RHBA-2021:3299
4.9 has no available release notes

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Comment by YuviGold** [comment]
@danielerez why does the title mentions 4.9.0 twice?

**Comment by danielerez** [comment]
> @danielerez why does the title mentions 4.9.0 twice?

1st for rhcos update, 2nd for release update.
Tried to improve title in https://github.com/openshift/assisted-service/pull/2559

**Comment by YuviGold** [comment]
mirror.openshift.com network issue?
```
NAME                                           READY   STATUS             RESTARTS   AGE
pod/assisted-image-service-8658f7c6d4-wwpgh    0/1     ImagePullBackOff   0          27m
pod/assisted-service-54c4c8f55b-tdb7d          1/2     CrashLoopBackOff   9          27m
pod/infrastructure-operator-7f44b487fd-nkg47   1/1     Running            0          27m


time="2021-09-09T13:59:01Z" level=fatal msg="Failed to upload boot files" func=main.main.func1 file="/go/src/github.com/openshift/origin/cmd/main.go:192" error="Failed uploading boot files for OCP version 4.8 CPU architecture x86_64: Failed fetching from URL https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso: Get \"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso\": dial tcp 54.172.163.83:443: connect: network is unreachable"
```

/retest

**Comment by YuviGold** [comment]
```
time="2021-09-10T17:20:41Z" level=fatal msg="Failed to upload boot files" func=main.main.func1 file="/go/src/github.com/openshift/origin/cmd/main.go:192" error="Failed uploading boot files for OCP version 4.8 CPU architecture x86_64: Failed fetching from URL https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso: Get \"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso\": dial tcp 54.173.18.88:443: connect: network is unreachable"
```
@danielerez @osherdp  When there are multiple images (4.8, 4.9) it seems like the mirroring doesn't work well


It should be resolved but not mandatory to block this bump.
/lgtm

**Comment by osherdp** [comment]
@YuviGold Why do we run ztp-disconnected job on version bumps?

**Comment by YuviGold** [comment]
> @YuviGold Why do we run ztp-disconnected job on version bumps?

@osherdp we want to run all the jobs to verify that nothing is getting broken due to the bumping.

**Comment by osherdp** [comment]
> > @YuviGold Why do we run ztp-disconnected job on version bumps?
> 
> @osherdp we want to run all the jobs to verify that nothing is getting broken due to the bumping.

But do we use those versions of those files in ztp job? I thought we use 4.9 on periodics and candidate 4.8 on presubmits

I thought this bump mainly related to the SaaS product

**Pull request merged**
