### PR TITLE
Added doc on how to boot discovery image on AWS EC2

### PR DESCRIPTION
**Pull request by mvazquezc**
# Assisted Pull Request

## Description

Document how to boot a discovery image on AWS EC2, this is a recurring question from people doing tests on EC2.

- Should this PR be tested by the reviewer? - Not really
- Is this PR relying on CI for an e2e test run? - No
- Should this PR be tested in a specific environment? - No
- Any logs, screenshots, etc that can help with the review process? - No

## List all the issues related to this PR

- [ ] New Feature
- [ ] Bug fix
- [ ] Tests
- [x] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @romfreiman 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [x] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by filanov** [comment]
Maybe it should be under `docs/user-guide`? 
Need to change the commit and title to `NO-ISSUE: Added doc on how to boot discovery image on AWS EC2`

**Comment by mvazquezc** [comment]
> Maybe it should be under `docs/user-guide`? Need to change the commit and title to `NO-ISSUE: Added doc on how to boot discovery image on AWS EC2`

Hey @filanov changed commit message and moved the doc to user-guide folder.

Thanks

**Comment by filanov** [comment]
Are there any steps after that? changing boot order or something like that? or the installation will work as expected?

**Comment by mvazquezc** [comment]
The installation will work as expected. Instance will boot from the discovery image that will run coreos-installer and write rhcos to the disk where CentOS 8 was installed, next boot instead of centos rhcos will be booted.

**Review by filanov — APPROVED** [review]

**Pull request merged**
