### PR TITLE
[release-ocm-2.7] OCPBUGS-15152: Don't require key encipherment usage for approving CSRs

### PR DESCRIPTION
**Pull request by carbonin**
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/5322

### CODE REVIEW

**Comment by eranco74** [comment]
/hold
Let's re-run the capi test.
The test failed because the ingress-opreator pod (of the hosted control plane) wasn't ready:
```
[2023-07-06 20:06:09]     "name": "ingress-operator",
[2023-07-06 20:06:09]     "ready": false,
```
But from the pod yaml it seems that it was ready :confused: 
 
 https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/5341/pull-ci-openshift-assisted-service-release-ocm-2.7-e2e-ai-operator-ztp-capi/1677018019882078208/artifacts/e2e-ai-operator-ztp-capi/assisted-baremetal-operator-gather/artifacts/capi/assisted-spoke-cluster-assisted-test-cluster/pods_ingress-operator-578c9bb576-fhg8z.yaml
 
 /test e2e-ai-operator-ztp-capi

**Review by filanov — APPROVED** [review]

**Comment by carbonin** [comment]
The CAPI test failure is due to a known issue in hypershift which should be fixed by https://github.com/openshift/hypershift/pull/2787, but since our CI is using hypershift 4.12, we'll need that backported before the job will be fixed.

I think it's safe to skip this test in this case, but I'll let @filanov make the call on that.

**Pull request merged**
