### PR TITLE
Add registry config for ironic agent image

### PR DESCRIPTION
**Pull request by carbonin**
When using the converged ZTP flow in a disconnected environment we need to ensure that the agent gets registry configuration for both the in-prow image repos as well as the internal images which will still likely be using quay.io

Specifically this is a problem for the ironic agent image which previously couldn't be pulled by the host during discovery despite being mirrored properly by dev-scripts.

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-11998

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

Will be tested as a part of https://github.com/openshift/release/pull/36093

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
Putting hold on until I see the registries.conf changes in the disconnected job

**Review by adriengentil — APPROVED** [review]

**Review by adriengentil — APPROVED** [review]

**Comment by carbonin** [comment]
Much better:
```
[2023-02-21 18:54:49] +++ oc adm release info --image-for=ironic-agent registry.build05.ci.openshift.org/ci-op-cnss2vhi/release@sha256:0fe11cd7d1434733a3fdbbb1f127acef899cf00cef71ddad3f13272c425c54ca
[2023-02-21 18:54:49] ++ ironic_agent_image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:51ad3c2b7792f2a0c551282b6c0650d8eb80c5cfd5fc912a6b7e79e088ad67e0

...

[2023-02-21 18:54:50]   registries.conf: |
[2023-02-21 18:54:50]     unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
[2023-02-21 18:54:50] 
[2023-02-21 18:54:50]     
[2023-02-21 18:54:50]     [[registry]]
[2023-02-21 18:54:50]       location = "registry.build05.ci.openshift.org/ci-op-cnss2vhi/release"
[2023-02-21 18:54:50]       insecure = false
[2023-02-21 18:54:50]       mirror-by-digest-only = true
[2023-02-21 18:54:50] 
[2023-02-21 18:54:50]       [[registry.mirror]]
[2023-02-21 18:54:50]         location = "virthost.ostest.test.metalkube.org:5000/ci-op-cnss2vhi/release"
[2023-02-21 18:54:50]   
[2023-02-21 18:54:50]     
[2023-02-21 18:54:50]     [[registry]]
[2023-02-21 18:54:50]       location = "registry.build05.ci.openshift.org/ci-op-cnss2vhi/stable-stable-4-10"
[2023-02-21 18:54:50]       insecure = false
[2023-02-21 18:54:50]       mirror-by-digest-only = true
[2023-02-21 18:54:50] 
[2023-02-21 18:54:50]       [[registry.mirror]]
[2023-02-21 18:54:50]         location = "virthost.ostest.test.metalkube.org:5000/ci-op-cnss2vhi/release"
[2023-02-21 18:54:50]   
[2023-02-21 18:54:50]     
[2023-02-21 18:54:50]     [[registry]]
[2023-02-21 18:54:50]       location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
[2023-02-21 18:54:50]       insecure = false
[2023-02-21 18:54:50]       mirror-by-digest-only = true
[2023-02-21 18:54:50] 
[2023-02-21 18:54:50]       [[registry.mirror]]
[2023-02-21 18:54:50]         location = "virthost.ostest.test.metalkube.org:5000/ci-op-cnss2vhi/release"
[2023-02-21 18:54:50]   
[2023-02-21 18:54:50]     
[2023-02-21 18:54:50]     [[registry]]
[2023-02-21 18:54:50]       location = "registry.build05.ci.openshift.org/ci-op-cnss2vhi/pipeline"
[2023-02-21 18:54:50]       insecure = false
[2023-02-21 18:54:50]       mirror-by-digest-only = true
[2023-02-21 18:54:50] 
[2023-02-21 18:54:50]       [[registry.mirror]]
[2023-02-21 18:54:50]         location = "virthost.ostest.test.metalkube.org:5000/olm/ci-op-cnss2vhi-pipeline"
```

**Pull request merged**
