### PR TITLE
MGMT-12312: Adds node-boot log type

### PR DESCRIPTION
**Pull request by nmagnezi**
Per https://github.com/openshift/assisted-service/pull/4444, add a new log type named: `node-boot`.

This change updates both `V2UploadLogs` and `V2DownloadClusterLogs` to accept the new log type.
In addition:
1. A new event was added: `host_boot_logs_uploaded`.
2. Defined download name: `<cluster_name>_<host_role>_boot_<host_id>.tar.gz`.
3. Note that `V2UploadLogs` with log type `node-boot` will not update the host progress.

## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
this is WIP

**Comment by carbonin** [comment]
Looks like there's still quite a few questions in the enhancement.
The code looks good though. I'm curious about "boot logs" as a name though since we boot the host at least twice.

Maybe we need a more specific name since we're putting it in a user-facing event.
Maybe just saying `node boot` rather than `host` would be better?
Something like `post install boot logs` might work but is a bit confusing because we're done installing coreos, but the node isn't quite done yet.

@avishayt what do you think?

**Comment by avishayt** [comment]
Agree with @carbonin .  node-boot-logs is better than host-boot-logs, maybe boot-from-disk-logs is more explicit?

**Comment by nmagnezi** [comment]
> Agree with @carbonin . node-boot-logs is better than host-boot-logs, maybe boot-from-disk-logs is more explicit?

@carbonin, @avishayt,
I changed the log name to `node-boot`

**Comment by avishayt** [comment]
> 

Excellent,  thanks

**Pull request merged**
