### PR TITLE
MGMT-4020, Bump OCP version from 4.6.12 to 4.6.16 (auto created)

### PR DESCRIPTION
**Pull request by oshercc**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by oshercc** [comment]
test-infra test failed, HOLD label is set, see http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/4523/

**Comment by oshercc** [comment]
@gamli75 there is an issue in the script when testing test-infra. 
the label needs to be removed manually when/if the test-infra test passes

**Comment by gamli75** [comment]
Need to sync

**Pull request closed without merging**
