### PR TITLE
NO-ISSUE generate-from-swagger should regenerate KUBE_API manifests

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by YuviGold** [comment]
generate-from-swagger shouldn't take care about manifests. At least from the name.
IMO we should split all the generations targets (swagger, manifests, onprem yamls, mocks, keys, etc) into scripts and just have 1 target of `generate` that will call them all. Otherwise, someone might forget to use one of them.

**Comment by filanov** [comment]
> generate-from-swagger shouldn't take care about manifests. At least from the name.
> IMO we should split all the generations targets (swagger, manifests, onprem yamls, mocks, keys, etc) into scripts and just have 1 target of `generate` that will call them all. Otherwise, someone might forget to use one of them.

You don't always want to generate everything, this is why you have the makefile for.
Regarding this change, we got into a situation that changes in swagger break something in kube-api, and this is a way to prevent it.

**Comment by YuviGold** [comment]
> > generate-from-swagger shouldn't take care about manifests. At least from the name.
> > IMO we should split all the generations targets (swagger, manifests, onprem yamls, mocks, keys, etc) into scripts and just have 1 target of `generate` that will call them all. Otherwise, someone might forget to use one of them.
> 
> You don't always want to generate everything, this is why you have the makefile for.
> Regarding this change, we got into a situation that changes in swagger break something in kube-api, and this is a way to prevent it.

In most cases, you want to generate everything. Especially when this type of new generation is being added and most of the contributors aren't aware of.
Once in a while, you want to check some features, so you will be able to call explicitly that matching script.

**Comment by nmagnezi** [comment]
>  Once in a while, you want to check some features, so you will be able to call explicitly that matching script.

So why not keep the granularity we already have, and have `generate-all` endpoint to all type of generate endpoints?

**Review by nmagnezi — COMMENTED** [review]
/test assisted-service-aws

**Comment by YuviGold** [comment]
> > In most cases, you want to generate everything. Especially when this type of new generation is being added and most of the contributors aren't aware of.
> > Once in a while, you want to check some features, so you will be able to call explicitly that matching script.
> 
> So why not keep the granularity we already have, and have `generate-all` endpoint to all type of generate endpoints?

IMO we shouldn't keep the same path.
BTW, should use `$(MAKE)` instead of calling `make` to support calling the Makefile from another directory.

**Comment by nmagnezi** [comment]
> > > In most cases, you want to generate everything. Especially when this type of new generation is being added and most of the contributors aren't aware of.
> > > Once in a while, you want to check some features, so you will be able to call explicitly that matching script.
> > 
> > 
> > So why not keep the granularity we already have, and have `generate-all` endpoint to all type of generate endpoints?
> 
> IMO we shouldn't keep the same path.
> BTW, should use `$(MAKE)` instead of calling `make` to support calling the Makefile from another directory.

Done.

**Review by filanov — APPROVED** [review]

**Comment by filanov** [comment]
Wanted to make sure that we don't break anything after https://github.com/openshift/assisted-service/pull/1058 go in.
@YuviGold do we have a call for make generate somewhere in jenkins?

**Pull request merged**
