### PR TITLE
NO-ISSUE: Pin version of butane utility

### PR DESCRIPTION
**Pull request by mkowalski**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @omertuc 
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by omertuc** [comment]
A word or two about why you did this? (e.g. "newer butane versions generate code differently, causing our verify-generated-code job to suddenly fail when new butane versions get released. This is only a problem in release-ocm-2.5 because in the master branch we've already stopped using this utility")

**Comment by mkowalski** [comment]
/retest

`Init container place-entrypoint not ready: (state: waiting, reason: "CreateContainerError", message: "context deadline exceeded")` ???

**Comment by omertuc** [comment]
Should probably be closed in favor of https://github.com/openshift/assisted-service/pull/4104

**Pull request closed without merging**
