### PR TITLE
MGMT-9779: Call cluster-info with a namespace

### PR DESCRIPTION
**Pull request by nmagnezi**
In some cases, the user does not own the cluster and thus cannot
run cluster-info without the scope of a namespace.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @osherdp 
/cc @omertuc 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
how it looked when I ran it locally (on a minikube node):
```sh
Successfully built cc32c0f82786
Successfully tagged assisted-service-build:latest
python3 ./tools/wait_for_cluster_info.py --namespace "assisted-installer"
2022-03-29 08:17:40.156445 DEBUG - kubectl --namespace assisted-installer cluster-info
Kubernetes control plane is running at https://192.168.76.2:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Review by osherdp — APPROVED** [review]

**Comment by omertuc** [comment]
:man_facepalming: The `--help` doesn't mention anything about a namespace... oh well

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-net-suite
(broken)

**Pull request merged**
