### PR TITLE
Provide the inspector URL to the ironic ignition builder

### PR DESCRIPTION
**Pull request by carbonin**
Recent changes have introduced a second URL that is required for the ironic agent to work properly. Without this URL the agent would fail of the ironic service and the inspector service were running on different nodes on the hub.

This PR bumps the version of the image customization controller we rely on and adds the inspector URL to the ignition payload.

## List all the issues related to this PR

Resolves https://issues.redhat.com/browse/MGMT-12585

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

Tested this with converged flow + dev-scripts.
Successfully discovered 3 agents and installed a cluster.

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
@eranco74 @osherdp It looks like we reverted the running converged by default, but didn't add the converged-specific jobs back in. Is that right?

This should fix it, but I'd feel better if I could run it through CI first.

**Comment by osherdp** [comment]
> 

@eranco74 or @adriengentil should remember what we did with regarding to converged flow

**Comment by adriengentil** [comment]
/test edge-e2e-ai-operator-ztp-converged
:crossed_fingers:

**Comment by adriengentil** [comment]
@osherdp any idea why the job is not available to this PR?

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by carbonin** [comment]
hmmm looks like a permissions issue :worried: 

```
time="2022-12-15T13:57:09Z" level=error msg="unable to determine Ironic's IP" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMOUtils).GetIronicServiceURLS" file="/assisted-service/internal/controller/controllers/bmo_utils.go:71" error="Cannot get the 'cluster' object from infrastructure API: infrastructures.config.openshift.io \"cluster\" is forbidden: User \"system:serviceaccount:assisted-installer:assisted-service\" cannot get resource \"infrastructures\" in API group \"config.openshift.io\" at the cluster scope" pkg=baremetal_operator_utils
```

Will look into this.

**Comment by carbonin** [comment]
My guess is that this has been broken since we merged https://github.com/openshift/assisted-service/pull/4491, but I'm not seeing it locally because my dev-scripts cluster is configured differently somehow from the one in CI

I'll add the permission and see if it helps.

**Comment by carbonin** [comment]
@smg247 @adriengentil @osherdp any reason we can't seem to trigger this job?

Do we need some kind of special permission? Should I close and re-open the PR?

**Comment by osherdp** [comment]
> @smg247 @adriengentil @osherdp any reason we can't seem to trigger this job?
> 
> Do we need some kind of special permission? Should I close and re-open the PR?

no permission should be needed to trigger jobs (or more precisely, you should have all permissions to do that as you're part of our org)

maybe there's some kind of outage with prow (or bug in the trigger plugin)?

**Comment by carbonin** [comment]
I guess I can just try a few more times :man_shrugging: 

That one seemed to work

**Comment by carbonin** [comment]
From the converged job logs it looks like we hit the case where the ironic and inspector IPs are different and it passed:
```
time="2022-12-15T17:26:16Z" level=info msg="The baremetal operator version is 4.12.0-0.nightly-2022-12-14-135139, the minimal version for the converged flow is 4.12.0-0.alpha" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMOUtils).ConvergedFlowAvailable" file="/assisted-service/internal/controller/controllers/bmo_utils.go:54" pkg=baremetal_operator_utils
time="2022-12-15T17:26:16Z" level=info msg="Converged flow enabled: true" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMOUtils).ConvergedFlowAvailable" file="/assisted-service/internal/controller/controllers/bmo_utils.go:60" pkg=baremetal_operator_utils
time="2022-12-15T17:26:16Z" level=info msg="Ironic URL is: https://192.168.111.5" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMOUtils).GetIronicServiceURLS" file="/assisted-service/internal/controller/controllers/bmo_utils.go:76" pkg=baremetal_operator_utils
time="2022-12-15T17:26:16Z" level=info msg="Inspector URL is: https://192.168.111.20" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMOUtils).GetIronicServiceURLS" file="/assisted-service/internal/controller/controllers/bmo_utils.go:78" pkg=baremetal_operator_utils
```

This should be good to go.

**Pull request merged**
