### PR TITLE
MGMT-6458 Add a test for sno hw req bug

### PR DESCRIPTION
**Pull request by carbonin**
Previously we were updating the entry in the requirements
by version map when setting them up for sno.

This ensures that a later cluster which isn't sno will have the correct
hardware requirements

Since https://github.com/openshift/assisted-service/pull/1724 is already running tests and approved and Igal should be sleeping I'll just leave this here until tomorrow.

cc @tsorya

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

This will fail unit tests until https://github.com/openshift/assisted-service/pull/1724 is in

**Comment by jakub-dzon** [comment]
I think that test is no longer needed, as it's just been covered at lower level with https://github.com/openshift/assisted-service/blob/7acd467ff179b3912df7bafd7684e070ee5afcab/internal/hardware/versioned-requirements_test.go#L2570

**Comment by carbonin** [comment]
Ah okay, specifically this change https://github.com/openshift/assisted-service/pull/1715/files#diff-6b18573abf16301d79349e97be77f043f340843e7184a783002bf0b17551dbffR257

:+1: closing this one

**Pull request closed without merging**
