### PR TITLE
MGMT-11585: Add release and OS images for OCP 4.12

### PR DESCRIPTION
**Pull request by eliorerz**
Add images to `data/default_os_images.json` and `data/default_release_images.json` for supporting OCP 4.12 on our e2e jobs.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @osherdp 
/cc @gamli75

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by gamli75** [comment]
@eliorerz please mark this version as Beta

**Review by osherdp — APPROVED** [review]

**Pull request merged**
