### PR TITLE
MGMT-6576 - Bump 4.8 OCP to fc.5

### PR DESCRIPTION
**Pull request by eranco74**
Fixes:
 - BZ 1961173: recreate existing static pod manifests instead of updating kube-apiserver for 4.8/4.8.0
 - BZ 1957708: Keepalived- verify that unicast peers list isn't empty on master nodes

### CODE REVIEW

**Comment by romfreiman** [comment]
Does it updates the operator as well?

**Comment by eranco74** [comment]
> Does it updates the operator as well?

Now it does

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by gamli75** [comment]
> Does it updates the operator as well?

Yes, see @djzager PR: https://github.com/openshift/assisted-service/commit/1e9a56ba4c76a165ec8925b2673b65f7be264802

**Pull request merged**
