### PR TITLE
Adding missing parameters section

### PR DESCRIPTION
**Pull request by apahim**
Signed-off-by: Amador Pahim <apahim@redhat.com>

### CODE REVIEW

**Comment by apahim** [comment]
@carbonin @YuviGold

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by apahim** [comment]
That's a required field, so the default will never be used.

**Comment by apahim** [comment]
The IMAGE_TAG is always provded by the saas deployer as the short commit hash.

**Comment by carbonin** [comment]
Probably should remove the default then, I don't think it's needed there

**Comment by apahim** [comment]
You can't

**Comment by carbonin** [comment]
```
10:08:57:~/Source/assisted-service (master *)$ git diff
diff --git a/openshift/template-post-deploy-job.yaml b/openshift/template-post-deploy-job.yaml
index 895e26d..8fbba90 100644
--- a/openshift/template-post-deploy-job.yaml
+++ b/openshift/template-post-deploy-job.yaml
@@ -1,4 +1,7 @@
 ---
+parameters:
+- name: IMAGE_TAG
+  required: true
 apiVersion: v1
 kind: Template
 metadata:
10:09:05:~/Source/assisted-service (master *)$ oc process --local -f openshift/template-post-deploy-job.yaml -p=IMAGE_TAG=asdf | head
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "batch/v1",
            "kind": "Job",
            "metadata": {
                "name": "assisted-service-post-deploy-asdf"
```

**Comment by apahim** [comment]
oh, that's new :/
updating, thanks!

**Pull request merged**
