### PR TITLE
WIP: NO-ISSUE: Don't run operators preflight operator requirements on day2 cluster

### PR DESCRIPTION
**Pull request by tsorya**
NO-ISSUE: Don't run operators preflight operator requirements on day2 cluster

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by tsorya** [comment]
test ?

**Comment by slaviered** [comment]
Why is it important to close the preflight API on such cluster (theoretically no one use it) and do you intend to close the corresponding validations as well?

**Comment by tsorya** [comment]
this is example for the issue we are debugging in https://github.com/openshift/assisted-service/pull/4434 
The issue is that new operator logic requires openshift version but we don't want day2 to require openshift version.
So or we somehow allow operator check without it or we don't run operator HW requirement on day2. IMO i don't see any reason why we need to check operator preflight reqs in day2

**Comment by tsorya** [comment]
Changes will be added to https://github.com/openshift/assisted-service/pull/4434

**Pull request closed without merging**
