### PR TITLE
MGMT-19085: fix 'object has been modified' error in kubeapi subsystem

### PR DESCRIPTION
**Pull request by danielerez**
Similar to https://github.com/openshift/assisted-service/pull/6850, fixed timing issue in kube-api test on BMH update. Also, removed BMH finalizers on cleanup.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by danmanor** [comment]
Maybe we should remove all finalizers before deletion as part of the cleanup ? @danielerez

**Comment by danielerez** [comment]
> Maybe we should remove all finalizers before deletion as part of the cleanup ? @danielerez

Tried adding 'GracePeriodSeconds: 0' to the deletion. Let's see.

**Comment by danielerez** [comment]
> > Maybe we should remove all finalizers before deletion as part of the cleanup ? @danielerez
> 
> Tried adding 'GracePeriodSeconds: 0' to the deletion. Let's see.

Seems ok, trying again.

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
