### PR TITLE
MGMT-4942 Download rootfs from mirror.openshift.com (take 2)

### PR DESCRIPTION
**Pull request by carbonin**
Currently, to support a minimal iso, our service also hosts the rootfs over the API.
Serving that rootfs to many hosts booting the minimal iso simultaneously may cause a load on the service that is unacceptable for resource or performance reasons.

The rootfs is also available as a release artifact on mirror.openshift.com so use that by default.

For a disconnected environment, this will mean that the rootfs will need to be hosted somewhere the hosts can access it and `OPENSHIFT_VERSIONS` should be configured with the new download path. (Same requirement as the base iso)

cc @jparrill 

----------------------------------------------------------
Take 2 info:

See https://github.com/openshift/assisted-service/pull/1669 for the first attempt at this which was reverted due to CI failures like:

`time="2021-05-09T04:58:02Z" level=fatal msg="Failed to upload boot files" func=main.main.func1 file="/go/src/github.com/openshift/origin/cmd/main.go:170" error="Failed uploading boot files for OCP version 4.6: RHCOS rootfs was missing for openshift version 4.6"`

I'm still not sure where we have an instance of `OPENSHIFT_VERSIONS` outside of this PR that could have caused that issue so I'm re-opening this as-is for discussion and to let the tests run.

### CODE REVIEW

**Comment by carbonin** [comment]
Also going to wait to rebase on https://github.com/openshift/assisted-service/pull/1693 to generate the operator openshift versions hash.

**Comment by osherdp** [comment]
ok, about the failing assisted-operator job, It doesn't seem to reproduce:
https://github.com/openshift/release/pull/18474

So I'm not sure how that broke the job previously

**Comment by carbonin** [comment]
Yeah, so I knew I missed the operator and that has since been added to the generator so that it comes from the same json file as everywhere else we keep that hash. That last rebase used the new generator code to update the operator in the first commit.

I still really don't understand how this could have broken CI for the regular flow. Is it possible that only the image was updated in some ci runs and not the code to deploy that image? Still trying to figure out how that would have happened, but it's the only thing that makes sense.

**Comment by osherdp** [comment]
maybe it will be good to add some more logs if the previous logs weren't enough to understand the problem

**Comment by osherdp** [comment]
/test system-test
let's let it run some more flows

**Comment by carbonin** [comment]
> if the previous logs weren't enough to understand the problem

It was clear what was happening. The rootfs url was missing from `OPENSHIFT_VERSIONS` what wasn't clear was where that `OPENSHIFT_VERSIONS` string was coming from. It would be from wherever the CI was started.

**Comment by osherdp** [comment]
@carbonin so on test-infra/release?
the suggestion remains, just with some other repos :)

**Comment by carbonin** [comment]
The previous errors were caused because of the way we run our test jobs.

Specifically [this line](https://github.com/openshift/release/blob/5e027d5cbd360e433c19a3aae943faf5122a87cc/ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh#L84) means that the `assisted-service` source we use to run the test is taken from the PR HEAD commit rather than a merge commit.

That means that after merging this PR every other PR will get the code in the service that requires `rhcos_rootfs` be set in `OPENSHIFT_VERSIONS` but the test infra code won't be able to see the deployment updates that add it.
The failing PRs can be fixed with a rebase.

I also opened a PR to openshift/release to try to address the issue here https://github.com/openshift/release/pull/18500

Removing WIP

**Review by djzager — APPROVED** [review]

**Pull request merged**
