### PR TITLE
Set infra-env kernel params on preprovisioning image

### PR DESCRIPTION
**Pull request by carbonin**
This will allow the kernel parameters set on the infra-env to also apply to discovery when using ipxe boot with ZTP converged flow.

## List all the issues related to this PR

Resolves https://issues.redhat.com/browse/ACM-2270

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

Deployed a devscripts environment with BMHs configured to boot using iPXE.
Created an infra-env with:
```
    kernelArguments:
    - operation: append
      value: rd.net.timeout.carrier=60
```

Observed that the preprovisioningimage had the expected `extraKernelParams` value:
```
  extraKernelParams: coreos.live.rootfs_url=https://assisted-image-service-assisted-installer.apps.ostest.test.metalkube.org/boot-artifacts/rootfs?arch=x86_64&version=4.12
    rd.net.timeout.carrier=60
  format: initrd
```

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

cc @eranco74 @ori-amizur 

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by eranco74** [comment]
Since it's not applicable for live-iso we should probably set some status condition in case we see
 kernel parameters set on the infra-env but the accepted format isn't initrd.

**Comment by carbonin** [comment]
It works for live iso as well, it's just baked into the iso.

This (ipxe+ZTP) is a special case that @ori-amizur didn't know about when implementing the discovery kernel params everywhere else.

**Pull request merged**
