### PR TITLE
Bug 1965026: Configure IPv6 DHCP in dual-stack

### PR DESCRIPTION
**Pull request by empovit**
In order for NICs to retain IPv6 addresses received from DHCP
across reboots, `ipv6.dhcp-duid=ll` must be configured. We did
it for IPv6-only hosts, but it should be done also for dual-stack
hosts. For dual-stack OCP installation it only matters if all the
hosts of a cluster are dual stack.

### CODE REVIEW

**Comment by romfreiman** [comment]
@empovit should we push it to 4.8 as well? If so, it will need a BZ in the title, as we discussed today

**Comment by empovit** [comment]
/retitle Bug 1965026: Configure IPv6 DHCP in dual-stack

**Comment by ronniel1** [comment]
/retitle Bug 1965026: Configure IPv6 DHCP in dual-stack

**Review by ori-amizur — APPROVED** [review]
/lgtm

**Pull request merged**
