### PR TITLE
OCPBUGSM-34182: skip IsDNSWildcardNotConfigured validation in day2

### PR DESCRIPTION
**Pull request by osherdp**
# Assisted Pull Request

## Description

This is a backport fix for the issue we have of day 2 installations on prod.

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @tsorya 
/cc @YuviGold 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
Original fix from #2526

**Review by YuviGold — APPROVED** [review]

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-single-node
/override ci/prow/e2e-metal-assisted
/override ci/prow/e2e-metal-assisted-olm 

(there's a sync problem, as it's working with latest agent and installer)

**Pull request merged**
