### PR TITLE
MGMT-7045: Bump OCP versions 4.7.13 -> 4.7.16, 4.8.0-fc.9 -> 4.8.0-rc.0, rchos 4.7.7 -> 4.7.13

### PR DESCRIPTION
**Pull request by oshercc**
@gamli75 @oshercc @YuviGold
4.8 has no available release notes
4.7 release notes: https://access.redhat.com/errata/RHSA-2021:2286

### CODE REVIEW

**Comment by oshercc** [comment]
Running all tests

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
