### PR TITLE
AGENT-909: Restructure gencrypto package

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
The agent installer is implementing a new auth type and could reuse the existing functionality of generating the public/private keys and JWT tokens. This change restructures the existing code for agent installer to be able to import it. 
## List all the issues related to this PR

- [ ] New Feature 
- [x] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by pawanpinjarkar** [comment]
Moving the code in `pkg` is not useful for installer because it can only access `api`, `models` and `client` packages.

**Comment by danmanor** [comment]
@carbonin As continue of our talk, I think it would be best placing this pkg in a separate repository inside `openshift-assisted`. WDYT ?

**Comment by carbonin** [comment]
Yes, I think breaking it out into its own repo so we don't have to deal with more local modules and so that it can be easily shared with the installer folks.

**Comment by danmanor** [comment]
@carbonin I have created - https://issues.redhat.com/browse/MGMT-17779 to address this

**Pull request closed without merging**
