### PR TITLE
MGMT-4327 Remove old FIO tool from service after the new tool is in use

### PR DESCRIPTION
**Pull request by ori-amizur**
Epic [MGMT-3563](https://issues.redhat.com/browse/MGMT-3563) introduced and new tool - disk-speed-check, which replaces the old tool fio-perf-check
    Here we remove the old definitions from swagger and generated code for that tool, since it is not used any more

### CODE REVIEW

**Comment by djzager** [comment]
/hold 

I need #1697 and #1699 to go in so I can put the operator up on community-operators. Will cancel hold once they merge.

**Comment by djzager** [comment]
Leaving the hold because this will fail on retest until it's rebased on master (with the rootfs url change from #1697 )

**Comment by flaper87** [comment]
Friendly reminder to authors and reviewers that a proper description should be provided in both, the PR and the commit.

https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines

/cc @ori-amizur @tsorya @djzager

**Pull request merged**
