### PR TITLE
Bug 2023616: Add LivenessProbe to Image Service (#2751)

### PR DESCRIPTION
**Pull request by rollandf**
# Assisted Pull Request

## List all the issues related to this PR

- [ ] New Feature
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
@rollandf I think you need to fix bugzilla state. it's the only required step not yet fulfilled

**Comment by rollandf** [comment]
```
[2021-11-16T22:21:04.523Z] + docker run -u 0:0 -v /home/workspace/****-service_PR-2939:/home/workspace/****-service_PR-2939:rw,Z -v /etc/passwd:/etc/passwd -w /home/workspace/****-service_PR-2939 quay.io/goswagger/swagger:v0.25.0 generate client --template=stratoscale -f swagger.yaml --template-dir=/templates/contrib

[2021-11-16T22:21:04.523Z] ./hack/generate.sh: line 23: docker: command not found

```

**Comment by osherdp** [comment]
/retest
Seems like there's a global issue accessing epel repository, trying to see if that's still the case

**Pull request merged**
