### PR TITLE
[WIP] NO-ISSUE Use hive apis submodule

### PR DESCRIPTION
**Pull request by carbonin**

### CODE REVIEW

**Comment by carbonin** [comment]
cc @filanov @danielerez @ronniel1

**Comment by carbonin** [comment]
The branch in my fork that I'm pointing to here contains the changes from https://github.com/openshift/hive/pull/1277 as well as [my submodule PR ](https://github.com/openshift/hive/pull/1280)

**Comment by filanov** [comment]
I'll try to take the changes to my PR, hope it will help https://github.com/openshift/assisted-service/pull/1050

**Comment by filanov** [comment]
Locally make all passed

**Comment by carbonin** [comment]
Closing in favor of https://github.com/openshift/assisted-service/pull/1050

**Pull request closed without merging**
