### PR TITLE
Backport podman installation mode changes

### PR DESCRIPTION
**Pull request by osherdp**
Backports #3023, #3100, and #3110 in order to have a stable tag that contains all changes related to podman mode installation via ``Makefile``.

/cc @filanov @eliorerz

### CODE REVIEW

**Comment by osherdp** [comment]
/override e2e-metal-assisted-ipv4v6
(known gap of v2.0)

/test e2e-metal-assisted-onprem

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by osherdp** [comment]
/test e2e-metal-assisted-ocp49
we sometimes have those infra problems, for no apparent reason.
maybe we can try to just change this to regular ``scp`` usage:
```
tar -czf - . | ssh "${SSHOPTS[@]}" "root@${IP}" "cat > /root/assisted.tar.gz"
```

**Comment by osherdp** [comment]
/test subsystem-aws
reported https://issues.redhat.com/browse/MGMT-8827

**Comment by osherdp** [comment]
/test e2e-metal-assisted-ocp46
not worth investigating it I guess

**Pull request merged**
