### PR TITLE
MGMT-5302 Restoring /host_requirements for e2e tests

### PR DESCRIPTION
**Pull request by jakub-dzon**
This PR retores `/host_requirements` endpoint, because it is extensively used by e2e tests. Removal needs to be done when e2e tests start using newer APIs.

Reverts commit 45105c16a7c833f84132cad02c4940106cceebb0

### CODE REVIEW

**Comment by omertuc** [comment]
Please include PR description in commit message

**Comment by omertuc** [comment]
Also please provide the commit that this is reverting, even if partially

**Comment by jakub-dzon** [comment]
@omertuc - done.

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
