### PR TITLE
MGMT-7228: Add AgentClusterInstall shortName aci

### PR DESCRIPTION
**Pull request by nmagnezi**
# Assisted Pull Request

## Description

Add `AgentClusterInstall` shortName  --> aci

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @filanov 
/cc @rollandf 
/cc @mkowalski 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
Tested when deploying on minikube:

Existing:
```sh
$ kubectl -n spoke-cluster get agentclusterinstalls.extensions.hive.openshift.io
NAME                         AGE
test-agent-cluster-install   5d20h
```
New:
```sh
$ kubectl -n spoke-cluster get aci
NAME                         AGE
test-agent-cluster-install   5d20h
```

**Review by flaper87 — APPROVED** [review]
:pizza:

**Pull request merged**
