### PR TITLE
[release-ocm-2.9] MGMT-15501: ClusterServiceVersion for release 2.9 branch references `latest` tag

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @adriengentil @danielerez @osherdp

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
@eliorerz @adriengentil I think ``e2e-agent-compact-ipv4`` is only relevant to ABI (i.e. openshift versions). So we should remove it from this branch

**Comment by adriengentil** [comment]
> @eliorerz @adriengentil I think e2e-agent-compact-ipv4 is only relevant to ABI (i.e. openshift versions). So we should remove it from this branch

it's not defined in the config, it was triggered because this PR was initially opened against master and then was changed to target release-ocm-2.9.

**Pull request merged**
