### PR TITLE
MGMT-17848: Assisted service should not format multipath devices

### PR DESCRIPTION
**Pull request by adriengentil**
Exclude multipath drive type from being formatted.

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Comment by adriengentil** [comment]
/cherry-pick ocm-release-2.10 ocm-release-2.9 ocm-release-2.8

**Comment by adriengentil** [comment]
/cherry-pick ocm-release-2.10 ocm-release-2.9 ocm-release-2.8

**Comment by adriengentil** [comment]
/cherry-pick release-ocm-2.10 release-ocm-2.9 release-ocm-2.8

**Pull request merged**
