### PR TITLE
MGMT-19141: Ensure no finalizer is set for BMHs without the infraenv label

### PR DESCRIPTION
**Pull request by carbonin**
Previously BMAC was setting our finalizer for every BMH in the cluster and only removing them when we either saw the delete agent annotation or the paused annotation. This meant that no other BMHs could be removed without manually removing this finalizer.

This commit ensures the finalizer handling sees the finalizer being removed as a change and sets the "dirty" return flag accordingly and also ensures we never set out finalizer on a BMH without an infraenv label (one we don't own).

## List all the issues related to this PR

Resolves https://issues.redhat.com/browse/MGMT-19141

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

Manually tested by deploying to an environment with BMHs for multiple purposes.
Saw that finalizers were no longer being set for BMHs without the infraenv label.

- [ ] assisted-test-infra environment
- [x] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

Still doing some testing, but wanted to get this out to get CI running.

**Comment by carbonin** [comment]
I'm going to change this to trigger based on the presence of the infraenv label on the BMH rather than whether or not the infraenv actually exists.

That's mainly because we don't care about the infraenv, we only really want to know if this is a BMH that is meant for us or not.

I mention this because I deployed an image with this change and I ended up with a BMH that references a missing infraenv having no finalizer but also having the paused annotation. This means that it would be impossible to delete regularly.

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Pull request merged**
