### PR TITLE
Bug 2048981: Add default value to default_release_images.json

### PR DESCRIPTION
**Pull request by eliorerz**
Fix e2e jobs missing openshift default value

```
d/discovery-infra/bootstrap_in_place.py", line 16, in <module>
    from download_logs import download_must_gather, gather_sosreport_data
  File "/home/assisted/discovery-infra/download_logs.py", line 37, in <module>
    from tests.config import ClusterConfig, TerraformConfig
  File "/home/assisted/discovery-infra/tests/config/__init__.py", line 1, in <module>
    from .global_configs import ClusterConfig, Day2ClusterConfig, InfraEnvConfig, TerraformConfig, global_variables
  File "/home/assisted/discovery-infra/tests/config/global_configs.py", line 12, in <module>
    global_variables = GlobalVariables()
  File "<string>", line 56, in __init__
  File "/home/assisted/discovery-infra/test_infra/utils/global_variables/global_variables.py", line 60, in __post_init__
    self._set("openshift_version", utils.get_openshift_version(allow_default=True, client=client))
  File "/home/assisted/discovery-infra/test_infra/utils/utils.py", line 483, in get_openshift_version
    return get_default_openshift_version(client)
  File "/home/assisted/discovery-infra/test_infra/utils/utils.py", line 450, in get_default_openshift_version
    assert len(versions) == 1, f"There should be exactly one default version {versions}"
AssertionError: There should be exactly one default version []
make: *** [Makefile:341: _deploy_nodes] Error 1
```

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @tsorya 
/cc @osherdp 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
seems like ``make generate-all`` is needed

**Review by osherdp — APPROVED** [review]
/unhold

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
/override ci/prow/e2e-metal-assisted-operator-disconnected
(both broken)

**Comment by osherdp** [comment]
hmm, @eliorerz I think this fails because you didn't attach bugzilla issue, not because of failing tests

**Comment by mkowalski** [comment]
/retitle Bug 2048981: Add default value to default_release_images.json

**Comment by mkowalski** [comment]
/hold
After proper fixes of the branch we will probably not need this PR

**Pull request merged**
