### PR TITLE
MGMT-3690 - Fix tests that never ran, add lint to prevent

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Comment by eranco74** [comment]
https://github.com/kyoh86/scopelint - OBSOLETED
Use looppointer or exportloopref instead.

**Comment by ronniel1** [comment]
Good job.
I think that the format of:
```
for i := range tests {
   t := tests[i]
   It(...) {
       ...
   }
}
```
is better then:
```
for _, ti := range tests {
   t := t
   It(...) {
       ...
   }
}
```
because it looks a lot less voodoo.
What do you think?

**Comment by omertuc** [comment]
> [kyoh86/scopelint](https://github.com/kyoh86/scopelint) - OBSOLETED
> Use looppointer or exportloopref instead.

We [pinned golangci-lint to 1.24](https://github.com/openshift/assisted-service/blob/b981df4845576636704d2c9bacc55ce6ed56738a/Dockerfile.assisted-service-build#L10). 

@filanov any particular reason for that? The linters we're looking for are not available in that version

**Comment by omertuc** [comment]
> Good job.
> I think that the format of:
> 
> ```
> for i := range tests {
>    t := tests[i]
>    It(...) {
>        ...
>    }
> }
> ```
> 
> is better then:
> 
> ```
> for _, ti := range tests {
>    t := t
>    It(...) {
>        ...
>    }
> }
> ```
> 
> because it looks a lot less voodoo.
> What do you think?

I personally prefer `t := t` since it strongly implies "Something is wrong here" and makes people ask questions (questions they should be asking to eventually to become aware of this issue).

When I see `t := tests[i]` I get annoyed and think "why not just use foreach loop!", it doesn't make me realize there's something odd going on, it "hides" the issue

**Comment by filanov** [comment]
I don't mind both options are ok for me.

**Comment by filanov** [comment]
> > [kyoh86/scopelint](https://github.com/kyoh86/scopelint) - OBSOLETED
> > Use looppointer or exportloopref instead.
> 
> We [pinned golangci-lint to 1.24](https://github.com/openshift/assisted-service/blob/b981df4845576636704d2c9bacc55ce6ed56738a/Dockerfile.assisted-service-build#L10).
> 
> @filanov any particular reason for that? The linters we're looking for are not available in that version

No specific reason, we just specify the version to make sure the everyone are using the same one, we can update it if needed.

**Comment by omertuc** [comment]
Neither looppointer (which isn't even a part of golangci-lint) or exportloopref (which requires an upgrade of golangci-lint which brings up a lot of new issues) can even detect this bug.

I propose we keep using obsolete scopelint - it brings value to us and there was only one case that kinda seemed like a false negative to me, so it's still worth it.

@eranco74 @YuviGold @ronniel1 @filanov do you oppose we keep using `scopelint`?

**Comment by YuviGold** [comment]
> > Good job.
> > I think that the format of:
> > ```
> > for i := range tests {
> >    t := tests[i]
> >    It(...) {
> >        ...
> >    }
> > }
> > ```
> > 
> > 
> > is better then:
> > ```
> > for _, ti := range tests {
> >    t := t
> >    It(...) {
> >        ...
> >    }
> > }
> > ```
> > 
> > 
> > because it looks a lot less voodoo.
> > What do you think?
> 
> I personally prefer `t := t` since it strongly implies "Something is wrong here" and makes people ask questions (questions they should be asking to eventually to become aware of this issue).
> 
> When I see `t := tests[i]` I get annoyed and think "why not just use foreach loop!", it doesn't make me realize there's something odd going on, it "hides" the issue

I can relate to what you wrote.. But still, I'm not sure everyone would notice that.

> Neither looppointer (which isn't even a part of golangci-lint) or exportloopref (which requires an upgrade of golangci-lint which brings up a lot of new issues) can even detect this bug. They seem to deal only with pointers, not closure variable capture.
> 
> I propose we keep using obsolete scopelint - it brings value to us and there was only one case that kinda seemed like a false negative to me, so it's still worth it.
> 
> @eranco74 @YuviGold @ronniel1 @filanov do you oppose we keep using `scopelint`?

I am fine with that for now. Still, we should look for ongoing linters, since Golang language is being upgraded as well.

**Comment by filanov** [comment]
@omertuc the fix is not as simple as you think
```
[2021-01-20T09:13:39.854Z] internal/host/transition_test.go:608: File is not `goimports`-ed (goimports)
[2021-01-20T09:13:39.854Z] 		state      string
[2021-01-20T09:13:39.854Z] 		success    bool
[2021-01-20T09:13:39.854Z] 		changeState    bool
[2021-01-20T09:13:39.854Z] 		statusCode int32
```

**Comment by filanov** [comment]
@omertuc please run make format

**Comment by omertuc** [comment]
/hold

Not working on it ATM

**Review by filanov — APPROVED** [review]

**Pull request merged**
