### PR TITLE
NO-ISSUE: For ZTP CI add more Hive condition checks

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by mkowalski** [comment]
/hold

Let me check the status of the optional ZTP jobs before shipping it

**Comment by mkowalski** [comment]
/close

From discussion with Hive team, we should not use `ProvisionStopped` as a marker for installation being successful. Using `.spec.installed` is the good way

**Pull request closed without merging**
