### PR TITLE
MGMT-4413, Bump OCP versions

### PR DESCRIPTION
**Pull request by oshercc**
@romfreiman @ronniel1 @gamli75 @oshercc

### CODE REVIEW

**Comment by gamli75** [comment]
@oshercc can you please manually changed it to 4.6.16? And can you check the strange RHCOS version: 47.83.202102090044-0 ignition.firstboot?

**Comment by oshercc** [comment]
test-infra test failed for release 4.6, see http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/326/

**Comment by oshercc** [comment]
test infra passed: http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/331/

**Comment by gamli75** [comment]
@oshercc can you please verify the RHCOS version? it looks strange that the image was changed and the RHCOS version remains the same.
When I ran oc adm release info quay.io/openshift-release-dev/ocp-release:4.7.2-x86_64 | grep machine-os | grep "Red Hat Enterprise Linux CoreOS"
  machine-os **47.83.202103051045-0** Red Hat Enterprise Linux CoreOS

**Comment by oshercc** [comment]
> @oshercc can you please verify the RHCOS version? it looks strange that the image was changed and the RHCOS version remains the same.
> When I ran oc adm release info quay.io/openshift-release-dev/ocp-release:4.7.2-x86_64 | grep machine-os | grep "Red Hat Enterprise Linux CoreOS"
> machine-os **47.83.202103051045-0** Red Hat Enterprise Linux CoreOS


When extracting the version in the method @YuviGold found this is what I get:
```
/tmp> curl https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso  -o rhcos-4.7.0-x86_64-live.x86_64.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  910M  100  910M    0     0  1647k      0  0:09:25  0:09:25 --:--:-- 1555k

/tmp> 7z x rhcos-4.7.0-x86_64-live.x86_64.iso zipl.prm
.
.
.
/tmp> cat zipl.prm
random.trust_cpu=on coreos.liveiso=rhcos-47.83.202102090044-0 ignition.firstboot ignition.platform.id=metal
```

**Comment by YuviGold** [comment]
@oshercc What happened to the commit message?
Bad bump - 4.6.18 went down to 4.6.16... 
/hold

**Comment by gamli75** [comment]
> > @oshercc can you please verify the RHCOS version? it looks strange that the image was changed and the RHCOS version remains the same.
> > When I ran oc adm release info quay.io/openshift-release-dev/ocp-release:4.7.2-x86_64 | grep machine-os | grep "Red Hat Enterprise Linux CoreOS"
> > machine-os **47.83.202103051045-0** Red Hat Enterprise Linux CoreOS
> 
> When extracting the version in the method @YuviGold found this is what I get:
> 
> ```
> /tmp> curl https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso  -o rhcos-4.7.0-x86_64-live.x86_64.iso
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  910M  100  910M    0     0  1647k      0  0:09:25  0:09:25 --:--:-- 1555k
> 
> /tmp> 7z x rhcos-4.7.0-x86_64-live.x86_64.iso zipl.prm
> .
> .
> .
> /tmp> cat zipl.prm
> random.trust_cpu=on coreos.liveiso=rhcos-47.83.202102090044-0 ignition.firstboot ignition.platform.id=metal
> ```

@YuviGold Can you please check the RHCOS version?

**Comment by oshercc** [comment]
@YuviGold the down bump to 4.6.16 was by @gamli75 request.

**Comment by YuviGold** [comment]
> > > @oshercc can you please verify the RHCOS version? it looks strange that the image was changed and the RHCOS version remains the same.
> > > When I ran oc adm release info quay.io/openshift-release-dev/ocp-release:4.7.2-x86_64 | grep machine-os | grep "Red Hat Enterprise Linux CoreOS"
> > > machine-os **47.83.202103051045-0** Red Hat Enterprise Linux CoreOS
> > 
> > 
> > When extracting the version in the method @YuviGold found this is what I get:
> > ```
> > /tmp> curl https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso  -o rhcos-4.7.0-x86_64-live.x86_64.iso
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> > 100  910M  100  910M    0     0  1647k      0  0:09:25  0:09:25 --:--:-- 1555k
> > 
> > /tmp> 7z x rhcos-4.7.0-x86_64-live.x86_64.iso zipl.prm
> > .
> > .
> > .
> > /tmp> cat zipl.prm
> > random.trust_cpu=on coreos.liveiso=rhcos-47.83.202102090044-0 ignition.firstboot ignition.platform.id=metal
> > ```
> 
> @YuviGold Can you please check the RHCOS version?

This is how I know to get the buildID of an RHCOS from the ISO. It was done correctly.
Regarding the `oc adm release info` we (ft. @ronniel1 ) found that this buildID doesn't necessarily reference an existing official build. Hence, what @oshercc took from the official mirror, supposed to be the real latest official RHCOS.

**Comment by YuviGold** [comment]
> @YuviGold the down bump to 4.6.16 was by @gamli75 request.

Please make a more informative commit message including the changes.
Downgrading isn't trivial at all and I guess there's a reason that should be documented.

**Pull request merged**
