### PR TITLE
MGMT-11309: add prometheus expoter for postgresql

### PR DESCRIPTION
**Pull request by rccrdpccl**
This PR adds prometheus exporter for assisted-installer.
It has been added to a separate template file, so that we can deploy it indipendently as it is not related directly with AI code, but only with its dependency.
This will allow us to have better insights on PG metrics. In this specific instance we were looking to count  added events, and we're trying to achieve this with the autoincrement counter (to account for deletions).
It also exposes other pg metrics that can be useful as replication lag and such (default in helm template used to generate this manifest)

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 
- [X] monitoring

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Assignees

/cc @gamli75 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by osherdp** [comment]
Is it possible having it in a different repository? like assisted-events-scraper

**Comment by rccrdpccl** [comment]
Sure, I can move it somewhere else, but I feel like does not belong to scraper either, as postgresql instance belongs to assisted-service.
I could create another dedicated repository for it, WDYT?

**Comment by osherdp** [comment]
> Sure, I can move it somewhere else, but I feel like does not belong to scraper either, as postgresql instance belongs to assisted-service. I could create another dedicated repository for it, WDYT?

If it's not too much work. Because I think assisted-service jobs will eventually slow us down by validating all those changes with unit-tests and those other jobs

Another option that might be good enough for now is to make those jobs to not trigger on changes to those template files. Is it possible changing configuration for unit-test and verify-generated-code jobs?

**Comment by rccrdpccl** [comment]
> If it's not too much work. Because I think assisted-service jobs will eventually slow us down by validating all those changes with unit-tests and those other jobs
> 
> Another option that might be good enough for now is to make those jobs to not trigger on changes to those template files. Is it possible changing configuration for unit-test and verify-generated-code jobs?

I see. I am interested in doing this the best way possible, as it won't take too much either way (new repo already created, though it could be deleted if necessary - https://github.com/openshift-assisted/postgres-monitoring/pull/1). Which way would you think it's best?

I would think it makes sense to have it in the assisted-service repo just because the DB belongs to it, however I might be missing some context that would make me change opinion.

In any case I will change the way the jobs unit-test and verify-generated-code are triggered so they won't run on openshift templates changes.

**Comment by osherdp** [comment]
> > If it's not too much work. Because I think assisted-service jobs will eventually slow us down by validating all those changes with unit-tests and those other jobs
> > Another option that might be good enough for now is to make those jobs to not trigger on changes to those template files. Is it possible changing configuration for unit-test and verify-generated-code jobs?
> 
> I see. I am interested in doing this the best way possible, as it won't take too much either way (new repo already created, though it could be deleted if necessary - [openshift-assisted/postgres-monitoring#1](https://github.com/openshift-assisted/postgres-monitoring/pull/1)). Which way would you think it's best?
> 
> I would think it makes sense to have it in the assisted-service repo just because the DB belongs to it, however I might be missing some context that would make me change opinion.
> 
> In any case I will change the way the jobs unit-test and verify-generated-code are triggered so they won't run on openshift templates changes.

maybe you're right and it should reside in assisted-service repo
I don't have a very strong opinion on that

**Review by osherdp — APPROVED** [review]

**Comment by rccrdpccl** [comment]
related: https://github.com/openshift/release/pull/30966

**Pull request merged**
