### PR TITLE
Raz/mgmt 1685

### PR DESCRIPTION
**Pull request by RazRegev**

### CODE REVIEW

**Comment by RazRegev** [comment]
/ cc @eranco74

**Review by eranco74 — COMMENTED** [review]
I know that essentially in the assisted-installer the timeout is set for waiting for control plane yet I think the name is a bit confusing.
Consider renaming to installation-timeout:
1. it will be consistent between the service and the installer. 
2. I'll update the implementation in the installer to return an error when the timeout expires (currently return only when the bootstrap gets to "waiting for control plane"

**Review by eranco74 — COMMENTED** [review]
/approve

**Pull request merged**
