### PR TITLE
NO-ISSUE: Trigger VIP reallocation only when the primary machine CIDR changes

### PR DESCRIPTION
**Pull request by mkowalski**
Cherry-picks: #2527

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by mkowalski** [comment]
/retest-required
```
 ssh: connect to host 147.75.94.239 port 22: Connection timed out
Could not create directory '/.ssh'.
```

**Comment by mkowalski** [comment]
/retitle Bug 1999297: Trigger VIP reallocation only when the primary machine CIDR changes

**Comment by mkowalski** [comment]
/retitle NO-ISSUE: Trigger VIP reallocation only when the primary machine CIDR changes

**Review by gamli75 — APPROVED** [review]

**Pull request merged**
