### PR TITLE
MGMT-2448 Add installer image caching to host discovery

### PR DESCRIPTION
**Pull request by filanov**
Added download of the installer image in order to cache it for the installtion.
The command have a timeout of 15 minuts and will try to download the image during this period.

Images list from one of the hosts before installation:
```
sudo podman images
REPOSITORY                                  TAG      IMAGE ID       CREATED        SIZE
quay.io/ocpmetal/assisted-installer-agent   latest   10b6aace1fab   9 hours ago    473 MB
quay.io/ocpmetal/assisted-installer         latest   4cc8e21c65d5   12 hours ago   69.9 MB
```
Passed test-infra

### CODE REVIEW

**Comment by filanov** [comment]
cc: @ronniel1 @gamli75 @eranco74

**Comment by gamli75** [comment]
@filanov what about the postStepReply?

**Comment by filanov** [comment]
> @filanov what about the postStepReply?

We don't really care about the reply because we don't write it to the DB or retry. So you will see the reply in the logs.
It's only a cache maybe the user wait long enough and the image that we downloaded is not relevant anymore.
Do you expect a different behavior?

**Comment by filanov** [comment]
> s.
> It's only a cache maybe the user wait long enough and the image that we downloaded is not relevant anymore.

example of the logs:
```
time="2020-10-14T09:33:02Z" level=info msg="Submitting step <execute> id <execute-8972cb3c> to cluster <8a32dfac-6208-4963-a18c-4a4ec4bfc1de> host <2c3cedf7-9618-4551-b22a-7e436f8fcc8a> Command: <timeout> Arguments: <[15m bash -c until podman pull quay.io/ocpmetal/assisted-installer:latest; do sleep 1; done]>" func=github.com/openshift/assisted-service/internal/host.logSteps file="/go/src/github.com/openshift/origin/internal/host/instructionmanager.go:149" cluster_id=8a32dfac-6208-4963-a18c-4a4ec4bfc1de go-id=943 host_id=2c3cedf7-9618-4551-b22a-7e436f8fcc8a pkg=instructions request_id=88d01289-8c5b-431a-8fca-8054e1e9b80f
time="2020-10-14T09:33:04Z" level=info msg="Received step reply <execute-8972cb3c> from cluster <8a32dfac-6208-4963-a18c-4a4ec4bfc1de> host <2c3cedf7-9618-4551-b22a-7e436f8fcc8a>  exit-code <0> stdout <4cc8e21c65d563f479e8feb585ac3ceb1047b0609e054fe172cc3f5c51f5de35\n> stderr <Trying to pull quay.io/ocpmetal/assisted-installer:latest...\nGetting image source signatures\nCopying blob sha256:344bb7aec2e60df561b4203133096bd715c0d152971d822eccde61ab791d7d0b\nCopying blob sha256:3f589afea86ce222b8605575e7aa60e6a1e52d6ca2e5ab34a7606fe3c334837a\nCopying blob sha256:63d818470a91b4429eb677b9e1546e1099b682a5c8bbe8c3342dd79fcb763e47\nCopying blob sha256:b89aa7cc56cc1de31bb3d488b0b63b5d77f408c6b95ea66ceea3d06248b918a9\nCopying blob sha256:df20fa9351a15782c64e6dddb2d4a6f50bf6d3688060a34c4014b0d9a752eb4c\nCopying config sha256:4cc8e21c65d563f479e8feb585ac3ceb1047b0609e054fe172cc3f5c51f5de35\nWriting manifest to image destination\nStoring signatures\n>" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).PostStepReply" file="/go/src/github.com/openshift/origin/internal/bminventory/inventory.go:1868" cluster_id=8a32dfac-6208-4963-a18c-4a4ec4bfc1de go-id=943 host_id=2c3cedf7-9618-4551-b22a-7e436f8fcc8a pkg=Inventory request_id=88d01289-8c5b-431a-8fca-8054e1e9b80f
```

**Comment by avishayt** [comment]
> > @filanov what about the postStepReply?
> 
> We don't really care about the reply because we don't write it to the DB or retry. So you will see the reply in the logs.
> It's only a cache maybe the user wait long enough and the image that we downloaded is not relevant anymore.
> Do you expect a different behavior?

What if it fails? IMO a benefit of this PR is to do a step earlier and notify if there's an issue,

**Comment by filanov** [comment]
> > > @filanov what about the postStepReply?
> > 
> > 
> > We don't really care about the reply because we don't write it to the DB or retry. So you will see the reply in the logs.
> > It's only a cache maybe the user wait long enough and the image that we downloaded is not relevant anymore.
> > Do you expect a different behavior?
> 
> What if it fails? IMO a benefit of this PR is to do a step earlier and notify if there's an issue,

Not sure what will the user do with this error - it's not something that he can control. 
When we talked about this request it was to cache the image because sometimes quay.io is slow and we don't want to run the install command multiple times and make the installation longer

If we want to fail the cluster or give some kind of warning before starting the installation then maybe another state is required - or use preparing for installation but then it will just make the install process longer again. 

Maybe we can create another state that require several command on the host, like downloading the image and formatting disks?

**Comment by filanov** [comment]
/hold
Putting this PR on hold until we figure out what is the best way to solve it.

**Comment by avishayt** [comment]
> Not sure what will the user do with this error - it's not something that he can control.

Of course, but it's also better that the user doesn't start installing and fail in a strange way if we know it won't succeed.

> When we talked about this request it was to cache the image because sometimes quay.io is slow and we don't want to run the install command multiple times and make the installation longer
> 
> If we want to fail the cluster or give some kind of warning before starting the installation then maybe another state is required - or use preparing for installation but then it will just make the install process longer again.
> 
> Maybe we can create another state that require several command on the host, like downloading the image and formatting disks?

Maybe a property that is set if we failed to download, and a validation that we didn't fail?  So if it fails the host goes to "insufficient" until it passes?

**Comment by filanov** [comment]
> > Not sure what will the user do with this error - it's not something that he can control.
> 
> Of course, but it's also better that the user doesn't start installing and fail in a strange way if we know it won't succeed.
> 
> > When we talked about this request it was to cache the image because sometimes quay.io is slow and we don't want to run the install command multiple times and make the installation longer
> > If we want to fail the cluster or give some kind of warning before starting the installation then maybe another state is required - or use preparing for installation but then it will just make the install process longer again.
> > Maybe we can create another state that require several command on the host, like downloading the image and formatting disks?
> 
> Maybe a property that is set if we failed to download, and a validation that we didn't fail? So if it fails the host goes to "insufficient" until it passes?

So it will not be a cache anymore, because we will need to validate that he image that we have is the same as the one that will be during the installation, in this case we will need to download it as close as we can to the installation time. 
I wonder if it worth the effort, after all, we already know how to handle installation that have already started.

**Comment by gamli75** [comment]
@avishayt I think that we should have a different process that verifies all our external URLs are reachable, such as installer image, ocp image ... and inform all the users that the installation process is not available.

**Comment by avishayt** [comment]
> > > Not sure what will the user do with this error - it's not something that he can control.
> > 
> > 
> > Of course, but it's also better that the user doesn't start installing and fail in a strange way if we know it won't succeed.
> > > When we talked about this request it was to cache the image because sometimes quay.io is slow and we don't want to run the install command multiple times and make the installation longer
> > > If we want to fail the cluster or give some kind of warning before starting the installation then maybe another state is required - or use preparing for installation but then it will just make the install process longer again.
> > > Maybe we can create another state that require several command on the host, like downloading the image and formatting disks?
> > 
> > 
> > Maybe a property that is set if we failed to download, and a validation that we didn't fail? So if it fails the host goes to "insufficient" until it passes?
> 
> So it will not be a cache anymore, because we will need to validate that he image that we have is the same as the one that will be during the installation, in this case we will need to download it as close as we can to the installation time.
> I wonder if it worth the effort, after all, we already know how to handle installation that have already started.

It will still be a cache.  We just won't proceed with the installation if we can't download whatever image is currently being used (if we can't download this version, we probably won't be able to download the newer version we might need for the installation).  Maybe it will give us a hint that the pull secret doesn't have the necessary permissions to download, or the mirror is down, etc.

**Comment by filanov** [comment]
> > > > Not sure what will the user do with this error - it's not something that he can control.
> > > 
> > > 
> > > Of course, but it's also better that the user doesn't start installing and fail in a strange way if we know it won't succeed.
> > > > When we talked about this request it was to cache the image because sometimes quay.io is slow and we don't want to run the install command multiple times and make the installation longer
> > > > If we want to fail the cluster or give some kind of warning before starting the installation then maybe another state is required - or use preparing for installation but then it will just make the install process longer again.
> > > > Maybe we can create another state that require several command on the host, like downloading the image and formatting disks?
> > > 
> > > 
> > > Maybe a property that is set if we failed to download, and a validation that we didn't fail? So if it fails the host goes to "insufficient" until it passes?
> > 
> > 
> > So it will not be a cache anymore, because we will need to validate that he image that we have is the same as the one that will be during the installation, in this case we will need to download it as close as we can to the installation time.
> > I wonder if it worth the effort, after all, we already know how to handle installation that have already started.
> 
> It will still be a cache. We just won't proceed with the installation if we can't download whatever image is currently being used (if we can't download this version, we probably won't be able to download the newer version we might need for the installation). Maybe it will give us a hint that the pull secret doesn't have the necessary permissions to download, or the mirror is down, etc.

Let me see if understand, it will become of the validations, we will need to store this info the DB in order downlaod it once. 
Host will be insufficient if we failed to download or still didn't download. 
Anything that i missed?

**Review by avishayt — APPROVED** [review]

**Comment by filanov** [comment]
Opened https://issues.redhat.com/browse/MGMT-2453 to complete the fix

**Pull request merged**
