### PR TITLE
MGMT-8206: Bump OCP versions release 4.9.5 -> 4.9.6

### PR DESCRIPTION
**Pull request by osherdp**
4.9 release notes: https://access.redhat.com/errata/RHBA-2021:4119

/cc @romfreiman @celebdor @gamli75
/hold

### CODE REVIEW

**Review by nmagnezi — COMMENTED** [review]
Looks okay, but the failing jobs should probably be fixed first ; otherwise approving this will just cause a retry loop.

**Comment by osherdp** [comment]
/test e2e-metal-assisted-multi-version
(flaky job)

**Review by nmagnezi — APPROVED** [review]
/lgtm
The failed jobs are broken regardless of this PR, and are being fixed separately.

**Pull request merged**
