### PR TITLE
MGMT-18501: Configure sast-snyk-check in konflux pipelines

### PR DESCRIPTION
**Pull request by giladravid16**
Configure sast-snyk-check in konflux pipelines

## List all the issues related to this PR

Part-of [MGMT-18501](https://issues.redhat.com//browse/MGMT-18501)

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by paul-maidment** [comment]
What is the consequence of doing this, will CI jobs fail when the vulnerabilities are detected by snyk or is this a purely informative check?

Where can I learn more about this change?

**Comment by giladravid16** [comment]
@paul-maidment the configuration I have here will probably change a little, I'm talking to the konflux team to see how to get the sast-snyk-check to use the existing project in snyk instead of creating a new one. But my answer should remain the same regardless.

The konflux build pipelines don't fail on snyk errors (or any similar error for that matter), but it does store the result of the sast-snyk-check task.
So if we try to release an image that failed on sast-snyk-check we will get an error unless we have an exception for that in our EnterpriseContractPolicy (currently we do because we skip the task entirely).
If we want to deny PRs that don't pass sast-snyk-check then we can create an integration test in konflux that checks the EnterpriseContractPolicy (it's very easy to configure).

**Pull request merged**
