### PR TITLE
NO-ISSUE: validate PULL_SECRET value before using it

### PR DESCRIPTION
**Pull request by osherdp**
/hold
/cc @YuviGold 
fixes #527

### CODE REVIEW

**Comment by eranco74** [comment]
Assisted-service log:
```
29ecb5634e7d go-id=6003 host_id=77569058-28d4-45a7-841d-1a04e2f2fb90 pkg=Inventory request_id=40e67a74-84bd-4167-9263-b9bd1108a40e
time="2021-02-17T12:51:15Z" level=error msg="error parsing ignition: unsupported config version" func="github.com/openshift/assisted-service/internal/ignition.(*installerGenerator).updateBootstrap" file="/go/src/github.com/openshift/origin/internal/ignition/ignition.go:462" go-id=5846 pkg=k8s-job-wrapper request_id=edc09cec-4905-4ace-b120-04ee0c40dd99
time="2021-02-17T12:51:15Z" level=error msg="failed generating kubeconfig files for cluster df47c786-96f1-4976-ac12-29ecb5634e7d" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).generateClusterInstallConfig" file="/go/src/github.com/openshift/origin/internal/bminventory/inventory.go:1629" error="error parsing ignition: unsupported config version" go-id=5846 pkg=Inventory request_id=edc09cec-4905-4ace-b120-04ee0c40dd99
```
Code:
```
	config, _, err := config_31.Parse(configBytes)
	if err != nil {
		return nil, errors.Errorf("error parsing ignition: %v", err)
	}
```

**Comment by eranco74** [comment]
Seems that we are installing OCP 4.8!! I guess it produces Ignition config with a higher version than 3.1
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/1103/pull-ci-openshift-assisted-service-master-e2e-metal-assisted/1362012586991685632/artifacts/e2e-metal-assisted/baremetalds-assisted-gather/artifacts/2021-02-17_12:50:49_df47c786-96f1-4976-ac12-29ecb5634e7d/metdata.json
```

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
