### PR TITLE
MGMT-9035: Fix validation of CA bundle

### PR DESCRIPTION
**Pull request by mkowalski**
This commit fixes the logic used to validate the CA bundle provided for
the purpose of oVirt platform.

Currently the validation passes when provided an incomplete bundle
because all the certificates were used as roots, including the
certificate that is a subject of the validation.

With this fix we are changing the behaviour so that all the certificates
in the bundle are identified as Root or Intermediary and afterwards the
verification is performed whether they can form a correct chain.

It is important to note that for a bundle to be considered valid every
certificate inside it must be correctly validating against a Root
certificate present in the aforementioned bundle.

Closes: [MGMT-9035](https://issues.redhat.com/browse/MGMT-9035)

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @carbonin 
/cc @mmartinv 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by carbonin** [comment]
I'd rather the changes from https://github.com/openshift/assisted-service/pull/3227 be included here so that we can actually run the unit tests for the new code before we merge.

**Review by carbonin — APPROVED** [review]

**Comment by mkowalski** [comment]
The test file contains 2 tests that were written as broken and we never spotted it because they were disabled from the beginning... How should we handle that?

```
�[91m�[1m[Fail] �[0m�[90mget hosts by role �[0m�[91m�[1m[It] 5 nodes autoassign �[0m
�[37m/opt/app-root/src/internal/common/common_test.go:233�[0m

�[91m�[1m[Fail] �[0m�[90mget hosts by role �[0m�[91m�[1m[It] 5 nodes autoassign - 1 disabled �[0m
�[37m/opt/app-root/src/internal/common/common_test.go:246�[0m
```

**Comment by carbonin** [comment]
I think the autoassign logic/timing changed.
@slaviered may know more.

If it's not a quick fix I would just delete the failing tests.

**Review by carbonin — APPROVED** [review]

**Pull request merged**
