### PR TITLE
Raz/ocpbugsm 16608 - Added Reset Timeout

### PR DESCRIPTION
**Pull request by RazRegev**
OCPBUGSM-16608: Add reset timeout

Checked by cluster monitor, if one or more hosts hangs on
resetting state for more then 3m (configurable), set all hosts
to resetting-pending-user-action and by that require the user
to reboot the hosts manually to the live iso mode.
This will help cluster to recover from edge cases where the 
agent on the host is down or hangs.

### CODE REVIEW

**Comment by rollandf** [comment]
@RazRegev I think that the title of the PR should have more information on what is the change about.
Also having a few lines describing the change and why it is needed will be welcomed.

**Comment by RazRegev** [comment]
> @RazRegev I think that the title of the PR should have more information on what is the change about.
> Also having a few lines describing the change and why it is needed will be welcomed.

I described this PR to two commits, each commits has information about the purpose of this pr (hope you noticed).
Anyway copied the info from the commit to the pr info. thanks.

**Comment by rollandf** [comment]
> > @RazRegev I think that the title of the PR should have more information on what is the change about.
> > Also having a few lines describing the change and why it is needed will be welcomed.
> 
> I divided this PR to two commits, each commit has information about the purpose of this pr (hope you noticed).
> Anyway copied the info from the commit to the pr info. thanks.

Thanks! I think also the PR title should be more informative than `Raz/ocpbugsm 16608`

**Pull request closed without merging**
