### PR TITLE
MGMT-5268 SetStatusCondition causes controllers reconcile endless loop

### PR DESCRIPTION
**Pull request by tsorya**
Each time we use SetStatusCondition it updates heartbeat variable in condition.
This update causes another reconcile and if it takes more than a second we will have endless loop.
Moving to use SetStatusConditionNoHeartbeat

### CODE REVIEW

**Review by djzager — APPROVED** [review]
Pretty simple :sunglasses: looks good to me.

**Comment by carbonin** [comment]
> This update causes another reconcile

Out of curiosity why would this ever be desired behavior?

**Comment by djzager** [comment]
> Out of curiosity why would this ever be desired behavior?

I suspect it makes the most sense on Node's status conditions. There are mechanisms to filter out this noise (see https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/predicate/predicate.go#L155) but I think it's best for the library to support skipping the lastheartbeattime unless someone wants that behavior.

**Pull request merged**
