### PR TITLE
[WIP] MGMT-16310: Implement ACI v1beta2 - VIPs

### PR DESCRIPTION
**Pull request by nmagnezi**
## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by nmagnezi** [comment]
/hold
adding more tests, but reviews are very welcomed.

**Review by filanov — COMMENTED** [review]
please try running all subsystem tests with v2

**Comment by avishayt** [comment]
I did a quick scan, looks OK.  Were there any other changes we wanted to make, as long as we're bumping the version?
@filanov ?

**Review by mhrivnak — CHANGES_REQUESTED** [review]
If ever there's a change that merits a commit message, this is it. We should have a complete explanation of the API change or a link to a doc in the repo that explains it (like an enhancement proposal). Even then, a brief summary would be appropriate here.

What's the conversion strategy?

Here are good resources in case they're helpful:
* https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/
* https://developer.ibm.com/tutorials/create-a-conversion-webhook-with-the-operator-sdk/

For the latter one, I would hope there's a better option now than borrowing code from knative, but the fundamentals of implementing conversion should still be relevant.

**Comment by nmagnezi** [comment]
> If ever there's a change that merits a commit message, this is it. We should have a complete explanation of the API change or a link to a doc in the repo that explains it (like an enhancement proposal). Even then, a brief summary would be appropriate here.
> 
> What's the conversion strategy?
> 
> Here are good resources in case they're helpful:
> 
> * https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/
> * https://developer.ibm.com/tutorials/create-a-conversion-webhook-with-the-operator-sdk/
> 
> For the latter one, I would hope there's a better option now than borrowing code from knative, but the fundamentals of implementing conversion should still be relevant.

You are, of course - right.
I just wanted to get some initial feedback from CI and you guys. 
I’ll definitely add a lot more details about what I’m doing here.

As for the conversion strategy - webhooks were not planned to be a part of this PR. If that's a concern, we can discuss it further.

Thanks for the references!

**Comment by nmagnezi** [comment]
@mhrivnak , @avishayt , @filanov:
Here's the current plan (open for discussion):
1. As soon as 'v1beta2' is ready, we'll announce the deprecation of 'v1beta1'.
2.  We'll support 'v1beta1' and 'v1beta2' ACI versions for two (or more?) cycles, such that both versions co-exist on the same setup.
3. The current master branch is still a work in progress; webhooks might not get included in this PR, but those will get into the version in a future PR.
4. The 'v1beta2' brings more changes: Removing user-managed networking and some changes to platform type. This is also out of the scope of this specific PR; however, it will be included with the same release and API version. (@avishayt's question)

As for the webhooks conversion strategy, we have two options:
1. Allow both versions of ACIs and be able to reconcile them both. Apply webhooks for conversion only when v1beta1 is no longer supported.
2. Convert any v1beta1 ACI immediately to v1beta2 upon reconciliation (create or update).
I'm not sure what we plan to do here yet - TBD.

Nir

**Comment by avishayt** [comment]
> > I did a quick scan, looks OK. Were there any other changes we wanted to make, as long as we're bumping the version? @filanov ?
> 
> we want to remove user managed network in the same version but we can do it later because the version is going to be released in a few months

Thanks, I remembered there was something else but not what it was.

**Comment by filanov** [comment]
closing, this PR will be replaced by another one

**Pull request closed without merging**
