### PR TITLE
[WIP] Enable unit tests for ./internal/common

### PR DESCRIPTION
**Pull request by mkowalski**
This commit fixes unit tests for the ./internal/common that were never
executed due to the missing `testing.T` initializer.

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [x] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by filanov — APPROVED** [review]

**Comment by osherdp** [comment]
/retitle [WIP] Enable unit tests for ./internal/common

**Comment by mkowalski** [comment]
```
=== FAIL: internal/common TestCommon (0.00s)
Running Suite: Common test suite
================================
Random Seed: 1643021228
Will run 10 of 10 specs

get hosts by role 
  no hosts
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:155
•
------------------------------
get hosts by role 
  3 masters 2 workers
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:161
•
------------------------------
get hosts by role 
  3 masters 2 workers - 1 master disabled
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:174
•
------------------------------
get hosts by role 
  5 workers
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:187
•
------------------------------
get hosts by role 
  5 masters
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:200
•
------------------------------
get hosts by role 
  5 nodes autoassign
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:213

• Failure [0.001 seconds]
get hosts by role
/home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:154
  5 nodes autoassign [It]
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:213

  Expected
      <[]models.Host | len:0, cap:0>: nil
  to have length 3

  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:223
------------------------------
get hosts by role 
  5 nodes autoassign - 1 disabled
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:226

• Failure [0.000 seconds]
get hosts by role
/home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:154
  5 nodes autoassign - 1 disabled [It]
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:226

  Expected
      <[]models.Host | len:0, cap:0>: nil
  to have length 3

  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:236
------------------------------
test PEM CA bundle verification 
  full CA chain
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:137
•
------------------------------
test PEM CA bundle verification 
  incomplete CA chain
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:142

• Failure [0.001 seconds]
test PEM CA bundle verification
/home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:136
  incomplete CA chain [It]
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:142

  Expected an error to have occurred.  Got:
      <nil>: nil

  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:145
------------------------------
test PEM CA bundle verification 
  malformed PEM
  /home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:147
•
JUnit path was configured: ./junit_unit_test.xml

JUnit report was created: /home/kmateusz/git/github.com/assisted-service/internal/common/junit_unit_test.xml


Summarizing 3 Failures:

[Fail] get hosts by role [It] 5 nodes autoassign 
/home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:223

[Fail] get hosts by role [It] 5 nodes autoassign - 1 disabled 
/home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:236

[Fail] test PEM CA bundle verification [It] incomplete CA chain 
/home/kmateusz/git/github.com/assisted-service/internal/common/common_test.go:145

Ran 10 of 10 Specs in 0.003 seconds
FAIL! -- 7 Passed | 3 Failed | 0 Pending | 0 Skipped

DONE 1 tests, 1 failure in 0.894s
```

**Comment by mkowalski** [comment]
After https://github.com/openshift/assisted-service/pull/3234 is merged we can get this in

**Comment by carbonin** [comment]
I'd rather you just add this to #3234 

That way we can see that PR go green when it actually runs the tests.

**Comment by filanov** [comment]
> I'd rather you just add this to #3234
> 
> That way we can see that PR go green when it actually runs the tests.

agree, no need for both

**Comment by mkowalski** [comment]
/close

Changes squashed with https://github.com/openshift/assisted-service/pull/3234

**Pull request closed without merging**
