### PR TITLE
NO-ISSUE: Enable Day 2 cluster in kube api

### PR DESCRIPTION
**Pull request by rollandf**
## Description
Enable Day 2 cluster in kube api

Signed-off-by: Fred Rolland <frolland@redhat.com>

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [ ] Operator Managed Deployments
- [x] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @nmagnezi 
/cc @danielerez 
/cc @filanov 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by filanov** [comment]
@avishayt @ravidbro @yevgeny-shnaidman currently once cluster is deleted from the DB we delete the agents in this cluster. 
What will happen in late binding?

**Comment by ravidbro** [comment]
I see two options:
1. return them to the pool.
2. block deletion of cluster until the user will bind them to the pool first

**Comment by filanov** [comment]
> I see two options:
> 
> 1. return them to the pool.
> 2. block deletion of cluster until the user will bind them to the pool first

Then in this case we cannot delete the day1 cluster, maybe instead of creating a new cluster we should just change installed cluster into a day2 cluster ?
Otherwise we will need to hold both day1 and day2.

**Comment by yevgeny-shnaidman** [comment]
> > I see two options:
> > 
> > 1. return them to the pool.
> > 2. block deletion of cluster until the user will bind them to the pool first
> 
> Then in this case we cannot delete the day1 cluster, maybe instead of creating a new cluster we should just change installed cluster into a day2 cluster ?
> Otherwise we will need to hold both day1 and day2.

Maybe we can delete day1 cluster without doing anything with the agents: we do have connections between InfraEnv and installed agents, so in case we want to return the installed agents to the pool, we will be able to find them and move them as needed. Maybe we will need to handle  a special case where the currently attached cluster does not exists, but this is just a minor issue

**Comment by filanov** [comment]
> > > I see two options:
> > > 
> > > 1. return them to the pool.
> > > 2. block deletion of cluster until the user will bind them to the pool first
> > 
> > 
> > Then in this case we cannot delete the day1 cluster, maybe instead of creating a new cluster we should just change installed cluster into a day2 cluster ?
> > Otherwise we will need to hold both day1 and day2.
> 
> Maybe we can delete day1 cluster without doing anything with the agents: we do have connections between InfraEnv and installed agents, so in case we want to return the installed agents to the pool, we will be able to find them and move them as needed. Maybe we will need to handle a special case where the currently attached cluster does not exists, but this is just a minor issue

sounds a bit hacky to me. thinking about the cloud it will require the user to follow the same pattern.
User install a cluster and want to add hosts from the pool to it, he will need to have both clusters that point to same installed cluster. IMO keeping one entity is clearer

**Comment by rollandf** [comment]
/hold
Waiting for decision regarding late binding behavior

**Comment by filanov** [comment]
> /hold
> Waiting for decision regarding late binding behavior

@rollandf I don't think that you need to hold this PR, there is some time before late binding is implemented and we need to handle adding remote workers to SNO as well so it will be probably with a day2 cluster as well.
For now this change LGTM

**Review by filanov — APPROVED** [review]

**Comment by yevgeny-shnaidman** [comment]
> > > > I see two options:
> > > > 
> > > > 1. return them to the pool.
> > > > 2. block deletion of cluster until the user will bind them to the pool first
> > > 
> > > 
> > > Then in this case we cannot delete the day1 cluster, maybe instead of creating a new cluster we should just change installed cluster into a day2 cluster ?
> > > Otherwise we will need to hold both day1 and day2.
> > 
> > 
> > Maybe we can delete day1 cluster without doing anything with the agents: we do have connections between InfraEnv and installed agents, so in case we want to return the installed agents to the pool, we will be able to find them and move them as needed. Maybe we will need to handle a special case where the currently attached cluster does not exists, but this is just a minor issue
> 
> sounds a bit hacky to me. thinking about the cloud it will require the user to follow the same pattern.
> User install a cluster and want to add hosts from the pool to it, he will need to have both clusters that point to same installed cluster. IMO keeping one entity is clearer

it means that you will have to keep day1 cluster indefinitely, even if the user does not want to add any hosts in day2.

**Comment by filanov** [comment]
> > > > > I see two options:
> > > > > 
> > > > > 1. return them to the pool.
> > > > > 2. block deletion of cluster until the user will bind them to the pool first
> > > > 
> > > > 
> > > > Then in this case we cannot delete the day1 cluster, maybe instead of creating a new cluster we should just change installed cluster into a day2 cluster ?
> > > > Otherwise we will need to hold both day1 and day2.
> > > 
> > > 
> > > Maybe we can delete day1 cluster without doing anything with the agents: we do have connections between InfraEnv and installed agents, so in case we want to return the installed agents to the pool, we will be able to find them and move them as needed. Maybe we will need to handle a special case where the currently attached cluster does not exists, but this is just a minor issue
> > 
> > 
> > sounds a bit hacky to me. thinking about the cloud it will require the user to follow the same pattern.
> > User install a cluster and want to add hosts from the pool to it, he will need to have both clusters that point to same installed cluster. IMO keeping one entity is clearer
> 
> it means that you will have to keep day1 cluster indefinitely, even if the user does not want to add any hosts in day2.

If you are working with a pool then yes. otherwise you will not know when to return a host to cluster. 
In hive when you delete cluster deployment it is expected that the manged cluster get destroyed.

**Comment by ravidbro** [comment]
maybe when you delete a cluster...
we will look per host to the infra-env it belongs to, if the infra_env has the optional cluster_id set to the one we deleted - we delete the agent.
if the cluster_id of the associated infra_env is null we the agent just reset its cluster_id and getting back to the pool.

**Pull request merged**
