### PR TITLE
Handle ironic URLs in dual stack hub and IPv6 spoke

### PR DESCRIPTION
**Pull request by carbonin**
This PR updates the cluster baremetal operator dependency to include the addition of the inspector proxy as well as the ability to fetch the proxy IP in both IPv4 and IPv6 for dual-stack hub clusters.

Before this change the inspector service was not using a proxy, this meant that the following chain of events could lead to a host failing to register:

1. ISO is created - inspector service URL is embedded into ignition
2. Inspector service is rescheduled and changes nodes
3. Hosts are booted - these hosts would not be able to reach the inspector service

With this change the hosts will be booted as the discovery ignition will contain the proxy address for the inspector service.

Previously when running on a dual-stack hub cluster only the IPv4 ironic addresses would ever be configured in the discovery ignition. This PR also checks the spoke cluster machine networks to determine the IP family to provide. It defaults to v4 unless the spoke is v6-only.

This only works if the infra-env has a cluster associated with it. With late-binding there's no way for assisted-service to tell what IP address version can be used by any potential agent so the ignition will always be configured with the first address returned (v4 in dual-stack or the available address in single-stack).

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-13925
https://issues.redhat.com/browse/MGMT-14432

- [ ] New Feature 
- [ ] Enhancement 
- [x] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

Telco QE is running this through tests, also relying on e2e tests to catch regressions

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

Waiting on QE to report back about their testing.

**Comment by carbonin** [comment]
/unhold

This was tested and an IPv6 only spoke successfully registered to a dual-stack hub.

**Review by filanov — APPROVED** [review]

**Pull request merged**
