### PR TITLE
OCPBUGSM-24075 - Fix spelling of `canceled` in both american and british

### PR DESCRIPTION
**Pull request by eliorerz**
Both spellings canceled(Americans) and canceled(British) are in use.
This patch changes all `cancelled` to `canceled`.

https://bugzilla.redhat.com/show_bug.cgi?id=1923268

### CODE REVIEW

**Comment by omertuc** [comment]
This is a breaking API change, please don't modify the instances of this in the swagger. test-infra [relies](https://github.com/openshift/assisted-test-infra/blob/ff6c263b2e4435326d49d7fcbdd9fd65b1ca6066/discovery-infra/test_infra/consts.py#L77) on this specific value

**Comment by eliorerz** [comment]
@omertuc I know.  I'm currently working on a solution in test infra.

**Comment by omertuc** [comment]
> @omertuc I know. I'm currently working on a solution in test infra.

This is not just test-infra. This may also mess app metrics dashboards that look for this value, and also maybe UI?

**Comment by eliorerz** [comment]
@omertuc So just leave different spelling for the same meaning?

**Comment by omertuc** [comment]
> @omertuc So just leave different spelling for the same meaning?

Not sure, what do you mean exactly?

**Comment by eliorerz** [comment]
@omertuc As you can see, there are a lot of misspellings for canceled. It's reflates statuses, events and more. I'm not sure changing just the event is the right approach here, But as you mentioned I think we should check first what effect it has on

**Comment by omertuc** [comment]
> @omertuc As you can see, there are a lot of misspellings for canceled. It's reflates statuses, events and more. I'm not sure changing just the event is the right approach here, But as you mentioned I think we should check first what effect it has on

Yeah obviously it's not ideal, but it really stands out in that message, because it appears twice in different spellings. 

You should consider whether this is worth fixing or not

**Comment by avishayt** [comment]
Agree with @omertuc .  This should be part of Epic MGMT-3493.  We can definitely change the API but need to make sure that the controllers, tests, and UI don't break.

**Comment by eliorerz** [comment]
Will be solved as part of https://issues.redhat.com/browse/MGMT-3493

**Pull request closed without merging**
