### PR TITLE
MGMT-9109: v1 RegisterCluster cleanup

### PR DESCRIPTION
**Pull request by slaviered**
Remove v1 flags in RegisterCluster APIs throughout the code
and adjust the tests

## List all the issues related to this PR

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [x] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [x] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by nmagnezi — CHANGES_REQUESTED** [review]
There is also a `v1Flag` in `V2ImportClusterInternal()`, that should be removed

**Comment by slaviered** [comment]
> There is also a `v1Flag` in `V2ImportClusterInternal()`, that should be removed
This one is out of scope for this PR

**Review by nmagnezi — CHANGES_REQUESTED** [review]
please fix the prefix from MTMT to MGMT in your commit-msg

**Comment by nmagnezi** [comment]
> > There is also a `v1Flag` in `V2ImportClusterInternal()`, that should be removed
> > This one is out of scope for this PR

Okay, we will do this in [MGMT-9430](https://issues.redhat.com/browse/MGMT-9430)

**Review by nmagnezi — APPROVED** [review]
/lgtm

**Pull request merged**
