### PR TITLE
Add Agent Auth to Hosts list API

### PR DESCRIPTION
**Pull request by rollandf**
In https://github.com/oshercc/ignition-manifests-and-kubeconfig-generate, there is call to assisted-service for Hosts List API.

In this PR, I enable the API to be able to be called it as a Agent authenticated in addition to User.

This is needed for :
https://github.com/oshercc/ignition-manifests-and-kubeconfig-generate/pull/19

### CODE REVIEW

**Comment by rollandf** [comment]
@avishayt @ronniel1 @filanov @eranco74 @yevgeny-shnaidman @tsorya

**Comment by avishayt** [comment]
The code in ignition-manifests-and-kubeconfig-generate is run in a job by assisted-service, not agent.  We shouldn't be making API calls from assisted-service jobs IMO.

**Comment by eranco74** [comment]
@avishayt we are already making the calls.
The job get's the pull secret so it was the easy way to authenticate.
We can discuss on removing them, for now let's make it work by allowing the API call.

**Comment by yevgeny-shnaidman** [comment]
Unless we change the way we pass input parameters to the job, i think that
this is the best option. we need all the inventory data + addition host
data for all the hosts, which can mount up to tens (if not hundreds) of Ks
of data ( especially on real BM) and i think it is not feasible to pass it
via environment variabl

**Comment by avishayt** [comment]
Let's proceed and open a tech-debt JIRA to take a look at re-architecturing
this.

**Comment by nmagnezi** [comment]
should probably update [host CRUD subsystem](https://github.com/openshift/assisted-service/blob/master/subsystem/host_test.go#L44-L68) test to use both auth types.

**Comment by rollandf** [comment]
> should probably update [host CRUD subsystem](https://github.com/openshift/assisted-service/blob/master/subsystem/host_test.go#L44-L68) test to use both auth types.

Done

**Comment by rollandf** [comment]
ping

**Comment by carbonin** [comment]
This PR now is attempting to address all of the endpoints which should have had agent auth, but didn't.
This includes ones that were called by the controller as well as the kubeconfig generation containers.

**Comment by carbonin** [comment]
This PR combined with https://github.com/oshercc/ignition-manifests-and-kubeconfig-generate/pull/19 and https://github.com/openshift/assisted-test-infra/pull/71 allows for a successful run of `assisted-test-infra` with authentication enabled.

**Pull request merged**
