### PR TITLE
KONFLUX-1611: Add labels, licenses & user to Dockerfile

### PR DESCRIPTION
**Pull request by pastequo**
* Add labels
* Add default user
* Add licenses under /licenses/

Requirements come from https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#additional_resources and would prevent us from releasing an image (we have an exception for "based_on_ubi image")

## List all the issues related to this PR

- [ ] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [x] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [ ] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [x] No tests needed

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rccrdpccl** [comment]
What's the plan about recreating this branch? Should we add some doc/util about it (in a separate PR)?

**Comment by pastequo** [comment]
I was thinking of that https://docs.google.com/document/d/1LhxsGTyygkEUpcMvkyRttzsyYnAje0krBliLP9Jfy5s/edit#heading=h.sete96qzfbij

**Comment by adriengentil** [comment]
@pastequo is this PR still relevant?

**Comment by pastequo** [comment]
yes it is

**Review by adriengentil — APPROVED** [review]

**Comment by pastequo** [comment]
/retest

This might look weird

**Pull request closed without merging**
