### PR TITLE
NO-ISSUE: Move SaaS networking documentation to Telco Docs

### PR DESCRIPTION
**Pull request by mkowalski**
/cc @omertuc

### CODE REVIEW

**Comment by omertuc** [comment]
GitLab is behind VPN, let's wait for the docs to be published before deleting?

**Comment by mkowalski** [comment]
> GitLab is behind VPN, let's wait for the docs to be published before deleting?

Sure think, no problem with clicking "merge" here only after we publish

**Comment by mkowalski** [comment]
/unhold

Published as https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform/2022/html/assisted_installer_for_openshift_container_platform/assembly_network-configuration

**Comment by mkowalski** [comment]
/override ci/prow/edge-e2e-ai-operator-ztp
/override ci/prow/edge-e2e-metal-assisted-cnv
/override ci/prow/edge-e2e-metal-assisted-lvm
/override ci/prow/edge-e2e-metal-assisted-ocs
/override ci/prow/edge-e2e-metal-assisted-odf

Modifies only docs/ directory

**Pull request merged**
