### PR TITLE
MGMT-4922 remove flaky call of updateAt while static

### PR DESCRIPTION
**Pull request by oshercc**

### CODE REVIEW

**Review by gamli75 — APPROVED** [review]

**Comment by nmagnezi** [comment]
/hold
@oshercc can you explain why you remove it? it was a part of a test..

**Comment by oshercc** [comment]
@nmagnezi I added this test to the PR fixing the constant DB updates. 
the problem was that the DB is constantly updated even if noting is updated. 
when we want to test it we need to sample the updated_at after we are sure the cluster is stable which can take between 1 or 2 monitor runs when every monitor run can take between 10 to ~40 seconds depending on the system stress.
So taking under consideration this has a good cover by the UT and already validated on integration I think we can live without this check and not add almost 2 minutes to every subsystem run that is already very long as is.

**Comment by nmagnezi** [comment]
/unhold
ok.. let's stabilize the CI first. Still, it would be nice to know why this is the solution.

**Pull request merged**
