### PR TITLE
Bug 2066917: Set boot artifact URLs in infra-env

### PR DESCRIPTION
**Pull request by carbonin**
When reconciling the infra env, set the boot artifact (rootfs, kernel, initrd, ipxe-script) links.

This includes some refactoring to move the logic for creating URLs to the image service out of the inventory API package and into a separate one so that they can be shared between the API and controller.

Depends on https://github.com/openshift/assisted-service/pull/3460

## List all the issues related to this PR

https://issues.redhat.com/browse/MGMT-9349

- [x] New Feature 
- [ ] Enhancement 
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [ ] Cloud
- [x] Operator Managed Deployments
- [ ] None

## How was this code tested?

- [ ] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [x] Manual (Elaborate on how it was tested)
- [ ] No tests needed

Deployed this code in a CRC cluster using the operator, created an infra-env and saw the values get correctly populated.
Example infra-env status:
```
status:
  agentLabelSelector:
    matchLabels:
      infraenvs.agent-install.openshift.io: infra-env-74322c8
  bootArtifacts:
    initrd: https://assisted-image-service-assisted-installer.apps-crc.testing/images/a2c1dc4f-de0d-4955-a861-7e333906caad/pxe-initrd?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZyYV9lbnZfaWQiOiJhMmMxZGM0Zi1kZTBkLTQ5NTUtYTg2MS03ZTMzMzkwNmNhYWQifQ.Pr2ySHpmTHbPlDE6eZyF1qeOXHYuMRFWnFGz4FvdCD9_ZDmhn6P6ZaTBnvWJjHETq85iKGWzMGzd4cdY_tToeQ&arch=x86_64&version=4.9
    ipxeScript: https://assisted-service-assisted-installer.apps-crc.testing/api/assisted-install/v2/infra-envs/a2c1dc4f-de0d-4955-a861-7e333906caad/downloads/files?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZyYV9lbnZfaWQiOiJhMmMxZGM0Zi1kZTBkLTQ5NTUtYTg2MS03ZTMzMzkwNmNhYWQifQ.5iMLfbAkxoRL-Iym6CfYg2IP4aaObJKezEDO1kPJJ60rdE2-72QAYbi9W6amu1ZG0_RAXGQskksT_aL9_2kSUw&file_name=ipxe-script
    kernel: https://assisted-image-service-assisted-installer.apps-crc.testing/boot-artifacts/kernel?arch=x86_64&version=4.9
    rootfs: https://assisted-image-service-assisted-installer.apps-crc.testing/boot-artifacts/rootfs?arch=x86_64&version=4.9
  conditions:
  - lastTransitionTime: "2022-03-14T19:22:50Z"
    message: Image has been created
    reason: ImageCreated
    status: "True"
    type: ImageCreated
  createdTime: "2022-03-14T19:22:50Z"
  debugInfo:
    eventsURL: https://assisted-service-assisted-installer.apps-crc.testing/api/assisted-install/v2/events?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZyYV9lbnZfaWQiOiJhMmMxZGM0Zi1kZTBkLTQ5NTUtYTg2MS03ZTMzMzkwNmNhYWQifQ.JwzmKUw1lO0QG4oXm92ewVpzeip-PQ5QZmhv2sTpRFz5x7QFFNyqfnWG3JQYifHN-qk3QtNoWrjJ9MHwscSZDw&infra_env_id=a2c1dc4f-de0d-4955-a861-7e333906caad
  isoDownloadURL: https://assisted-image-service-assisted-installer.apps-crc.testing/images/a2c1dc4f-de0d-4955-a861-7e333906caad?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZyYV9lbnZfaWQiOiJhMmMxZGM0Zi1kZTBkLTQ5NTUtYTg2MS03ZTMzMzkwNmNhYWQifQ.RjQ5wvlMHwH49JNy3Bx7rE5SgaSmVoRGUHXTWxNZZ1WAfHBSBzHosGg0p_yTnhyT6y6aJGEw15nMy01ZpLZ6UQ&arch=x86_64&type=minimal-iso&version=4.9
```

## Assignees

/cc @filanov 
/cc @nmagnezi 

## Checklist

- [x] Title and description added to both, commit and PR.
- [x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [x] Reviewers have been listed
- [x] This change does not require a documentation update (docstring, `docs`, README, etc)
- [x] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- Are the title and description (in both PR and commit) meaningful and clear?
- Is there a bug required (and linked) for this change?
- Should this PR be backported?

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

until https://github.com/openshift/assisted-service/pull/3460 is merged

**Comment by filanov** [comment]
will need to backport to 2.5

**Comment by carbonin** [comment]
/override ci/prow/e2e-metal-assisted-capi

This will be broken until https://github.com/openshift/assisted-test-infra/pull/1546 and https://github.com/openshift/release/pull/27177 are merged.

**Pull request merged**
