### PR TITLE
Adapt service to use only V2 APIs for agent Register, GetNextSteps, PostStepReply

### PR DESCRIPTION
**Pull request by ori-amizur**
# Assisted Pull Request

## Description
[MGMT-7413](https://issues.redhat.com/browse/MGMT-7413): Change post step reply tools to use V2 structure
- Make post step reply to use only V2 structures
[MGMT-7462](https://issues.redhat.com/browse/MGMT-7462): Remove V1 agent APIs from service
- RegisterHost, GetNextSteps, PostStepReply

## List all the issues related to this PR

- [x] New Feature
- [ ] Bug fix
- [ ] Tests
- [ ] Documentation
- [ ] CI/CD 

## What environments does this code impact?

- [ ] Automation (CI, tools, etc)
- [x] Cloud
- [x] Operator Managed Deployments
- [x] None

## How was this code tested?

- [x] assisted-test-infra environment
- [ ] dev-scripts environment
- [ ] Reviewer's test appreciated
- [ ] Waiting for CI to do a full test run
- [ ] Manual (Elaborate on how it was tested)
- [ ] No tests needed

## Assignees

/cc @ravidbro 
/cc @yevgeny-shnaidman 

## Checklist

- [ ] Title and description added to both, commit and PR.
- [ ] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit-tests (note that code changes require unit-tests)

## Reviewers Checklist

- [ ] Are the title and description (in both PR and commit) meaningful and clear?
- [ ] Is there a bug required (and linked) for this change?
- [ ] Should this PR be backported?

[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ravidbro** [comment]
General question: don't we need to support a case where the service is upgraded but the agents are still old and calling v1 APIs?

**Comment by flaper87** [comment]
> General question: don't we need to support a case where the service is upgraded but the agents are still old and calling v1 APIs?

For the operator-based workflow, I think the requirement is for there not to be any ongoing installation during an upgrade. For the cloud workflow, I don't think this is true. It is possible to communicate a maintenance window.

That said, I think I would rather keep backward compatibility and make sure existing agents won't break.

There are other, a bit more complex, solutions that would provide a seamless experience. It may not be worth digging too much into those as keeping backward compatibility or (explicitly communicating the incompatibility to users) should be enough.

**Comment by yevgeny-shnaidman** [comment]
> General question: don't we need to support a case where the service is upgraded but the agents are still old and calling v1 APIs?

It was agreed that in case there are still active agents while the assisted service is upgraded to the new version, we/user will need to reboot those agent.

**Pull request merged**
